// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/3DFx/VizCards/templates/VizCards.html":'\x3cdiv data-dojo-attach-point\x3d"containerNode" class\x3d"${css.root}" role\x3d"presentation"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"contentNode" class\x3d"${css.content}"\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("dojo/Evented dojo/_base/declare dojo/_base/array dojo/_base/Color dojo/_base/lang dojo/_base/html dojo/dom-class dojo/dom-construct dojo/dom-style dojo/number dojo/on dojo/query dojox/gfx dijit/_WidgetBase dijit/_TemplatedMixin dojo/text!./templates/VizCards.html".split(" "),function(u,v,w,x,n,r,g,l,q,y,z,t,A,B,C,D){return v("VizCards",[B,C,u],{declaredClass:"esri.widgets.VizCards",templateString:D,css:{root:"esri-viz-cards",content:"content"},constructor:function(b,a){this.rtl=!1;this.options=
{view:null,features:[],vizField:null,displayField:null,color:"#ff0000",showPercent:!1};n.mixin(this.options,b);this.domNode=a;this._currentSelectedCardNode=null},postCreate:function(){this.inherited(arguments);0<t(".dj_rtl").length&&(this.rtl=!0);this.own(z(this.contentNode,"click",n.hitch(this,this._clickCard)))},startup:function(){this.inherited(arguments);this._updateCards()},destroy:function(){this.view=null;this.inherited(arguments)},clear:function(){this.containerNode.innerHTML=""},update:function(b){n.mixin(this.options,
b);this._updateCards()},selectCard:function(b){var a=this.domNode.id+"_card_"+b;this.unselectCards();if(a=t("#"+a,this.domNode)[0])g.add(a,"selected"),this._currentSelectedCardNode=a;var a=r.getContentBox(this.containerNode).w,e=180*b-a/2+90;this.rtl&&(e=180*(this.options.features.length-b)-a/2-90);0>e&&(e=0);this.containerNode.scrollLeft=e},unselectCards:function(){this._currentSelectedCardNode&&(g.remove(this._currentSelectedCardNode,"selected"),this._currentSelectedCardNode=null)},_getTotal:function(){var b=
this.options.vizField,a=0;w.forEach(this.options.features,function(e){a+=e.attributes[b]});return a},_updateCards:function(){var b=this.contentNode;q.set(b,"color",this.options.color);var a=this.options.features,e=this._getTotal();b.innerHTML="";var f=0;this.rtl&&(f=180*a.length);this.containerNode.scrollLeft=f;q.set(b,"width",180*a.length+"px");for(var f=a.length,d=null,c,h,k=null,n=this.options.showPercent&&400>=f,p=0;p<f;p++){d=a[p];c=d.attributes;d=c[this.options.vizField];h=y.format(d);k||(k=
Math.floor(150/h.length+3),10>k&&(k=10),60<k&&(k=60));var m=c[this.options.displayField];null!==d&&(c=l.create("div",{id:this.domNode.id+"_card_"+p},b),g.add(c,"card"),m=l.create("div",{innerHTML:p+1+". "+m},c),g.add(m,"header"),h=l.create("div",{innerHTML:h},c),n?(g.add(h,"value"),h=parseInt(d/e*100,10),m=h+"%",0<d&&1>h&&(m="\x3c1%"),c=l.create("div",{},c),g.add(c,"area"),d=l.create("div",{},c),g.add(d,"chart"),c=l.create("div",{innerHTML:m},c),g.add(c,"pct"),this._createChart(d,h)):(g.add(h,"valueBig"),
q.set(h,"fontSize",k+"px")))}},_createChart:function(b,a){var e=r.getContentBox(b),f=Math.min(e.w,e.h),e=f/2,d=f/2,c=e-3;b=A.createSurface(b,f,f);b.clear();b.createCircle({cx:e,cy:d,r:c}).setStroke({width:6,color:x.fromArray([255,255,255,.15]),cap:"round"});0<a&&(100<=a&&(a=99),f=360*a/100,a=!1,180<=f&&(a=!0),f=this._getEndPoint(c,f,e,d),d-=c,b.createPath().moveTo(e,d).arcTo(c,c,0,a,!0,f.x,f.y).setStroke({width:6,color:this.options.color,cap:"round"}))},_getEndPoint:function(b,a,e,f){var d=a;0<a&&
90>a?d+=270:90<a&&(d=a-90);a=d*Math.PI/180;return{x:e+Math.cos(a)*b,y:f+Math.sin(a)*b}},_clickCard:function(b){b=b.target||b.srcElement;if(!g.contains(b,"card"))for(;b&&b.parentNode&&(b=b.parentNode,!g.contains(b,"card")););if(b){var a=b.id.replace(this.domNode.id+"_card_",""),a=parseInt(a,10);isNaN(a)||null==a||(g.contains(b,"selected")?(this.unselectCards(),this.emit("selection",{})):(this.unselectCards(),g.add(b,"selected"),this._currentSelectedCardNode=b,this.emit("selection",{data:this.options.features[a]})))}}})});