// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"jimu/layoutManagers/BaseLayoutManager":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dijit/_WidgetBase dojo/Deferred dojo/promise/all ../utils ../WidgetPlaceholder ../OnScreenWidgetIcon".split(" "),function(p,a,c,f,l,m,g,k,n,v){var q=null,t;t=p([l],{constructor:function(){this.widgetPlaceholders=[];this.onScreenWidgetIcons=[];this.invisibleWidgetIds=[]},name:"BaseLayoutManager",mapId:"map",sceneView:null,layoutId:"jimu-layout-manager",postCreate:function(){this.containerNode=
this.domNode;this.layoutId=jimuConfig.layoutId},resize:function(){},isSupportEdit:function(){return!1},getMapDiv:function(){},setSceneView:function(h){this.sceneView=h},onEnter:function(h,a){var d=new m;this.appConfig=h;this.mapId=a;d.resolve();return d},onLeave:function(){},onThemeLoad:function(){},loadAndLayout:function(a){},openWidget:function(a){},onLayoutChange:function(a){},onWidgetChange:function(a,d){},onGroupChange:function(a,d){},onWidgetPoolChange:function(a,d){this.reloadControllerWidget(a,
d.controllerId)},onOnScreenOrderChange:function(h,d){c.forEach(d,a.hitch(this,function(d){d.uri?c.some(this.onScreenWidgetIcons,a.hitch(this,function(a){if(a.configId===d.id)return f.setStyle(a.domNode,k.getPositionStyle({top:d.position.top,left:d.position.left,right:d.position.right,bottom:d.position.bottom,width:40,height:40})),a.moveTo(d.position),!0})):c.some(this.widgetPlaceholders,a.hitch(this,function(a){if(a.index===d.placeholderIndex){var h=k.getPositionStyle({top:d.position.top,left:d.position.left,
right:d.position.right,bottom:d.position.bottom,width:40,height:40});f.setStyle(a.domNode,h);return!0}}))}))},onActionTriggered:function(a){},onLayoutDefinitionChange:function(a,d){},onOnScreenGroupsChange:function(a,d){},destroyOnScreenWidgetsAndGroups:function(a){},loadOnScreenWidgets:function(a){var d=[];c.forEach(a.widgetOnScreen.widgets,function(h){!1===h.visible?this.invisibleWidgetIds.push(h.id):d.push(this.loadOnScreenWidget(h,a))},this);return g(d)},loadOnScreenWidget:function(h,d){var c=
new m;if("config"===d.mode&&!h.uri)return d=this._createOnScreenWidgetPlaceHolder(h),c.resolve(d),c;if(!h.uri)return c.resolve(null),c;h.inPanel||h.closeable?(d=this._createOnScreenWidgetIcon(h),c.resolve(d)):this.widgetManager.loadWidget(h).then(a.hitch(this,function(a){try{a.setPosition(a.position),this.widgetManager.openWidget(a)}catch(u){console.log(console.error("fail to startup widget "+a.name+". "+u.stack))}a.configId=h.id;c.resolve(a)}),function(a){c.reject(a)});return c},onOnScreenWidgetChange:function(a,
d){d=a.getConfigElementById(d.id);d.isController?this.reloadControllerWidget(a,d.id):(c.forEach(this.widgetPlaceholders,function(c){c.configId===d.id&&(c.destroy(),this.loadOnScreenWidget(d,a))},this),this.removeDestroyed(this.widgetPlaceholders),this._updatePlaceholder(a),c.forEach(this.onScreenWidgetIcons,function(c){if(c.configId===d.id){var h=c.state;c.destroy();this.loadOnScreenWidget(d,a).then(function(a){if(d.uri&&"opened"===h)a.onClick()})}},this),this.removeDestroyed(this.onScreenWidgetIcons),
c.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(c){c.configId===d.id&&(c.destroy(),!1===d.visible?0>this.invisibleWidgetIds.indexOf(d.id)&&this.invisibleWidgetIds.push(d.id):this.loadOnScreenWidget(d,a))},this),c.forEach(this.invisibleWidgetIds,function(c){c===d.id&&!1!==d.visible&&(this.loadOnScreenWidget(d,a),c=this.invisibleWidgetIds.indexOf(d.id),this.invisibleWidgetIds.splice(c,1))},this),d.isOnScreen||c.forEach(this.widgetManager.getControllerWidgets(),function(c){c.widgetIsControlled(d.id)&&
this.reloadControllerWidget(a,c.id)},this))},destroyOnScreenWidgetIcons:function(){c.forEach(this.onScreenWidgetIcons,function(a){a.destroy()},this);this.onScreenWidgetIcons=[]},destroyOnScreenOffPanelWidgets:function(){c.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(a){a.isController?this._destroyControllerWidget(a):this.widgetManager.destroyWidget(a)},this)},destroyWidgetPlaceholders:function(){c.forEach(this.widgetPlaceholders,function(a){a.destroy()},this);this.widgetPlaceholders=
[]},removeDestroyed:function(a){var d=[];c.forEach(a,function(a){a._destroyed&&d.push(a)});c.forEach(d,function(d){d=a.indexOf(d);a.splice(d,1)})},_createOnScreenWidgetPlaceHolder:function(c){var d;d="map"===c.position.relativeTo?this.mapId:this.layoutId;var h=a.clone(c);h.position.width=40;h.position.height=40;var g=k.getPositionStyle(h.position);c=new n({index:h.placeholderIndex,configId:c.id});f.setStyle(c.domNode,g);f.place(c.domNode,d);this.widgetPlaceholders.push(c);return c},_createOnScreenWidgetIcon:function(a){var d=
new v({panelManager:this.panelManager,widgetManager:this.widgetManager,widgetConfig:a,configId:a.id,sceneView:this.sceneView});"map"===a.position.relativeTo?f.place(d.domNode,this.mapId):f.place(d.domNode,this.layoutId);f.setStyle(d.domNode,k.getPositionStyle({top:a.position.top,left:a.position.left,right:a.position.right,bottom:a.position.bottom,width:40,height:40}));d.startup();!this.openAtStartWidget&&a.openAtStart&&(d.switchToOpen(),this.openAtStartWidget=a.name);this.onScreenWidgetIcons.push(d);
return d},reloadControllerWidget:function(a,d){var c=this.widgetManager.getWidgetById(d);if(c){var k=c.getOpenedIds(),h=c.windowState;this._destroyControllerWidget(c);this._loadControllerWidget(a,d,k,h)}else this._loadControllerWidget(a,d)},_destroyControllerWidget:function(a){c.forEach(a.getAllConfigs(),function(a){if(a.widgets)this.panelManager.destroyPanel(a.id+"_panel"),c.forEach(a.widgets,function(a){this.panelManager.destroyPanel(a.id+"_panel")},this);else{var d=this.widgetManager.getWidgetById(a.id);
d&&(a.inPanel?this.panelManager.destroyPanel(d.getPanel()):this.widgetManager.destroyWidget(d))}},this);this.widgetManager.destroyWidget(a)},_loadControllerWidget:function(c,d,k,f){d=c.getConfigElementById(d);!1!==d.visible&&this.loadOnScreenWidget(d,c).then(a.hitch(this,function(a){f&&this.widgetManager.changeWindowStateTo(a,f);k&&a.setOpenedIds(k)}))},_updatePlaceholder:function(a){c.forEach(this.widgetPlaceholders,function(c){c.setIndex(a.getConfigElementById(c.configId).placeholderIndex)},this)}});
t.getInstance=function(){null===q&&(q=new t);return q};return t})},"jimu/WidgetPlaceholder":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/html","dijit/_WidgetBase","./utils"],function(p,a,c,f,l){return p(f,{"class":"jimu-widget-placeholder",position:null,postCreate:function(){this.inherited(arguments);this.indexNode=c.create("div",{"class":"inner",innerHTML:this.index},this.domNode);c.setAttr(this.domNode,"title",window.jimuNls.widgetPlaceholderTooltip)},moveTo:function(f){this.position=
a.clone(f);var g={left:"auto",right:"auto",bottom:"auto",top:"auto",width:"auto",height:"auto"},g=a.mixin(g,l.getPositionStyle(f));delete g.width;delete g.height;c.setStyle(this.domNode,g)},setIndex:function(a){this.index=a;this.indexNode.innerHTML=a}})})},"jimu/OnScreenWidgetIcon":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dijit/_WidgetBase ./utils".split(" "),function(p,a,c,f,l,m,g){return p(m,{"class":"jimu-widget-onscreen-icon",postCreate:function(){this.inherited(arguments);
this.iconNode=f.create("img",{src:this.widgetConfig.icon},this.domNode);window.isRTL&&this.widgetConfig.mirrorIconForRTL&&f.addClass(this.iconNode,"jimu-flipx");f.setAttr(this.domNode,"title",this.widgetConfig.label);this.own(l(this.domNode,"click",a.hitch(this,function(){this.onClick()})));this.position=a.clone(this.widgetConfig.position);"map"===this.widgetConfig.position.relativeTo&&this.own(l(this.sceneView,"resize",a.hitch(this,function(){var c=a.clone(this.position);delete c.width;delete c.height;
this.panel&&this.panel.setPosition(c)})));this.state="closed"},startup:function(){this.inherited(arguments)},onClick:function(){"closed"===this.state?this.switchToOpen():this.switchToClose()},moveTo:function(c){var k={left:"auto",right:"auto",bottom:"auto",top:"auto",width:"auto",height:"auto"},k=a.mixin(k,g.getPositionStyle(c));delete k.width;delete k.height;f.setStyle(this.domNode,k);this.position=a.clone(c);this.widgetConfig&&this.widgetConfig.panel&&(this.widgetConfig.panel.position=a.clone(c),
this.widgetConfig.position=a.clone(c));this.panel&&this.panel.setPosition(a.clone(c));this.widget&&this.widget.setPosition(this.getOffPanelWidgetPosition(this.widget))},destroy:function(){this.panel?this.panelManager.destroyPanel(this.panel):this.widget&&this.widgetManager.destroyWidget(this.widget);this.inherited(arguments)},switchToOpen:function(){this.state="opened";this.panelManager.closeAllPanelsInGroup(this.widgetConfig.gid);c.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(a){a.closeable&&
this.widgetManager.closeWidget(a)},this);f.addClass(this.domNode,"jimu-state-selected");this._showLoading();!1===this.widgetConfig.inPanel?this.widgetManager.loadWidget(this.widgetConfig).then(a.hitch(this,function(c){this.widget=c;c.setPosition(this.getOffPanelWidgetPosition(c));this.widgetManager.openWidget(c);this.own(l(c,"close",a.hitch(this,function(){this.switchToClose()})));this._hideLoading()})):this.panelManager.showPanel(a.clone(this.widgetConfig)).then(a.hitch(this,function(c){this.panel=
c;this.own(l(c,"close",a.hitch(this,function(){this.switchToClose()})));this._hideLoading()}))},switchToClose:function(){this.state="closed";f.removeClass(this.domNode,"jimu-state-selected");!1===this.widgetConfig.inPanel?this.widgetManager.closeWidget(this.widget):this.panelManager.closePanel(this.panel)},getOffPanelWidgetPosition:function(a){var c={relativeTo:a.position.relativeTo},g=f.getMarginBox(this.domNode);a=this.widgetManager.getWidgetMarginBox(a);var k=f.getMarginBox("map"===c.relativeTo?
this.sceneView.map.id:jimuConfig.layoutId),l=g.t+g.h+1;l+a.h>k.h?c.bottom=k.h-g.t+1:c.top=l;window.isRTL?c.right=0>g.l+g.w-a.w?0:g.l+g.w-a.w:g.l+a.w>k.w?c.right=0:c.left=g.l;return c},_showLoading:function(){f.setAttr(this.iconNode,"src",require.toUrl("jimu")+"/images/loading_circle.gif")},_hideLoading:function(){f.setAttr(this.iconNode,"src",this.widgetConfig.icon)}})})}}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/topic dojo/on dojo/dom-construct dojo/dom-geometry dojo/Deferred dojo/debounce require ../WidgetManager ../PanelManager ../utils ../dijit/LoadingShelter ./BaseLayoutManager".split(" "),function(p,a,c,f,l,m,g,k,n,v,q,t,h,d,y,z){var u=null,w;w=p([z],{isEditing:!1,maxStackId:0,dashboardWidgets:[],dashboardPanels:{},currentMode:0,_createLayoutDeferred:null,_isDestroying:!1,nls:null,_addWidgetTipTemplate:'\x3cdiv class\x3d"tip"\x3e\x3cdiv class\x3d"idx"\x3e${groupIndex}\x3c/div\x3e\x3cdiv class\x3d"label"\x3e${this.nls.addWidgetTip}\x3c/div\x3e\x3c/div\x3e',
name:"GridLayoutManager",constructor:function(b,e){this.widgetManager=t.getInstance();this.panelManager=h.getInstance();this.widgetPlaceholders=[];this.preloadWidgetIcons=[];this.preloadGroupPanels=[];this.invisibleWidgetIds=[];this.own(m(window,"resize",a.hitch(this,this.resize)));this.id=e;this._createLayoutDeferred=null},postMixInProperties:function(){this.inherited(arguments);this.nls={};a.mixin(this.nls,window.jimuNls.gridLayout,window.jimuNls.common);this._addWidgetTipTemplate=this._addWidgetTipTemplate.replace("${this.nls.addWidgetTip}",
this.nls.addWidgetTip)},isSupportEdit:function(){return!0},postCreate:function(){this.containerNode=this.domNode},layout:null,sceneView:null,mapContainer:null,mapId:"map",hlDiv:null,animTime:500,resize:function(){this._resizeLayout();c.forEach(this.widgetManager.getAllWidgets(),function(a){!1===a.inPanel&&a.resize()},this)},setSceneView:function(a){this.inherited(arguments);this.panelManager.setSceneView(a)},_resizeLayout:function(){var a,e;!this.isEditing&&this.layout?(a=$(this.layoutContainer),
e=a.width(),a=a.height(),this.layout.updateSize(e,a)):this.isEditing&&this.editingLayout&&(a=$(this.editLayoutDiv),e=a.width(),a=a.height(),this.editingLayout.updateSize(e,a))},loadAndLayout:function(b){this.appConfig=b;var e=new y;e.placeAt(this.layoutId);e.startup();this._createLayoutDeferred&&!this._createLayoutDeferred.isResolved()?b=this._createLayoutDeferred:(b=new n,b.resolve());b.then(a.hitch(this,this._loadOnScreenGroups)).then(a.hitch(this,this._reArrangeWidgetsLayout,!0)).then(a.hitch(this,
function(){e&&(e.destroy(),e=null);console.timeEnd("Load widgetOnScreen");l.publish("preloadWidgetsLoaded")}),a.hitch(this,function(){e&&(e.destroy(),e=null);console.timeEnd("Load widgetOnScreen");l.publish("preloadWidgetsLoaded")}))},createMapDiv:function(b){f.byId(b)?this.mapDiv=f.byId(b):this.mapDiv=f.create("div",{id:b,style:a.mixin({position:"absolute",backgroundColor:"#EEEEEE",overflow:"hidden",minWidth:"1px",minHeight:"1px"},d.getPositionStyle(this.appConfig.map.position))},this.layoutId)},
getMapDiv:function(){return this.mapDiv},onThemeLoad:function(){this._resizeLayout()},_enableEditing:function(){this.isEditing||(this._createEditingLayout(),$(this.layoutContainer).addClass("hidden"),$(this.editContainer).removeClass("hidden"),$(this.modifyLayoutBtn).addClass("hidden"),this.isEditing=!0,this._resizeLayout())},_disableEditing:function(){$(this.layoutContainer).removeClass("hidden");$(this.editContainer).addClass("hidden");$(this.modifyLayoutBtn).removeClass("hidden");this.isEditing=
!1;this._resizeLayout()},_resetLayoutDefinition:function(){this._disableEditing();this._createLayout(!1,!1);l.publish("editLayoutCancelled")},_saveLayoutDefinition:function(){var b=a.clone(this.editingLayout.toConfig()),e=a.clone(this.appConfig.layoutDefinition);this._simplifyLayoutDefinition(b.content[0]);this._disableEditing();var d=this.editingLayout.root.contentItems[0].getItemsByType("stack"),r=[];c.forEach(d,function(b){!c.some(b.contentItems,a.hitch(this,function(a){if(a.isComponent&&"map"===
a.config.componentName)return!0}))&&/^dd_group_\d+$/.test(b.config.id)&&r.push(b.config.id)});e.layout.config.content=b.content;l.publish("layoutDefinitionChanged",{layoutDefinition:e,groupIds:r})},_simplifyLayoutDefinition:function(b){if("component"!==b.type)if("stack"===b.type){var e;b.activeItemIndex=0;c.some(b.content,a.hitch(this,function(a){if("component"===a.type&&"map"===a.componentName)return e=a,!0}));e?(b.id="map",b.content=[e]):b.content=[]}else c.forEach(b.content,a.hitch(this,function(a){this._simplifyLayoutDefinition(a)}))},
_bindLayoutEvents:function(){this.editingLayout.on("initialised",a.hitch(this,function(){this.editingLayout.createDragSource($(this.dragCreateBtn),{title:" ",type:"component",reorderEnabled:!1,componentName:"widget panel"});var a=this.editingLayout.root.contentItems[0].getItemsByType("stack"),e=[];c.forEach(a,function(a){/^dd_group_\d+$/.test(a.config.id)&&(a=parseInt(a.config.id.split("_")[2],10),e.push(a))});0<e.length?(e=e.sort(function(a,b){return a>b}),this.maxStackId=e[e.length-1]):this.maxStackId=
0;this._arrangeWidgetsInEditingLayout()}));this.editingLayout.on("stackCreated",a.hitch(this,function(a){this.maxStackId++;a.config.id||(a.config.id="dd_group_"+this.maxStackId)}))},_arrangeWidgetsInEditingLayout:function(){c.forEach(this.appConfig.widgetOnScreen.groups,a.hitch(this,function(b){b=this.appConfig.getConfigElementById(b.id);var e=this.editingLayout.root.contentItems[0].getItemsById(b.id),d;e&&0<e.length&&"stack"===e[0].type&&(d=e[0]);d&&c.forEach(b.widgets,a.hitch(this,function(a,b){var e=
{id:a.id,type:"component",title:a.label,reorderEnabled:!1,componentName:"widget panel",componentState:{label:a.label}};d.contentItems.length>b?(b=d.contentItems[b],b.config.id=a.id,b.setTitle(a.label)):d.addChild(e)}))}))},_createActionBar:function(b){if(!this.actionBar){this.actionBar=g.create("div",{"class":"layout-actionbar"},b);this.dragCreateBtn=g.create("div",{"class":"jimu-btn jimu-float-leading jimu-leading-margin2 add-btn",innerHTML:this.nls.dragToAdd},this.actionBar);b=g.create("div",{"class":"jimu-btn-vacation jimu-float-trailing jimu-trailing-margin2 cancel-btn",
innerHTML:this.nls.cancel},this.actionBar);var e=g.create("div",{"class":"jimu-btn jimu-float-trailing save-btn",innerHTML:this.nls.ok},this.actionBar);this.own(m(b,"click",a.hitch(this,this._resetLayoutDefinition)));this.own(m(e,"click",a.hitch(this,this._saveLayoutDefinition)))}},_destroyActionBar:function(){g.destroy(this.actionBar);this.actionBar=null},_createLayout:function(b,e,c){return this._createLayoutDeferred&&!this._createLayoutDeferred.isResolved()?this._createLayoutDeferred.then(a.hitch(this,
function(){return this._doCreateLayout(b,e,c)})):this._doCreateLayout(b,e,c)},_doCreateLayout:function(b,e,c){var d=new n;this._createLayoutDeferred=new n;if(this.isEditing)return this._createEditingLayout();c?this._createNormalLayout().then(a.hitch(this,function(){this._createLayoutDeferred.resolve();d.resolve()})):b?this._createNormalLayout().then(a.hitch(this,this._loadOnScreenGroups)).then(a.hitch(this,this._reArrangeWidgetsLayout,e)).then(a.hitch(this,function(){this._createLayoutDeferred.resolve();
d.resolve()})):this._createNormalLayout().then(a.hitch(this,this._reArrangeWidgetsLayout,e)).then(a.hitch(this,function(){this._createLayoutDeferred.resolve();d.resolve()}));return d},_detachWidgets:function(b){if("stack"===b.type){for(;1<b.contentItems.length;)b.removeChild(b.contentItems[0],!0);var e=b.contentItems[0];b.addChild({type:"component",componentName:"widget panel",title:" ",isClosable:!1});b.removeChild(e,!0)}else c.forEach(b.contentItems,a.hitch(this,function(a){this._detachWidgets(a)}))},
_setupWidgets:function(b,e){b.isClosable=e;"component"!==b.type&&("stack"===b.type?0===b.content.length&&(b.content=[{type:"component",componentName:"widget panel",title:" ",isClosable:e}]):c.forEach(b.content,a.hitch(this,function(a){this._setupWidgets(a)})))},_onActivePanelChanged:function(b){var e;if(!this._isDestroying&&"widget panel"===b.componentName&&b.config.id){(e=this.dashboardPanels[b.config.id])&&e.domNode?(0===b.container.getElement().find(".jimu-panel").length&&(b.container.getElement().html(e.domNode),
b.container.on("resize",v(a.hitch(this,function(){0<b.container.width&&0<b.container.height&&e&&e.resize()}),200))),e.resize(),this.panelManager.openPanel(e)):this._loadDashboardWidget(b.config.id).then(a.hitch(this,function(e){e&&(b.container.getElement().html(e.domNode),b.container.on("resize",v(a.hitch(this,function(){0<b.container.width&&0<b.container.height&&e.resize()}),200)),e.resize(),this.panelManager.openPanel(e))}));var d=b.parent.config.id,r;c.some(this.appConfig.widgetOnScreen.groups,
a.hitch(this,function(a){if(a.id===d)return r=a.widgets,!0}));c.forEach(r,a.hitch(this,function(a){a.id!==b.config.id&&(e=this.dashboardPanels[a.id])&&this.panelManager.closePanel(e)}))}},_createNormalLayout:function(){var b=new n;this._isDestroying=!1;this.layoutContainer||(this.layoutContainer=g.create("div",{"class":"config"===this.appConfig.mode?"jimu-dnd-layout config":"jimu-dnd-layout"},this.layoutId),"config"===this.appConfig.mode&&(this.modifyLayoutBtn=g.create("div",{"class":"jimu-dnd-layout modify-btn",
innerHTML:'\x3cdiv class\x3d"jimu-ellipsis"\x3e\x3cspan class\x3d"feature-action icon-edit"\x3e\x3c/span\x3e'+this.nls.modifyLayout+"\x3c/div\x3e"},this.layoutId),this.own(m(this.modifyLayoutBtn,"click",a.hitch(this,function(){l.publish("editLayout")})))));c.some(this.appConfig.widgetOnScreen.widgets,function(a){if("themes/DashboardTheme/widgets/Header/Widget"===a.uri)return a.visible?f.setStyle(this.layoutContainer,"top","80px"):(this._removeHighLight(a.id),f.setStyle(this.layoutContainer,"top",
0)),!0},this);var e=this.layout,d=a.clone(this.appConfig.layoutDefinition.layout.config);"config"===this.appConfig.mode&&(d.settings.reorderEnabled=!1,d.settings.resizeEnabled=!1,d.settings.enableHeaderDragging=!1,d.dimensions={borderWidth:5,dragProxyWidth:0,dragProxyHeight:0});this._setupWidgets(d.content[0],!1);q(["libs/goldenlayout/goldenlayout"],a.hitch(this,function(r){"config"===this.appConfig.mode&&$(this.modifyLayoutBtn).removeClass("hidden");this.layout=new r(d,this.layoutContainer);this.layout.registerComponent("widget panel",
a.hitch(this,function(a,b){var e=a.parent.parent.config.id,d;b.widgetId||(b=this._addWidgetTipTemplate,c.some(this.appConfig.widgetOnScreen.groups,function(a){if(a.id===e)return"config"===this.appConfig.mode&&0===a.widgets.length&&(d=a.placeholderIndex),!0},this),d&&(b=b.replace("${groupIndex}",d),a.getElement().html(b)))}));this.layout.registerComponent("map",a.hitch(this,function(a){a.setTitle("");this.mapContainer=a.getElement();$("#"+this.mapId).appendTo(this.mapContainer);e&&(this._isDestroying=
!0,this._detachWidgets(e.root.contentItems[0]),e.destroy(),this._isDestroying=!1)}));this.layout.on("initialised",a.hitch(this,function(){b.resolve()}));this.layout.on("stackCreated",a.hitch(this,function(b){b.on("activeContentItemChanged",a.hitch(this,function(a){this._onActivePanelChanged(a)}))}));this.layout.init()}));return b},_createEditingLayout:function(){this.editContainer||(this.editContainer=g.create("div",{"class":"jimu-edit-layout hidden"},this.layoutId),this._createActionBar(this.editContainer),
this.editLayoutDiv=g.create("div",{"class":"layout-container"},this.editContainer));var b=this.editingLayout,e=a.clone(this.appConfig.layoutDefinition.layout.config);e.settings.enableHeaderDropping=!1;e.settings.reorderEnabled=!1;e.dimensions={borderWidth:5,dragProxyWidth:0,dragProxyHeight:0};this._setupWidgets(e.content[0],!0);q(["libs/goldenlayout/goldenlayout"],a.hitch(this,function(c){this.editingLayout=new c(e,this.editLayoutDiv);this.editingLayout.registerComponent("widget panel",a.hitch(this,
function(a){a.getElement().html("")}));this.editingLayout.registerComponent("map",a.hitch(this,function(a){a.setTitle("");a.getElement().html('\x3cdiv class\x3d"maptip"\x3e'+this.nls.sceneArea+"\x3c/div\x3e");b&&b.destroy()}));this._bindLayoutEvents();this.editingLayout.init()}))},_destroyLayout:function(){$("#"+this.mapId).appendTo("#"+this.layoutId);this.layout&&(this.layout.destroy(),this.layout=null,g.destroy(this.layoutContainer),this.layoutContainer=null,this.modifyLayoutBtn&&(g.destroy(this.modifyLayoutBtn),
this.modifyLayoutBtn=null));this.editingLayout&&(this._destroyActionBar(),this.editingLayout.destroy(),this.editingLayout=null,g.destroy(this.editContainer),this.editContainer=null)},destroyOnScreenWidgetsAndGroups:function(){this._destroyOnScreenWidgets();this._destroyOnScreenGroups()},onActionTriggered:function(a){if("editLayout"===a.action)this._enableEditing();else if("highLight"===a.action){var b=this._findContentItemById(a.elementId);b?b.isStack?$(b.element).addClass("highlight"):b.isComponent&&
$(b.tab.element).addClass("highlight"):(c.forEach(this.widgetPlaceholders,function(b){b.configId===a.elementId&&this._highLight(b)},this),c.forEach(this.onScreenWidgetIcons,function(b){b.configId===a.elementId&&this._highLight(b)},this),c.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(b){b.configId===a.elementId&&this._highLight(b)},this))}else"removeHighLight"===a.action?this._removeHighLight(a.elementId):"showLoading"===a.action?(f.setStyle(jimuConfig.loadingId,"display","block"),
f.setStyle(jimuConfig.mainPageId,"display","none")):"showApp"===a.action&&(f.setStyle(jimuConfig.loadingId,"display","none"),f.setStyle(jimuConfig.mainPageId,"display","block"))},_findContentItemById:function(a,e){return(a=this.layout.root.contentItems[0].getItemsById(a))&&0<a.length&&(!e||e===a[0].type)?a[0]:null},_highLight:function(a){if(a.domNode){this.hlDiv&&this._removeHighLight(a);var b=k.getMarginBox(a.domNode);this.hlDiv=g.create("div",{style:{position:"absolute",left:b.l+"px",top:b.t+"px",
width:b.w+"px",height:b.h+"px"},"class":"icon-highlight"},a.domNode,"before")}},_removeHighLight:function(a){/^dd_group_\d+$/.test(a)?(a=this._findContentItemById(a,"stack"))&&$(a.element).removeClass("highlight"):/^widgets_\w+_\d+$/.test(a)&&(a=this._findContentItemById(a,"component"))&&$(a.tab.element).removeClass("highlight");this.hlDiv&&(g.destroy(this.hlDiv),this.hlDiv=null)},onEnter:function(a,e){this.appConfig=a;this.isEditing=!1;this.createMapDiv(e);return this._createLayout(!1,!1,!0)},onLeave:function(){this._destroyLayout();
this.sceneView=null},onWidgetChange:function(a,e){this.appConfig=a;"themes/DashboardTheme/widgets/Header/Widget"===e.uri&&(e.visible?f.setStyle(this.layoutContainer,"top","80px"):(this._removeHighLight(e.id),f.setStyle(this.layoutContainer,"top",0)),this._resizeLayout());e=a.getConfigElementById(e.id);var b=this.dashboardPanels[e.id];if(b)b.reloadWidget(e),(a=this.layout.root.contentItems[0].getItemsByType("component"))&&0<a.length&&a.forEach(function(a){a.config.id===e.id&&a.config.title!==e.label&&
(a.config.title=e.label,a.setTitle(e.label))});else this.onOnScreenWidgetChange(a,e)},onOnScreenGroupsChange:function(a){this.appConfig=a;this._createLayout(!0,!1)},onGroupChange:function(a,e){this.appConfig=a;e=a.getConfigElementById(e.id);e.isOnScreen?this._createLayout(!0,!1):(c.forEach(this.widgetManager.getControllerWidgets(),function(b){b.isControlled(e.id)&&this.reloadControllerWidget(a,b.id)},this),c.forEach(this.panelManager.panels,function(a){a.config.id===e.id&&a.updateConfig(e)},this))},
_reArrangeWidgetsLayout:function(a){a&&this._destroyOnScreenWidgets();a&&this.loadOnScreenWidgets(this.appConfig);this._reArrangeWidgetsInDesktopLayout()},_reArrangeWidgetsInDesktopLayout:function(){c.forEach(this.appConfig.widgetOnScreen.groups,a.hitch(this,function(b){b=this.appConfig.getConfigElementById(b.id);var e=this._findContentItemById(b.id,"stack");e&&c.forEach(b.widgets,a.hitch(this,function(a,b){var c={id:a.id,type:"component",title:a.label,componentName:"widget panel",componentState:{widgetId:a.id}};
e.contentItems.length>b?(b=e.contentItems[b],b.config.id=a.id,b.config.title=a.label,b.config.componentState={widgetId:a.id},b.setTitle(a.label),e.setActiveContentItem(b)):e.addChild(c)}))}))},_loadDashboardWidget:function(b){var e=new n,d=this.dashboardPanels[b];if(d&&d.domNode)return e.resolve(this.dashboardPanels[b]),e;var f;c.some(this.appConfig.widgetOnScreen.groups,a.hitch(this,function(e){return c.some(e.widgets,a.hitch(this,function(a){if(a.id===b)return f=a,!0}))}));if(!f)return e.resolve(null),
e;var g=this.appConfig.layoutDefinition.layout.panel;q([g.uri],a.hitch(this,function(c){var d={config:f,uri:g.uri,sceneView:this.sceneView,widgetManager:this.widgetManager,panelManager:this.panelManager,id:b+"_panel",position:{}},h;a.mixin(d,f.options);try{h=new c(d),this.dashboardPanels[b]=h,e.resolve(h),console.log("panel ["+d.id+"] created.")}catch(x){console.log("create panel error: "+x+", panelId: "+d.id),e.reject(x)}}));return e},onLayoutDefinitionChange:function(a){this.appConfig=a;this._createLayout(!1,
!1)},onLayoutChange:function(b){this.isEditing||(this.appConfig=b,this._createLayout(!1,!1).then(a.hitch(this,function(){c.forEach(this.widgetPlaceholders,function(a){a.moveTo(b.getConfigElementById(a.configId).position)},this);c.forEach(this.onScreenWidgetIcons,function(a){a.moveTo(b.getConfigElementById(a.configId).position)},this);c.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(a){if(!a.closeable){var c=b.getConfigElementById(a.id).position;a.setPosition(c)}},this)})))},openWidget:function(a){var b;
(a=this._findContentItemById(a,"component"))&&(b=a.parent)&&b.isStack&&b.setActiveContentItem(a)},_loadOnScreenGroups:function(){var b=this.appConfig.widgetOnScreen.groups,e=[],d=new n;c.forEach(b,a.hitch(this,function(a){a=this.appConfig.getConfigElementById(a.id);c.forEach(a.widgets,function(a){e.push(a.id)})}));c.forEach(this.dashboardWidgets,a.hitch(this,function(a){if(0>e.indexOf(a)){var b=this.dashboardPanels[a];b&&(this.panelManager.closePanel(b),b.destroy());this.dashboardPanels[a]=null}}));
this.dashboardWidgets=e;d.resolve();return d},_destroyOnScreenWidgets:function(){this.destroyOnScreenOffPanelWidgets();this.destroyWidgetPlaceholders();this.destroyOnScreenWidgetIcons()},_destroyOnScreenGroups:function(){c.forEach(this.dashboardWidgets,a.hitch(this,function(a){if(a=this.dashboardPanels[a])this.panelManager.closePanel(a),a.destroy(),a=null}));this.panelManager.destroyAllPanels();this.dashboardWidgets=[];this.dashboardPanels={}}});w.getInstance=function(a,c){null===u&&(u=new w(a,c),
window._layoutManager=u);return u};return w});