//>>built
define("dojo/_base/lang dojo/_base/array esri/core/declare esri/core/lang esri/views/3d/webgl-engine/lib/Util esri/views/3d/webgl-engine/lib/gl-matrix esri/views/3d/support/projectionUtils ../../webgl-engine-extensions/VertexBufferLayout ../../webgl-engine-extensions/GLXBO ../../webgl-engine-extensions/GLVertexArrayObject ../../support/fx3dUtils ../../support/fx3dUnits ../Effect ./PointExtrudeMaterial".split(" "),function(w,E,F,q,x,r,G,H,A,I,h,k,B,J){var C=r.vec3d,l=r.mat4d,D=r.mat4,m=x.VertexAttrConstants,
K=x.setMatrixTranslation3,t=C.create();l.identity();tmpTranslationOriginMat=l.identity();tmpTransformationRelToOrigin=l.create();tmpInvTranspTransformation=l.create();renderObjectItem=null;tmpViewMat=D.create();return F([B],{declaredClass:"esri.views.3d.effects.PointExtrude.PointExtrudeEffect",effectName:"PointExtrude",constructor:function(b){this.orderId=2;this._sizeInMeters=[];this.localOriginFactory=B.createLocalOriginFactory();this._renderObjects={}},_initRenderingInfo:function(){this.renderingInfo.radius=
6E4;this.renderingInfo.height=8E5;this.renderingInfo.topColors=[h.rgbNames.cadetblue,h.rgbNames.yellowgreen,h.rgbNames.lightpink,h.rgbNames.orangered,h.rgbNames.green,h.rgbNames.indianred];this._colorBarDirty=!0;this.renderingInfo.bottomColor=[0,255,0];this.renderingInfo.shapeType="cylinder";this._renderingInfoDirty=!0;this._segments=32;this._shapeDirty=this._vacDirty=!0;this.inherited(arguments)},_doRenderingInfoChange:function(b){this.inherited(arguments);for(var a in b)b.hasOwnProperty(a)&&this.renderingInfo.hasOwnProperty(a)&&
(q.endsWith(a.toLowerCase(),"info")?h.isInforAttrChanged(this.renderingInfo[a],b[a])&&(this._renderingInfoDirty=!0):q.endsWith(a.toLowerCase(),"color")?b[a]instanceof Array&&3==b[a].length&&(this.renderingInfo[a]=[b[a][0]/255,b[a][1]/255,b[a][2]/255]):q.endsWith(a.toLowerCase(),"colors")?b[a]instanceof Array&&(this.renderingInfo[a]=b[a],this._colorBarDirty=!0,this._renderingInfoDirty=!0):"shapetype"===a.toLowerCase()?this.renderingInfo[a]!=b[a].toLowerCase()&&(this._vacDirty=!0,this._shapeDirty=!0,
this._isAddingGeometry=!1,this._renderingInfoDirty=!0,this.renderingInfo[a]=b[a].toLowerCase(),"cuboid"===this.renderingInfo[a]?this._segments=4:"hexahedron"===this.renderingInfo[a]?this._segments=6:"cylinder"===this.renderingInfo[a]&&(this._segments=32)):"radius"===a.toLowerCase()||"height"===a.toLowerCase()||"transparency"===a.toLowerCase()?(this._clampScope(b,a),"radius"==a&&this._radiusUnit?this.renderingInfo[a]=k.toMeters(this._radiusUnit,b[a],this._view.viewingMode):"height"==a&&this._heightUnit?
(this.renderingInfo[a]=k.toMeters(this._heightUnit,b[a],this._view.viewingMode),this._updateDefaultLabelHeight()):this.renderingInfo[a]=b[a]):typeof b[a]==typeof this.renderingInfo[a]&&(this.renderingInfo[a]=b[a]))},_updateDefaultLabelHeight:function(){this._layer._labelDefaultHeight={flag:1,min:this._scopes.height[0],max:this.renderingInfo.height}},setContext:function(b){this.inherited(arguments);this._effectConfig&&w.isArray(this._effectConfig.renderingInfo)&&(this._radiusUnit=null,this._heightUnit=
null,E.forEach(this._effectConfig.renderingInfo,function(a){"radius"===a.name.toLowerCase()?(this._radiusUnit=a.unit,this.renderingInfo.radius=k.toMeters(this._radiusUnit,this.renderingInfo.radius,this._view.viewingMode)):"height"===a.name.toLowerCase()&&(this._heightUnit=a.unit,this.renderingInfo.height=k.toMeters(this._heightUnit,this.renderingInfo.height,this._view.viewingMode),this._updateDefaultLabelHeight())}.bind(this)))},destroy:function(){this._resetBuffers()},_resetBuffers:function(){for(var b in this._renderObjects)this._dispose(this._renderObjects[b].vbo),
this._dispose(this._renderObjects[b].ibo),this._dispose(this._renderObjects[b].vao);this._renderObjects={}},_initVertexLayout:function(){this._vertexBufferLayout=new H([m.POSITION,m.AUXPOS1,m.NORMAL,m.AUXPOS2],[3,3,3,3],[5126,5126,5126,5126])},_initRenderContext:function(){if(this.inherited(arguments),this._vacDirty)if(this._initVertexLayout(),this._vacDirty=!1,this._isAddingGeometry)for(var b in this._renderObjects)this._unBindBuffer(this._renderObjects[b].vao,this._renderObjects[b].vbo,this._renderObjects[b].ibo),
this._renderObjects[b].vao&&(this._renderObjects[b].vao._initialized=!1);else this._resetBuffers();return this._geometryVertexNum=2*this._segments,this._geometryIndexNum=3*(2*this._segments+(this._segments-2)),this._localBindsCallback||(this._localBindsCallback=this._localBinds.bind(this)),this._buildPolyHedronGeometries()},_buildPolyHedronGeometries:function(){var b=this._isAddingGeometry?this._addedGraphics:this._allGraphics(),a=this._isAddingGeometry?this._toAddGraphicsIndex:0;if(0<b.length){var f,
u,c,e,d,g,n,p,v,k,m,q,r,w=(this._vertexBufferLayout.getStride(),2*Math.PI),x=1/this._segments;for(u=0;u<b.length;u++)if(f=b[u].geometry,null!=f){C.set3(f.longitude,f.latitude,f.altitude||1,t);d=l.create();G.computeLinearTransformation(this._wgs84SpatialReference,t,d,this.view.renderSpatialReference);"global"===this._view.viewingMode?h.wgs84ToSphericalEngineCoords(t,0,t,0):"local"===this._view.viewingMode&&h.wgs84ToWebMerc(t,0,t,0);e=this.localOriginFactory.getOrigin(t);this._renderObjects[e.id]||
(this._renderObjects[e.id]={vbo:new A(this._gl,!0,this._vertexBufferLayout),ibo:new A(this._gl,!1),vao:this._vaoExt?new I(this._gl,this._vaoExt):null,offset:0,origin:e.vec3});e=this._renderObjects[e.id];K(tmpTranslationOriginMat,-e.origin[0],-e.origin[1],-e.origin[2]);l.multiply(tmpTranslationOriginMat,d,tmpTransformationRelToOrigin);l.inverse(tmpTransformationRelToOrigin,tmpInvTranspTransformation);l.transpose(tmpInvTranspTransformation);n=g=0;p=1;m=tmpInvTranspTransformation[0]*g+tmpInvTranspTransformation[4]*
n+tmpInvTranspTransformation[8]*p+tmpInvTranspTransformation[12];q=tmpInvTranspTransformation[1]*g+tmpInvTranspTransformation[5]*n+tmpInvTranspTransformation[9]*p+tmpInvTranspTransformation[13];r=tmpInvTranspTransformation[2]*g+tmpInvTranspTransformation[6]*n+tmpInvTranspTransformation[10]*p+tmpInvTranspTransformation[14];var z=[],y=[];d=e.offset;for(c=0;c<this._segments;c++)v=w*c*x,g=Math.cos(v),n=Math.sin(v),p=0,v=tmpTransformationRelToOrigin[0]*g+tmpTransformationRelToOrigin[4]*n+tmpTransformationRelToOrigin[8]*
p,k=tmpTransformationRelToOrigin[1]*g+tmpTransformationRelToOrigin[5]*n+tmpTransformationRelToOrigin[9]*p,g=tmpTransformationRelToOrigin[2]*g+tmpTransformationRelToOrigin[6]*n+tmpTransformationRelToOrigin[10]*p,z.push(v,k,g,tmpTransformationRelToOrigin[12],tmpTransformationRelToOrigin[13],tmpTransformationRelToOrigin[14],m,q,r,u+a,c,0),z.push(v,k,g,tmpTransformationRelToOrigin[12],tmpTransformationRelToOrigin[13],tmpTransformationRelToOrigin[14],m,q,r,u+a,c,1),c!==this._segments-1?y.push(2*c+d,2*
c+2+d,2*c+3+d,2*c+d,2*c+3+d,2*c+1+d):y.push(2*c+d,0+d,1+d,2*c+d,1+d,2*c+1+d);for(c=0;c<this._segments-2;c++)y.push(1+d,2*c+3+d,2*c+5+d);e.vbo.addData(!0,new Float32Array(z));e.offset+=this._geometryVertexNum;e.ibo.addData(!0,new Uint32Array(y));e.vao&&(e.vao._initialized=!1)}return this._resetAddGeometries(),!0}return!1},_loadShaders:function(){return this.inherited(arguments),this._material||(this._material=new J({pushState:this._pushState.bind(this),restoreState:this._restoreState.bind(this),gl:this._gl,
viewingMode:this._view.viewingMode,shaderSnippets:this._shaderSnippets})),this._material.loadShaders()},_initColorBar:function(){if(!this._colorBarDirty)return!0;this._colorBarTexture||(this._colorBarTexture=this._gl.createTexture());var b=this._gl.getParameter(32873);this._gl.bindTexture(3553,this._colorBarTexture);this._gl.pixelStorei(37440,!0);this._gl.texParameteri(3553,10240,9728);this._gl.texParameteri(3553,10241,9728);this._gl.texParameteri(3553,10242,33071);this._gl.texParameteri(3553,10243,
33071);var a=h.createColorBarTexture(32,1,this.renderingInfo.topColors);return this._gl.texImage2D(3553,0,6408,6408,5121,a),this._gl.generateMipmap(3553),this._gl.bindTexture(3553,b),0===this._gl.getError()},_localBinds:function(b,a){b.bind(this._material._program);this._vertexBufferLayout.enableVertexAttribArrays(this._gl,this._material._program);a.bind()},_bindBuffer:function(b,a,f){b?(b._initialized||b.initialize(this._localBindsCallback,[a,f]),b.bind()):this._localBinds(a,f)},_unBindBuffer:function(b,
a,f){b?b.unbind():(a.unbind(),this._vertexBufferLayout.disableVertexAttribArrays(this._gl,this._material._program),f.unbind())},render:function(b,a){if(this.inherited(arguments),this._layer.visible&&this.ready&&this._bindPramsReady()){this._hasSentReady||(this._layer.emit("fx3d-ready"),this._hasSentReady=!0);this._sizeInMeters[0]=this.renderingInfo.radius;this._sizeInMeters[1]=this._scopes.height[0];this._sizeInMeters[2]=this.renderingInfo.height;this._material.bind(w.mixin({},{pp:this._vizFieldVerTextures[this._vizFieldDefault],
sp:this._vizFieldVerTextures[this._vizFields[this._currentVizPage]],op:this._vizFieldVerTextureSize,mo:this.renderingInfo.animationInterval,oi:this._sizeInMeters,pl:this.renderingInfo.transparency,lp:this.renderingInfo.bottomColor,el:this._vizFieldMinMaxs[this._vizFieldDefault].min>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min?this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min:this._vizFieldMinMaxs[this._vizFieldDefault].min,pm:this._vizFieldMinMaxs[this._vizFieldDefault].max>
this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max?this._vizFieldMinMaxs[this._vizFieldDefault].max:this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max,lm:1/this._segments,ss:this._colorBarTexture},b),a);for(var f in this._renderObjects)renderObjectItem=this._renderObjects[f],D.translate(b.view,renderObjectItem.origin,tmpViewMat),this._material.bindMat4("viewMat",tmpViewMat),this._material.bindVec3fv("origin",renderObjectItem.origin),this._material.bindVec3f("camPos",b.viewInvTransp[3]-
renderObjectItem.origin[0],b.viewInvTransp[7]-renderObjectItem.origin[1],b.viewInvTransp[11]-renderObjectItem.origin[2]),this._bindBuffer(renderObjectItem.vao,renderObjectItem.vbo,renderObjectItem.ibo),this._gl.drawElements(4,renderObjectItem.ibo.getNum(),5125,0);this._material.release(a);this._unBindBuffer(renderObjectItem.vao,renderObjectItem.vbo,renderObjectItem.ibo)}}})});