//>>built
define("dojo/_base/lang dojo/_base/array esri/core/declare esri/core/lang esri/views/3d/webgl-engine/lib/Util esri/core/libs/gl-matrix-2/vec3f64 esri/core/libs/gl-matrix-2/vec2f64 esri/core/libs/gl-matrix-2/vec3 esri/core/libs/gl-matrix-2/vec2 ../../webgl-engine-extensions/VertexBufferLayout ../../webgl-engine-extensions/GLVertexArrayObject ../../webgl-engine-extensions/GLXBO ../../webgl-engine-extensions/GLVerTexture ../../support/fx3dUtils ../../support/fx3dUnits ../Effect ./JetTrailMaterial".split(" "),
function(n,y,B,k,C,D,E,t,w,F,x,p,G,g,q,H,I){k=D.vec3f64;t=t.vec3;var J=E.vec2f64;w=w.vec2;var u=k.create(),v=k.create(),z=k.create(),m=0,A=C.VertexAttrConstants;return B([H],{declaredClass:"esri.views.3d.effects.JetTrail.JetTrailEffect",effectName:"JetTrail",constructor:function(b){n.hitch(this,b);this.orderId=2;this._needsAllLoaded=!0},_initRenderingInfo:function(){this.renderingInfo.radius=20;this.renderingInfo.pulseRadius=1E5;this.renderingInfo.colors=[g.rgbNames.cadetblue,g.rgbNames.yellowgreen,
g.rgbNames.lightpink,g.rgbNames.orangered,g.rgbNames.green,g.rgbNames.indianred];this._renderingInfoDirty=this._colorBarDirty=this.renderingInfo.showEndPoints=!0;this._curveType=1;this._shapeDirty=this._vacDirty=!0;this._needsRenderPulse=!1;this.inherited(arguments)},_doRenderingInfoChange:function(b){this.inherited(arguments);for(var a in b)b.hasOwnProperty(a)&&this.renderingInfo.hasOwnProperty(a)&&(g.endsWith(a.toLowerCase(),"info")?g.isInforAttrChanged(this.renderingInfo[a],b[a])&&(this._renderingInfoDirty=
!0):g.endsWith(a.toLowerCase(),"colors")?b[a]instanceof Array&&(this.renderingInfo[a]=b[a],this._colorBarDirty=!0,this._renderingInfoDirty=!0):"radius"===a.toLowerCase()||"pulseRadius"===a.toLowerCase()||"transparency"===a.toLowerCase()?(this._clampScope(b,a),"radius"==a&&this._radiusUnit?this.renderingInfo[a]=q.toMeters(this._radiusUnit,b[a],this._view.viewingMode):"pulseRadius"==a&&this._pulseRadiusUnit?this.renderingInfo[a]=q.toMeters(this._pulseRadiusUnit,b[a],this._view.viewingMode):this.renderingInfo[a]=
b[a]):typeof b[a]==typeof this.renderingInfo[a]&&(this.renderingInfo[a]=b[a]))},setContext:function(b){this.inherited(arguments);this._effectConfig&&n.isArray(this._effectConfig.renderingInfo)&&(this._radiusUnit=null,this._pulseRadiusUnit=null,y.forEach(this._effectConfig.renderingInfo,function(a){"radius"===a.name.toLowerCase()?(this._radiusUnit=a.unit,this.renderingInfo.radius=q.toMeters(this._radiusUnit,this.renderingInfo.radius,this._view.viewingMode)):"pulseRadius"===a.name.toLowerCase()&&(this._pulseRadiusUnit=
a.unit,this.renderingInfo.pulseRadius=q.toMeters(this._pulseRadiusUnit,this.renderingInfo.pulseRadius,this._view.viewingMode))}.bind(this)),this._aroundVerticesTexture=new G(this._gl),this._aroundVerticesTextureSize=J.create())},destroy:function(){this._resetXBOs();this._dispose("_aroundVerticesTexture");this._dispose("_headVAO");this._dispose("_tailVAO");this._dispose("_pulseVAO")},_resetXBOs:function(){this._dispose("_headVBO");this._dispose("_tailVBO");this._dispose("_tailIBO");this._dispose("_pulseVBO");
this._dispose("_pulseIBO");this._needsRenderPulse=!1},_initVertexLayout:function(){this._vertexAttrConstants=[A.AUXPOS1,A.AUXPOS2];this._vertexBufferLayout=new F(this._vertexAttrConstants,[2,3],[5126,5126])},_initRenderContext:function(){return this.inherited(arguments),this._vacDirty&&(this._initVertexLayout(),this._resetXBOs(),this._vacDirty=!1,this._headVAO&&(this._headVAO.unbind(),this._headVAO._initialized=!1),this._tailVAO&&(this._tailVAO.unbind(),this._tailVAO._initialized=!1),this._pulseVAO&&
(this._pulseVAO.unbind(),this._pulseVAO._initialized=!1)),this._headVBO||(this._headVBO=new p(this._gl,!0,this._vertexBufferLayout)),this._tailVBO||(this._tailVBO=new p(this._gl,!0,this._vertexBufferLayout)),this._tailIBO||(this._tailIBO=new p(this._gl,!1)),this._pulseVBO||(this._pulseVBO=new p(this._gl,!0,this._vertexBufferLayout)),this._pulseIBO||(this._pulseIBO=new p(this._gl,!1)),this._vaoExt&&(this._headVAO=new x(this._gl,this._vaoExt),this._tailVAO=new x(this._gl,this._vaoExt),this._pulseVAO=
new x(this._gl,this._vaoExt)),this._localBindsCallback||(this._localBindsCallback=this._localBinds.bind(this)),1===this._curveType?this._buildAroundPathGeometries():0===this._curveType&&this._buildAlongPathGeometries()},_buildAroundPathGeometries:function(){if(!this._needsAllLoaded)return console.warn("All features should be loaded first."),!1;var b=this._allGraphics();if(0<b.length){var a,c,d,e,f,r,h,l=[],m=[],p=[],n=0,k=[];return this._pathIdNum=0,y.forEach(b,function(b,q){if(null!==b.geometry)for(f=
b.geometry.paths,r=0;r<f.length;r++)if(!(2>f[r].length)){a=f[r][0];null==a[2]&&(a[2]=1.11);c=f[r][f[r].length-1];null==c[2]&&(c[2]=1.11);t.set(u,a[0],a[1],a[2]);"global"===this._view.viewingMode?g.wgs84ToSphericalEngineCoords(u,0,u,0):"local"===this._view.viewingMode&&g.wgs84ToWebMerc(u,0,u,0);t.set(v,c[0],c[1],c[2]);"global"===this._view.viewingMode?g.wgs84ToSphericalEngineCoords(v,0,v,0):"local"===this._view.viewingMode&&g.wgs84ToWebMerc(v,0,v,0);t.subtract(z,u,v);e=t.length(z);"global"===this._view.viewingMode?
d=1E3>=e?32:1E4>=e?24:5E5>=e?18:1E6>=e?40:Math.floor(1E-5*e):"local"===this._view.viewingMode&&(d=1E3>=e?48:1E4>=e?42:1E5>=e?32:1E6>=e?24:2E6>=e?36:Math.floor(6E-6*e));d=2*d-1;d=Math.max(5,Math.floor(.26*d));l.push(this._pathIdNum,q,1,d-1,d-1);k.push([a[0],a[1],a[2]]);k.push([c[0],c[1],c[2]]);for(h=0;h<d;h++)m.push(this._pathIdNum,q,4,h,d-1),h<d-1&&p.push(n+h,n+h+1);this._pathIdNum++;n+=d}}.bind(this)),this._headVBO.addData(!1,new Float32Array(l)),this._tailVBO.addData(!1,new Float32Array(m)),this._tailIBO.addData(!1,
new Uint32Array(p)),this._headVAO&&(this._headVAO._initialized=!1),this._tailVAO&&(this._tailVAO._initialized=!1),this._resetAddGeometries(),this._initAroundVerticesTexture(k)&&this._initPulseGeometries(k)}return!1},_buildAlongPathGeometries:function(){return!1},_initAroundVerticesTexture:function(b){if(2*this._pathIdNum!==b.length)return console.warn("The quantity of paths and points is invalid."),!1;var a=this._gl.getParameter(3379),c=2*this._pathIdNum,d=g.nextHighestPowerOfTwo(c);d>a&&(d=a,console.warn("Too many graphics, and some data will be discarded."));
c=Math.ceil(c/d);c=g.nextHighestPowerOfTwo(c);c>a&&(c=a,console.warn("Too many graphics, and some data will be discarded."));for(var e,f=new Float32Array(d*c*4),a=0;a<this._pathIdNum;a++)e=8*a,f[0+e]=a,f[1+e]=b[2*a][0],f[2+e]=b[2*a][1],f[3+e]=b[2*a][2],f[4+e]=a,f[5+e]=b[2*a+1][0],f[6+e]=b[2*a+1][1],f[7+e]=b[2*a+1][2];return this._aroundVerticesTexture.setData(d,c,f),w.set(this._aroundVerticesTextureSize,d,c),!0},_initPulseGeometries:function(b){if(2*this._pathIdNum!==b.length)return console.warn("The quantity of paths and points is invalid."),
!1;if(0<b.length){var a,c,d,e,f,g=this._vertexBufferLayout.getStride(),h=new Float32Array(41*g*this._pathIdNum),l=new Uint32Array(120*this._pathIdNum),k=2*Math.PI;for(a=0;a<this._pathIdNum;a++){e=41*a*g;f=b[2*a+1];h[e+2]=f[0];h[e+3]=f[1];h[e+4]=f[2];h[e+0]=-1;h[e+1]=a;e+=g;for(c=0;40>c;c++)d=e+g*c,h[d+2]=f[0],h[d+3]=f[1],h[d+4]=f[2],h[d+0]=c/40*k,h[d+1]=a;f=41*a;e=3*f;for(c=0;39>c;c++)d=e+3*c,l[d+0]=0+f,l[d+1]=c+1+f,l[d+2]=c+2+f;d=e+117;l[d+0]=0+f;l[d+1]=40+f;l[d+2]=1+f}return this._pulseVBO.addData(!1,
h),this._pulseIBO.addData(!1,l),this._pulseVAO&&(this._pulseVAO._initialized=!1),!0}return!1},_initColourMap:function(){this._colourMapTexture||(this._colourMapTexture=this._gl.createTexture());var b=new Image;b.src=g.spriteImg;var a=this;return b.onload=function(){var c=a._gl.getParameter(a._gl.TEXTURE_BINDING_2D);a._gl.bindTexture(3553,a._colourMapTexture);a._gl.pixelStorei(37440,!0);a._gl.texParameteri(3553,10240,9728);a._gl.texParameteri(3553,10241,9728);a._gl.texParameteri(3553,10242,33071);
a._gl.texParameteri(3553,10243,33071);a._gl.texImage2D(3553,0,6408,6408,5121,b);a._gl.generateMipmap(3553);a._gl.bindTexture(3553,c)},0===this._gl.getError()},_loadShaders:function(){return this.inherited(arguments),this._material||(this._material=new I({pushState:this._pushState.bind(this),restoreState:this._restoreState.bind(this),gl:this._gl,viewingMode:this._view.viewingMode,shaderSnippets:this._shaderSnippets})),this._material.loadShaders()},_initColorBar:function(){if(!this._colorBarDirty)return!0;
this._colorBarTexture||(this._colorBarTexture=this._gl.createTexture());var b=this._gl.getParameter(32873);this._gl.bindTexture(3553,this._colorBarTexture);this._gl.pixelStorei(37440,!0);this._gl.texParameteri(3553,10240,9728);this._gl.texParameteri(3553,10241,9728);this._gl.texParameteri(3553,10242,33071);this._gl.texParameteri(3553,10243,33071);var a=g.createColorBarTexture(32,1,this.renderingInfo.colors);return this._gl.texImage2D(3553,0,6408,6408,5121,a),this._gl.generateMipmap(3553),this._gl.bindTexture(3553,
b),0===this._gl.getError()},_localBinds:function(b,a,c){b.bind(c);this._vertexBufferLayout.enableVertexAttribArrays(this._gl,c);a&&a.bind()},_bindBuffer:function(b,a,c,d){b?(b._initialized||b.initialize(this._localBindsCallback,[a,c,d]),b.bind()):this._localBinds(a,c,d)},_unBindBuffer:function(b,a,c,d){b?b.unbind():(a.unbind(),this._vertexBufferLayout.disableVertexAttribArrays(this._gl,d),c&&c.unbind())},render:function(b,a){this.inherited(arguments);this._layer.visible&&this.ready&&this._bindPramsReady()&&
(this._hasSentReady||(this._layer.emit("fx3d-ready"),this._hasSentReady=!0),this._material.bind(n.mixin({},{se:this._aroundVerticesTexture,pl:this._aroundVerticesTextureSize,ip:this._colourMapTexture,pm:this._vizFieldVerTextures[this._vizFields[this._currentVizPage]],im:this._vizFieldVerTextureSize,lp:this.renderingInfo.animationInterval,ss:this.renderingInfo.radius,ll:this.renderingInfo.transparency,mp:this._vizFieldMinMaxs[this._vizFieldDefault].min>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min?
this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min:this._vizFieldMinMaxs[this._vizFieldDefault].min,mm:this._vizFieldMinMaxs[this._vizFieldDefault].max>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max?this._vizFieldMinMaxs[this._vizFieldDefault].max:this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max,ls:this._colorBarTexture},b),a),this._material.blend(!0,a),this._bindBuffer(this._tailVAO,this._tailVBO,this._tailIBO,this._material._program),this._gl.drawElements(1,
this._tailIBO.getNum(),5125,0),this._unBindBuffer(this._tailVAO,this._tailVBO,this._tailIBO,this._material._program),this._material.blend(!1,a),this._bindBuffer(this._headVAO,this._headVBO,null,this._material._program),this._gl.drawArrays(0,0,this._headVBO.getNum()),this._unBindBuffer(this._headVAO,this._headVBO,null,this._material._program),this._needsRenderPulse||(m=this.time/this.renderingInfo.animationInterval,.8<m-Math.floor(m)&&(this._needsRenderPulse=!0)),this._needsRenderPulse&&(this.renderingInfo.showEndPoints&&
(this._material.bindPulse(n.mixin({},{pm:this._vizFieldVerTextures[this._vizFields[this._currentVizPage]],im:this._vizFieldVerTextureSize,lp:this.renderingInfo.animationInterval,es:[this._scopes.pulseRadius[0]>this._layerView._minDelta?this._layerView._minDelta||10:this._scopes.pulseRadius[0],this.renderingInfo.pulseRadius>this._layerView._minDelta?this._layerView._minDelta||10:this.renderingInfo.pulseRadius],ll:this.renderingInfo.transparency,mp:this._vizFieldMinMaxs[this._vizFieldDefault].min>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min?
this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min:this._vizFieldMinMaxs[this._vizFieldDefault].min,mm:this._vizFieldMinMaxs[this._vizFieldDefault].max>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max?this._vizFieldMinMaxs[this._vizFieldDefault].max:this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max,ls:this._colorBarTexture},b),a),this._material.blend(!0,a),this._bindBuffer(this._pulseVAO,this._pulseVBO,this._pulseIBO,this._material._pulseProgram),this._gl.drawElements(4,
this._pulseIBO.getNum(),5125,0),this._unBindBuffer(this._pulseVAO,this._pulseVBO,this._pulseIBO,this._material._pulseProgram)),m=this.time/this.renderingInfo.animationInterval,.79<m-Math.floor(m)&&(this._needsRenderPulse=!1)),this._material.release(a))}})});