// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"esri/widgets/Locate":function(){define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/accessorSupport/decorators ./support/widget ./Widget ./Locate/LocateViewModel dojo/i18n!./Locate/nls/Locate".split(" "),function(h,n,c,d,e,f,k,m,l){return function(h){function a(b){b=h.call(this)||this;b.geolocationOptions=null;b.goToLocationEnabled=null;b.graphic=null;b.view=null;b.viewModel=new m;return b}c(a,h);a.prototype.locate=function(){};
a.prototype.render=function(){var b=this.get("viewModel.state"),a="locating"===b,e=(c={},c["esri-disabled"]="disabled"===b,c["esri-hidden"]="feature-unsupported"===b,c),a=(d={},d["esri-icon-loading-indicator"]=a,d["esri-rotating"]=a,d["esri-icon-locate"]=!a,d);return f.tsx("div",{bind:this,class:"esri-locate esri-widget-button esri-widget",classes:e,hidden:"feature-unsupported"===b,onclick:this._locate,onkeydown:this._locate,role:"button",tabIndex:0,"aria-label":l.title,title:l.title},f.tsx("span",
{classes:a,"aria-hidden":"true",class:f.join("esri-icon","esri-icon-locate")}),f.tsx("span",{class:"esri-icon-font-fallback-text"},l.title));var c,d};a.prototype._locate=function(){this.locate()};d([e.aliasOf("viewModel.geolocationOptions")],a.prototype,"geolocationOptions",void 0);d([e.aliasOf("viewModel.goToLocationEnabled")],a.prototype,"goToLocationEnabled",void 0);d([e.aliasOf("viewModel.graphic")],a.prototype,"graphic",void 0);d([e.aliasOf("viewModel.view")],a.prototype,"view",void 0);d([e.property({type:m}),
f.renderable("viewModel.state"),f.vmEvent(["locate","locate-error"])],a.prototype,"viewModel",void 0);d([e.aliasOf("viewModel.locate")],a.prototype,"locate",null);d([f.accessibleHandler()],a.prototype,"_locate",null);return a=d([e.subclass("esri.widgets.Locate")],a)}(e.declared(k))})},"esri/widgets/Locate/LocateViewModel":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/accessorSupport/decorators ../../core/promiseUtils ../../core/Error dojo/Deferred ../support/GeolocationPositioning".split(" "),
function(h,n,c,d,e,f,k,m,l){return function(h){function a(b){b=h.call(this,b)||this;b.locate=b.locate.bind(b);return b}c(a,h);a.prototype.destroy=function(){this._locating&&(this._locating.cancel(),this._locating=null)};Object.defineProperty(a.prototype,"state",{get:function(){return this._geolocationUsable?this.get("view.ready")?this._locating?"locating":"ready":"disabled":"feature-unsupported"},enumerable:!0,configurable:!0});a.prototype.locate=function(){var b=this;if("disabled"===this.state)return f.reject(new k("locate:disabled-state",
"Cannot locate when disabled."));if("feature-unsupported"===this.state)return f.reject(new k("locate:feature-unsupported-state","Cannot locate in unsecure domain."));this._locating&&(this._locating.cancel(),this._locating=null);var a=this._getCurrentPosition(this.geolocationOptions).then(function(a){return b._setPosition(a)}).then(function(a){b.view.graphics.remove(b.graphic);b.graphic&&(b.graphic=b.graphic.clone(),b.view.graphics.push(b.graphic));b.emit("locate",{position:a});return a}).otherwise(function(a){b.emit("locate-error",
{error:a});throw a;});this._locating=a;this.notifyChange("state");return f.timeout(a,15E3,void 0).then(function(a){b._locating=null;b.notifyChange("state");return a}).otherwise(function(a){b._locating.cancel();b._locating=null;b.notifyChange("state");throw a;})};a.prototype._getCurrentPosition=function(a){var b=new m;navigator.geolocation.getCurrentPosition(b.resolve,b.reject,a);return b.promise};d([e.property({dependsOn:["view.ready"],readOnly:!0})],a.prototype,"state",null);d([e.property()],a.prototype,
"locate",null);return a=d([e.subclass("esri.widgets.Locate.LocateViewModel")],a)}(e.declared(l))})},"esri/widgets/support/GeolocationPositioning":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/accessorSupport/decorators ../../geometry/support/webMercatorUtils ../../config ../../Graphic ../../core/Accessor ../../core/Error ../../core/Evented ../../core/promiseUtils ../../geometry/Point ../../portal/Portal ../../symbols/PictureMarkerSymbol ../../tasks/support/ProjectParameters ../../tasks/GeometryService dojo/_base/lang".split(" "),
function(h,n,c,d,e,f,k,m,l,p,a,b,q,t,r,u,v,w){return function(a){function g(){var b=null!==a&&a.apply(this,arguments)||this;b._geolocationUsable=!0;b._iconPath=h.toUrl("../../images/support/sdk_gps_location.png");b.geolocationOptions={maximumAge:0,timeout:15E3,enableHighAccuracy:!0};b.goToLocationEnabled=!0;b.graphic=new m({symbol:new r({url:b._iconPath,width:21,height:21})});b.scale=null;b.view=null;return b}c(g,a);g.prototype.initialize=function(){var b=navigator.geolocation,a=window.hasOwnProperty("isSecureContext"),
a=a&&window.isSecureContext||!a&&"https:"===window.location.protocol;a&&b||(this._geolocationUsable=!1);b||console.log(this.declaredClass,"navigator.geolocation unsupported.");a||console.log(this.declaredClass,"navigator.geolocation requires a secure origin.")};g.prototype.destroy=function(){this._clear();this.view=null};g.prototype._clear=function(){this.view&&this.view.graphics.remove(this.graphic)};g.prototype._clonePosition=function(b){return b?{coords:w.mixin({},b.coords),timestamp:b.timestamp}:
b};g.prototype._getGeometryServiceUrl=function(){if(k.geometryServiceUrl)return b.resolve(k.geometryServiceUrl);var a=t.getDefault();return a.load().always(function(){return a.get("helperServices.geometry.url")})};g.prototype._projectPoint=function(a){var d=this.get("view.spatialReference");return d.isWGS84?b.resolve(a):d.isWebMercator?b.resolve(f.geographicToWebMercator(a)):this._getGeometryServiceUrl().then(function(c){if(!c)return b.reject(new p("geometry-service:missing-url","Geometry service URL is missing"));
c=new v({url:c});var e=new u({geometries:[a],outSR:d});return c.project(e).then(function(a){return a[0]})})};g.prototype._getScale=function(a){a=a&&a.coords&&a.coords.accuracy;return this.scale||a||5E4};g.prototype._createPoint=function(a){return(a=a&&a.coords)?new q({longitude:a.longitude,latitude:a.latitude,z:a.altitude||null,spatialReference:{wkid:4326}}):null};g.prototype._animatePoint=function(a,c,d){return this.goToLocationEnabled?this.view.goTo({target:a,scale:d}).then(function(){return c}):
b.resolve(c)};g.prototype._setPosition=function(a){var c=this;a=this._clonePosition(a);var d=this._createPoint(a),e=this._getScale(a);return d?this._projectPoint(d).then(function(b){c.graphic&&(c.graphic.geometry=b);c._animatePoint(b,a,e)}).then(function(){return a}):b.reject(new p("positioning:invalid-point","Cannot position invalid point"))};d([e.property()],g.prototype,"geolocationOptions",void 0);d([e.property()],g.prototype,"goToLocationEnabled",void 0);d([e.property()],g.prototype,"graphic",
void 0);d([e.property()],g.prototype,"scale",void 0);d([e.property()],g.prototype,"view",void 0);return g=d([e.subclass("esri.widgets.support.GeolocationPositioning")],g)}(e.declared(l,a))})},"widgets/MyLocation/_build-generate_module":function(){define(["dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/MyLocation/css/style.css":'.jimu-widget-mylocation {background-color: #fff; opacity: 0.8; color: rgba(0, 0, 0, 0.8);}.jimu-widget-mylocation:hover {opacity: 1;}.jimu-widget-mylocation.nohttps:hover{opacity: 0.8;}.jimu-widget-mylocation.onCenter {background-color: #000;}.jimu-widget-mylocation .esri-locate-node {display: none;}.jimu-widget-mylocation .place-holder {width: 32px; height: 32px; background-color: #666; -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none; cursor: pointer; border: 1px solid rgba(0, 0, 0, 0.3); text-align: center; line-height: 30px; font-size: 14px; background-position: center center; background-repeat: no-repeat;}.jimu-widget-mylocation .place-holder:before {font-family: \'Themefont\'; content: "\\a907";}.jimu-widget-mylocation .place-holder.locating:before {content: "";}.jimu-widget-mylocation .place-holder.locating {background-image: url("images/loading_black.gif"); background-repeat: no-repeat; background-position: center;}.jimu-widget-mylocation .place-holder.nohttps{color: #bcbcbc;}.jimu-widget-mylocation .place-holder.tracking:before {content: "\\a913" !important; color: rgba(255, 255, 255, 0.8);}.jimu-widget-mylocation .place-holder {background-color: rgba(0, 0, 0, 0);}.jimu-widget-mylocation.onCenter .place-holder {color: #fff;}.jimu-widget-mylocation.onLocate .place-holder {background-color: rgba(0, 0, 0, 0.4);}',
"*now":function(h){h(['dojo/i18n!*preload*widgets/MyLocation/nls/Widget*["ar","bs","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])}}});
define("dojo/_base/declare jimu/BaseWidget dojo/_base/html dojo/on dojo/when dojo/_base/lang esri/layers/GraphicsLayer esri/widgets/Locate esri/widgets/Locate/LocateViewModel esri/symbols/PictureMarkerSymbol esri/geometry/Point esri/geometry/SpatialReference esri/geometry/support/webMercatorUtils esri/tasks/support/ProjectParameters esri/Graphic esri/config jimu/utils".split(" "),function(h,n,c,d,e,f,k,m,l,p,a,b,q,t,r,u,v){h=h([n],{name:"MyLocation",baseClass:"jimu-widget-mylocation",startup:function(){this.inherited(arguments);
this.placehoder=c.create("div",{"class":"place-holder",title:this.label},this.domNode);this.isNeedHttpsButNot=v.isNeedHttpsButNot();!0===this.isNeedHttpsButNot?(console.log("LocateButton::navigator.geolocation requires a secure origin."),c.addClass(this.domNode,"nohttps"),c.addClass(this.placehoder,"nohttps"),c.setAttr(this.placehoder,"title",this.nls.httpNotSupportError)):window.navigator.geolocation?this.own(d(this.placehoder,"click",f.hitch(this,this.onLocationClick))):c.setAttr(this.placehoder,
"title",this.nls.browserError)},onLocationClick:function(){c.hasClass(this.domNode,"onCenter")||c.hasClass(this.domNode,"locating")?(c.removeClass(this.domNode,"onCenter"),c.removeClass(this.placehoder,"tracking"),this._destroyGeoLocate()):(this._createGeoLocate(),this.geoLocate.viewModel.locate(),c.addClass(this.placehoder,"locating"))},onLocate:function(a){c.removeClass(this.placehoder,"locating");this.graphicsLayer.clear();this.geoLocate.viewModel.tracking&&c.addClass(this.placehoder,"tracking");
if(a.error)this.onLocateError(a.error);else c.addClass(this.domNode,"onCenter"),this.neverLocate=!1,this._pointMarkerManualy(a)},onLocateError:function(a){console.error(a.error);c.removeClass(this.placehoder,"locating");c.removeClass(this.domNode,"onCenter");c.removeClass(this.placehoder,"tracking")},_createGeoLocate:function(){var a=this.config.locateButton,b={maximumAge:0,timeout:15E3,enableHighAccuracy:!0};a.geolocationOptions&&f.mixin(b,a.geolocationOptions);this.graphicsLayer=new k;this.sceneView.map.add(this.graphicsLayer);
var e=c.create("div",{"class":"esri-locate-node"},this.domNode);this.geoLocate=new m({viewModel:new l({view:this.sceneView,graphicsLayer:this.graphicsLayer,geolocationOptions:b,locationSymbolEnabled:a.highlightLocation,scale:a.scale,tracking:a.useTracking,clearOnTrackingStopEnabled:!1}),container:e,visible:!1});this.geoLocate.startup();this.geoLocate.own(d(this.geoLocate.viewModel,"locate",f.hitch(this,this.onLocate)));this.geoLocate.own(d(this.geoLocate.viewModel,"locate-error",f.hitch(this,this.onLocateError)))},
_destroyGeoLocate:function(){this.graphicsLayer&&(this.graphicsLayer.clear(),this.sceneView.map.remove(this.graphicsLayer));this.geoLocate&&(this.geoLocate.viewModel.clear(),this.geoLocate.destroy());this.geoLocate=null},destroy:function(){this._destroyGeoLocate();this.inherited(arguments)},_pointMarkerManualy:function(c){"undefined"!==typeof this.config.locateButton.highlightLocation&&!1!==this.config.locateButton.highlightLocation&&(this.highlightSymbol=new p({url:this.folderUrl+"css/images/sdk_gps_location.png",
size:28,width:28,height:28,xoffset:14,yoffset:14}),c=new a({longitude:c.position.coords.longitude,latitude:c.position.coords.latitude,spatialReference:new b({wkid:4326})}),this._project(c).then(f.hitch(this,function(a){a=new r({geometry:a[0],symbol:this.highlightSymbol});this.config.locateButton.highlightLocation&&this.graphicsLayer.add(a)}),f.hitch(this,function(a){this.onLocateError(a)})))},_project:function(a){var b=this.sceneView.spatialReference;if(a.spatialReference.equals(b))return e([a]);
if(q.canProject(a,b))return e([q.project(a,b)]);var c=new t;c.geometries=[a];c.outSR=b;return u.geometryService.project(c)}});h.inPanel=!1;h.hasUIFile=!1;return h});