// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"esri/widgets/Locate":function(){define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/i18n!./Locate/nls/Locate ../core/accessorSupport/decorators ./Widget ./Locate/LocateViewModel ./support/widget".split(" "),function(k,q,e,b,l,d,p,m,h){return function(k){function a(g){g=k.call(this)||this;g.geolocationOptions=null;g.goToLocationEnabled=null;g.graphic=null;g.iconClass="esri-icon-north-navigation";g.scale=null;g.useHeadingEnabled=null;
g.view=null;g.viewModel=new m;return g}e(a,k);a.prototype.locate=function(){};a.prototype.render=function(){var g=this.get("viewModel.state"),a="locating"===g,f=(c={},c["esri-disabled"]="disabled"===g,c["esri-hidden"]="feature-unsupported"===g,c),a=(n={},n["esri-icon-loading-indicator"]=a,n["esri-rotating"]=a,n["esri-icon-locate"]=!a,n);return h.tsx("div",{bind:this,class:"esri-locate esri-widget-button esri-widget",classes:f,hidden:"feature-unsupported"===g,onclick:this._locate,onkeydown:this._locate,
role:"button",tabIndex:0,"aria-label":l.title,title:l.title},h.tsx("span",{classes:a,"aria-hidden":"true",class:h.join("esri-icon","esri-icon-locate")}),h.tsx("span",{class:"esri-icon-font-fallback-text"},l.title));var c,n};a.prototype._locate=function(){this.locate()};b([d.aliasOf("viewModel.geolocationOptions")],a.prototype,"geolocationOptions",void 0);b([d.aliasOf("viewModel.goToLocationEnabled")],a.prototype,"goToLocationEnabled",void 0);b([d.aliasOf("viewModel.graphic")],a.prototype,"graphic",
void 0);b([d.property()],a.prototype,"iconClass",void 0);b([d.aliasOf("viewModel.scale")],a.prototype,"scale",void 0);b([d.aliasOf("viewModel.useHeadingEnabled")],a.prototype,"useHeadingEnabled",void 0);b([d.aliasOf("viewModel.view")],a.prototype,"view",void 0);b([d.property({type:m}),h.renderable("viewModel.state"),h.vmEvent(["locate","locate-error"])],a.prototype,"viewModel",void 0);b([d.aliasOf("viewModel.locate")],a.prototype,"locate",null);b([h.accessibleHandler()],a.prototype,"_locate",null);
return a=b([d.subclass("esri.widgets.Locate")],a)}(d.declared(p))})},"esri/widgets/Locate/LocateViewModel":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Error ../../core/geolocationUtils ../../core/promiseUtils ../../core/accessorSupport/decorators ../support/GeolocationPositioning".split(" "),function(k,q,e,b,l,d,p,m,h){return function(h){function a(a){a=h.call(this,a)||this;a.locate=a.locate.bind(a);return a}e(a,h);a.prototype.destroy=
function(){this._locating&&(this._locating.cancel(),this._locating=null)};Object.defineProperty(a.prototype,"state",{get:function(){return this._geolocationUsable?this.get("view.ready")?this._locating?"locating":"ready":"disabled":"feature-unsupported"},enumerable:!0,configurable:!0});a.prototype.locate=function(){var a=this;if("disabled"===this.state)return p.reject(new l("locate:disabled-state","Cannot locate when disabled."));if("feature-unsupported"===this.state)return p.reject(new l("locate:feature-unsupported-state",
"Cannot locate in unsecure domain."));this._locating&&(this._locating.cancel(),this._locating=null);var b=d.getCurrentPosition(this.geolocationOptions).then(function(b){return a._setPosition(b)}).then(function(b){a.view.graphics.remove(a.graphic);a.graphic&&(a.graphic=a.graphic.clone(),a.view.graphics.push(a.graphic));a.emit("locate",{position:b});return b}).catch(function(b){a.emit("locate-error",{error:b});throw b;});b.always(function(b){a._locating=null;a.notifyChange("state")});this._locating=
b;this.notifyChange("state");return b};b([m.property({dependsOn:["view.ready"],readOnly:!0})],a.prototype,"state",null);b([m.property()],a.prototype,"locate",null);return a=b([m.subclass("esri.widgets.Locate.LocateViewModel")],a)}(m.declared(h))})},"esri/core/geolocationUtils":function(){define("require exports ./tsSupport/assignHelper ../config ./Error ./promiseUtils ../geometry/Point ../geometry/support/webMercatorUtils ../portal/Portal ../tasks/GeometryService ../tasks/support/ProjectParameters".split(" "),
function(k,q,e,b,l,d,p,m,h,r,a){function g(c,b){var n=b.spatialReference;return n.isWGS84?d.resolve(c):n.isWebMercator?d.resolve(m.geographicToWebMercator(c)):t().then(function(b){if(!b)return d.reject(new l("geometry-service:missing-url","Geometry service URL is missing"));b=new r({url:b});var v=new a({geometries:[c],outSR:n});return b.project(v).then(function(c){return c[0]})})}function t(){if(b.geometryServiceUrl)return d.resolve(b.geometryServiceUrl);var c=h.getDefault();return c.load().always(function(){return c.get("helperServices.geometry.url")})}
Object.defineProperty(q,"__esModule",{value:!0});var f={maximumAge:0,timeout:15E3,enableHighAccuracy:!0};q.supported=function(){var c=!!navigator.geolocation;c||console.log("geolocation: unsupported.");c&&((c=(c=window.hasOwnProperty("isSecureContext"))&&window.isSecureContext||!c&&"https:"===window.location.protocol)||console.log("geolocation: requires a secure origin."));return c};q.getCurrentPosition=function(c){c||(c=f);var a=d.create(function(a,b){navigator.geolocation.getCurrentPosition(a,b,
c)});return d.timeout(a,15E3,void 0)};q.positionToPoint=function(c,a){var b=c&&c.coords||{},b={accuracy:b.accuracy,altitude:b.altitude,altitudeAccuracy:b.altitudeAccuracy,heading:b.heading,latitude:b.latitude,longitude:b.longitude,speed:b.speed};c=c?{coords:b,timestamp:c.timestamp}:c;c=(c=c&&c.coords)?new p({longitude:c.longitude,latitude:c.latitude,z:c.altitude||null,spatialReference:{wkid:4326}}):null;return g(c,a)}})},"esri/widgets/support/GeolocationPositioning":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../Graphic ../../core/Accessor ../../core/Error ../../core/Evented ../../core/geolocationUtils ../../core/promiseUtils ../../core/accessorSupport/decorators ../../symbols/PictureMarkerSymbol".split(" "),
function(k,q,e,b,l,d,p,m,h,r,a,g){return function(d){function f(){var c=null!==d&&d.apply(this,arguments)||this;c._geolocationUsable=!0;c._iconPath=k.toUrl("../../images/support/sdk_gps_location.png");c.geolocationOptions=null;c.goToLocationEnabled=!0;c.graphic=new l({symbol:new g({url:c._iconPath,width:21,height:21})});c.scale=null;c.useHeadingEnabled=!0;c.view=null;return c}e(f,d);f.prototype.initialize=function(){h.supported()||(this._geolocationUsable=!1)};f.prototype.destroy=function(){this._clear();
this.view=null};f.prototype._clear=function(){this.view&&this.view.graphics.remove(this.graphic)};f.prototype._getScaleWithinConstraints=function(c,a){return a?"2d"===a.type?(a=a.constraints,Math.min(a.effectiveMinScale,Math.max(a.effectiveMaxScale,c))):c:c};f.prototype._getScale=function(c,a){c=this.scale;return this._getScaleWithinConstraints("number"===typeof c?c:2500,a)};f.prototype._getHeading=function(a,b){b=b.spatialReference;a=a.coords&&a.coords.heading;if(!(!b||!b.isWebMercator&&!b.isWGS84||
"number"!==typeof a||0>a||360<a))return a};f.prototype._animatePoint=function(a,b,d){if(!this.goToLocationEnabled)return r.resolve(b);var c=this.view,e=this.useHeadingEnabled?this._getHeading(b,c):void 0;a={target:a,scale:d};void 0!==e&&"3d"===c.type&&(a.heading=e);void 0!==e&&"2d"===c.type&&(c.rotation=e);return c.goTo(a).then(function(){return b})};f.prototype._setPosition=function(a){var b=this;return h.positionToPoint(a,this.view).then(function(c){b.graphic&&(b.graphic.geometry=c);var d=b._getScale(a,
b.view);b._animatePoint(c,a,d);return a}).catch(function(){return r.reject(new p("positioning:invalid-point","Cannot position invalid point"))})};b([a.property()],f.prototype,"geolocationOptions",void 0);b([a.property()],f.prototype,"goToLocationEnabled",void 0);b([a.property()],f.prototype,"graphic",void 0);b([a.property()],f.prototype,"scale",void 0);b([a.property()],f.prototype,"useHeadingEnabled",void 0);b([a.property()],f.prototype,"view",void 0);return f=b([a.subclass("esri.widgets.support.GeolocationPositioning")],
f)}(a.declared(d,m))})},"widgets/MyLocation/_build-generate_module":function(){define(["dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/MyLocation/css/style.css":'.jimu-widget-mylocation {background-color: #fff; opacity: 0.8; color: rgba(0, 0, 0, 0.8);}.jimu-widget-mylocation:hover {opacity: 1;}.jimu-widget-mylocation.nohttps:hover{opacity: 0.8;}.jimu-widget-mylocation.onCenter {background-color: #000;}.jimu-widget-mylocation .esri-locate-node {display: none;}.jimu-widget-mylocation .place-holder {width: 32px; height: 32px; background-color: #666; -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none; cursor: pointer; border: 1px solid rgba(0, 0, 0, 0.3); text-align: center; line-height: 30px; font-size: 14px; background-position: center center; background-repeat: no-repeat;}.jimu-widget-mylocation .place-holder:before {font-family: \'Themefont\'; content: "\\a907";}.jimu-widget-mylocation .place-holder.locating:before {content: "";}.jimu-widget-mylocation .place-holder.locating {background-image: url("images/loading_black.gif"); background-repeat: no-repeat; background-position: center;}.jimu-widget-mylocation .place-holder.nohttps{color: #bcbcbc;}.jimu-widget-mylocation .place-holder.tracking:before {content: "\\a913" !important; color: rgba(255, 255, 255, 0.8);}.jimu-widget-mylocation .place-holder {background-color: rgba(0, 0, 0, 0);}.jimu-widget-mylocation.onCenter .place-holder {color: #fff;}.jimu-widget-mylocation.onLocate .place-holder {background-color: rgba(0, 0, 0, 0.4);}',
"*now":function(k){k(['dojo/i18n!*preload*widgets/MyLocation/nls/Widget*["ar","bs","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sl","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])}}});
define("dojo/_base/declare jimu/BaseWidget dojo/_base/html dojo/on dojo/when dojo/_base/lang esri/layers/GraphicsLayer esri/widgets/Locate esri/widgets/Locate/LocateViewModel esri/symbols/PictureMarkerSymbol esri/geometry/Point esri/geometry/SpatialReference esri/geometry/support/webMercatorUtils esri/tasks/support/ProjectParameters esri/Graphic esri/config jimu/utils".split(" "),function(k,q,e,b,l,d,p,m,h,r,a,g,t,f,c,n,u){k=k([q],{name:"MyLocation",baseClass:"jimu-widget-mylocation",startup:function(){this.inherited(arguments);
this.placehoder=e.create("div",{"class":"place-holder",title:this.label},this.domNode);this.isNeedHttpsButNot=u.isNeedHttpsButNot();!0===this.isNeedHttpsButNot?(console.log("LocateButton::navigator.geolocation requires a secure origin."),e.addClass(this.domNode,"nohttps"),e.addClass(this.placehoder,"nohttps"),e.setAttr(this.placehoder,"title",this.nls.httpNotSupportError)):window.navigator.geolocation?this.own(b(this.placehoder,"click",d.hitch(this,this.onLocationClick))):e.setAttr(this.placehoder,
"title",this.nls.browserError)},onLocationClick:function(){e.hasClass(this.domNode,"onCenter")||e.hasClass(this.domNode,"locating")?(e.removeClass(this.domNode,"onCenter"),e.removeClass(this.placehoder,"tracking"),this._destroyGeoLocate()):(this._createGeoLocate(),this.geoLocate.viewModel.locate(),e.addClass(this.placehoder,"locating"))},onLocate:function(a){e.removeClass(this.placehoder,"locating");this.graphicsLayer.removeAll();this.geoLocate.viewModel.tracking&&e.addClass(this.placehoder,"tracking");
if(a.error)this.onLocateError(a.error);else e.addClass(this.domNode,"onCenter"),this.neverLocate=!1,this._pointMarkerManualy(a)},onLocateError:function(a){console.error(a.error);e.removeClass(this.placehoder,"locating");e.removeClass(this.domNode,"onCenter");e.removeClass(this.placehoder,"tracking")},_createGeoLocate:function(){var a=this.config.locateButton,c={maximumAge:0,timeout:15E3,enableHighAccuracy:!0};a.geolocationOptions&&d.mixin(c,a.geolocationOptions);this.graphicsLayer=new p;this.sceneView.map.add(this.graphicsLayer);
var f=e.create("div",{"class":"esri-locate-node"},this.domNode);this.geoLocate=new m({viewModel:new h({view:this.sceneView,graphicsLayer:this.graphicsLayer,geolocationOptions:c,locationSymbolEnabled:a.highlightLocation,scale:a.scale,tracking:a.useTracking,clearOnTrackingStopEnabled:!1}),container:f,visible:!1});this.geoLocate.startup();this.geoLocate.own(b(this.geoLocate.viewModel,"locate",d.hitch(this,this.onLocate)));this.geoLocate.own(b(this.geoLocate.viewModel,"locate-error",d.hitch(this,this.onLocateError)))},
_destroyGeoLocate:function(){this.graphicsLayer&&(this.graphicsLayer.removeAll(),this.sceneView.map.remove(this.graphicsLayer));this.geoLocate&&(this.geoLocate.viewModel.graphicsLayer.removeAll(),this.geoLocate.destroy());this.geoLocate=null},destroy:function(){this._destroyGeoLocate();this.inherited(arguments)},_pointMarkerManualy:function(b){"undefined"!==typeof this.config.locateButton.highlightLocation&&!1!==this.config.locateButton.highlightLocation&&(this.highlightSymbol=new r({url:this.folderUrl+
"css/images/sdk_gps_location.png",size:28,width:28,height:28,xoffset:14,yoffset:14}),b=new a({longitude:b.position.coords.longitude,latitude:b.position.coords.latitude,spatialReference:new g({wkid:4326})}),this._project(b).then(d.hitch(this,function(a){a=new c({geometry:a[0],symbol:this.highlightSymbol});this.config.locateButton.highlightLocation&&this.graphicsLayer.add(a)}),d.hitch(this,function(a){this.onLocateError(a)})))},_project:function(a){var b=this.sceneView.spatialReference;if(a.spatialReference.equals(b))return l([a]);
if(t.canProject(a,b))return l([t.project(a,b)]);var c=new f;c.geometries=[a];c.outSR=b;return n.geometryService.project(c)}});k.inPanel=!1;k.hasUIFile=!1;return k});