// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"esri/widgets/BasemapGallery":function(){define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/i18n!./BasemapGallery/nls/BasemapGallery ../core/Handles ../core/watchUtils ../core/accessorSupport/decorators ./Widget ./BasemapGallery/BasemapGalleryViewModel ./support/widget".split(" "),function(r,t,m,a,l,n,p,h,q,k,b){var c=r.toUrl("../themes/base/images/basemap-toggle-64.svg");return function(d){function f(g){g=d.call(this)||this;g._handles=
new n;g.activeBasemap=null;g.iconClass="esri-icon-basemap";g.label=l.widgetLabel;g.source=null;g.view=null;g.viewModel=new k;return g}m(f,d);f.prototype.postInitialize=function(){var g=this,a=this._handles;this.own([p.on(this,"viewModel.items","change",function(b){var d=b.added;b=b.moved;a.remove("basemap-gallery-item-changes");a.add(d.concat(b).map(function(b){return b.watch("state",function(){return g.scheduleRender()})}),"basemap-gallery-item-changes");g.scheduleRender()}),a,p.whenOnce(this,"source",
function(){return g.viewModel.load()})])};f.prototype.render=function(){var g,a="loading"===this.get("source.state"),d="disabled"===this.get("viewModel.state"),f=this.get("viewModel.items").toArray().map(this._renderBasemapGalleryItem,this),d=(g={},g["esri-basemap-gallery--source-loading"]=a,g["esri-disabled"]=d,g);g=a?b.tsx("div",{class:"esri-basemap-gallery__loader",key:"esri-basemap-gallery__loader"}):null;a=a?null:0<f.length?b.tsx("ul",{class:"esri-basemap-gallery__item-container",key:"esri-basemap-gallery__item-container",
role:"menu"},f):b.tsx("div",{class:"esri-widget__content--empty",key:"esri-basemap-gallery__empty-message"},b.tsx("h2",{class:"esri-widget__heading"},l.noBasemaps));return b.tsx("div",{class:this.classes("esri-basemap-gallery esri-widget esri-widget--panel-height-only",d)},g,a)};f.prototype._handleClick=function(a){a=a.currentTarget["data-item"];"ready"===a.state&&(this.activeBasemap=a.basemap)};f.prototype._renderBasemapGalleryItem=function(a){var d,f=a.get("basemap.thumbnailUrl")||c,g=a.get("basemap.title"),
e=a.get("basemap.portalItem.snippet"),e=a.get("error.message")||e||g,y="ready"===a.state?0:-1,w=this.viewModel.basemapEquals(a.basemap,this.activeBasemap),h=(d={},d["esri-basemap-gallery__item--selected"]=w,d["esri-basemap-gallery__item--loading"]="loading"===a.state,d["esri-basemap-gallery__item--error"]="error"===a.state,d);return b.tsx("li",{"aria-selected":w,bind:this,class:this.classes("esri-basemap-gallery__item",h),"data-item":a,onkeydown:this._handleClick,onclick:this._handleClick,role:"menuitem",
tabIndex:y,title:e},b.tsx("img",{alt:"",class:"esri-basemap-gallery__item-thumbnail",src:f}),b.tsx("div",{class:"esri-basemap-gallery__item-title"},g))};a([h.aliasOf("viewModel.activeBasemap"),b.renderable()],f.prototype,"activeBasemap",void 0);a([h.property()],f.prototype,"iconClass",void 0);a([h.property()],f.prototype,"label",void 0);a([h.aliasOf("viewModel.source"),b.renderable("source.state")],f.prototype,"source",void 0);a([h.aliasOf("viewModel.view"),b.renderable()],f.prototype,"view",void 0);
a([h.property(),b.renderable(["viewModel.state"])],f.prototype,"viewModel",void 0);a([b.accessibleHandler()],f.prototype,"_handleClick",null);return f=a([h.subclass("esri.widgets.BasemapGallery")],f)}(h.declared(q))})},"esri/widgets/BasemapGallery/BasemapGalleryViewModel":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Accessor ../../core/Collection ../../core/Handles ../../core/Loadable ../../core/promiseUtils ../../core/watchUtils ../../core/accessorSupport/decorators ../../support/basemapUtils ./support/basemapCompatibilityUtils ./support/BasemapGalleryItem ./support/LocalBasemapsSource ./support/PortalBasemapsSource".split(" "),
function(r,t,m,a,l,n,p,h,q,k,b,c,d,f,g,u){var v=n.ofType(f);return function(h){function e(a){a=h.call(this)||this;a._handles=new p;a.activeBasemap=null;a.items=new v;a.source=new u;a.view=null;return a}m(e,h);e.prototype.initialize=function(){var a=this;this._handles.add([k.init(this,["compatibilityFunction","state"],function(){return a._updateItems()}),k.on(this,"source.basemaps","change",function(){return a._updateItems()})])};e.prototype.destroy=function(){this._handles.destroy();this._handles=
null};Object.defineProperty(e.prototype,"compatibilityFunction",{get:function(){return void 0===this._get("compatibilityFunction")?"3d"===this.get("view.type")?d.default3DCompatibility:d.default2DCompatibility:this._get("compatibilityFunction")},set:function(a){this._set("compatibilityFunction",a)},enumerable:!0,configurable:!0});e.prototype.castSource=function(a){return Array.isArray(a)||n.isCollection(a)?new g({basemaps:a}):a&&"esri.portal.Portal"===a.declaredClass?new u({portal:a}):!a||a instanceof
u||!a.portal&&!a.query?a&&"basemaps"in a&&"state"in a&&"refresh"in a?a:null:new u(a)};Object.defineProperty(e.prototype,"state",{get:function(){return this.get("view.ready")&&this.source?"ready":"disabled"},enumerable:!0,configurable:!0});e.prototype.basemapEquals=function(a,b){return c.contentEquals(a,b)};e.prototype.refresh=function(){this._updateItems()};e.prototype.load=function(a){this.addResolvingPromise("function"===typeof this.source.load?this.source.load(a):q.resolve());return this.when()};
e.prototype._updateItems=function(){if("disabled"!==this.state){var a=this.get("source.basemaps"),b=this.view,d=this.compatibilityFunction;this.items.removeAll().forEach(function(a){return a.destroy()});this.items.addMany(a.map(function(a){return new f({basemap:a,compatibilityFunction:d,view:b})}))}};a([b.property({aliasOf:"view.map.basemap"})],e.prototype,"activeBasemap",void 0);a([b.property({dependsOn:["view.type"]})],e.prototype,"compatibilityFunction",null);a([b.property({readOnly:!0,type:v})],
e.prototype,"items",void 0);a([b.property()],e.prototype,"source",void 0);a([b.cast("source")],e.prototype,"castSource",null);a([b.property({readOnly:!0,dependsOn:["view.ready"]})],e.prototype,"state",null);a([b.property()],e.prototype,"view",void 0);return e=a([b.subclass("esri.widgets.BasemapGallery.BasemapGalleryViewModel")],e)}(b.declared(l,h))})},"esri/widgets/BasemapGallery/support/basemapCompatibilityUtils":function(){define("require exports ../../../core/compilerUtils ../../../core/Error ../../../core/promiseUtils ../../../views/3d/terrain/terrainUtils ../../../views/3d/terrain/TilingScheme ../../../views/support/spatialReferenceSupport".split(" "),
function(r,t,m,a,l,n,p,h){function q(b,c){var d=b.basemap,f=b.view;return d.load(c).then(function(){if(0!==d.baseLayers.length){var b=d.baseLayers.concat(d.referenceLayers),b=k(b);if(b.length)throw b[0];return m.typeCast(d.baseLayers.getItemAt(0))().load(c).then(function(b){var d=b.tileInfo;if(d){var c=f.get("viewingMode");if(c){if(!h.isSpatialReferenceSupported(d.spatialReference,c))throw new a("basemapgalleryitem:spatial-reference-unsupported-"+c,"Basemap spatial reference is unsupported in "+c+
" mode");if("global"===c){var g=n.checkIfTileInfoSupportedForView(d,b.fullExtent,null,c);g&&b.compatibleTileInfo256&&!n.checkIfTileInfoSupportedForView(b.compatibleTileInfo256,b.fullExtent,null,c)&&(g=null);if(g)throw new a("basemapgalleryitem:tiling-scheme-unsupported-"+(d.spatialReference.isWebMercator?"web-mercator":"wgs84")+"-global","Basemap tiling scheme is unsupported in global mode",{error:g});}else if(p.checkUnsupported(d))throw new a("basemapgalleryitem:tiling-scheme-unsupported-local",
"Basemap tiling scheme is unsupported in local mode");c=f.get("basemapTerrain.tilingScheme");if(!(!c||c.compatibleWith(d)||b.compatibleTileInfo256&&c.compatibleWith(b.compatibleTileInfo256)))throw new a("basemapgalleryitem:tiling-scheme-incompatible","Basemap tiling scheme is incompatible with the view");}}})}}).catch(function(b){var d=b.name,c=b.message;throw new a(void 0===d?"basemap-compatibility:unknown-error":d,void 0===c?"Unknown basemap compatibility error":c,b.details);})}function k(b){var c=
["ArcGISTiledImageServiceLayer","ArcGISTiledMapServiceLayer","OpenStreetMap","VectorTileLayer","WebTiledLayer"];return b.toArray().filter(function(a){return-1===c.indexOf(a.operationalLayerType)}).map(function(b){return new a("basemap-compatibility:unsupported-basemap-layer-type","Unsupported basemap layer type ${operationalLayerType}",{layer:b,operationalLayerType:b.operationalLayerType||"unknown"})})}Object.defineProperty(t,"__esModule",{value:!0});t.default3DCompatibility=function(a,c){void 0===
c&&(c={});return q(a,c).then(function(){return l.throwIfAborted(c)})};t.default2DCompatibility=function(b,c){void 0===c&&(c={});var d=b.basemap,f=b.view;return d.load(c).then(function(){l.throwIfAborted(c);if(0!==d.baseLayers.length){var b=d.baseLayers.getItemAt(0);return b.load(c).then(function(){l.throwIfAborted(c);var d=(b.get("supportedSpatialReferences")||[b.get("tileInfo.spatialReference")]).filter(Boolean);if(0!==d.length&&d.every(function(a){return!f.spatialReference.equals(a)}))return l.reject(new a("basemap-compatibility:incompatible-spatial-reference",
"Basemap spatial reference is not compatible with the view"))})}})}})},"esri/widgets/BasemapGallery/support/BasemapGalleryItem":function(){define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper @dojo/framework/shim/AbortController ../../../core/Accessor ../../../core/Handles ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators".split(" "),function(r,t,m,a,l,n,p,h,q,k){return function(b){function c(a){a=b.call(this)||
this;a._handles=new p;a.compatibilityFunction=null;a.error=null;a.state="loading";a.view=null;return a}m(c,b);c.prototype.initialize=function(){var a=this;this._handles.add(q.init(this,["basemap.loadStatus","compatibilityFunction","view.basemapTerrain.tilingScheme","view.ready","view.spatialReference"],function(){return a.refresh()}))};c.prototype.destroy=function(){this._cancelCompatibilityCheck();this._handles.destroy();this.view=this.compatibilityFunction=this.basemap=this._handles=null};Object.defineProperty(c.prototype,
"basemap",{set:function(a){var b=this._get("basemap");b&&b.cancelLoad();a&&a.load();this._set("basemap",a)},enumerable:!0,configurable:!0});c.prototype.refresh=function(){var a=this;this._cancelCompatibilityCheck();this._set("state","loading");var b=this.get("basemap.loadStatus");if("loaded"===b||"failed"===b)this.compatibilityFunction?(b=new l.default,this.compatibilityFunction(this,{signal:b.signal}).then(function(){a._set("state","ready");a._set("error",null)}).catch(function(b){h.isAbortError(b)||
(a._set("state","error"),a._set("error",b))}),this._lastCompatibilityCheckController=b):"loaded"===b?(this._set("state","ready"),this._set("error",null)):(this._set("state","error"),this._set("error",this.basemap.loadError))};c.prototype._cancelCompatibilityCheck=function(){this._lastCompatibilityCheckController&&(this._lastCompatibilityCheckController.abort(),this._lastCompatibilityCheckController=null)};a([k.property()],c.prototype,"basemap",null);a([k.property()],c.prototype,"compatibilityFunction",
void 0);a([k.property({readOnly:!0})],c.prototype,"error",void 0);a([k.property({readOnly:!0})],c.prototype,"state",void 0);a([k.property()],c.prototype,"view",void 0);return c=a([k.subclass("esri.widgets.BasemapGallery.support.BasemapGalleryItem")],c)}(k.declared(n))})},"esri/widgets/BasemapGallery/support/LocalBasemapsSource":function(){define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../Basemap ../../../core/Accessor ../../../core/Collection ../../../core/accessorSupport/decorators".split(" "),
function(r,t,m,a,l,n,p,h){var q=p.ofType(l);return function(k){function b(a){a=k.call(this)||this;a.basemaps=new q;return a}m(b,k);Object.defineProperty(b.prototype,"state",{get:function(){return"ready"},enumerable:!0,configurable:!0});b.prototype.refresh=function(){};a([h.property({type:q})],b.prototype,"basemaps",void 0);a([h.property({readOnly:!0})],b.prototype,"state",null);return b=a([h.subclass("esri.widgets.BasemapGallery.support.LocalBasemapsSource")],b)}(h.declared(n))})},"esri/widgets/BasemapGallery/support/PortalBasemapsSource":function(){define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper @dojo/framework/shim/AbortController ../../../Basemap ../../../core/Collection ../../../core/Error ../../../core/Handles ../../../core/Loadable ../../../core/Logger ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../../portal/Portal ./LocalBasemapsSource".split(" "),
function(r,t,m,a,l,n,p,h,q,k,b,c,d,f,g,u){var v=p.ofType(n),x=b.getLogger("esri.widgets.BasemapGallery.support.PortalBasemapsSource");return function(b){function e(a){a=b.call(this)||this;a._handles=new q;a.basemaps=new v;a.filterFunction=null;a.portal=g.getDefault();a.query=null;a.updateBasemapsCallback=null;return a}m(e,b);e.prototype.initialize=function(){var a=this;this._handles.add([d.init(this,"filterFunction loadStatus portal.basemapGalleryGroupQuery portal.user query updateBasemapsCallback".split(" "),
function(){return a.refresh()})])};e.prototype.destroy=function(){this._handles.destroy();this.portal=this.filterFunction=this._handles=null};Object.defineProperty(e.prototype,"state",{get:function(){return"not-loaded"===this.loadStatus?"not-loaded":"loading"===this.loadStatus||this._lastPortalBasemapFetchController?"loading":"ready"},enumerable:!0,configurable:!0});e.prototype.load=function(a){this.addResolvingPromise(this.portal.load(a));this.notifyChange("state");return this.when()};e.prototype.refresh=
function(){var a=this;if("ready"===this.state){this._lastPortalBasemapFetchController&&(this._lastPortalBasemapFetchController.abort(),this._lastPortalBasemapFetchController=null);var b=this.portal,d=new l.default;this._lastPortalBasemapFetchController=d;b.fetchBasemaps(this._toQueryString(this.query),d).then(function(b){return a._updateBasemaps(b)}).catch(function(b){if(c.isAbortError(b))throw b;x.warn(new h("basemap-source:fetch-basemaps-error","Could not fetch basemaps from portal.",{error:b}));
a._updateBasemaps()}).then(function(){a._lastPortalBasemapFetchController=null;a.notifyChange("state")});this.notifyChange("state")}};e.prototype._toQueryString=function(a){return a&&"string"!==typeof a?Object.keys(a).map(function(b){return b+":"+a[b]}).join(" AND "):a};e.prototype._updateBasemaps=function(a){void 0===a&&(a=[]);a=this.filterFunction?a.filter(this.filterFunction):a;a=this.updateBasemapsCallback?this.updateBasemapsCallback(a):a;this.basemaps.removeAll();this.basemaps.addMany(a)};a([f.property({readOnly:!0,
type:v})],e.prototype,"basemaps",void 0);a([f.property()],e.prototype,"filterFunction",void 0);a([f.property({type:g})],e.prototype,"portal",void 0);a([f.property()],e.prototype,"query",void 0);a([f.property({dependsOn:["loadStatus"],readOnly:!0})],e.prototype,"state",null);a([f.property()],e.prototype,"updateBasemapsCallback",void 0);return e=a([f.subclass("esri.widgets.BasemapGallery.support.PortalBasemapsSource")],e)}(f.declared(u,k))})},"widgets/BasemapGallery/_build-generate_module":function(){define(["dojo/text!./Widget.html",
"dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/BasemapGallery/Widget.html":"\x3cdiv\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d'basemapGalleryNode'\x3e\x3c/div\x3e\r\n\x3c/div\x3e","url:widgets/BasemapGallery/css/style.css":".jimu-widget-basemap-gallery{width: 100%; height: 100%;}.jimu-widget-basemap-gallery .esri-basemap-gallery.esri-widget{width: 100%; height: 100%; max-height: 100%; background-color: transparent;}.jimu-widget-basemap-gallery .esri-basemap-gallery {max-width: none;}",
"*now":function(r){r(['dojo/i18n!*preload*widgets/BasemapGallery/nls/Widget*["ar","bs","ca","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","hu","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sl","sr","sv","th","tr","zh-cn","vi","uk","zh-hk","zh-tw","ROOT"]'])}}});
define(["dojo/_base/declare","jimu/BaseWidget","esri/widgets/BasemapGallery","esri/widgets/BasemapGallery/BasemapGalleryViewModel"],function(r,t,m,a){return r([t],{name:"BasemapGallery",baseClass:"jimu-widget-basemap-gallery",postCreate:function(){this.inherited(arguments)},startup:function(){this.basemapGallery=new m({container:this.basemapGalleryNode,viewModel:new a({view:this.sceneView})});this.basemapGallery.render()},destroy:function(){this.basemapGallery&&this.basemapGallery.destroy();this.inherited(arguments)}})});