// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"esri/widgets/BasemapGallery":function(){define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/i18n!./BasemapGallery/nls/BasemapGallery ../core/Handles ../core/watchUtils ../core/accessorSupport/decorators ./Widget ./BasemapGallery/BasemapGalleryViewModel ./support/widget".split(" "),function(p,r,h,b,l,m,n,g,e,f,a){var t=p.toUrl("../themes/base/images/basemap-toggle-64.svg");return function(u){function c(d){d=u.call(this)||this;d._handles=
new m;d.activeBasemap=null;d.iconClass="esri-icon-basemap";d.label=l.widgetLabel;d.source=null;d.view=null;d.viewModel=new f;return d}h(c,u);c.prototype.postInitialize=function(){var d=this,a=this._handles;this.own([n.on(this,"viewModel.items","change",function(c){var q=c.added;c=c.moved;a.remove("basemap-gallery-item-changes");a.add(q.concat(c).map(function(a){return a.watch("state",function(){return d.scheduleRender()})}),"basemap-gallery-item-changes");d.scheduleRender()}),a])};c.prototype.render=
function(){var d="loading"===this.get("source.state"),c="disabled"===this.get("viewModel.state"),b=this.get("viewModel.items").toArray().map(this._renderBasemapGalleryItem,this),c=(q={},q["esri-basemap-gallery--source-loading"]=d,q["esri-disabled"]=c,q),q=d?a.tsx("div",{class:"esri-basemap-gallery__loader",key:"esri-basemap-gallery__loader"}):null,d=d?null:0<b.length?a.tsx("ul",{class:"esri-basemap-gallery__item-container",key:"esri-basemap-gallery__item-container",role:"menu"},b):a.tsx("div",{class:"esri-basemap-gallery__empty-message",
key:"esri-basemap-gallery__empty-message"},l.noBasemaps);return a.tsx("div",{class:"esri-basemap-gallery esri-widget esri-widget--panel-height-only",classes:c},q,d);var q};c.prototype._handleClick=function(d){d=d.currentTarget["data-item"];"ready"===d.state&&(this.activeBasemap=d.basemap)};c.prototype._renderBasemapGalleryItem=function(d){var c=d.get("basemap.thumbnailUrl")||t,b=d.get("basemap.title"),q=d.get("error.message")||b,f="ready"===d.state?0:-1,g=this.viewModel.basemapEquals(d.basemap,this.activeBasemap),
u=(e={},e["esri-basemap-gallery__item--selected"]=g,e["esri-basemap-gallery__item--loading"]="loading"===d.state,e["esri-basemap-gallery__item--error"]="error"===d.state,e),e="loading"===d.state?a.tsx("div",{class:"esri-basemap-gallery__loader",key:"esri-basemap-gallery__loader"}):null;return a.tsx("li",{"aria-selected":g,bind:this,class:"esri-basemap-gallery__item",classes:u,"data-item":d,onkeydown:this._handleClick,onclick:this._handleClick,role:"menuitem",tabIndex:f,title:q},e,a.tsx("img",{alt:"",
class:"esri-basemap-gallery__item-thumbnail",src:c}),a.tsx("div",{class:"esri-basemap-gallery__item-title"},b));var e};b([g.aliasOf("viewModel.activeBasemap"),a.renderable()],c.prototype,"activeBasemap",void 0);b([g.property()],c.prototype,"iconClass",void 0);b([g.property()],c.prototype,"label",void 0);b([g.aliasOf("viewModel.source"),a.renderable("source.state")],c.prototype,"source",void 0);b([g.aliasOf("viewModel.view"),a.renderable()],c.prototype,"view",void 0);b([g.property(),a.renderable(["viewModel.state"])],
c.prototype,"viewModel",void 0);b([a.accessibleHandler()],c.prototype,"_handleClick",null);return c=b([g.subclass("esri.widgets.BasemapGallery")],c)}(g.declared(e))})},"esri/widgets/BasemapGallery/BasemapGalleryViewModel":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Accessor ../../core/Collection ../../core/Handles ../../core/watchUtils ../../core/accessorSupport/decorators ../../support/basemapUtils ./support/basemapCompatibilityUtils ./support/BasemapGalleryItem ./support/LocalBasemapsSource ./support/PortalBasemapsSource".split(" "),
function(p,r,h,b,l,m,n,g,e,f,a,t,u,c){var d=m.ofType(t);return function(l){function k(a){a=l.call(this)||this;a._handles=new n;a.activeBasemap=null;a.items=new d;a.source=new c;a.view=null;return a}h(k,l);k.prototype.initialize=function(){var a=this;this._handles.add([g.init(this,["compatibilityFunction","state"],function(){return a._updateItems()}),g.on(this,"source.basemaps","change",function(){return a._updateItems()})])};k.prototype.destroy=function(){this._handles.destroy();this._handles=null};
Object.defineProperty(k.prototype,"compatibilityFunction",{get:function(){return void 0===this._get("compatibilityFunction")?"3d"===this.get("view.type")?a.default3DCompatibility:void 0:this._get("compatibilityFunction")},set:function(a){this._set("compatibilityFunction",a)},enumerable:!0,configurable:!0});k.prototype.castSource=function(a){return Array.isArray(a)||m.isCollection(a)?new u({basemaps:a}):a&&"esri.portal.Portal"===a.declaredClass?new c({portal:a}):!a||a instanceof c||!a.portal&&!a.query?
a&&"basemaps"in a&&"state"in a&&"refresh"in a?a:null:new c(a)};Object.defineProperty(k.prototype,"state",{get:function(){return this.get("view.ready")&&this.source?"ready":"disabled"},enumerable:!0,configurable:!0});k.prototype.basemapEquals=function(a,d){return f.contentEquals(a,d)};k.prototype.refresh=function(){this._updateItems()};k.prototype._updateItems=function(){if("disabled"!==this.state){var a=this.get("source.basemaps"),d=this.view,c=this.compatibilityFunction;this.items.removeAll().forEach(function(a){return a.destroy()});
this.items.addMany(a.map(function(a){return new t({basemap:a,compatibilityFunction:c,view:d})}))}};b([e.property({aliasOf:"view.map.basemap"})],k.prototype,"activeBasemap",void 0);b([e.property({dependsOn:["view.type"]})],k.prototype,"compatibilityFunction",null);b([e.property({readOnly:!0,type:d})],k.prototype,"items",void 0);b([e.property()],k.prototype,"source",void 0);b([e.cast("source")],k.prototype,"castSource",null);b([e.property({readOnly:!0,dependsOn:["view.ready"]})],k.prototype,"state",
null);b([e.property()],k.prototype,"view",void 0);return k=b([e.subclass("esri.widgets.BasemapGallery.BasemapGalleryViewModel")],k)}(e.declared(l))})},"esri/widgets/BasemapGallery/support/basemapCompatibilityUtils":function(){define("require exports ../../../core/Error ../../../core/promiseUtils ../../../views/3d/terrain/terrainUtils ../../../views/3d/terrain/TilingScheme".split(" "),function(p,r,h,b,l,m){function n(f){var a=f.basemap,t=f.view;return a.load().then(function(){if(0!==a.baseLayers.length){var f=
a.baseLayers.concat(a.referenceLayers),f=g(f);return f.length?b.reject(f[0]):a.baseLayers.getItemAt(0).load().then(function(a){return e(a,t)})}}).catch(function(a){var c=a.name,d=a.message;return b.reject(new h(void 0===c?"basemap-compatibility:unknown-error":c,void 0===d?"Unknown basemap compatibility error":d,a.details))})}function g(b){var a=["ArcGISTiledImageServiceLayer","ArcGISTiledMapServiceLayer","OpenStreetMap","VectorTileLayer","WebTiledLayer"];return b.toArray().filter(function(b){return-1===
a.indexOf(b.operationalLayerType)}).map(function(a){return new h("basemap-compatibility:unsupported-basemap-layer-type","Unsupported basemap layer type ${operationalLayerType}",{layer:a,operationalLayerType:a.operationalLayerType||"unknown"})})}function e(f,a){var e=f.tileInfo;if(e){var g=a.get("viewingMode");if(g){var c;c=e.spatialReference;c=null==c?!1:"global"===g?c.isWebMercator||c.isWGS84:!c.isGeographic;if(!c)return b.reject(new h("basemapgalleryitem:spatial-reference-unsupported-"+g,"Basemap spatial reference is unsupported in "+
g+" mode"));if("global"===g){if((c=l.checkIfTileInfoSupportedForView(e,f.fullExtent,null,g))&&f.compatibleTileInfo256&&!l.checkIfTileInfoSupportedForView(f.compatibleTileInfo256,f.fullExtent,null,g)&&(c=null),c)return b.reject(new h("basemapgalleryitem:tiling-scheme-unsupported-"+(e.spatialReference.isWebMercator?"web-mercator":"wgs84")+"-global","Basemap tiling scheme is unsupported in global mode",{error:c}))}else if(m.checkUnsupported(e))return b.reject(new h("basemapgalleryitem:tiling-scheme-unsupported-local",
"Basemap tiling scheme is unsupported in local mode"));a=a.get("basemapTerrain.tilingScheme");if(!(!a||a.compatibleWith(e)||f.compatibleTileInfo256&&a.compatibleWith(f.compatibleTileInfo256)))return b.reject(new h("basemapgalleryitem:tiling-scheme-incompatible","Basemap tiling scheme is incompatible with the view"))}}}Object.defineProperty(r,"__esModule",{value:!0});r.default3DCompatibility=function(b){return n(b).then(function(){})}})},"esri/widgets/BasemapGallery/support/BasemapGalleryItem":function(){define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/Accessor ../../../core/Handles ../../../core/watchUtils ../../../core/accessorSupport/decorators".split(" "),
function(p,r,h,b,l,m,n,g){return function(e){function f(a){a=e.call(this)||this;a._handles=new m;a.compatibilityFunction=null;a.error=null;a.state="loading";a.view=null;return a}h(f,e);f.prototype.initialize=function(){var a=this;this._handles.add(n.init(this,["basemap.loadStatus","compatibilityFunction","view.basemapTerrain.tilingScheme","view.ready","view.spatialReference"],function(){return a.refresh()}))};f.prototype.destroy=function(){this._cancelCompatibilityCheck();this._handles.destroy();
this.view=this.compatibilityFunction=this.basemap=this._handles=null};Object.defineProperty(f.prototype,"basemap",{set:function(a){var b=this._get("basemap");b&&b.cancelLoad();a&&a.load();this._set("basemap",a)},enumerable:!0,configurable:!0});f.prototype.refresh=function(){var a=this;this._cancelCompatibilityCheck();this._set("state","loading");var b=this.get("basemap.loadStatus");if("loaded"===b||"failed"===b)if(this.compatibilityFunction){var e=!1,c=this.compatibilityFunction(this).then(function(){e||
(a._set("state","ready"),a._set("error",null))}).catch(function(d){e||(a._set("state","error"),a._set("error",d))});this._lastCompatibilityCheck={cancel:function(){e=!0;c.cancel()}}}else"loaded"===b?(this._set("state","ready"),this._set("error",null)):(this._set("state","error"),this._set("error",this.basemap.loadError))};f.prototype._cancelCompatibilityCheck=function(){this._lastCompatibilityCheck&&(this._lastCompatibilityCheck.cancel(),this._lastCompatibilityCheck=null)};b([g.property()],f.prototype,
"basemap",null);b([g.property()],f.prototype,"compatibilityFunction",void 0);b([g.property({readOnly:!0})],f.prototype,"error",void 0);b([g.property({readOnly:!0})],f.prototype,"state",void 0);b([g.property()],f.prototype,"view",void 0);return f=b([g.subclass("esri.widgets.BasemapGallery.support.BasemapGalleryItem")],f)}(g.declared(l))})},"esri/widgets/BasemapGallery/support/LocalBasemapsSource":function(){define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../Basemap ../../../core/Accessor ../../../core/Collection ../../../core/accessorSupport/decorators".split(" "),
function(p,r,h,b,l,m,n,g){var e=n.ofType(l);return function(f){function a(a){a=f.call(this)||this;a.basemaps=new e;a.state="ready";return a}h(a,f);a.prototype.refresh=function(){};b([g.property({type:e})],a.prototype,"basemaps",void 0);b([g.property({readOnly:!0})],a.prototype,"state",void 0);return a=b([g.subclass("esri.widgets.BasemapGallery.support.LocalBasemapsSource")],a)}(g.declared(m))})},"esri/widgets/BasemapGallery/support/PortalBasemapsSource":function(){define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../Basemap ../../../core/Collection ../../../core/Handles ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../../portal/Portal ./LocalBasemapsSource".split(" "),
function(p,r,h,b,l,m,n,g,e,f,a){var t=m.ofType(l);return function(a){function c(d){d=a.call(this)||this;d._handles=new n;d.basemaps=new t;d.filterFunction=null;d.portal=f.getDefault();d.query=null;return d}h(c,a);c.prototype.initialize=function(){var a=this;this._handles.add([g.init(this,["filterFunction","portal.basemapGalleryGroupQuery","portal.user","query"],function(){return a.refresh()})])};c.prototype.destroy=function(){this._handles.destroy();this.portal=this.filterFunction=this._handles=null};
Object.defineProperty(c.prototype,"state",{get:function(){return this._get("state")},enumerable:!0,configurable:!0});c.prototype.refresh=function(){var a=this;this._set("state","loading");this._lastPortalBasemapFetch&&(this._lastPortalBasemapFetch.cancel(),this._lastPortalBasemapFetch=null);var b=this.portal;if(b){var c=!1;this._lastPortalBasemapFetch={cancel:function(){c=!0}};b.load().then(function(){if(!c)return b.fetchBasemaps(a._toQueryString(a.query))}).then(function(b){c||(b=a.filterFunction?
b.filter(a.filterFunction):b,a.basemaps.removeAll(),a.basemaps.addMany(b))}).catch(function(){c||a.basemaps.removeAll()}).then(function(){c||a._set("state","ready")})}else this.basemaps.removeAll(),this._set("state","ready")};c.prototype._toQueryString=function(a){return a&&"string"!==typeof a?Object.keys(a).map(function(b){return b+":"+a[b]}).join(" AND "):a};b([e.property({readOnly:!0,type:t})],c.prototype,"basemaps",void 0);b([e.property()],c.prototype,"filterFunction",void 0);b([e.property({type:f})],
c.prototype,"portal",void 0);b([e.property()],c.prototype,"query",void 0);b([e.property({readOnly:!0,value:"loading"})],c.prototype,"state",null);return c=b([e.subclass("esri.widgets.BasemapGallery.support.PortalBasemapsSource")],c)}(e.declared(a))})},"widgets/BasemapGallery/_build-generate_module":function(){define(["dojo/text!./Widget.html","dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/BasemapGallery/Widget.html":"\x3cdiv\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d'basemapGalleryNode'\x3e\x3c/div\x3e\r\n\x3c/div\x3e",
"url:widgets/BasemapGallery/css/style.css":".jimu-widget-basemap-gallery{width: 100%; height: 100%;}.jimu-widget-basemap-gallery .esri-basemap-gallery.esri-widget{width: 100%; height: 100%; max-height: 100%; background-color: transparent;}.jimu-widget-basemap-gallery .esri-basemap-gallery {max-width: none;}","*now":function(p){p(['dojo/i18n!*preload*widgets/BasemapGallery/nls/Widget*["ar","bs","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sl","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])}}});
define(["dojo/_base/declare","jimu/BaseWidget","esri/widgets/BasemapGallery","esri/widgets/BasemapGallery/BasemapGalleryViewModel"],function(p,r,h,b){return p([r],{name:"BasemapGallery",baseClass:"jimu-widget-basemap-gallery",postCreate:function(){this.inherited(arguments)},startup:function(){this.basemapGallery=new h({container:this.basemapGalleryNode,viewModel:new b({view:this.sceneView})});this.basemapGallery.render()},destroy:function(){this.basemapGallery&&this.basemapGallery.destroy();this.inherited(arguments)}})});