// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/Deferred dojo/when dojo/promise/all jimu/portalUtils esri/lang esri/request".split(" "),function(e,f,k,l,g,m,q,n){return{map:null,layerInfosObj:null,appConfig:null,_esriLocatorRegExp:/geocode(.){0,3}\.arcgis.com\/arcgis\/rest\/services\/World\/GeocodeServer/g,setMap:function(a){this.map=a},setLayerInfosObj:function(a){this.layerInfosObj=a},setAppConfig:function(a){this.appConfig=a},getConfigInfo:function(a){if(a&&a.sources&&0<a.sources.length){var b=null;
return this.searchLayer(this.map)&&a.upgradeFromGeocoder?(b=this.map.itemInfo.itemData.applicationProperties.viewing.search,b=f.map(b.layers,e.hitch(this,function(a,b){b.hintText=a;return this._getQueryTypeGeocoder(b)},b.hintText)),g(b).then(e.hitch(this,function(b){a.sources=[].concat(b).concat(a.sources);return a}))):a}return l(this._getSoucesFromPortalAndWebmap()).then(e.hitch(this,function(a){return{allPlaceholder:"",showInfoWindowOnSelect:!0,sources:a}}))},_getSoucesFromPortalAndWebmap:function(){var a=
[],b=null;this.searchLayer(this.map)&&(b=this.map.itemInfo.itemData.applicationProperties.viewing.search,f.forEach(b.layers,e.hitch(this,function(b,h){h.hintText=b;a.push(this._getQueryTypeGeocoder(h))},b.hintText)));return m.getPortalSelfInfo(this.appConfig.portalUrl).then(e.hitch(this,function(b){if((b=b.helperServices&&b.helperServices.geocode)&&0<b.length)for(var c=0,p=b.length;c<p;c++){var f=b[c];f&&a.push(this._processSingleLine(f))}return g(a).then(e.hitch(this,function(a){for(var b=[],c=0;c<
a.length;c++){var d=a[c];d&&(d&&"query"===d.type||(d={name:d.name||this._getGeocodeName(d.url),url:d.url,singleLineFieldName:d.singleLineFieldName,placeholder:d.placeholder||window.jimuNls.common.findAddressOrPlace||d.name||this._getGeocodeName(d.url),maxResults:6,searchInCurrentMapExtent:!1,type:"locator"}),b.push(d))}return b}))}))},_getQueryTypeGeocoder:function(a){var b=this.map.findLayerById(a.id),c=null,e=null,e=a.id,c=null;b&&b.allSublayers&&(c=b.allSublayers.find(function(b){return b.id===
a.subLayer}));return b?(c="scene"===b.type?b.url+"/layers/"+b.layerId:c?c.url||b.url+"/"+a.subLayer:b.url+"/"+b.layerId,{name:b.title,layerId:e,url:c,placeholder:a.hintText||window.jimuNls.common.findAddressOrPlace,searchFields:[a.field.name],displayField:a.field.name,exactMatch:a.field.exactMatch||!1,maxResults:6,searchInCurrentMapExtent:!1,type:"query"}):null},_isEsriLocator:function(a){this._esriLocatorRegExp.lastIndex=0;return this._esriLocatorRegExp.test(a)},_processSingleLine:function(a){if(a.singleLineFieldName)return a;
if(this._isEsriLocator(a.url))return a.singleLineFieldName="SingleLine",a;var b=new k;n({url:a.url,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}).then(e.hitch(this,function(c){c.singleLineAddressField&&c.singleLineAddressField.name?(a.singleLineFieldName=c.singleLineAddressField.name,b.resolve(a)):(console.warn(a.url+"has no singleLineFieldName"),b.resolve(null))}),e.hitch(this,function(a){console.error(a);b.resolve(null)}));return b.promise},_getGeocodeName:function(a){if("string"!==
typeof a)return"geocoder";a=a.split("/");return a[a.length-2]||"geocoder"},getGeocoderName:function(a){return this._getGeocodeName(a)},hasAppSearchInfo:function(a){return a.itemInfo&&a.itemInfo.itemData&&a.itemInfo.itemData.applicationProperties&&a.itemInfo.itemData.applicationProperties.viewing&&a.itemInfo.itemData.applicationProperties.viewing.search},searchLayer:function(a){if(!a||!this.hasAppSearchInfo(a))return!1;a=a.itemInfo.itemData.applicationProperties.viewing.search;return a.enabled&&0!==
a.layers.length?!0:!1}}});