//>>built
define("esri/core/declare esri/geometry/support/centroid esri/views/3d/support/PromiseLightweight esri/views/3d/layers/graphics/Graphics3DSymbolCommonCode esri/core/libs/earcut/earcut esri/views/3d/webgl-engine/lib/gl-matrix ../../support/geometryUtils".split(" "),function(I,J,K,E,L,M,N){var b=M.vec3d,A=b.create(),C=b.create(),F=b.create(),G=b.create(),H=b.create(),u=b.create(),w=b.create(),z=b.create(),D=Math.cos(Math.PI/180*5);return I(K.Promise,{constructor:function(c,b,f){var a=c.geometry.rings;
this.center=J.polygonCentroid({rings:a,hasZ:!1});(this._geometryData=E.copyPathData(a,c.geometry.hasZ))&&0<=b&&0<=f?(this.index=b,this.stride=f,this.resolve()):this.reject()},createBuffers:function(c,b){var f,a,e,d,y,r=this._geometryData.polygons,h=[],g=this._geometryData.vertexData;if(!g)return h;var m=g.length/3,k=new Float64Array(g.length);E.reproject(g,0,c,k,0,b,m);b=new Float64Array(k);for(var p=0;p<r.length;++p){c=r[p];e=c.count;y=c.index;var l=new Float64Array(g.buffer,3*y*g.BYTES_PER_ELEMENT,
3*e);if(f=c.holeIndices.map(function(a){return a-y}),a=L(l,f,3),!(1>a.length)){var n={polygonIndex:p},t=new Float64Array(b.buffer,3*y*b.BYTES_PER_ELEMENT,3*e),q=this._computeNormalAndDistance(t);n.dist=q.distance;if(e=N.getOrigin(k,m,y,e)){n.origin=e;var q=[],u=[];e=c.count;for(var v=0;v<e;v++)d=v*this.stride,q[0+d]=l[0+3*v],q[1+d]=l[1+3*v],q[2+d]=1,q[3+d]=this.index,q[4+d]=0,q[5+d]=this.center[0],q[6+d]=this.center[1],d=(v+e)*this.stride,q[0+d]=l[0+3*v],q[1+d]=l[1+3*v],q[2+d]=100.11,q[3+d]=this.index,
q[4+d]=1,q[5+d]=this.center[0],q[6+d]=this.center[1];for(var w=v=d=0;w<c.pathLengths.length;w++){for(var v=c.pathLengths[w],x=0;x<v;x++)x!==v-1?u.push(x+1+d,x+d,x+1+e+d,x+1+e+d,x+d,x+e+d):u.push(0+d,x+d,0+e+d,0+e+d,x+d,x+e+d);d+=v}this._subdivision2(l,t,a,e,q,u);n.indexNums=u.length;n.vertexNum=q.length/this.stride;n.vertices=new Float32Array(q);n.indices=new Uint32Array(u);h.push(n)}}}return h},_computeNormalAndDistance:function(c){var e=0,f=3,a=6;b.set3(c[e++],c[e++],c[e++],A);b.set3(c[f++],c[f++],
c[f++],C);b.set3(c[a++],c[a++],c[a++],F);b.subtract(A,C,G);b.subtract(F,C,H);c=b.create();b.cross(G,H,c);b.normalize(c,c);e=6378137-Math.abs(b.dot(c,A));f=b.normalize(A);f=b.dot(c,f);return{normal:c,distance:Math.abs(e/f)}},_subdivision:function(c,b,f,a,u,d){for(var e,r,h,g,m,k,p,l=b.length/3,n=0,t=0,q=0;q<l;q++)g=b[n++],m=b[n++],k=b[n++],e=3*g,r=3*m,h=3*k,p=(c[e]+c[r]+c[h])/3,e=(c[e+1]+c[r+1]+c[h+1])/3,u.push(p,e,100.11,this.index,1,this.center[0],this.center[1]),d.push(g+f,m+f,a+t),d.push(m+f,k+
f,a+t),d.push(k+f,g+f,a+t),t++},_doSubdivision:function(c,e,f){if(0<c.length)for(var a,B,d,y,r,h,g,m,k,p,l=-1,n=e.length/this.stride;null!=(a=c.pop());)if(b.set(a.pt0,u),b.set(a.pt1,w),b.set(a.pt2,z),a.n0||(a.n0=b.create(),b.normalize(u,a.n0)),a.n1||(a.n1=b.create(),b.normalize(w,a.n1)),a.n2||(a.n2=b.create(),b.normalize(z,a.n2)),B=b.dot(a.n0,a.n1),d=b.dot(a.n1,a.n2),y=b.dot(a.n0,a.n2),B<D||d<D||y<D){if(r=Math.min(B,d,y),!isNaN(r)&&null!=r)if(r==B){l++;h=.5*(u[0]+w[0]);g=.5*(u[1]+w[1]);m=.5*(u[2]+
w[2]);k=.5*(a.pt00[0]+a.pt11[0]);p=.5*(a.pt00[1]+a.pt11[1]);var t=b.createFrom(h,g,m);b.normalize(t);c.push({pt0:a.pt0,pt1:[h,g,m],pt2:a.pt2,pt00:a.pt00,pt11:[k,p],pt22:a.pt22,index0:a.index0,index1:n+l,index2:a.index2,n0:a.n0,n1:t,n2:a.n2});c.push({pt0:[h,g,m],pt1:a.pt1,pt2:a.pt2,pt00:[k,p],pt11:a.pt11,pt22:a.pt22,index0:n+l,index1:a.index1,index2:a.index2,n0:t,n1:a.n1,n2:a.n2});e.push(k,p,100.11,this.index,1,this.center[0],this.center[1]);f.push(n+l,a.index0,a.index1)}else r==d?(l++,h=.5*(w[0]+
z[0]),g=.5*(w[1]+z[1]),m=.5*(w[2]+z[2]),k=.5*(a.pt22[0]+a.pt11[0]),p=.5*(a.pt22[1]+a.pt11[1]),t=b.createFrom(h,g,m),b.normalize(t),c.push({pt0:a.pt0,pt1:a.pt1,pt2:[h,g,m],pt00:a.pt00,pt11:a.pt11,pt22:[k,p],index0:a.index0,index1:a.index1,index2:n+l,n0:a.n0,n1:a.n1,n2:t}),c.push({pt0:a.pt0,pt1:[h,g,m],pt2:a.pt2,pt00:a.pt00,pt11:[k,p],pt22:a.pt22,index0:a.index0,index1:n+l,index2:a.index2,n0:a.n0,n1:t,n2:a.n2}),e.push(k,p,100.11,this.index,1,this.center[0],this.center[1]),f.push(n+l,a.index1,a.index2)):
r==y&&(l++,h=.5*(u[0]+z[0]),g=.5*(u[1]+z[1]),m=.5*(u[2]+z[2]),k=.5*(a.pt22[0]+a.pt00[0]),p=.5*(a.pt22[1]+a.pt00[1]),t=b.createFrom(h,g,m),b.normalize(t),c.push({pt0:a.pt0,pt1:a.pt1,pt2:[h,g,m],pt00:a.pt00,pt11:a.pt11,pt22:[k,p],index0:a.index0,index1:a.index1,index2:n+l,n0:a.n0,n1:a.n1,n2:t}),c.push({pt0:[h,g,m],pt1:a.pt1,pt2:a.pt2,pt00:[k,p],pt11:a.pt11,pt22:a.pt22,index0:n+l,index1:a.index1,index2:a.index2,n0:t,n1:a.n1,n2:a.n2}),e.push(k,p,100.11,this.index,1,this.center[0],this.center[1]),f.push(n+
l,a.index2,a.index0))}else f.push(a.index0,a.index1,a.index2)},_subdivision2:function(c,b,f,a,u,d){for(var e,r,h,g,m,k,p=f.length/3,l=0,n=0;n<p;n++)g=f[l++],m=f[l++],k=f[l++],e=3*g,r=3*m,h=3*k,this._doSubdivision([{pt0:[b[e],b[e+1],b[e+2]],pt1:[b[r],b[r+1],b[r+2]],pt2:[b[h],b[h+1],b[h+2]],pt00:[c[e],c[e+1]],pt11:[c[r],c[r+1]],pt22:[c[h],c[h+1]],index0:g+a,index1:m+a,index2:k+a}],u,d)},destroy:function(){this.isFulfilled()||this.reject()}})});