//>>built
define("dojo/_base/lang dojo/_base/array esri/core/declare esri/core/lang esri/views/3d/webgl-engine/lib/Util esri/core/libs/earcut/earcut ../../webgl-engine-extensions/VertexBufferLayout ../../webgl-engine-extensions/GLVertexArrayObject ../../webgl-engine-extensions/GLXBO ../../webgl-engine-extensions/GLVerTexture ../../support/fx3dUtils ../../support/fx3dUnits ../Effect ./AreaExtrudeMaterial ./AreaExtrudeGeometry".split(" "),function(n,p,t,A,u,B,v,w,q,C,h,r,x,y,z){var g,m=u.VertexAttrConstants;
return window.WebGLRenderingContext,t([x],{declaredClass:"esri.views.3d.effects.AreaExtrude.AreaExtrudeEffect",effectName:"AreaExtrude",constructor:function(a){this.orderId=2;this._polygonIndex=this._polygonIdNum=0;this._polygonNormals=[];this._vertexNums=this._indexNums=0;this._renderObjects={};this._maxDist=0;this._needsAllLoaded=!1},_initRenderingInfo:function(){this.renderingInfo.height=1E4;this.renderingInfo.topColors=[[128,100,253],[160,162,140],[255,100,128]];this._colorBarDirty=!0;this.renderingInfo.bottomColor=
[0,255,0];this._shapeDirty=this._vacDirty=this._renderingInfoDirty=!0;this.inherited(arguments)},_doRenderingInfoChange:function(a){this.inherited(arguments);for(var b in a)a.hasOwnProperty(b)&&this.renderingInfo.hasOwnProperty(b)&&(h.endsWith(b.toLowerCase(),"info")?h.isInforAttrChanged(this.renderingInfo[b],a[b])&&(this._renderingInfoDirty=!0):h.endsWith(b.toLowerCase(),"color")?a[b]instanceof Array&&3==a[b].length&&(this.renderingInfo[b]=[a[b][0]/255,a[b][1]/255,a[b][2]/255]):h.endsWith(b.toLowerCase(),
"colors")?a[b]instanceof Array&&(this.renderingInfo[b]=a[b],this._colorBarDirty=!0,this._renderingInfoDirty=!0):"height"===b.toLowerCase()||"transparency"===b.toLowerCase()?(this._clampScope(a,b),"height"==b&&this._heightUnit?(this.renderingInfo[b]=r.toMeters(this._heightUnit,a[b],this._view.viewingMode),this._updateDefaultLabelHeight()):this.renderingInfo[b]=a[b]):typeof a[b]==typeof this.renderingInfo[b]&&(this.renderingInfo[b]=a[b]))},_updateDefaultLabelHeight:function(){this._layer._labelDefaultHeight=
{flag:1,min:this._scopes.height[0],max:this.renderingInfo.height}},setContext:function(a){this.inherited(arguments);this._effectConfig&&n.isArray(this._effectConfig.renderingInfo)&&(this._heightUnit=null,p.forEach(this._effectConfig.renderingInfo,function(a){"height"===a.name.toLowerCase()&&(this._heightUnit=a.unit,this.renderingInfo.height=r.toMeters(this._heightUnit,this.renderingInfo.height,this._view.viewingMode),this._updateDefaultLabelHeight())}.bind(this)))},destroy:function(){this._resetBuffers()},
_resetBuffers:function(){for(var a in this._renderObjects)this._dispose(this._renderObjects[a].vbo),this._dispose(this._renderObjects[a].ibo),this._dispose(this._renderObjects[a].vao);this._renderObjects={}},_initVertexLayout:function(){this._vertexAttrConstants=[m.POSITION,m.AUXPOS1,m.AUXPOS2];this._vertexBufferLayout=new v(this._vertexAttrConstants,[3,2,2],[5126,5126,5126])},_initRenderContext:function(){if(this.inherited(arguments),this._vacDirty)if(this._initVertexLayout(),this._vacDirty=!1,this._isAddingGeometry)for(var a in this._renderObjects)this._unBindBuffer(this._renderObjects[a].vao,
this._renderObjects[a].vbo,this._renderObjects[a].ibo),this._renderObjects[a].vao&&(this._renderObjects[a].vao._initialized=!1);else this._resetBuffers();return this._localBindsCallback||(this._localBindsCallback=this._localBinds.bind(this)),this._buildAreaGeometries()},_buildAreaGeometries:function(){var a=this._isAddingGeometry?this._addedGraphics:this._allGraphics();if(0<a.length){var b=this._vertexBufferLayout.getStride();this._isAddingGeometry||(this._polygonIdNum=0,this._indexNums=0,this._vertexNums=
0);for(var c=[],d=0;d<a.length;d++){var e=a[d];if(null!=e.geometry){var k=e.geometry.rings;k&&0!==k.length&&(c.push(new z(e,this._polygonIdNum,b)),this._polygonIdNum++)}}for(a=0;a<c.length;a++)this.waitForGeometry(c[a]);return this._resetAddGeometries(),!0}return!1},waitForGeometry:function(a){if(a){a=a.createBuffers(this._wgs84SpatialReference,this.view.renderSpatialReference);for(var b=0;b<a.length;b++){var c=a[b];c&&(this._renderObjects[c.origin.id]||(this._renderObjects[c.origin.id]={vbo:new q(this._gl,
!0,this._vertexBufferLayout),ibo:new q(this._gl,!1),vao:this._vaoExt?new w(this._gl,this._vaoExt):null,offset:0,origin:c.origin.vec3,buffers:[]}));var d=this._renderObjects[c.origin.id];d.vbo.addData(!0,c.vertices);for(var e=c.indices,k=0;k<e.length;k++)e[k]+=d.offset;d.ibo.addData(!0,c.indices);d.offset+=c.vertexNum;d.buffers.push(c);this._maxDist<c.dist&&(this._maxDist=c.dist);1E5<this._maxDist&&(this._maxDist=1E5);d.vao&&(d.vao._initialized=!1)}this._polygonIndex+=a.length}},_initPolygonNormalVerTexture:function(){var a=
this._allGraphics();if(0<a.length){var b=this._gl.getParameter(3379),c=a.length,d=h.nextHighestPowerOfTwo(c);d>b&&(d=b,console.warn("Too many graphics, and extra features will be discarded."));var e=Math.ceil(c/d),e=h.nextHighestPowerOfTwo(e);e>b&&(e=b,console.warn("Too many graphics, and extra features will be discarded."));this._vizFieldVerTextures[this._vizFieldDefault].setData(d,e,new Float32Array(d*e*4));var k,f,g,l;return p.forEach(this._vizFields,function(b){var c=new Float32Array(d*e*4);(f=
a[0].attributes[b])||(f=0);(!f||"number"!=typeof f||0>f)&&(f=0);g=l=f;for(var h=0;h<a.length;h++)k=a[h].attributes,f=k[b],(!f||"number"!=typeof f||0>f)&&(f=0),c[4*h]=f,l<f&&(l=f),g>f&&(g=f);this._vizFieldVerTextures[b].setData(d,e,c);this._vizFieldMinMaxs[b].min=g;this._vizFieldMinMaxs[b].max=l;this._updateVizFieldMinMaxToLayer()}.bind(this)),vec2d.set2(d,e,this._vizFieldVerTextureSize),!0}return!1},_loadShaders:function(){return this.inherited(arguments),this._material||(this._material=new y({pushState:this._pushState.bind(this),
restoreState:this._restoreState.bind(this),gl:this._gl,viewingMode:this._view.viewingMode,shaderSnippets:this._shaderSnippets})),this._material.loadShaders()},_initColorBar:function(){if(!this._colorBarDirty)return!0;this._colorBarTexture||(this._colorBarTexture=this._gl.createTexture());var a=this._gl.getParameter(32873);this._gl.bindTexture(3553,this._colorBarTexture);this._gl.pixelStorei(37440,!0);this._gl.texParameteri(3553,10240,9728);this._gl.texParameteri(3553,10241,9728);this._gl.texParameteri(3553,
10242,33071);this._gl.texParameteri(3553,10243,33071);var b=h.createColorBarTexture(32,1,this.renderingInfo.topColors);return this._gl.texImage2D(3553,0,6408,6408,5121,b),this._gl.generateMipmap(3553),this._gl.bindTexture(3553,a),0===this._gl.getError()},_localBinds:function(a,b){a.bind(this._material._program);this._vertexBufferLayout.enableVertexAttribArrays(this._gl,this._material._program);b.bind()},_bindBuffer:function(a,b,c){a?(a._initialized||a.initialize(this._localBindsCallback,[b,c]),a.bind()):
this._localBinds(b,c)},_unBindBuffer:function(a,b,c){a?a.unbind():(b.unbind(),this._vertexBufferLayout.disableVertexAttribArrays(this._gl,this._material._program),c.unbind())},render:function(a,b){if(this.inherited(arguments),this._layer.visible&&this.ready&&this._bindPramsReady()){this._hasSentReady||(this._layer.emit("fx3d-ready"),this._hasSentReady=!0);this._material.bind(n.mixin({},{el:this._vizFieldVerTextures[this._vizFieldDefault],me:this._vizFieldVerTextures[this._vizFields[this._currentVizPage]],
sl:this._vizFieldVerTextureSize,li:this.renderingInfo.animationInterval,po:[this._scopes.height[0],this.renderingInfo.height],im:this.renderingInfo.transparency,ls:this.renderingInfo.bottomColor,es:this._vizFieldMinMaxs[this._vizFieldDefault].min>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min?this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min:this._vizFieldMinMaxs[this._vizFieldDefault].min,pp:this._vizFieldMinMaxs[this._vizFieldDefault].max>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max?
this._vizFieldMinMaxs[this._vizFieldDefault].max:this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max,lp:this._colorBarTexture,io:this._maxDist},a),b);for(var c in this._renderObjects)g=this._renderObjects[c],this._bindBuffer(g.vao,g.vbo,g.ibo),this._gl.drawElements(4,g.ibo.getNum(),5125,0);this._material.release(b);this._unBindBuffer(g.vao,g.vbo,g.ibo)}}})});