//>>built
define("esri/core/declare esri/geometry/support/centroid esri/views/3d/support/PromiseLightweight esri/views/3d/layers/graphics/Graphics3DSymbolCommonCode esri/core/libs/earcut/earcut esri/core/libs/gl-matrix-2/vec3f64 esri/core/libs/gl-matrix-2/vec3 ../../support/geometryUtils".split(" "),function(K,L,F,G,M,N,c,O){var k=N.vec3f64;c=c.vec3;var B=k.create(),D=k.create(),H=k.create(),I=k.create(),J=k.create(),w=k.create(),z=k.create(),A=k.create(),E=Math.cos(Math.PI/180*5);return K(F["default"]||F.PromiseLightweight,
{constructor:function(b,e,g){var a=b.geometry.rings;this.center=L.polygonCentroid({rings:a,hasZ:!1});(this._geometryData=G.copyPathData(a,b.geometry.hasZ))&&0<=e&&0<=g?(this.index=e,this.stride=g,this.resolve()):this.reject()},createBuffers:function(b,e){var g,a,f,d,c,y=this._geometryData.polygons,l=[],h=this._geometryData.vertexData;if(!h)return l;var p=h.length/3,m=new Float64Array(h.length);G.reproject(h,0,b,m,0,e,p);e=new Float64Array(m);for(var r=0;r<y.length;++r){b=y[r];f=b.count;c=b.index;
var n=new Float64Array(h.buffer,3*c*h.BYTES_PER_ELEMENT,3*f);if(g=b.holeIndices.map(function(a){return a-c}),a=M(n,g,3),!(1>a.length)){var q={polygonIndex:r},t=new Float64Array(e.buffer,3*c*e.BYTES_PER_ELEMENT,3*f),u=this._computeNormalAndDistance(t);q.dist=u.distance;if(f=O.getOrigin(m,p,c,f)){q.origin=f;var u=[],k=[];f=b.count;for(var v=0;v<f;v++)d=v*this.stride,u[0+d]=n[0+3*v],u[1+d]=n[1+3*v],u[2+d]=1,u[3+d]=this.index,u[4+d]=0,u[5+d]=this.center[0],u[6+d]=this.center[1],d=(v+f)*this.stride,u[0+
d]=n[0+3*v],u[1+d]=n[1+3*v],u[2+d]=100.11,u[3+d]=this.index,u[4+d]=1,u[5+d]=this.center[0],u[6+d]=this.center[1];for(var w=v=d=0;w<b.pathLengths.length;w++){for(var v=b.pathLengths[w],x=0;x<v;x++)x!==v-1?k.push(x+1+d,x+d,x+1+f+d,x+1+f+d,x+d,x+f+d):k.push(0+d,x+d,0+f+d,0+f+d,x+d,x+f+d);d+=v}this._subdivision2(n,t,a,f,u,k);q.indexNums=k.length;q.vertexNum=u.length/this.stride;q.vertices=new Float32Array(u);q.indices=new Uint32Array(k);l.push(q)}}}return l},_computeNormalAndDistance:function(b){var e=
0,g=3,a=6;c.set(B,b[e++],b[e++],b[e++]);c.set(D,b[g++],b[g++],b[g++]);c.set(H,b[a++],b[a++],b[a++]);c.subtract(I,B,D);c.subtract(J,H,D);b=k.create();c.cross(b,I,J);c.normalize(b,b);e=6378137-Math.abs(c.dot(b,B));g=c.normalize(B,B);g=c.dot(b,g);return{normal:b,distance:Math.abs(e/g)}},_subdivision:function(b,e,c,a,f,d){for(var g,k,l,h,p,m,r,n=e.length/3,q=0,t=0,u=0;u<n;u++)h=e[q++],p=e[q++],m=e[q++],g=3*h,k=3*p,l=3*m,r=(b[g]+b[k]+b[l])/3,g=(b[g+1]+b[k+1]+b[l+1])/3,f.push(r,g,100.11,this.index,1,this.center[0],
this.center[1]),d.push(h+c,p+c,a+t),d.push(p+c,m+c,a+t),d.push(m+c,h+c,a+t),t++},_doSubdivision:function(b,e,g){if(0<b.length)for(var a,f,d,C,y,l,h,p,m,r,n=-1,q=e.length/this.stride;null!=(a=b.pop());)if(c.copy(w,a.pt0),c.copy(z,a.pt1),c.copy(A,a.pt2),a.n0||(a.n0=k.create(),c.normalize(a.n0,w)),a.n1||(a.n1=k.create(),c.normalize(a.n1,z)),a.n2||(a.n2=k.create(),c.normalize(a.n2,A)),f=c.dot(a.n0,a.n1),d=c.dot(a.n1,a.n2),C=c.dot(a.n0,a.n2),f<E||d<E||C<E){if(y=Math.min(f,d,C),!isNaN(y)&&null!=y)if(y==
f){n++;l=.5*(w[0]+z[0]);h=.5*(w[1]+z[1]);p=.5*(w[2]+z[2]);m=.5*(a.pt00[0]+a.pt11[0]);r=.5*(a.pt00[1]+a.pt11[1]);var t=k.fromValues(l,h,p);c.normalize(t,t);b.push({pt0:a.pt0,pt1:[l,h,p],pt2:a.pt2,pt00:a.pt00,pt11:[m,r],pt22:a.pt22,index0:a.index0,index1:q+n,index2:a.index2,n0:a.n0,n1:t,n2:a.n2});b.push({pt0:[l,h,p],pt1:a.pt1,pt2:a.pt2,pt00:[m,r],pt11:a.pt11,pt22:a.pt22,index0:q+n,index1:a.index1,index2:a.index2,n0:t,n1:a.n1,n2:a.n2});e.push(m,r,100.11,this.index,1,this.center[0],this.center[1]);g.push(q+
n,a.index0,a.index1)}else y==d?(n++,l=.5*(z[0]+A[0]),h=.5*(z[1]+A[1]),p=.5*(z[2]+A[2]),m=.5*(a.pt22[0]+a.pt11[0]),r=.5*(a.pt22[1]+a.pt11[1]),t=k.fromValues(l,h,p),c.normalize(t,t),b.push({pt0:a.pt0,pt1:a.pt1,pt2:[l,h,p],pt00:a.pt00,pt11:a.pt11,pt22:[m,r],index0:a.index0,index1:a.index1,index2:q+n,n0:a.n0,n1:a.n1,n2:t}),b.push({pt0:a.pt0,pt1:[l,h,p],pt2:a.pt2,pt00:a.pt00,pt11:[m,r],pt22:a.pt22,index0:a.index0,index1:q+n,index2:a.index2,n0:a.n0,n1:t,n2:a.n2}),e.push(m,r,100.11,this.index,1,this.center[0],
this.center[1]),g.push(q+n,a.index1,a.index2)):y==C&&(n++,l=.5*(w[0]+A[0]),h=.5*(w[1]+A[1]),p=.5*(w[2]+A[2]),m=.5*(a.pt22[0]+a.pt00[0]),r=.5*(a.pt22[1]+a.pt00[1]),t=k.fromValues(l,h,p),c.normalize(t,t),b.push({pt0:a.pt0,pt1:a.pt1,pt2:[l,h,p],pt00:a.pt00,pt11:a.pt11,pt22:[m,r],index0:a.index0,index1:a.index1,index2:q+n,n0:a.n0,n1:a.n1,n2:t}),b.push({pt0:[l,h,p],pt1:a.pt1,pt2:a.pt2,pt00:[m,r],pt11:a.pt11,pt22:a.pt22,index0:q+n,index1:a.index1,index2:a.index2,n0:t,n1:a.n1,n2:a.n2}),e.push(m,r,100.11,
this.index,1,this.center[0],this.center[1]),g.push(q+n,a.index2,a.index0))}else g.push(a.index0,a.index1,a.index2)},_subdivision2:function(b,c,g,a,k,d){for(var e,f,l,h,p,m,r=g.length/3,n=0,q=0;q<r;q++)h=g[n++],p=g[n++],m=g[n++],e=3*h,f=3*p,l=3*m,this._doSubdivision([{pt0:[c[e],c[e+1],c[e+2]],pt1:[c[f],c[f+1],c[f+2]],pt2:[c[l],c[l+1],c[l+2]],pt00:[b[e],b[e+1]],pt11:[b[f],b[f+1]],pt22:[b[l],b[l+1]],index0:h+a,index1:p+a,index2:m+a}],k,d)},destroy:function(){this.isFulfilled()||this.reject()}})});