//>>built
define("dojo/_base/lang dojo/_base/array esri/core/declare esri/views/layers/LayerView esri/layers/graphics/controllers/SnapshotController esri/geometry/Point esri/geometry/Extent esri/views/3d/support/projectionUtils esri/core/libs/gl-matrix-2/vec3f64 esri/core/libs/gl-matrix-2/vec3 esri/geometry/SpatialReference esri/core/watchUtils esri/core/Collection esri/Graphic esri/symbols/PictureMarkerSymbol esri/geometry/support/centroid ../effects/FxEffectRenderer ../effects/FxEffectFactory ../support/fx3dUtils".split(" "),
function(p,A,B,C,D,E,x,y,n,l,F,G,H,v,I,J,t,K,w){n=n.vec3f64;l=l.vec3;var k=n.create(),q=n.create(),r=n.create(),u=n.create(),z=n.create();return B(C,{declaredClass:"esri.views.3d.layers.FxLayerView3D",constructor:function(){this._perPageScale=1;this.supportsDraping=!1;this._fx3dSpatialReference=F.WGS84;this.availableFields=["*"]},initialize:function(){this.layer.when().then(function(){t.init(this.view);this._eventHandles=[];this.loadedGraphics=null;this._graphicsLoading=!0;this._graphicsCollectionEventHandle=
null;this._graphicsControllerEventHandles=[];var b=this._initEffect();b.then(p.hitch(this,this._initGraphicsController));this.addResolvingPromise(b);this._eventHandles.push(this.layer.on("destroy-fxlayer",function(){t.pause();t.destroy(this._layerVizType,this._layerId);this.view.map.remove(this.layer)}.bind(this)));this._eventHandles.push(this.layer.on("show-feature-label",p.hitch(this,this._onShowFeatureLabel)));this._eventHandles.push(this.layer.on("hide-feature-label",function(){this.layer._labelsLayer&&
(this.layer._labelsLayer.removeAll(),this._selectedFeature=null)}.bind(this)));this._eventHandles.push(this.view.on("click",p.hitch(this,this._viewClicked)))}.bind(this))},destroy:function(){this._viewModelHandler&&(this._viewModelHandler.remove(),this._viewModelHandler=null);var b=function(a){a.remove()};this.controller&&(this.controller.destroy(),this.controller=null);this._graphicsCollectionEventHandle&&this._graphicsCollectionEventHandle.remove();this._graphicsControllerEventHandles.forEach(b);
this._tilingSchemeHandle&&this._tilingSchemeHandle.remove();this._eventHandles.forEach(b);this.inherited(arguments)},getLoadedGraphics:function(){return this.loadedGraphics&&this.loadedGraphics.toArray?[].concat(this.loadedGraphics.toArray()):[]},_initEffect:function(){return K.make({layer:this.layer,layerView:this,view:this.view})},_calculateExtentCenter:function(b){var a=b.length;if(a){var c,e,f,d,g,m,h;if("point"==this.layer.geometryType)for(c=e=b[0].geometry.longitude,f=d=b[0].geometry.latitude,
m=1;m<a;m++)g=b[m],null!=g.geometry&&(g.geometry.longitude<c&&(c=g.geometry.longitude),g.geometry.longitude>e&&(e=g.geometry.longitude),g.geometry.latitude<f&&(f=g.geometry.latitude),g.geometry.latitude>d&&(d=g.geometry.latitude));else if("polyline"==this.layer.geometryType||"polygon"==this.layer.geometryType)for(h=b[0].geometry.extent,c=h.xmin,e=h.xmax,f=h.ymin,d=h.ymax,m=1;m<a;m++)g=b[m],null!=g.geometry&&null!=g.geometry.extent&&(h=g.geometry.extent,h.xmin<c&&(c=h.xmin),h.xmax>e&&(e=h.xmax),h.ymin<
f&&(f=h.ymin),h.ymax>d&&(d=h.ymax));return this._minDelta=6937.5*Math.min(e-c,d-f),new x(c,f,e,d,this._fx3dSpatialReference)}return null},_getGeomZFromPolyline:function(b,a){return l.set(q,b[0],b[1],b[2]||1),w.wgs84ToSphericalEngineCoords(q,0,q,0),l.set(r,a[0],a[1],a[2]||1),w.wgs84ToSphericalEngineCoords(r,0,r,0),l.subtract(z,q,r),l.add(u,q,r),l.scale(u,u,.5),l.length(u)+.6*l.length(z)-6378137},_calculatePerfectPosition:function(b){var a={};if(null==b||null==b.geometry)return console.warn("Feature or geometry is invalid."),
a;var c,e,f,d=b.geometry;if("point"===this.layer.geometryType)a.x=d.longitude,a.y=d.latitude,d=this.layer._labelDefaultHeight,a.z=5E3,d&&this.layer._currentVizFieldMinMax&&(f=this.layer._currentVizFieldMinMax.max-this.layer._currentVizFieldMinMax.min,isNaN(f)||"number"==typeof this.layer._currentVizPage&&(c=this.layer.vizFields[this.layer._currentVizPage],e=b.attributes[c],null!=e&&(0===d.flag?(a.z+=d.max,0!=f?a.z*=(e-this.layer._currentVizFieldMinMax.min)/f:a.z=d.min):1===d.flag&&(d.max===d.min?
a.z+=d.max:0!=f?a.z+=1.2*(d.min+(d.max-d.min)*(e-this.layer._currentVizFieldMinMax.min)/f):0!=this.layer._currentVizFieldMinMax.max?a.z+=d.max:a.z=d.min))));else if("polyline"===this.layer.geometryType){if(null==d.paths)return console.warn("Paths of feature is invalid."),a;b=d.paths[0];c=b.length;a.x=(b[0][0]+b[c-1][0])/2;a.y=(b[0][1]+b[c-1][1])/2;a.z=1.1*this._getGeomZFromPolyline(b[0],b[c-1])}else if("polygon"===this.layer.geometryType){if(null==d.rings)return console.warn("Rings of feature is invalid."),
a;f=J.polygonCentroid({rings:d.rings,hasZ:!1});if(isNaN(f[0])||isNaN(f[1]))return null;a.x=f[0];a.y=f[1];d=this.layer._labelDefaultHeight;a.z=10;f=this.layer._currentVizFieldMinMax.max-this.layer._currentVizFieldMinMax.min;isNaN(f)||(c=this.layer.vizFields[this.layer._currentVizPage],e=b.attributes[c],null!=e&&(0===d.flag?(a.z+=d.max,0!=f?a.z*=(e-this.layer._currentVizFieldMinMax.min)/f:a.z=d.min):1===d.flag&&(d.max===d.min?a.z+=d.max:0!=f?a.z+=1.3*(d.min+(d.max-d.min)*(e-this.layer._currentVizFieldMinMax.min)/
f):0!=this.layer._currentVizFieldMinMax.max?a.z+=d.max:a.z=d.min)))}return isNaN(a.z)&&(a.z=null),a},_calculatePerfectHeight:function(){var b=this.layer._labelDefaultHeight,a=10;this.layer._currentVizFieldMinMax.max==this.layer._currentVizFieldMinMax.min&&0==this.layer._currentVizFieldMinMax.max?a=b&&b.min||1E3:b&&(0===b.flag?a+=b.max:1===b.flag&&(a+=b.max===b.min?b.max:1.2*(b.min+(b.max-b.min))));b=Math.abs(a)/111E3;return"local"==this.view.viewModel&&(b=Math.abs(a)/235596.8),10<b&&(b=10),{z:a,lonD:b}},
_onShowFeatureLabel:function(b){if(this.layer._labelsLayer&&this.layer._labelsLayer.visible){if(this._selectedFeature=null,b.feature){if(null==b.feature.geometry)return void console.warn("The feature with FID has no geometry content.");this.layer._labelsLayer.removeAll();var a=this._calculatePerfectPosition(b.feature);if(null==a.x||null==a.y)return;null==a.z?a.z=10:a.z+=1E3;var c=w.createTextTexture(""+b.feature.attributes[this.layer.displayField],14,"#ffffff","center","Arial","rgba(0,0,0,0.5)"),
c=new I({url:c.toDataURL(),width:c.width,height:c.height,contentType:"image/png"}),e=new E(a.x,a.y,a.z,this._fx3dSpatialReference),c=new v(e,c,b.feature.attributes,this.layer.popupTemplate);this.layer._labelsLayer.add(c);c=Math.abs(a.z)/111E3;e=Math.abs(a.z)/(111E3*Math.cos(a.y*Math.PI/180));"local"==this.view.viewModel&&(c=Math.abs(a.z)/111319.5,e=Math.abs(a.z)/235596.8);10<e&&(e=10);20<c&&(c=20);c=new x(a.x-c,a.y-e,a.x+c,a.y+e,this._fx3dSpatialReference);c.zmin=a.z-1;c.zmax=a.z;this._animateTo(c)}else this.layer._labelsLayer.removeAll();
this._selectedFeature=b.feature}},_updateSelectedFeatureLabel:function(){if(this.layer._labelsLayer){var b=0<this.layer._labelsLayer.graphics.toArray().length;this.layer._labelsLayer.removeAll();b&&this._selectedFeature&&this._onShowFeatureLabel({feature:this._selectedFeature})}},_viewClicked:function(b){if(b.graphic)if(this.layer._labelsLayer&&b.graphic.layer===this.layer._labelsLayer)0==this.layer._labelsLayer.graphics.length&&this._onShowFeatureLabel({feature:b.graphic});else{if(b.graphic.layer===
this.layer&&this.view&&this.view.popup.viewModel.selectedFeature){b=this.view.popup.viewModel.selectedFeature;var a=new v({attributes:p.clone(b.attributes),geometry:b.geometry&&b.geometry.clone()||null,popupTemplate:b.popupTemplate||null,symbol:b.symbol||null,visible:b.visible});null!=a&&(this._onShowFeatureLabel({feature:a}),this.layer.emit("selected-feature-from-globe",{selectedFeature:a}),this.view.popup.viewModel._set("selectedFeature",null))}}else if(this.layer._labelsLayer&&0<this.layer._labelsLayer.graphics.length&&
(this.layer._labelsLayer.removeAll(),this._selectedFeature=null,this.layer.emit("abandon-selected-feature"),this.view&&this.view.popup.viewModel._set("selectedFeature",null)),this.view&&this.view.popup.viewModel.selectedFeature)try{this.view.popup.viewModel.selectedFeature.symbol=null,this.view.popup.viewModel.selectedFeature.popupTemplate=null,a=this.view.popup.viewModel.selectedFeature.clone(),this._onShowFeatureLabel({feature:a}),this.layer.emit("selected-feature-from-globe",{selectedFeature:a})}finally{this.view.popup.viewModel._set("selectedFeature",
null)}},_animateTo:function(b,a,c){this.view&&this.view.goTo({target:b,heading:this.view.camera.heading,tilt:this.view.camera.tilt})},_initGraphicsController:function(b){if(t.add(this.layer,b)){this._layerId=this.layer.id;this._layerVizType=this.layer.vizType;var a=this.view.map.layers.find(function(a){return a.url===this.layer.url&&"esri.layers.FeatureLayer"===a.declaredClass&&"Feature Layer"===a.type&&!0===a.loaded}.bind(this)),c=this;b=function(){var a=H.ofType(v),a={layer:c.layer,layerView:c,
maxPageSize:300,graphics:new a};c.controller=new D(a);G.whenTrueOnce(c.view,"basemapTerrain.ready",function(){c.controller.when().then(function(){var a=null;c.loadedGraphics=c.controller.graphics;c._graphicsCollectionEventHandle=c.loadedGraphics.on("change",c._collectionChangeHandler.bind(c));0<c.loadedGraphics.length&&(a=c.loadedGraphics.toArray(),c._add([].concat(a)));c._graphicsControllerEventHandles.push(c.controller.on("query-end",function(){c._graphicsLoading=!1}));c.controller.startup()},function(a){console.log(a)})})};
if(a){var e=this.view.layerViews.find(function(b){return b.layer.url===a.url&&b.layer.id===a.id}.bind(this));e?(a.source&&this.layer._initLayerProperties(a.source),this.loadedGraphics=e.loadedGraphics,0<this.loadedGraphics.length&&this._add([].concat(this.loadedGraphics.toArray())),this.layer.on("can-locating-now",function(){var a=this._calculateExtentCenter(this.loadedGraphics);if(a){var b=this._calculatePerfectHeight();a.zmax=b.z;a.zmin=b.z-1;a.xmax+=2+b.lonD;a.xmin-=2+b.lonD;a.ymax+=1+b.lonD;a.ymin-=
1+b.lonD;this._animateTo(a)}}.bind(this)),this.layer.emit("all-features-loaded",{graphics:[].concat(this.loadedGraphics.toArray())})):b()}else b()}},_collectionChangeHandler:function(b){this._add([].concat(b.added));this._remove([].concat(b.removed))},_add:function(b){function a(a){var b,d;a=[].concat(a);A.forEach(a,function(a){if(b=a.geometry)if("point"==c.layer.geometryType)y.xyzToVector(b.x,b.y,b.z,b.spatialReference,k,c._fx3dSpatialReference),b.longitude=k[0],b.latitude=k[1],b.altitude=isNaN(k[2])?
null:k[2];else{if("polyline"==c.layer.geometryType||"polygon"==c.layer.geometryType)for(d=b.paths||b.rings,a=0;a<d.length;a++)for(var e=0;e<d[a].length;e++)y.xyzToVector(d[a][e][0],d[a][e][1],d[a][e][2],b.spatialReference,k,c._fx3dSpatialReference),d[a][e][0]=k[0],d[a][e][1]=k[1],d[a][e][2]=isNaN(k[2])?null:k[2]}else console.warn("No geometry information found in feature: "+a.attributes.FID)});c.layer.emit("fx3d-add-graphics",{graphics:a});c._graphicsLoading||(c.layer.on("can-locating-now",function(){var a=
c._calculateExtentCenter(c.getLoadedGraphics());if(a){var b=c._calculatePerfectHeight();a.zmax=b.z;a.zmin=b.z-1;a.xmax+=2+b.lonD;a.xmin-=2+b.lonD;a.ymax+=1+b.lonD;a.ymin-=1+b.lonD;c._animateTo(a)}}),c.layer.emit("all-features-loaded",{graphics:c.getLoadedGraphics()}))}if(p.isArray(b)&&0<b.length){var c=this;this.isResolved()?a(b):this.when().then(function(){a(b)})}},_remove:function(b){p.isArray(b)&&0<b.length}})});