// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"Suora viivan mittaus",hint:"Aloita mittaus napsauttamalla maisemaa ja sijoita ensimm\u00e4inen pisteesi",unsupported:"Kolmiulotteista suoran viivan mittausta tuetaan vain SceneView-sovelluksessa.",distance:"Et\u00e4isyys",direct:"Suora",horizontal:"Vaaka",vertical:"Pysty",unit:"Yksikk\u00f6",newMeasurement:"Uusi mittaus",units:{metric:"Metrij\u00e4rjestelm\u00e4",imperial:"Mailij\u00e4rjestelm\u00e4",kilometers:"Kilometri\u00e4",
meters:"Metri\u00e4",miles:"Mailia",inches:"Tuumaa",feet:"Jalkaa",yards:"Jaardia","nautical-miles":"Meripeninkulmaa","us-feet":"Jalkaa (Yhdysvallat)","degrees-minutes-seconds":"DMS",degrees:"Asteet"},_localized:{}},"esri/core/nls/Units":{measures:{length:"Pituus",area:"Alue",volume:"Tilavuus",angle:"Kulma"},units:{millimeters:{singular:"millimetri",plural:"millimetri\u00e4",abbr:"mm"},centimeters:{singular:"senttimetri",plural:"senttimetri\u00e4",abbr:"cm"},decimeters:{singular:"desimetri",plural:"desimetri\u00e4",
abbr:"dm"},meters:{singular:"metri",plural:"metri\u00e4",abbr:"m"},kilometers:{singular:"kilometri",plural:"kilometri\u00e4",abbr:"km"},inches:{singular:"tuuma",plural:"tuumaa",abbr:"tuuma"},feet:{singular:"jalka",plural:"jalkaa",abbr:"ft"},yards:{singular:"jaardi",plural:"jaardia",abbr:"yd"},miles:{singular:"maili",plural:"mailia",abbr:"mailia"},"nautical-miles":{singular:"merimaili",plural:"meripeninkulmaa",abbr:"mpk"},"us-feet":{singular:"jalka (Yhdysvallat)",plural:"jalkaa (Yhdysvallat)",abbr:"ft"},
"square-millimeters":{singular:"neli\u00f6millimetri",plural:"neli\u00f6millimetri\u00e4",abbr:"mm\u00b2"},"square-centimeters":{singular:"neli\u00f6senttimetri",plural:"neli\u00f6senttimetri\u00e4",abbr:"cm\u00b2"},"square-decimeters":{singular:"neli\u00f6desimetri",plural:"neli\u00f6desimetri\u00e4",abbr:"dm\u00b2"},"square-meters":{singular:"neli\u00f6metri",plural:"neli\u00f6metri\u00e4",abbr:"m\u00b2"},"square-kilometers":{singular:"neli\u00f6kilometri",plural:"neli\u00f6kilometri\u00e4",abbr:"km\u00b2"},
"square-inches":{singular:"neli\u00f6tuuma",plural:"neli\u00f6tuumaa",abbr:"in\u00b2"},"square-feet":{singular:"neli\u00f6jalka",plural:"neli\u00f6jalkaa",abbr:"ft\u00b2"},"square-yards":{singular:"neli\u00f6jaardi",plural:"neli\u00f6jaardia",abbr:"yd\u00b2"},"square-miles":{singular:"neli\u00f6maili",plural:"neli\u00f6mailia",abbr:"mi\u00b2"},"square-us-feet":{singular:"neli\u00f6jalka (Yhdysvallat)",plural:"neli\u00f6jalkaa (Yhdysvallat)",abbr:"ft\u00b2"},acres:{singular:"eekkeri",plural:"eekkeri\u00e4",
abbr:"eekkeri"},ares:{singular:"aari",plural:"a",abbr:"a"},hectares:{singular:"hehtaari",plural:"hehtaaria",abbr:"ha"},liters:{singular:"litra",plural:"litraa",abbr:"l"},"cubic-millimeters":{singular:"kuutiomillimetri",plural:"kuutiomillimetri\u00e4",abbr:"mm\u00b3"},"cubic-centimeters":{singular:"kuutiosenttimetri",plural:"kuutiosenttimetri\u00e4",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"kuutiodesimetri",plural:"kuutiodesimetri\u00e4",abbr:"dm\u00b3"},"cubic-meters":{singular:"kuutiometri",
plural:"kuutiometri\u00e4",abbr:"m\u00b3"},"cubic-kilometers":{singular:"kuutiokilometri",plural:"kuutiokilometri\u00e4",abbr:"km\u00b3"},"cubic-inches":{singular:"kuutiotuuma",plural:"kuutiotuumaa",abbr:"in\u00b3"},"cubic-feet":{singular:"neli\u00f6jalka",plural:"neli\u00f6jalkaa",abbr:"ft\u00b3"},"cubic-yards":{singular:"kuutiojaardi",plural:"kuutiojaardia",abbr:"yd\u00b3"},"cubic-miles":{singular:"kuutiomaili",plural:"kuutiomailia",abbr:"mi\u00b3"},radians:{singular:"radiaani",plural:"radiaania",
abbr:""},degrees:{singular:"aste",plural:"astetta",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"Alueen mittaus",hint:"Aloita mittaus napsauttamalla maisemaa ja sijoita ensimm\u00e4inen pisteesi",unsupported:"Kolmiulotteista alueen mittausta tuetaan vain SceneView-sovelluksessa.",perimeterLength:"Ymp\u00e4rysmitta",area:"Alue",unit:"Yksikk\u00f6",notApplicable:"ei mit\u00e4\u00e4n",newMeasurement:"Uusi mittaus",units:{metric:"Metrij\u00e4rjestelm\u00e4",
imperial:"Mailij\u00e4rjestelm\u00e4","square-kilometers":"Neli\u00f6kilometri\u00e4","square-meters":"Neli\u00f6metri\u00e4","square-miles":"Neli\u00f6mailia","square-inches":"Neli\u00f6tuumaa","square-feet":"Neli\u00f6jalkaa","square-yards":"Neli\u00f6jaardia","square-us-feet":"Neli\u00f6jalkaa (Yhdysvallat)",acres:"Eekkeri\u00e4",ares:"Aaria",hectares:"Hehtaaria"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"Mittaus",newMeasurement:"Uusi mittaus",distance:"Et\u00e4isyys",area:"Alue",
slice:"Viipalointi",measureDistance:"Mittaa et\u00e4isyys",measureArea:"Mittaa pinta-ala",sliceObjects:"Viipaleobjektit",hint:"Aloita valitsemalla ensin mittausty\u00f6kalu",_localized:{}}});