// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"\u00d6l\u00e7\u00fc",hint:"\u0130lk noktan\u0131z\u0131 yerle\u015ftirmek i\u00e7in sahneyi t\u0131klatarak \u00f6l\u00e7\u00fcme ba\u015flay\u0131n",unsupported:"3B do\u011frudan hat \u00f6l\u00e7\u00fcm\u00fc sadece SceneView\u2019da desteklenir.",distance:"Mesafe",direct:"Do\u011frudan",horizontal:"Yatay",vertical:"Dikey",unit:"Birim",newMeasurement:"Yeni \u00d6l\u00e7\u00fcm",units:{metric:"Metrik",imperial:"\u0130ngiliz",
kilometers:"Kilometre",meters:"Metre",miles:"Mil",inches:"\u0130n\u00e7",feet:"Fit",yards:"Yarda","nautical-miles":"Deniz Mili","us-feet":"Feet (ABD)","degrees-minutes-seconds":"DMS",degrees:"Derece"},_localized:{}},"esri/core/nls/Units":{measures:{length:"Uzunluk",area:"Alan",volume:"Hacim",angle:"A\u00e7\u0131"},units:{millimeters:{singular:"milimetre",plural:"milimetre",abbr:"mm"},centimeters:{singular:"santimetre",plural:"santimetre",abbr:"cm"},decimeters:{singular:"desimetre",plural:"desimetre",
abbr:"dm"},meters:{singular:"metre",plural:"metre",abbr:"m"},kilometers:{singular:"kilometre",plural:"kilometre",abbr:"km"},inches:{singular:"in\u00e7",plural:"in\u00e7",abbr:"in"},feet:{singular:"fit",plural:"fit",abbr:"ft"},yards:{singular:"yarda",plural:"yarda",abbr:"yd"},miles:{singular:"mil",plural:"mil",abbr:"mi"},"nautical-miles":{singular:"deniz mili",plural:"deniz mili",abbr:"nm"},"us-feet":{singular:"fit (ABD)",plural:"fit (ABD)",abbr:"ft"},"square-millimeters":{singular:"milimetrekare",
plural:"milimetrekare",abbr:"mm\u00b2"},"square-centimeters":{singular:"santimetrekare",plural:"santimetrekare",abbr:"cm\u00b2"},"square-decimeters":{singular:"desimetrekare",plural:"desimetrekare",abbr:"dm\u00b2"},"square-meters":{singular:"metrekare",plural:"metrekare",abbr:"m\u00b2"},"square-kilometers":{singular:"kilometrekare",plural:"kilometrekare",abbr:"km\u00b2"},"square-inches":{singular:"in\u00e7kare",plural:"in\u00e7kare",abbr:"in\u00b2"},"square-feet":{singular:"fitkare",plural:"fitkare",
abbr:"ft\u00b2"},"square-yards":{singular:"yardakare",plural:"yardakare",abbr:"yd\u00b2"},"square-miles":{singular:"milkare",plural:"milkare",abbr:"mi\u00b2"},"square-us-feet":{singular:"fitkare (ABD)",plural:"fitkare (ABD)",abbr:"ft\u00b2"},acres:{singular:"akre",plural:"akre",abbr:"akre"},ares:{singular:"ar",plural:"ar",abbr:"A"},hectares:{singular:"hektar",plural:"hektar",abbr:"ha"},liters:{singular:"litre",plural:"litre",abbr:"l"},"cubic-millimeters":{singular:"milimetrek\u00fcp",plural:"milimetrek\u00fcp",
abbr:"mm\u00b3"},"cubic-centimeters":{singular:"santimetrek\u00fcp",plural:"santimetrek\u00fcp",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"desimetrek\u00fcp",plural:"desimetrek\u00fcp",abbr:"dm\u00b3"},"cubic-meters":{singular:"metrek\u00fcp",plural:"metrek\u00fcp",abbr:"m\u00b3"},"cubic-kilometers":{singular:"kilometrek\u00fcp",plural:"kilometrek\u00fcp",abbr:"km\u00b3"},"cubic-inches":{singular:"in\u00e7k\u00fcp",plural:"in\u00e7k\u00fcp",abbr:"in\u00b3"},"cubic-feet":{singular:"fitk\u00fcp",
plural:"fitk\u00fcp",abbr:"ft\u00b3"},"cubic-yards":{singular:"yardak\u00fcp",plural:"yardak\u00fcp",abbr:"yd\u00b3"},"cubic-miles":{singular:"milk\u00fcp",plural:"milk\u00fcp",abbr:"mi\u00b3"},radians:{singular:"radyan",plural:"radyan",abbr:""},degrees:{singular:"derece",plural:"derece",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"\u00d6l\u00e7\u00fc",hint:"\u0130lk noktan\u0131z\u0131 yerle\u015ftirmek i\u00e7in sahneye t\u0131klayarak \u00f6l\u00e7\u00fcme ba\u015flay\u0131n",
unsupported:"3B alan \u00f6l\u00e7\u00fcm\u00fc sadece SceneView\u2019da desteklenir.",perimeterLength:"\u00c7evre",area:"Alan",unit:"Birim",notApplicable:"yok",newMeasurement:"Yeni \u00d6l\u00e7\u00fcm",units:{metric:"Metrik",imperial:"\u0130ngiliz","square-kilometers":"Kilometrekare","square-meters":"Metrekare","square-miles":"Milkare","square-inches":"\u0130n\u00e7kare","square-feet":"Fitkare","square-yards":"Yardakare","square-us-feet":"Fitkare (ABD)",acres:"Akre",ares:"Ar",hectares:"Hektar"},
_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"\u00d6l\u00e7\u00fcm",newMeasurement:"Yeni \u00d6l\u00e7\u00fcm",distance:"Mesafe",area:"Alan",slice:"Dilimle",measureDistance:"Mesafesi \u00d6l\u00e7",measureArea:"Alan \u00d6l\u00e7",sliceObjects:"Nesneleri Dilimle",hint:"Ba\u015flamak i\u00e7in \u00f6ncelikle bir \u00f6l\u00e7\u00fcm arac\u0131 se\u00e7in",_localized:{}}});