// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"Sirgjooneline m\u00f5\u00f5tmine",hint:"M\u00f5\u00f5tmise alustamiseks kl\u00f5psake stseeni, kuhu soovite asetada oma esimese punkti",unsupported:"3D-sirgjoonem\u00f5\u00f5tmist toetab ainult SceneView.",distance:"Vahemaa",direct:"Otse",horizontal:"Horisontaalne",vertical:"Vertikaalne",unit:"\u00dchik",newMeasurement:"Uus m\u00f5\u00f5tmine",units:{metric:"Meetriline",imperial:"Briti",kilometers:"Kilomeetrit",meters:"Meetrit",
miles:"Miili",inches:"Tolli",feet:"Jalga",yards:"Jardi","nautical-miles":"Meremiili","us-feet":"Jalga (USA)","degrees-minutes-seconds":"DMS",degrees:"Kraadi"},_localized:{}},"esri/core/nls/Units":{measures:{length:"Pikkus",area:"Pindala",volume:"Maht",angle:"Nurk"},units:{millimeters:{singular:"millimeeter",plural:"millimeetrit",abbr:"mm"},centimeters:{singular:"sentimeeter",plural:"sentimeetrit",abbr:"cm"},decimeters:{singular:"detsimeeter",plural:"detsimeetrit",abbr:"dm"},meters:{singular:"meeter",
plural:"meetrit",abbr:"m"},kilometers:{singular:"km",plural:"kilomeetrit",abbr:"km"},inches:{singular:"toll",plural:"tolli",abbr:":"},feet:{singular:"jalg",plural:"jalga",abbr:"jl"},yards:{singular:"jard",plural:"jardi",abbr:"jr"},miles:{singular:"miil",plural:"miilid",abbr:"mi"},"nautical-miles":{singular:"meremiil",plural:"meremiili",abbr:"nm"},"us-feet":{singular:"jalg (USA)",plural:"jalga (USA)",abbr:"jl"},"square-millimeters":{singular:"ruutmillimeeter",plural:"ruutmillimeetrit",abbr:"mm\u00b2"},
"square-centimeters":{singular:"ruutsentimeeter",plural:"ruutsentimeetrit",abbr:"cm\u00b2"},"square-decimeters":{singular:"ruutdetsimeeter",plural:"ruutdetsimeetrit",abbr:"dm\u00b2"},"square-meters":{singular:"ruutmeeter",plural:"ruutmeetrit",abbr:"m\u00b2"},"square-kilometers":{singular:"ruutkilomeeter",plural:"ruutkilomeetrit",abbr:"km\u00b2"},"square-inches":{singular:"ruuttoll",plural:"ruuttolli",abbr:"in\u00b2"},"square-feet":{singular:"ruutjalg",plural:"ruutjalga",abbr:"ft\u00b2"},"square-yards":{singular:"ruutjard",
plural:"ruutjardi",abbr:"yd\u00b2"},"square-miles":{singular:"ruutmiil",plural:"ruutmiili",abbr:"mi\u00b2"},"square-us-feet":{singular:"ruutjalg (USA)",plural:"ruutjalga (USA)",abbr:"ft\u00b2"},acres:{singular:"aaker",plural:"aakrit",abbr:"aaker"},ares:{singular:"aar",plural:"aari",abbr:"e.l."},hectares:{singular:"hektar",plural:"hektarit",abbr:"ha"},liters:{singular:"liiter",plural:"liitrit",abbr:"l"},"cubic-millimeters":{singular:"kuupmillimeeter",plural:"kuupmillimeetrit",abbr:"mm\u00b3"},"cubic-centimeters":{singular:"kuupsentimeeter",
plural:"kuupsentimeetrit",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"kuupdetsimeeter",plural:"kuupdetsimeetrit",abbr:"dm\u00b3"},"cubic-meters":{singular:"kuupmeeter",plural:"kuupmeetrit",abbr:"m\u00b3"},"cubic-kilometers":{singular:"kuupkilomeeter",plural:"kuupkilomeetrit",abbr:"km\u00b3"},"cubic-inches":{singular:"kuuptoll",plural:"kuuptolli",abbr:"in\u00b3"},"cubic-feet":{singular:"kuupjalg",plural:"kuupjalga",abbr:"ft\u00b3"},"cubic-yards":{singular:"kuupjard",plural:"kuupjardi",abbr:"yd\u00b3"},
"cubic-miles":{singular:"kuupmiil",plural:"kuupmiili",abbr:"mi\u00b3"},radians:{singular:"radiaan",plural:"radiaani",abbr:""},degrees:{singular:"kraad",plural:"kraadi",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"Pindala m\u00f5\u00f5tmine",hint:"M\u00f5\u00f5tmise alustamiseks kl\u00f5psake stseeni, kuhu soovite asetada oma esimese punkti",unsupported:"3D-pindala m\u00f5\u00f5tmist toetab ainult SceneView.",perimeterLength:"\u00dcmberm\u00f5\u00f5t",
area:"Pindala",unit:"\u00dchik",notApplicable:"Pole sobiv",newMeasurement:"Uus m\u00f5\u00f5tmine",units:{metric:"Meetriline",imperial:"Briti","square-kilometers":"Ruutkilomeetrit","square-meters":"ruutmeetrit","square-miles":"Ruutmiili","square-inches":"ruuttolli","square-feet":"ruutjalga","square-yards":"ruutjardi","square-us-feet":"ruutjalga (USA)",acres:"aakrit",ares:"Aari",hectares:"hektarit"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"M\u00f5\u00f5tmine",newMeasurement:"Uus m\u00f5\u00f5tmine",
distance:"Vahemaa",area:"Kihtdiagramm",slice:"Viiluta",measureDistance:"M\u00f5\u00f5da vahemaad",measureArea:"M\u00f5\u00f5da pindala",sliceObjects:"Viiluta objekte",hint:"Alustamiseks valige esmalt m\u00f5\u00f5tmise t\u00f6\u00f6riist",_localized:{}}});