// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"M\u0103surarea direct\u0103 a liniei",hint:"\u00cencepe\u0163i s\u0103 m\u0103sura\u0163i f\u0103c\u00e2nd clic \u00een scen\u0103 pentru a plasa primul punct",unsupported:"M\u0103surarea direct\u0103 a liniei 3D este acceptat\u0103 doar \u00een SceneView.",distance:"Distan\u0163\u0103",direct:"Direct",horizontal:"Orizontal",vertical:"Vertical",unit:"Unitate",newMeasurement:"M\u0103sur\u0103toare nou\u0103",units:{metric:"Metric",
imperial:"Englez",kilometers:"Kilometri",meters:"Metri",miles:"Mile",inches:"Inci",feet:"Ft",yards:"Yarzi","nautical-miles":"Mile marine","us-feet":"Picioare (SUA)","degrees-minutes-seconds":"DMS",degrees:"Grade"},_localized:{}},"esri/core/nls/Units":{measures:{length:"Lungime",area:"Suprafa\u0163\u0103",volume:"Volum",angle:"Unghi"},units:{millimeters:{singular:"milimetru",plural:"milimetri",abbr:"mm"},centimeters:{singular:"centimetru",plural:"centimetri",abbr:"cm"},decimeters:{singular:"decimetru",
plural:"decimetri",abbr:"dm"},meters:{singular:"metru",plural:"metri",abbr:"m"},kilometers:{singular:"kilometru",plural:"kilometri",abbr:"km"},inches:{singular:"\u021bol",plural:"\u021boli",abbr:"in"},feet:{singular:"picior",plural:"ft",abbr:"ft"},yards:{singular:"yard",plural:"yarzi",abbr:"yd"},miles:{singular:"mil\u0103",plural:"mile",abbr:"mi"},"nautical-miles":{singular:"mil\u0103 nautic\u0103",plural:"mile nautice",abbr:"nm"},"us-feet":{singular:"picior (SUA)",plural:"picioare (SUA)",abbr:"ft"},
"square-millimeters":{singular:"milimetru p\u0103trat",plural:"milimetri p\u0103tra\u0163i",abbr:"mm\u00b2"},"square-centimeters":{singular:"centimetru p\u0103trat",plural:"centimetri p\u0103tra\u0163i",abbr:"cm\u00b2"},"square-decimeters":{singular:"decimetru p\u0103trat",plural:"decimetri p\u0103tra\u021bi",abbr:"dm\u00b2"},"square-meters":{singular:"metru p\u0103trat",plural:"metri p\u0103tra\u0163i",abbr:"m\u00b2"},"square-kilometers":{singular:"kilometru p\u0103trat",plural:"kilometri p\u0103tra\u0163i",
abbr:"km\u00b2"},"square-inches":{singular:"\u021bol p\u0103trat",plural:"\u021boli p\u0103tra\u0163i",abbr:"in\u00b2"},"square-feet":{singular:"picior p\u0103trat",plural:"picioare p\u0103trate",abbr:"ft\u00b2"},"square-yards":{singular:"yard p\u0103trat",plural:"yarzi p\u0103tra\u021bi",abbr:"yd\u00b2"},"square-miles":{singular:"mil\u0103 p\u0103trat\u0103",plural:"mile p\u0103trate",abbr:"mi\u00b2"},"square-us-feet":{singular:"picior p\u0103trat (SUA)",plural:"picioare p\u0103trate (SUA)",abbr:"ft\u00b2"},
acres:{singular:"acru",plural:"acri",abbr:"acru"},ares:{singular:"ar",plural:"ari",abbr:"a"},hectares:{singular:"hectar",plural:"hectare",abbr:"ha"},liters:{singular:"litru",plural:"litri",abbr:"l"},"cubic-millimeters":{singular:"milimetru cub",plural:"milimetri cubi",abbr:"mm\u00b3"},"cubic-centimeters":{singular:"centimetru cub",plural:"centimetri cubi",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"decimetru cub",plural:"decimetri cubi",abbr:"dm\u00b3"},"cubic-meters":{singular:"metru cub",plural:"metri cubi",
abbr:"m\u00b3"},"cubic-kilometers":{singular:"kilometru cub",plural:"kilometri cubi",abbr:"km\u00b3"},"cubic-inches":{singular:"\u021bol cub",plural:"\u021boli cubi",abbr:"in\u00b3"},"cubic-feet":{singular:"picior cub",plural:"picioare cubice",abbr:"ft\u00b3"},"cubic-yards":{singular:"yard cub",plural:"yarzi cubi",abbr:"yd\u00b3"},"cubic-miles":{singular:"mil\u0103 cubic\u0103",plural:"mile cubice",abbr:"mi\u00b3"},radians:{singular:"radian",plural:"radiani",abbr:""},degrees:{singular:"grad",plural:"grade",
abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"M\u0103surarea zonei",hint:"\u00cencepe\u0163i s\u0103 m\u0103sura\u0163i f\u0103c\u00e2nd clic \u00een scen\u0103 pentru a plasa primul punct",unsupported:"M\u0103surarea suprafe\u021bei 3D este acceptat\u0103 doar \u00een SceneView.",perimeterLength:"Perimetru",area:"Suprafa\u0163\u0103",unit:"Unitate",notApplicable:"n/a",newMeasurement:"M\u0103sur\u0103toare nou\u0103",units:{metric:"Metric",imperial:"Englez",
"square-kilometers":"Kilometri p\u0103tra\u0163i","square-meters":"Metri p\u0103tra\u0163i","square-miles":"Mile p\u0103trate","square-inches":"Inci p\u0103tra\u0163i","square-feet":"Ft p\u0103tra\u0163i","square-yards":"Yarzi p\u0103tra\u0163i","square-us-feet":"Picioare p\u0103trate (SUA)",acres:"Acri",ares:"Ari",hectares:"Hectare"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"M\u0103surare",newMeasurement:"M\u0103sur\u0103toare nou\u0103",distance:"Distan\u021b\u0103",area:"Suprafa\u021b\u0103",
slice:"Segmentare",measureDistance:"Distan\u021b\u0103 de m\u0103surare",measureArea:"Suprafa\u021b\u0103 de m\u0103surare",sliceObjects:"Obiecte de segmentare",hint:"Pentru a \u00eencepe, mai \u00eent\u00e2i selecta\u021bi un instrument de m\u0103surare",_localized:{}}});