// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"Medir",hint:"Inicie a medi\u00e7\u00e3o clicando na cena para posicionar seu primeiro ponto",unsupported:"A medi\u00e7\u00e3o de linha direta 3D \u00e9 suportada somente no SceneView.",distance:"Dist\u00e2ncia",direct:"Direto",horizontal:"Horizontal",vertical:"Vertical",unit:"Unidade",newMeasurement:"Nova Medi\u00e7\u00e3o",units:{metric:"M\u00e9trico",imperial:"Imperial",kilometers:"Quil\u00f4metros",meters:"Metros",
miles:"Milhas",inches:"Polegadas",feet:"P\u00e9s",yards:"Jardas","nautical-miles":"Milhas N\u00e1uticas","us-feet":"P\u00e9s (US)","degrees-minutes-seconds":"DMS",degrees:"Graus"},_localized:{}},"esri/core/nls/Units":{measures:{length:"Comprimento",area:"\u00c1rea",volume:"Volume",angle:"\u00c2ngulo"},units:{millimeters:{singular:"mil\u00edmetro",plural:"mil\u00edmetros",abbr:"mm"},centimeters:{singular:"cent\u00edmetro",plural:"Cent\u00edmetros",abbr:"cm"},decimeters:{singular:"dec\u00edmetro",plural:"dec\u00edmetros",
abbr:"dm"},meters:{singular:"metro",plural:"metros",abbr:"m"},kilometers:{singular:"quil\u00f4metro",plural:"quil\u00f4metros",abbr:"km"},inches:{singular:"polegada",plural:"polegadas",abbr:"pol"},feet:{singular:"p\u00e9",plural:"p\u00e9s",abbr:"p\u00e9s"},yards:{singular:"jarda",plural:"jardas",abbr:"jd"},miles:{singular:"milha",plural:"milhas",abbr:"milhas"},"nautical-miles":{singular:"milhas n\u00e1uticas",plural:"milhas n\u00e1uticas",abbr:"mn"},"us-feet":{singular:"p\u00e9 (US)",plural:"p\u00e9s (US)",
abbr:"p\u00e9s"},"square-millimeters":{singular:"Mil\u00edmetro quadrado",plural:"Mil\u00edmetros quadrados",abbr:"mm\u00b2"},"square-centimeters":{singular:"cent\u00edmetro quadrado",plural:"cent\u00edmetros quadrados",abbr:"cm\u00b2"},"square-decimeters":{singular:"dec\u00edmetro quadrado",plural:"dec\u00edmetros quadrados",abbr:"dm\u00b2"},"square-meters":{singular:"metro quadrados",plural:"metros quadrados",abbr:"m\u00b2"},"square-kilometers":{singular:"quil\u00f4metro quadrado",plural:"quil\u00f4metros quadrados",
abbr:"km\u00b2"},"square-inches":{singular:"polegada quadrada",plural:"polegadas quadradas",abbr:"in\u00b2"},"square-feet":{singular:"p\u00e9s quadrados",plural:"p\u00e9s quadrados",abbr:"ft\u00b2"},"square-yards":{singular:"jarda quadrada",plural:"jardas quadradas",abbr:"yd\u00b2"},"square-miles":{singular:"Milhas Quadradas",plural:"milhas quadradas",abbr:"mi\u00b2"},"square-us-feet":{singular:"p\u00e9s quadrados (US)",plural:"p\u00e9 quadrado (US)",abbr:"ft\u00b2"},acres:{singular:"acre",plural:"acres",
abbr:"acre"},ares:{singular:"are (\u00e1rea)",plural:"ares",abbr:"a"},hectares:{singular:"hectare",plural:"hectares",abbr:"ha"},liters:{singular:"litro",plural:"litros",abbr:"l"},"cubic-millimeters":{singular:"mil\u00edmetro c\u00fabico",plural:"mil\u00edmetros c\u00fabicos",abbr:"mm\u00b3"},"cubic-centimeters":{singular:"cent\u00edmetro c\u00fabico",plural:"cent\u00edmetros c\u00fabicos",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"dec\u00edmetro c\u00fabico",plural:"dec\u00edmetros c\u00fabicos",
abbr:"dm\u00b3"},"cubic-meters":{singular:"metro c\u00fabico",plural:"metros c\u00fabicos",abbr:"m\u00b3"},"cubic-kilometers":{singular:"quil\u00f4metro c\u00fabico",plural:"quil\u00f4metros c\u00fabicos",abbr:"km\u00b3"},"cubic-inches":{singular:"polegada c\u00fabica",plural:"polegadas c\u00fabicas",abbr:"in\u00b3"},"cubic-feet":{singular:"p\u00e9 c\u00fabico",plural:"p\u00e9s c\u00fabicos",abbr:"ft\u00b3"},"cubic-yards":{singular:"jarda c\u00fabica",plural:"jardas c\u00fabicas",abbr:"yd\u00b3"},
"cubic-miles":{singular:"milha c\u00fabica",plural:"milhas c\u00fabicas",abbr:"mi\u00b3"},radians:{singular:"radiano",plural:"radianos",abbr:""},degrees:{singular:"grau",plural:"graus",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"Medir",hint:"Inicie a medi\u00e7\u00e3o clicando na cena para posicionar seu primeiro ponto",unsupported:"A medi\u00e7\u00e3o de \u00e1rea 3D \u00e9 suportada somente no SceneView.",perimeterLength:"Per\u00edmetro",area:"\u00c1rea",
unit:"Unidade",notApplicable:"n/a",newMeasurement:"Nova Medi\u00e7\u00e3o",units:{metric:"M\u00e9trico",imperial:"Imperial","square-kilometers":"Quil\u00f4metros Quadrados","square-meters":"Metros Quadrados","square-miles":"Milhas Quadradas","square-inches":"Polegadas Quadradas","square-feet":"P\u00e9s Quadrados","square-yards":"Jardas Quadradas","square-us-feet":"P\u00e9s Quadrados (US)",acres:"Acres",ares:"Ares",hectares:"Hectares"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"Medi\u00e7\u00e3o",
newMeasurement:"Nova Medi\u00e7\u00e3o",distance:"Dist\u00e2ncia",area:"\u00c1rea",slice:"Dividir",measureDistance:"Medir Dist\u00e2ncia",measureArea:"Medir \u00c1rea",sliceObjects:"Dividir Objetos",hint:"Selecione uma ferramenta de medi\u00e7\u00e3o primeiro para come\u00e7ar",_localized:{}}});