// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"Mesure de ligne directe",hint:"Commencer les mesures en cliquant dans la sc\u00e8ne pour placer le premier point",unsupported:"La mesure de ligne directe 3D est uniquement prise en charge dans la vue de sc\u00e8ne.",distance:"Distance",direct:"Direct",horizontal:"Horizontale",vertical:"Verticale",unit:"Unit\u00e9",newMeasurement:"Nouvelle mesure",units:{metric:"M\u00e9triques",imperial:"Imp\u00e9riales",kilometers:"Kilom\u00e8tres",
meters:"M\u00e8tres",miles:"Milles",inches:"Pouces",feet:"Pieds",yards:"Yards","nautical-miles":"Milles nautiques","us-feet":"Pieds (US)","degrees-minutes-seconds":"DMS",degrees:"Degr\u00e9s"},_localized:{}},"esri/core/nls/Units":{measures:{length:"Longueur",area:"Surface",volume:"Volume",angle:"Angle"},units:{millimeters:{singular:"millim\u00e8tre",plural:"millim\u00e8tres",abbr:"mm"},centimeters:{singular:"centim\u00e8tre",plural:"centim\u00e8tres",abbr:"cm"},decimeters:{singular:"d\u00e9cim\u00e8tre",
plural:"d\u00e9cim\u00e8tres",abbr:"dm"},meters:{singular:"m\u00e8tre",plural:"m\u00e8tres",abbr:"m"},kilometers:{singular:"kilom\u00e8tre",plural:"kilom\u00e8tres",abbr:"km"},inches:{singular:"pouce",plural:"pouces",abbr:"in"},feet:{singular:"pied",plural:"pieds",abbr:"pi"},yards:{singular:"yard",plural:"yards",abbr:"yd"},miles:{singular:"mile",plural:"miles",abbr:"mi"},"nautical-miles":{singular:"mille nautique",plural:"milles nautiques",abbr:"mn"},"us-feet":{singular:"pied (US)",plural:"pieds (US)",
abbr:"pi"},"square-millimeters":{singular:"millim\u00e8tre carr\u00e9",plural:"millim\u00e8tres carr\u00e9s",abbr:"mm\u00b2"},"square-centimeters":{singular:"centim\u00e8tre carr\u00e9",plural:"centim\u00e8tres carr\u00e9s",abbr:"cm\u00b2"},"square-decimeters":{singular:"d\u00e9cim\u00e8tre carr\u00e9",plural:"d\u00e9cim\u00e8tres carr\u00e9s",abbr:"dm\u00b2"},"square-meters":{singular:"m\u00e8tre carr\u00e9",plural:"m\u00e8tres carr\u00e9s",abbr:"m\u00b2"},"square-kilometers":{singular:"kilom\u00e8tre carr\u00e9",
plural:"kilom\u00e8tres carr\u00e9s",abbr:"km\u00b2"},"square-inches":{singular:"pouce carr\u00e9",plural:"pouces carr\u00e9s",abbr:"po\u00b2"},"square-feet":{singular:"pied carr\u00e9",plural:"pieds carr\u00e9s",abbr:"pi\u00b2"},"square-yards":{singular:"yard carr\u00e9",plural:"yards carr\u00e9s",abbr:"yd\u00b2"},"square-miles":{singular:"mile carr\u00e9",plural:"miles carr\u00e9s",abbr:"mi\u00b2"},"square-us-feet":{singular:"pied carr\u00e9 (US)",plural:"pieds carr\u00e9s (US)",abbr:"pi\u00b2"},
acres:{singular:"acre",plural:"acres",abbr:"acre"},ares:{singular:"are",plural:"ares",abbr:"a"},hectares:{singular:"hectare",plural:"hectares",abbr:"ha"},liters:{singular:"litre",plural:"litres",abbr:"l"},"cubic-millimeters":{singular:"millim\u00e8tre cube",plural:"millim\u00e8tres cubes",abbr:"mm\u00b3"},"cubic-centimeters":{singular:"centim\u00e8tre cube",plural:"centim\u00e8tres cubes",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"d\u00e9cim\u00e8tre cube",plural:"d\u00e9cim\u00e8tres cubes",
abbr:"dm\u00b3"},"cubic-meters":{singular:"m\u00e8tre cube",plural:"m\u00e8tres cubes",abbr:"m\u00b3"},"cubic-kilometers":{singular:"kilom\u00e8tre cube",plural:"kilom\u00e8tres cubes",abbr:"km\u00b3"},"cubic-inches":{singular:"pouce cube",plural:"pouces cubes",abbr:"po\u00b3"},"cubic-feet":{singular:"pied cube",plural:"pieds cubes",abbr:"pi\u00b3"},"cubic-yards":{singular:"yard cube",plural:"yards cubes",abbr:"yd\u00b3"},"cubic-miles":{singular:"mile cube",plural:"miles cubes",abbr:"mi\u00b3"},radians:{singular:"radian",
plural:"radians",abbr:""},degrees:{singular:"degr\u00e9",plural:"degr\u00e9s",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"Mesure de surface",hint:"Commencer les mesures en cliquant dans la sc\u00e8ne pour placer le premier point",unsupported:"La mesure de la zone 3D est uniquement prise en charge dans la vue de sc\u00e8ne.",perimeterLength:"P\u00e9rim\u00e8tre",area:"Surface",unit:"Unit\u00e9",notApplicable:"n/d",newMeasurement:"Nouvelle mesure",units:{metric:"M\u00e9triques",
imperial:"Imp\u00e9riales","square-kilometers":"Kilom\u00e8tres carr\u00e9s","square-meters":"M\u00e8tres carr\u00e9s","square-miles":"Miles carr\u00e9s","square-inches":"Pouces carr\u00e9s","square-feet":"Pieds carr\u00e9s","square-yards":"Yards carr\u00e9s","square-us-feet":"Pieds carr\u00e9s (US)",acres:"Acres",ares:"Ares",hectares:"Hectares"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"Mesure",newMeasurement:"Nouvelle mesure",distance:"Distance",area:"Surface",slice:"Coupe",
measureDistance:"Mesurer la distance",measureArea:"Mesurer la surface",sliceObjects:"Couper des objets",hint:"S\u00e9lectionner un outil de mesure avant de commencer",_localized:{}}});