// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"Misurazione linea diretta",hint:"Comincia a misurare cliccando sulla scena per posizionare il primo punto",unsupported:"La misurazione della linea diretta 3D \u00e8 supportata solo in SceneView.",distance:"Distanza",direct:"Diretto",horizontal:"Orizzontale",vertical:"Verticale",unit:"Unit\u00e0",newMeasurement:"Nuova misurazione",units:{metric:"Metrico",imperial:"Imperiale",kilometers:"Chilometri",meters:"Metri",miles:"Miglia",
inches:"Pollici",feet:"Piedi",yards:"Iarde","nautical-miles":"Miglia nautiche","us-feet":"Piede (USA)","degrees-minutes-seconds":"DMS",degrees:"Gradi"},_localized:{}},"esri/core/nls/Units":{measures:{length:"Lunghezza",area:"Area",volume:"Volume",angle:"Angolo"},units:{millimeters:{singular:"millimetro",plural:"millimetri",abbr:"mm"},centimeters:{singular:"centimetro",plural:"centimetri",abbr:"cm"},decimeters:{singular:"decimetro",plural:"decimetri",abbr:"dm"},meters:{singular:"metro",plural:"metri",
abbr:"m"},kilometers:{singular:"chilometro",plural:"chilometri",abbr:"km"},inches:{singular:"Pollice",plural:"pollici",abbr:"poll."},feet:{singular:"piede",plural:"piedi",abbr:"piedi"},yards:{singular:"iarda",plural:"iarde",abbr:"yd"},miles:{singular:"miglia",plural:"miglia",abbr:"mi"},"nautical-miles":{singular:"miglio nautico",plural:"miglia nautiche",abbr:"mn"},"us-feet":{singular:"piede (USA)",plural:"piedi (USA)",abbr:"piedi"},"square-millimeters":{singular:"millimetro quadrato",plural:"millimetri quadrati",
abbr:"mm\u00b2"},"square-centimeters":{singular:"centimetro quadrato",plural:"centimetri quadrati",abbr:"cm\u00b2"},"square-decimeters":{singular:"decimetro quadrato",plural:"decimetri quadrati",abbr:"dm\u00b2"},"square-meters":{singular:"metro quadrato",plural:"metri quadrati",abbr:"m\u00b2"},"square-kilometers":{singular:"chilometro quadrato",plural:"chilometri quadrati",abbr:"km\u00b2"},"square-inches":{singular:"pollice quadrato",plural:"pollici quadrati",abbr:"in\u00b2"},"square-feet":{singular:"piede quadrato",
plural:"piedi quadrati",abbr:"piedi\u00b2"},"square-yards":{singular:"iarda quadrata",plural:"iarde quadrate",abbr:"yd\u00b2"},"square-miles":{singular:"miglio quadrato",plural:"miglia quadrate",abbr:"mi\u00b2"},"square-us-feet":{singular:"piede quadrato (USA)",plural:"piedi quadrati (USA)",abbr:"piedi\u00b2"},acres:{singular:"acro",plural:"acri",abbr:"acro"},ares:{singular:"ara",plural:"a.",abbr:"a"},hectares:{singular:"ettari",plural:"ettari",abbr:"ha"},liters:{singular:"litro",plural:"litri",abbr:"l"},
"cubic-millimeters":{singular:"millimetro cubico",plural:"millimetri cubici",abbr:"mm\u00b3"},"cubic-centimeters":{singular:"centimetro cubico",plural:"centimetri cubici",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"decimetro cubico",plural:"decimetri cubici",abbr:"dm\u00b3"},"cubic-meters":{singular:"metro cubico",plural:"metri cubici",abbr:"m\u00b3"},"cubic-kilometers":{singular:"chilometro cubico",plural:"chilometri cubici",abbr:"km\u00b3"},"cubic-inches":{singular:"pollice cubico",plural:"pollici cubici",
abbr:"in\u00b3"},"cubic-feet":{singular:"piede cubico",plural:"piedi cubici",abbr:"ft\u00b3"},"cubic-yards":{singular:"iarda cubica",plural:"iarde cubiche",abbr:"yd\u00b3"},"cubic-miles":{singular:"miglio cubico",plural:"miglia cubiche",abbr:"mi\u00b3"},radians:{singular:"radiante",plural:"radianti",abbr:""},degrees:{singular:"grado",plural:"gradi",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"Misurazioni dell'area",hint:"Comincia a misurare cliccando sulla scena per posizionare il primo punto",
unsupported:"La misurazione dell'area 3D \u00e8 supportata solo in SceneView.",perimeterLength:"Perimetro",area:"Area",unit:"Unit\u00e0",notApplicable:"n/d",newMeasurement:"Nuova misurazione",units:{metric:"Metrico",imperial:"Imperiale","square-kilometers":"Chilometri quadrati","square-meters":"Metri quadrati","square-miles":"Miglia quadrate","square-inches":"Pollici quadrati","square-feet":"Piedi quadrati","square-yards":"Iarde quadrate","square-us-feet":"Piedi quadrati (USA)",acres:"Acri",ares:"Are",
hectares:"Ettari"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"Misura",newMeasurement:"Nuova misurazione",distance:"Distanza",area:"Area",slice:"Sezione",measureDistance:"Misura distanza",measureArea:"Misura area",sliceObjects:"Seziona oggetti",hint:"Prima seleziona uno strumento di misurazione per iniziare",_localized:{}}});