// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"Direkt linjem\u00e4tning",hint:"B\u00f6rja m\u00e4ta genom att klicka i scenen f\u00f6r att placera den f\u00f6rsta punkten",unsupported:"3D-direktlinjem\u00e4tning st\u00f6ds bara i SceneView.",distance:"Avst\u00e5nd",direct:"Direkt",horizontal:"Horisontell",vertical:"Vertikal",unit:"Enhet",newMeasurement:"Ny m\u00e4tning",units:{metric:"Metriska",imperial:"Imperial",kilometers:"Kilometer",meters:"Meter",miles:"Mile",
inches:"Tum",feet:"Fot",yards:"Yard","nautical-miles":"Nautiska mil","us-feet":"Fot (USA)","degrees-minutes-seconds":"DMS",degrees:"Grader"},_localized:{}},"esri/core/nls/Units":{measures:{length:"L\u00e4ngd",area:"Omr\u00e5de",volume:"Enhet",angle:"Vinkel"},units:{millimeters:{singular:"millimeter",plural:"millimeter",abbr:"mm"},centimeters:{singular:"centimeter",plural:"centimeter",abbr:"cm"},decimeters:{singular:"decimeter",plural:"decimeter",abbr:"dm"},meters:{singular:"meter",plural:"meter",
abbr:"m"},kilometers:{singular:"kilometer",plural:"kilometer",abbr:"km"},inches:{singular:"tum",plural:"tum",abbr:"tum"},feet:{singular:"fot",plural:"fot",abbr:"fot"},yards:{singular:"yard",plural:"yards",abbr:"yd"},miles:{singular:"engelsk mil",plural:"engelska miles",abbr:"mi"},"nautical-miles":{singular:"sj\u00f6mil",plural:"sj\u00f6mil",abbr:"M"},"us-feet":{singular:"fot (USA)",plural:"fot (USA)",abbr:"fot"},"square-millimeters":{singular:"kvadratmillimeter",plural:"kvadratmillimeter",abbr:"mm\u00b2"},
"square-centimeters":{singular:"kvadratcentimeter",plural:"kvadratcentimeter",abbr:"cm\u00b2"},"square-decimeters":{singular:"kvadratdecimeter",plural:"kvadratdecimeter",abbr:"dm\u00b2"},"square-meters":{singular:"kvadratmeter",plural:"kvadratmeter",abbr:"m\u00b2"},"square-kilometers":{singular:"kvadratkilometer",plural:"kvadratkilometer",abbr:"km\u00b2"},"square-inches":{singular:"kvadrattum",plural:"kvadrattum",abbr:"in\u00b2"},"square-feet":{singular:"kvadratfot",plural:"kvadratfot",abbr:"ft\u00b2"},
"square-yards":{singular:"kvadrat-yard",plural:"kvadrat-yard",abbr:"yd\u00b2"},"square-miles":{singular:"engelsk kvadratmil",plural:"engelsk kvadratmil",abbr:"mi\u00b2"},"square-us-feet":{singular:"kvadratfot (USA)",plural:"kvadratfot (USA)",abbr:"ft\u00b2"},acres:{singular:"tunnland",plural:"tunnland",abbr:"tunnland"},ares:{singular:"\u00e4r",plural:"ar",abbr:"a"},hectares:{singular:"hektar",plural:"hektar",abbr:"ha"},liters:{singular:"liter",plural:"liter",abbr:"I"},"cubic-millimeters":{singular:"kubikmillimeter",
plural:"kubikmillimeter",abbr:"mm\u00b3"},"cubic-centimeters":{singular:"kubikcentimeter",plural:"kubikcentimeter",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"kubikdecimeter",plural:"kubikdecimeter",abbr:"dm\u00b3"},"cubic-meters":{singular:"kubikmeter",plural:"kubikmeter",abbr:"m\u00b3"},"cubic-kilometers":{singular:"kubikkilometer",plural:"kubikkilometer",abbr:"km\u00b3"},"cubic-inches":{singular:"kubiktum",plural:"kubiktum",abbr:"in\u00b3"},"cubic-feet":{singular:"kubfot",plural:"kubikfot",
abbr:"ft\u00b3"},"cubic-yards":{singular:"kubik-yard",plural:"kubik-yard",abbr:"yd\u00b3"},"cubic-miles":{singular:"engelska kubikmil",plural:"engelska kubikmil",abbr:"mi\u00b3"},radians:{singular:"radian",plural:"radianer",abbr:""},degrees:{singular:"grad",plural:"grader",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"Ytm\u00e4tning",hint:"B\u00f6rja m\u00e4ta genom att klicka i scenen f\u00f6r att placera den f\u00f6rsta punkten",unsupported:"3D-aream\u00e4tning st\u00f6ds bara i SceneView.",
perimeterLength:"Omkrets",area:"Omr\u00e5de",unit:"Enhet",notApplicable:"saknas",newMeasurement:"Ny m\u00e4tning",units:{metric:"Metriska",imperial:"Imperial","square-kilometers":"Kvadratkilometer","square-meters":"Kvadratmeter","square-miles":"Kvadratmil (engelska)","square-inches":"Kvadrattum","square-feet":"Kvadratfot","square-yards":"Square Yards","square-us-feet":"Kvadratfot (USA)",acres:"Tunnland",ares:"Ar",hectares:"Hektar"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"M\u00e4tning",
newMeasurement:"Ny m\u00e4tning",distance:"Avst\u00e5nd",area:"Omr\u00e5de",slice:"Sektor",measureDistance:"M\u00e4t avst\u00e5nd",measureArea:"M\u00e4t omr\u00e5de",sliceObjects:"Skapa sektorer f\u00f6r objekt",hint:"V\u00e4lj f\u00f6rst ett m\u00e4tverktyg f\u00f6r att starta",_localized:{}}});