// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"Merenja",hint:"Otpo\u010dnite merenja klikom na scenu kako biste namestili prvu ta\u010dku",unsupported:"Direktno merenje linije u 3D je podr\u017eano samo u aplikaciji SceneView.",distance:"Rastojanje",direct:"Direktno",horizontal:"Horizontalno",vertical:"Vertikalno",unit:"Jedinica",newMeasurement:"Novo merenje",units:{metric:"Metrika",imperial:"Imperijalne",kilometers:"Kilometri",meters:"Metri",miles:"Milje",inches:"In\u010di",
feet:"Stope",yards:"Jardi","nautical-miles":"Nauti\u010dke milje","us-feet":"Stope (SAD)","degrees-minutes-seconds":"DMS",degrees:"Stepeni"},_localized:{}},"esri/core/nls/Units":{measures:{length:"Du\u017eina",area:"Povr\u0161ina",volume:"Zapremina",angle:"Ugao"},units:{millimeters:{singular:"milimetar",plural:"milimetri",abbr:"mm"},centimeters:{singular:"centimetar",plural:"centimetri",abbr:"cm"},decimeters:{singular:"decimetar",plural:"decimetri",abbr:"dm"},meters:{singular:"metar",plural:"metri",
abbr:"m"},kilometers:{singular:"kilometar",plural:"kilometri",abbr:"km"},inches:{singular:"in\u010d",plural:"in\u010di",abbr:"ulaz"},feet:{singular:"stopa",plural:"stope",abbr:"ft"},yards:{singular:"jard",plural:"jardi",abbr:"yd"},miles:{singular:"milja",plural:"milje",abbr:"mi"},"nautical-miles":{singular:"nauti\u010dka milja",plural:"nauti\u010dke milje",abbr:"nm"},"us-feet":{singular:"stopa (SAD)",plural:"stope (SAD)",abbr:"ft"},"square-millimeters":{singular:"kvadratni milimetar",plural:"kvadratni milimetri",
abbr:"mm\u00b2"},"square-centimeters":{singular:"kvadratni centimetar",plural:"kvadratni centimetri",abbr:"cm\u00b2"},"square-decimeters":{singular:"kvadratni decimetar",plural:"kvadratni decimetri",abbr:"dm\u00b2"},"square-meters":{singular:"kvadratni metar",plural:"kvadratni metri",abbr:"m\u00b2"},"square-kilometers":{singular:"kvadratni kilometar",plural:"kvadratni kilometri",abbr:"km\u00b2"},"square-inches":{singular:"kvadratni in\u010d",plural:"kvadratni in\u010di",abbr:"in\u00b2"},"square-feet":{singular:"kvadratna stopa",
plural:"kvadratne stope",abbr:"ft\u00b2"},"square-yards":{singular:"kvadratni jard",plural:"kvadratne jarde",abbr:"yd\u00b2"},"square-miles":{singular:"kvadratna milja",plural:"kvadratne milje",abbr:"mi\u00b2"},"square-us-feet":{singular:"kvadratna stopa (SAD)",plural:"kvadratne stope (SAD)",abbr:"ft\u00b2"},acres:{singular:"acre",plural:"acres",abbr:"acre"},ares:{singular:"ar",plural:"ari",abbr:"a"},hectares:{singular:"hektar",plural:"hektari",abbr:"ha"},liters:{singular:"litar",plural:"litri",abbr:"l"},
"cubic-millimeters":{singular:"kubni milimetar",plural:"kubni milimetri",abbr:"mm\u00b3"},"cubic-centimeters":{singular:"kubni centimetar",plural:"kubni centimetri",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"kubni decimetar",plural:"kubni decimetri",abbr:"dm\u00b3"},"cubic-meters":{singular:"kubni metar",plural:"kubni metri",abbr:"m\u00b3"},"cubic-kilometers":{singular:"kubni kilometar",plural:"kubni kilometri",abbr:"km\u00b3"},"cubic-inches":{singular:"kubni in\u010d",plural:"kubni in\u010di",
abbr:"in\u00b3"},"cubic-feet":{singular:"kubna stopa",plural:"kubne stope",abbr:"ft\u00b3"},"cubic-yards":{singular:"kubni jard",plural:"kubne jarde",abbr:"yd\u00b3"},"cubic-miles":{singular:"kubna milja",plural:"kubne milje",abbr:"mi\u00b3"},radians:{singular:"radijan",plural:"radijani",abbr:""},degrees:{singular:"stepen",plural:"stepeni",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"Merenje",hint:"Otpo\u010dnite merenja klikom na scenu kako biste namestili prvu ta\u010dku",
unsupported:"Merenje 3D povr\u0161ine je podr\u017eano samo u aplikaciji SceneView.",perimeterLength:"Obim",area:"Povr\u0161ina",unit:"Jedinica",notApplicable:"nije dostupno",newMeasurement:"Novo merenje",units:{metric:"Metrika",imperial:"Imperijalne","square-kilometers":"Kvadratni kilometri","square-meters":"Kvadratni metri","square-miles":"Kvadratne milje","square-inches":"Kvadratni in\u010d","square-feet":"Kvadratne stope","square-yards":"Kvadratni jardi","square-us-feet":"Kvadratne stope (SAD)",
acres:"Ari",ares:"Ari",hectares:"Hektari"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"Mera",newMeasurement:"Novo merenje",distance:"Rastojanje",area:"Povr\u0161ina",slice:"Ise\u010dak",measureDistance:"Izmeri rastojanje",measureArea:"Izmeri povr\u0161inu",sliceObjects:"Iseci objekte",hint:"Najpre odaberite alatku za merenje kako biste po\u010deli",_localized:{}}});