// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"M\u00e5ling av direkte linje",hint:"Begynn \u00e5 m\u00e5le ved \u00e5 klikke p\u00e5 scenen for \u00e5 plassere ditt f\u00f8rste punkt",unsupported:"3D-m\u00e5ling av direkte linje st\u00f8ttes bare i SceneView.",distance:"Avstand",direct:"Direkte",horizontal:"Vannrett",vertical:"Loddrett",unit:"Enhet",newMeasurement:"Ny m\u00e5ling",units:{metric:"Metrisk",imperial:"Britiske m\u00e5lenheter",kilometers:"Kilometer",
meters:"Meter",miles:"Miles",inches:"Tommer",feet:"Fot",yards:"Yard","nautical-miles":"Nautiske mil","us-feet":"fot (USA)","degrees-minutes-seconds":"DMS",degrees:"Grader"},_localized:{}},"esri/core/nls/Units":{measures:{length:"Lengde",area:"Areal",volume:"Volum",angle:"Vinkel"},units:{millimeters:{singular:"millimeter",plural:"millimeter",abbr:"mm"},centimeters:{singular:"centimeter",plural:"centimeter",abbr:"cm"},decimeters:{singular:"desimeter",plural:"desimeter",abbr:"dm"},meters:{singular:"meter",
plural:"meter",abbr:"m"},kilometers:{singular:"kilometer",plural:"kilometer",abbr:"km"},inches:{singular:"tomme",plural:"tommer",abbr:"tm"},feet:{singular:"fot",plural:"fot",abbr:"ft"},yards:{singular:"yard",plural:"yard",abbr:"yd"},miles:{singular:"mile",plural:"miles",abbr:"mi"},"nautical-miles":{singular:"nautisk mil",plural:"nautiske mil",abbr:"nm"},"us-feet":{singular:"fot (USA)",plural:"fot (USA)",abbr:"ft"},"square-millimeters":{singular:"kvadratmillimeter",plural:"kvadratmillimeter",abbr:"mm\u00b2"},
"square-centimeters":{singular:"kvadratcentimeter",plural:"kvadratcentimeter",abbr:"cm\u00b2"},"square-decimeters":{singular:"kvadratdesimeter",plural:"kvadratdesimeter",abbr:"dm\u00b2"},"square-meters":{singular:"kvadratmeter",plural:"kvadratmeter",abbr:"m\u00b2"},"square-kilometers":{singular:"kvadratkilometer",plural:"kvadratkilometer",abbr:"km\u00b2"},"square-inches":{singular:"kvadrattommer",plural:"kvadrattommer",abbr:"in\u00b2"},"square-feet":{singular:"kvadratfot",plural:"kvadratfot",abbr:"ft\u00b2"},
"square-yards":{singular:"kvadratyard",plural:"kvadratyard",abbr:"yd\u00b2"},"square-miles":{singular:"kvadratmiles",plural:"kvadratmiles",abbr:"mi\u00b2"},"square-us-feet":{singular:"kvadratfot (USA)",plural:"kvadratfot (USA)",abbr:"ft\u00b2"},acres:{singular:"acre",plural:"acre",abbr:"acre"},ares:{singular:"ar",plural:"ar",abbr:"a"},hectares:{singular:"hektar",plural:"hektar",abbr:"ha"},liters:{singular:"liter",plural:"liter",abbr:"l"},"cubic-millimeters":{singular:"kubikkmillimeter",plural:"kubikkmillimeter",
abbr:"mm\u00b3"},"cubic-centimeters":{singular:"kubikkcentimeter",plural:"kubikkcentimeter",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"kubikkdesimeter",plural:"kubikkdesimeter",abbr:"dm\u00b3"},"cubic-meters":{singular:"kubikkmeter",plural:"kubikkmeter",abbr:"m\u00b3"},"cubic-kilometers":{singular:"kubikkilometer",plural:"kubikkilometer",abbr:"km\u00b3"},"cubic-inches":{singular:"kubikktomme",plural:"kubikktommer",abbr:"in\u00b3"},"cubic-feet":{singular:"kubikkfot",plural:"kubikkfot",abbr:"ft\u00b3"},
"cubic-yards":{singular:"kubikkyard",plural:"kubikkyard",abbr:"yd\u00b3"},"cubic-miles":{singular:"kubikkmile",plural:"kubikkmiles",abbr:"mi\u00b3"},radians:{singular:"radian",plural:"radianer",abbr:""},degrees:{singular:"grad",plural:"grader",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"Arealm\u00e5ling",hint:"Begynn \u00e5 m\u00e5le ved \u00e5 klikke p\u00e5 scenen for \u00e5 plassere ditt f\u00f8rste punkt",unsupported:"3D-arealm\u00e5ling st\u00f8ttes kun i SceneView.",
perimeterLength:"Omkrets",area:"Areal",unit:"Enhet",notApplicable:"\u2013",newMeasurement:"Ny m\u00e5ling",units:{metric:"Metrisk",imperial:"Britiske m\u00e5lenheter","square-kilometers":"Kvadratkilometer","square-meters":"Kvadratmeter","square-miles":"Kvadratmiles","square-inches":"Kvadrattommer","square-feet":"Kvadratfot","square-yards":"Kvadratyard","square-us-feet":"Kvadratfot (USA)",acres:"Acre",ares:"ar",hectares:"Hektar"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"M\u00e5l",
newMeasurement:"Ny m\u00e5ling",distance:"Avstand",area:"Areal",slice:"Sektor",measureDistance:"M\u00e5l avstand",measureArea:"M\u00e5l omr\u00e5de",sliceObjects:"Sektorobjekter",hint:"Velg f\u00f8rst et m\u00e5leverkt\u00f8y for \u00e5 komme i gang",_localized:{}}});