// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"Opm\u00e5l",hint:"Start m\u00e5ling ved at klikke i scenen for at placere det f\u00f8rste punkt",unsupported:"Direkte linje-m\u00e5ling underst\u00f8ttes ikke i MapView.",distance:"Afstand",direct:"Direkte",horizontal:"Vandret",vertical:"Lodret",unit:"Enhed",newMeasurement:"Ny m\u00e5ling",units:{metric:"Metrisk",imperial:"Britiske",kilometers:"Kilometer",meters:"Meter",miles:"Miles",inches:"Tommer",feet:"Fod",yards:"Yards",
"nautical-miles":"S\u00f8mil","us-feet":"Fod (USA)","degrees-minutes-seconds":"DMS",degrees:"Grader"},_localized:{}},"esri/views/3d/interactive/measurementTools/support/nls/Units":{measures:{length:"L\u00e6ngde",area:"Omr\u00e5de",volume:"M\u00e6ngde",angle:"Vinkel"},units:{millimeters:{singular:"millimeter",plural:"millimeter",abbr:"mm"},centimeters:{singular:"centimeter",plural:"centimeter",abbr:"cm"},decimeters:{singular:"decimeter",plural:"decimeter",abbr:"dm"},meters:{singular:"Meter",plural:"meter",
abbr:"m"},kilometers:{singular:"kilometer",plural:"kilometer",abbr:"km"},inches:{singular:"tomme",plural:"tommer",abbr:"tomme"},feet:{singular:"fod",plural:"fod",abbr:"fod"},yards:{singular:"yard",plural:"yards",abbr:"yard"},miles:{singular:"mile",plural:"miles",abbr:"mile"},"nautical-miles":{singular:"s\u00f8mil",plural:"s\u00f8mil",abbr:"nm"},"us-feet":{singular:"fod (USA)",plural:"fod (USA)",abbr:"fod"},"square-millimeters":{singular:"kvadratmillimeter",plural:"kvadratmillimeter",abbr:"mm\u00b2"},
"square-centimeters":{singular:"kvadratcentimeter",plural:"kvadratcentimeter",abbr:"cm\u00b2"},"square-decimeters":{singular:"kvadratdecimeter",plural:"kvadratdecimeter",abbr:"dm\u00b2"},"square-meters":{singular:"kvadratmeter",plural:"kvadratmeter",abbr:"m\u00b2"},"square-kilometers":{singular:"kvadratkilometer",plural:"kvadratkilometer",abbr:"km\u00b2"},"square-inches":{singular:"kvadrattomme",plural:"kvadrattommer",abbr:"in\u00b2"},"square-feet":{singular:"kvadratfod",plural:"kvadratfod",abbr:"ft\u00b2"},
"square-yards":{singular:"kvadratyard",plural:"kvadratyards",abbr:"yd\u00b2"},"square-miles":{singular:"kvadratmile",plural:"kvadratmiles",abbr:"mi\u00b2"},"square-us-feet":{singular:"kvadratfod (USA)",plural:"kvadratfod (USA)",abbr:"ft\u00b2"},acres:{singular:"acre",plural:"acres",abbr:"acre"},ares:{singular:"acre",plural:"acres",abbr:"a"},hectares:{singular:"hektar",plural:"hektarer",abbr:"ha"},liters:{singular:"liter",plural:"liter",abbr:"l"},"cubic-millimeters":{singular:"kubikmillimeter",plural:"kubikmillimeter",
abbr:"mm\u00b3"},"cubic-centimeters":{singular:"kubikcentimeter",plural:"kubikcentimeter",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"kubikdecimeter",plural:"kubikdecimeter",abbr:"dm\u00b3"},"cubic-meters":{singular:"kubikmeter",plural:"kubikmeter",abbr:"m\u00b3"},"cubic-kilometers":{singular:"kubikkilometer",plural:"kubikkilometer",abbr:"km\u00b3"},"cubic-inches":{singular:"kubiktomme",plural:"kubiktommer",abbr:"in\u00b3"},"cubic-feet":{singular:"kubikfod",plural:"kubikfod",abbr:"ft\u00b3"},"cubic-yards":{singular:"kubik-yard",
plural:"kubik-yards",abbr:"yd\u00b3"},"cubic-miles":{singular:"kubikmile",plural:"kubikmiles",abbr:"mi\u00b3"},radians:{singular:"radian",plural:"radianer",abbr:""},degrees:{singular:"grad",plural:"grader",abbr:"\u00b0"}},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"M\u00e5ling",_localized:{}}});