// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"Medi\u00e7\u00e3o da Linha Direta",hint:"Comece a medir clicando na cena para colocar o seu primeiro ponto",unsupported:"Medi\u00e7\u00e3o de linha direta n\u00e3o se encontra dispon\u00edvel em MapView.",distance:"Dist\u00e2ncia",direct:"Direto",horizontal:"Horizontal",vertical:"Vertical",unit:"Unidade",newMeasurement:"Nova Medi\u00e7\u00e3o",units:{metric:"M\u00e9trico",imperial:"Imperial",kilometers:"Quil\u00f3metros",
meters:"Metros",miles:"Milhas",inches:"Polegadas",feet:"P\u00e9s",yards:"Jardas","nautical-miles":"Milhas N\u00e1uticas","us-feet":"P\u00e9s (EUA)","degrees-minutes-seconds":"DMS",degrees:"Graus"},_localized:{}},"esri/core/nls/Units":{measures:{length:"Comprimento",area:"\u00c1rea",volume:"Volume",angle:"\u00c2ngulo"},units:{millimeters:{singular:"mil\u00edmetro",plural:"millimetros",abbr:"mm"},centimeters:{singular:"cent\u00edmetro",plural:"centimetros",abbr:"cm"},decimeters:{singular:"dec\u00edmetro",
plural:"dec\u00edmetros",abbr:"dm"},meters:{singular:"metro",plural:"metros",abbr:"m"},kilometers:{singular:"quil\u00f3metro",plural:"quil\u00f3metros",abbr:"km"},inches:{singular:"polegada",plural:"polegadas",abbr:"pol"},feet:{singular:"p\u00e9",plural:"p\u00e9s",abbr:"ft"},yards:{singular:"jarda",plural:"jardas",abbr:"yd"},miles:{singular:"milha",plural:"milhas",abbr:"milhas"},"nautical-miles":{singular:"milha n\u00e1utica",plural:"milhas n\u00e1uticas",abbr:"nm"},"us-feet":{singular:"P\u00e9 (EUA)",
plural:"p\u00e9s (EUA)",abbr:"ft"},"square-millimeters":{singular:"mil\u00edmetro quadrado",plural:"mil\u00edmetros quadrados",abbr:"mm\u00b2"},"square-centimeters":{singular:"cent\u00edmetro quadrado",plural:"cent\u00edmetros quadrados",abbr:"cm\u00b2"},"square-decimeters":{singular:"dec\u00edmetro quadrado",plural:"dec\u00edmetros quadrados",abbr:"dm\u00b2"},"square-meters":{singular:"metro quadrado",plural:"metros quadrados",abbr:"m\u00b2"},"square-kilometers":{singular:"quil\u00f3metro quadrado",
plural:"quil\u00f3metros quadrados",abbr:"km\u00b2"},"square-inches":{singular:"polegada quadrada",plural:"polegadas quadradas",abbr:"in\u00b2"},"square-feet":{singular:"p\u00e9 quadrado",plural:"p\u00e9s quadrados",abbr:"ft\u00b2"},"square-yards":{singular:"jarda quadrada",plural:"jardas quadradas",abbr:"yd\u00b2"},"square-miles":{singular:"milha quadrada",plural:"milhas quadradas",abbr:"mi\u00b2"},"square-us-feet":{singular:"p\u00e9 quadrado (EUA)",plural:"p\u00e9s quadrados (EUA)",abbr:"ft\u00b2"},
acres:{singular:"acre",plural:"acres",abbr:"acre"},ares:{singular:"are",plural:"ares",abbr:"a"},hectares:{singular:"hectare",plural:"hectares",abbr:"ha"},liters:{singular:"litro",plural:"litros",abbr:"l"},"cubic-millimeters":{singular:"mil\u00edmetro c\u00fabico",plural:"mil\u00edmetros c\u00fabicos",abbr:"mm\u00b3"},"cubic-centimeters":{singular:"cent\u00edmetro c\u00fabico",plural:"cent\u00edmetros c\u00fabicos",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"dec\u00edmetro c\u00fabico",plural:"dec\u00edmetro c\u00fabicos",
abbr:"dm\u00b3"},"cubic-meters":{singular:"metro c\u00fabico",plural:"metros c\u00fabicos",abbr:"m\u00b3"},"cubic-kilometers":{singular:"quil\u00f3metro c\u00fabico",plural:"quil\u00f3metros c\u00fabicos",abbr:"km\u00b3"},"cubic-inches":{singular:"polegada c\u00fabica",plural:"polegadas c\u00fabicas",abbr:"in\u00b3"},"cubic-feet":{singular:"p\u00e9 c\u00fabico",plural:"p\u00e9s c\u00fabicos",abbr:"ft\u00b3"},"cubic-yards":{singular:"jarda c\u00fabica",plural:"jardas c\u00fabicas",abbr:"yd\u00b3"},
"cubic-miles":{singular:"milha c\u00fabica",plural:"milhas c\u00fabicas",abbr:"mi\u00b3"},radians:{singular:"radiano",plural:"radianos",abbr:""},degrees:{singular:"grau",plural:"graus",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"Medi\u00e7\u00e3o de \u00c1rea",hint:"Comece a medir clicando na cena para colocar o seu primeiro ponto",unsupported:"A medi\u00e7\u00e3o de \u00e1rea 3D s\u00f3 \u00e9 suportada em SceneView.",perimeterLength:"Per\u00edmetro",
area:"\u00c1rea",unit:"Unidade",notApplicable:"n/d",newMeasurement:"Nova Medi\u00e7\u00e3o",units:{metric:"M\u00e9trico",imperial:"Imperial","square-kilometers":"Quil\u00f3metros Quadrados","square-meters":"Metros Quadrados","square-miles":"Milhas Quadradas","square-inches":"Polegadas Quadradas","square-feet":"P\u00e9s Quadrados","square-yards":"Jardas Quadradas","square-us-feet":"P\u00e9s Quadrados (EUA)",acres:"Acres",ares:"Ares",hectares:"Hectares"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"Medi\u00e7\u00e3o",
newMeasurement:"Nova Medi\u00e7\u00e3o",distance:"Dist\u00e2ncia",area:"\u00c1rea",slice:"Seccionar",measureDistance:"Medi\u00e7\u00e3o de Dist\u00e2ncia",measureArea:"Medir \u00c1rea",sliceObjects:"Seccionar objetos",hint:"Selecionar uma ferramenta de medi\u00e7\u00e3o para iniciar",_localized:{}}});