// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"Messwert",hint:"Beginnen Sie die Messung, indem Sie in die Szene klicken, um den ersten Punkt zu positionieren.",unsupported:"Die direkte 3D-Linienmessung wird nur in SceneView unterst\u00fctzt.",distance:"Abstand",direct:"Direkt",horizontal:"Horizontal",vertical:"Vertikal",unit:"Einheit",newMeasurement:"Neue Messung",units:{metric:"Metrisch",imperial:"Britisch",kilometers:"Kilometer",meters:"Meter",miles:"Meilen",
inches:"Zoll",feet:"Fu\u00df",yards:"Yards","nautical-miles":"Seemeilen","us-feet":"Fu\u00df (US)","degrees-minutes-seconds":"DMS",degrees:"Grad"},_localized:{}},"esri/core/nls/Units":{measures:{length:"L\u00e4nge",area:"Fl\u00e4che",volume:"Volumen",angle:"Winkel"},units:{millimeters:{singular:"Millimeter",plural:"Millimeter",abbr:"mm"},centimeters:{singular:"Zentimeter",plural:"Zentimeter",abbr:"cm"},decimeters:{singular:"Dezimeter",plural:"Dezimeter",abbr:"dm"},meters:{singular:"Meter",plural:"Meter",
abbr:"m"},kilometers:{singular:"Kilometer",plural:"Kilometer",abbr:"km"},inches:{singular:"Zoll",plural:"Zoll",abbr:"in"},feet:{singular:"Fu\u00df",plural:"Fu\u00df",abbr:"ft"},yards:{singular:"Yard",plural:"Yards",abbr:"yd"},miles:{singular:"Meile",plural:"Meilen",abbr:"mi"},"nautical-miles":{singular:"Seemeile",plural:"Seemeilen",abbr:"sm"},"us-feet":{singular:"Fu\u00df (US)",plural:"Fu\u00df (US)",abbr:"ft"},"square-millimeters":{singular:"Quadratmillimeter",plural:"Quadratmillimeter",abbr:"mm\u00b2"},
"square-centimeters":{singular:"Quadratzentimeter",plural:"Quadratzentimeter",abbr:"cm\u00b2"},"square-decimeters":{singular:"Quadratdezimeter",plural:"Quadratdezimeter",abbr:"dm\u00b2"},"square-meters":{singular:"Quadratmeter",plural:"Quadratmeter",abbr:"m\u00b2"},"square-kilometers":{singular:"Quadratkilometer",plural:"Quadratkilometer",abbr:"km\u00b2"},"square-inches":{singular:"Quadratzoll",plural:"Quadratzoll",abbr:"in\u00b2"},"square-feet":{singular:"Quadratfu\u00df",plural:"Quadratfu\u00df",
abbr:"ft\u00b2"},"square-yards":{singular:"Quadratyard",plural:"Quadratyards",abbr:"yd\u00b2"},"square-miles":{singular:"Quadratmeile",plural:"Quadratmeilen",abbr:"mi\u00b2"},"square-us-feet":{singular:"Quadratfu\u00df (US)",plural:"Quadratfu\u00df (US)",abbr:"ft\u00b2"},acres:{singular:"Acre",plural:"Acres",abbr:"Acre"},ares:{singular:"are",plural:"Ar",abbr:"a"},hectares:{singular:"Hektar",plural:"Hektar",abbr:"ha"},liters:{singular:"Liter",plural:"Liter",abbr:"l"},"cubic-millimeters":{singular:"Kubikmillimeter",
plural:"Kubikmillimeter",abbr:"mm\u00b3"},"cubic-centimeters":{singular:"Kubikzentimeter",plural:"Kubikzentimeter",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"Kubikdezimeter",plural:"Kubikdezimeter",abbr:"dm\u00b3"},"cubic-meters":{singular:"Kubikmeter",plural:"Kubikmeter",abbr:"m\u00b3"},"cubic-kilometers":{singular:"Kubikkilometer",plural:"Kubikkilometer",abbr:"km\u00b3"},"cubic-inches":{singular:"Kubikzoll",plural:"Kubikzoll",abbr:"in\u00b3"},"cubic-feet":{singular:"Kubikfu\u00df",plural:"Kubikfu\u00df",
abbr:"ft\u00b3"},"cubic-yards":{singular:"Kubikyard",plural:"Kubikyards",abbr:"yd\u00b3"},"cubic-miles":{singular:"Kubikmeile",plural:"Kubikmeile",abbr:"mi\u00b3"},radians:{singular:"Radiant",plural:"Radiant",abbr:""},degrees:{singular:"Grad",plural:"Grad",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"Messen",hint:"Beginnen Sie die Messung, indem Sie in die Szene klicken, um den ersten Punkt zu positionieren.",unsupported:"Die 3D-Fl\u00e4chenmessung wird nur in SceneView unterst\u00fctzt.",
perimeterLength:"Umfang",area:"Fl\u00e4che",unit:"Einheit",notApplicable:"nicht zutreffend",newMeasurement:"Neue Messung",units:{metric:"Metrisch",imperial:"Britisch","square-kilometers":"Quadratkilometer","square-meters":"Quadratmeter","square-miles":"Quadratmeilen","square-inches":"Quadratzoll","square-feet":"Quadratfu\u00df","square-yards":"Quadratyards","square-us-feet":"Quadratfu\u00df (US)",acres:"Acres",ares:"Ar",hectares:"Hektar"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"Messen",
newMeasurement:"Neue Messung",distance:"Entfernung",area:"Fl\u00e4che",slice:"Ausschneiden",measureDistance:"L\u00e4nge messen",measureArea:"Fl\u00e4che messen",sliceObjects:"Ausschnittobjekte",hint:"W\u00e4hlen Sie zun\u00e4chst ein Messwerkzeug aus, um zu beginnen.",_localized:{}}});