// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"esri/widgets/DirectLineMeasurement3D/nls/DirectLineMeasurement3D":{title:"Direct Line Measurement",hint:"Start to measure by clicking in the scene to place your first point",unsupported:"3D direct line measurement is only supported in SceneView.",distance:"Distance",direct:"Direct",horizontal:"Horizontal",vertical:"Vertical",unit:"Unit",newMeasurement:"New Measurement",units:{metric:"Metric",imperial:"Imperial",kilometers:"Kilometers",meters:"Meters",miles:"Miles",inches:"Inches",feet:"Feet",
yards:"Yards","nautical-miles":"Nautical Miles","us-feet":"Feet (US)","degrees-minutes-seconds":"DMS",degrees:"Degrees"},_localized:{}},"esri/core/nls/Units":{measures:{length:"Length",area:"Area",volume:"Volume",angle:"Angle"},units:{millimeters:{singular:"millimeter",plural:"millimeters",abbr:"mm"},centimeters:{singular:"centimeter",plural:"centimeters",abbr:"cm"},decimeters:{singular:"decimeter",plural:"decimeters",abbr:"dm"},meters:{singular:"meter",plural:"meters",abbr:"m"},kilometers:{singular:"kilometer",
plural:"kilometers",abbr:"km"},inches:{singular:"inch",plural:"inches",abbr:"in"},feet:{singular:"foot",plural:"feet",abbr:"ft"},yards:{singular:"yard",plural:"yards",abbr:"yd"},miles:{singular:"mile",plural:"miles",abbr:"mi"},"nautical-miles":{singular:"nautical mile",plural:"nautical miles",abbr:"nm"},"us-feet":{singular:"foot (US)",plural:"feet (US)",abbr:"ft"},"square-millimeters":{singular:"square millimeter",plural:"square millimeters",abbr:"mm\u00b2"},"square-centimeters":{singular:"square centimeter",
plural:"square centimeters",abbr:"cm\u00b2"},"square-decimeters":{singular:"square decimeter",plural:"square decimeters",abbr:"dm\u00b2"},"square-meters":{singular:"square meter",plural:"square meters",abbr:"m\u00b2"},"square-kilometers":{singular:"square kilometer",plural:"square kilometers",abbr:"km\u00b2"},"square-inches":{singular:"square inch",plural:"square inches",abbr:"in\u00b2"},"square-feet":{singular:"square foot",plural:"square feet",abbr:"ft\u00b2"},"square-yards":{singular:"square yard",
plural:"square yards",abbr:"yd\u00b2"},"square-miles":{singular:"square mile",plural:"square miles",abbr:"mi\u00b2"},"square-us-feet":{singular:"square foot (US)",plural:"square feet (US)",abbr:"ft\u00b2"},acres:{singular:"acre",plural:"acres",abbr:"acre"},ares:{singular:"are",plural:"ares",abbr:"a"},hectares:{singular:"hectare",plural:"hectares",abbr:"ha"},liters:{singular:"liter",plural:"liters",abbr:"l"},"cubic-millimeters":{singular:"cubic millimeter",plural:"cubic millimeters",abbr:"mm\u00b3"},
"cubic-centimeters":{singular:"cubic centimeter",plural:"cubic centimeters",abbr:"cm\u00b3"},"cubic-decimeters":{singular:"cubic decimeter",plural:"cubic decimeters",abbr:"dm\u00b3"},"cubic-meters":{singular:"cubic meter",plural:"cubic meters",abbr:"m\u00b3"},"cubic-kilometers":{singular:"cubic kilometer",plural:"cubic kilometers",abbr:"km\u00b3"},"cubic-inches":{singular:"cubic inch",plural:"cubic inches",abbr:"in\u00b3"},"cubic-feet":{singular:"cubic foot",plural:"cubic feet",abbr:"ft\u00b3"},"cubic-yards":{singular:"cubic yard",
plural:"cubic yards",abbr:"yd\u00b3"},"cubic-miles":{singular:"cubic mile",plural:"cubic miles",abbr:"mi\u00b3"},radians:{singular:"radian",plural:"radians",abbr:""},degrees:{singular:"degree",plural:"degrees",abbr:"\u00b0"}},_localized:{}},"esri/widgets/AreaMeasurement3D/nls/AreaMeasurement3D":{title:"Area Measurement",hint:"Start to measure by clicking in the scene to place your first point",unsupported:"3D area measurement is only supported in SceneView.",perimeterLength:"Perimeter",area:"Area",
unit:"Unit",notApplicable:"n/a",newMeasurement:"New Measurement",units:{metric:"Metric",imperial:"Imperial","square-kilometers":"Square Kilometers","square-meters":"Square Meters","square-miles":"Square Miles","square-inches":"Square Inches","square-feet":"Square Feet","square-yards":"Square Yards","square-us-feet":"Square Feet (US)",acres:"Acres",ares:"Ares",hectares:"Hectares"},_localized:{}},"widgets/Measurement3D/nls/strings":{_widgetLabel:"Measurement",newMeasurement:"New Measurement",distance:"Distance",
area:"Area",slice:"Slice",measureDistance:"Measure Distance",measureArea:"Measure Area",sliceObjects:"Slice Objects",hint:"Select a measurement tool first to start",_localized:{}}});