// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"dijit/_WidgetsInTemplateMixin":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare","dojo/_base/lang","dojo/parser"],function(d,b,f,g,e){return f("dijit._WidgetsInTemplateMixin",null,{_earlyTemplatedStartup:!1,contextRequire:null,_beforeFillContent:function(){if(/dojoType|data-dojo-type/i.test(this.domNode.innerHTML)){var a=this.domNode;this.containerNode&&!this.searchContainerNode&&(this.containerNode.stopParser=!0);e.parse(a,{noStart:!this._earlyTemplatedStartup,
template:!0,inherited:{dir:this.dir,lang:this.lang,textDir:this.textDir},propsThis:this,contextRequire:this.contextRequire,scope:"dojo"}).then(g.hitch(this,function(a){this._startupWidgets=a;for(var c=0;c<a.length;c++)this._processTemplateNode(a[c],function(k,a){return k[a]},function(a,c,b){return c in a?a.connect(a,c,b):a.on(c,b,!0)});this.containerNode&&this.containerNode.stopParser&&delete this.containerNode.stopParser}));if(!this._startupWidgets)throw Error(this.declaredClass+": parser returned unfilled promise (probably waiting for module auto-load), unsupported by _WidgetsInTemplateMixin.   Must pre-load all supporting widgets before instantiation.");
}},_processTemplateNode:function(a,b,c){return b(a,"dojoType")||b(a,"data-dojo-type")?!0:this.inherited(arguments)},startup:function(){d.forEach(this._startupWidgets,function(a){a&&!a._started&&a.startup&&a.startup()});this._startupWidgets=null;this.inherited(arguments)}})})},"widgets/About/_build-generate_module":function(){define(["dojo/text!./Widget.html","dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/About/Widget.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"about-envelope" data-dojo-attach-point\x3d"envelopeNode"\x3e\r\n    \x3cdiv class\x3d"about-container" data-dojo-attach-point\x3d"splashContainerNode"\x3e\r\n      \x3cdiv class\x3d"about-content" data-dojo-attach-point\x3d"customContentNode"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e',
"url:widgets/About/css/style.css":".jimu-widget-about{width: 100%; height: 100%;}.jimu-widget-about-desktop .about-envelope{min-height: 300px; max-height: 500px; min-width: 350px; max-width: 800px; position: absolute; top: 0; bottom: 0; left: 0; right: 0; margin: auto; -moz-user-select: none; -webkit-user-select: none; -ms-user-select: none;}.jimu-widget-about-desktop .about-container{min-width: 350px; max-width: 800px; position: absolute; display: inline-block; background-color: #485566; box-shadow: 0 0 4px rgba(160, 160, 160, 0.4);}.jimu-widget-about-desktop .about-content{width: 560px; margin: 20px 40px; overflow: auto; color: #fff; max-height: 388px;}",
"*now":function(d){d(['dojo/i18n!*preload*widgets/About/nls/Widget*["ar","bs","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])}}});
define("dojo/_base/declare dojo/_base/html dojo/query dojo/on dojo/_base/lang dijit/_WidgetsInTemplateMixin jimu/BaseWidget".split(" "),function(d,b,f,g,e,a,h){return d([h,a],{baseClass:"jimu-widget-about",_hasContent:null,postCreate:function(){this.inherited(arguments);this._hasContent=this.config.about&&this.config.about.aboutContent},startup:function(){this.inherited(arguments);this.resize()},resize:function(){this._resizeContentImg()},_resizeContentImg:function(){if(this._hasContent){b.empty(this.customContentNode);
var a=b.toDom(this.config.about.aboutContent);b.place(a,this.customContentNode);this.customContentNode.nodeType&&1===this.customContentNode.nodeType&&(a=f("img",this.customContentNode))&&a.length&&a.forEach(e.hitch(this,function(a){"undefined"!==typeof a.complete&&!1===a.complete?this.own(g(a,"load",e.hitch(this,function(){this._resizeImg(a)}))):this._resizeImg(a)}))}},_resizeImg:function(a){var c=b.getContentBox(this.customContentNode),d=b.getContentBox(a);d&&d.w&&d.w>=c.w&&b.setStyle(a,{maxWidth:c.w-
20+"px",maxHeight:c.h-40+"px"})}})});