// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/topic dojo/Deferred dojo/on ./utils ./WidgetManager ./shared/AppVersionManager ./ConfigLoader ./tokenUtils ./portalUtils esri/config esri/tasks/GeometryService".split(" "),function(p,e,g,l,d,q,r,f,t,u,v,w,x,y,z){function n(a,b){var c=e.clone(a),h=f.widgetProperties;"undefined"===typeof b&&(b=!1);delete c.mode;f.visitElement(c,function(a,e){a.widgets?(delete a.isOnScreen,delete a.gid,"jimu.js/images/group_icon.png"===
a.icon&&delete a.icon,delete a.openType,e.isOnScreen&&a.panel&&f.isEqual(a.panel,c.widgetOnScreen.panel)&&delete a.panel):(a.icon&&a.icon===a.folderUrl+"images/icon.png?wab_dv\x3d"+window.deployVersion&&delete a.icon,delete a.panel,delete a.folderUrl,delete a.amdFolder,delete a.thumbnail,delete a.configFile,delete a.gid,delete a.isOnScreen,h.forEach(function(b){delete a[b]}),b?("undefined"===typeof a.openAtStart&&(a.openAtStart=!1),a.config||delete a.config):(a.visible&&delete a.visible,a.manifest&&
a.label===a.manifest.label&&delete a.label,a.isDefaultConfig&&(delete a.config,delete a.isDefaultConfig)),delete a.manifest)});delete c.rawAppConfig;delete c._ssl;delete c.getConfigElementById;delete c.getConfigElementsByName;delete c.getConfigElementByLabel;delete c.processNoUriWidgets;delete c.addElementId;delete c.getCleanConfig;delete c.visitElement;delete c.agolConfig;delete c._itemData;delete c.oldWabVersion;return c}var k=null,m;m=p(null,{urlParams:null,appConfig:null,configFile:null,_configLoaded:!1,
portalSelf:null,constructor:function(a){this.urlParams=a||{};this.listenBuilderEvents();this.versionManager=new u;this.widgetManager=t.getInstance();this.configLoader=v.getInstance(this.urlParams,{versionManager:this.versionManager});"config"===this.urlParams.mode&&window.parent.setConfigViewerTopic&&e.isFunction(window.parent.setConfigViewerTopic)&&window.parent.setConfigViewerTopic(d);"preview"===this.urlParams.mode&&window.parent.setPreviewViewerTopic&&e.isFunction(window.parent.setPreviewViewerTopic)&&
window.parent.setPreviewViewerTopic(d);r(window,"resize",e.hitch(this,this._onWindowResize))},listenBuilderEvents:function(){d.subscribe("builder/widgetChanged",e.hitch(this,this._onWidgetChanged));d.subscribe("builder/groupChanged",e.hitch(this,this._onGroupChanged));d.subscribe("builder/widgetPoolChanged",e.hitch(this,this._onWidgetPoolChanged));d.subscribe("builder/openAtStartChange",e.hitch(this,this._onOpenAtStartChanged));d.subscribe("builder/onScreenOrderChanged",e.hitch(this,this._onScreenOrderChanged));
d.subscribe("builder/layoutDefinitionChanged",e.hitch(this,this._onLayoutDefinitionChanged));d.subscribe("builder/sceneViewChanged",e.hitch(this,this._onSceneViewChanged));d.subscribe("builder/mapOptionsChanged",e.hitch(this,this._onMapOptionsChanged));d.subscribe("builder/appAttributeChanged",e.hitch(this,this._onAppAttributeChanged));d.subscribe("builder/setAppConfig",e.hitch(this,this._onAppConfigSet));d.subscribe("builder/themeChanged",e.hitch(this,this._onThemeChanged));d.subscribe("builder/layoutChanged",
e.hitch(this,this._onLayoutChanged));d.subscribe("builder/styleChanged",e.hitch(this,this._onStyleChanged));d.subscribe("builder/syncExtent",e.hitch(this,this._onSyncExtent));d.subscribe("builder/loadingPageChanged",e.hitch(this,this._onLoadingPageChanged));d.subscribe("builder/templateConfigChanged",e.hitch(this,this._onTemplateConfigChanged));d.subscribe("builder/sharedThemeChanged",e.hitch(this,this._onSharedThemeChanged))},loadConfig:function(){if("preview"!==this.urlParams.mode&&"config"!==this.urlParams.mode)return this.configLoader.loadConfig().then(e.hitch(this,
function(a){this.portalSelf=this.configLoader.portalSelf;this.appConfig=this._addDefaultValues(a);window.appInfo.isRunInMobile=this._isRunInMobile();console.timeEnd("Load Config");a=this.getAppConfig();d.publish("appConfigLoaded",a);return a}),e.hitch(this,function(a){console.error(a);a&&a.message&&"string"===typeof a.message&&this._showErrorMessage(a.message)}))},_showErrorMessage:function(a){l.create("div",{"class":"app-error",innerHTML:f.sanitizeHTML("Unable to create map: "+a)},document.body)},
getAppConfig:function(){var a;window.appInfo.isRunInMobile?(a=e.clone(this._getMobileConfig(this.appConfig)),a._originConfig=e.clone(this.appConfig)):a=e.clone(this.appConfig);a.getConfigElementById=function(a){return f.getConfigElementById(this,a)};a.getConfigElementByLabel=function(a){return f.getConfigElementByLabel(this,a)};a.getConfigElementsByName=function(a){return f.getConfigElementsByName(this,a)};a.getCleanConfig=function(a){return this._originConfig?n(this._originConfig,a):n(this,a)};a.visitElement=
function(a){f.visitElement(this,a)};return a},_onWindowResize:function(){var a=this._isRunInMobile();window.appInfo.isRunInMobile!==a&&(window.appInfo.isRunInMobile=a,this.appConfig&&d.publish("appConfigChanged",this.getAppConfig(),"layoutChange"))},_isRunInMobile:function(){var a=l.getMarginBox(window.jimuConfig.layoutId);if(a.w<=window.jimuConfig.breakPoints[0]||a.h<=window.jimuConfig.breakPoints[0])return l.addClass(window.jimuConfig.layoutId,"jimu-ismobile"),!0;l.removeClass(window.jimuConfig.layoutId,
"jimu-ismobile");return!1},_getMobileConfig:function(a){return f.mixinAppConfigPosition(a,a.mobileLayout)},_onWidgetChanged:function(a){var b=f.reCreateObject(a);a=f.getConfigElementById(this.appConfig,a.id);!1!==b.inPanel||a.uri||(b.closeable=!0);for(var c in b)a[c]=b[c];delete a.isDefaultConfig;this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);d.publish("appConfigChanged",this.getAppConfig(),"widgetChange",b)},_onGroupChanged:function(a){var b=f.reCreateObject(a);
a=f.getConfigElementById(this.appConfig,a.id);for(var c in b)a[c]=b[c];this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);d.publish("appConfigChanged",this.getAppConfig(),"groupChange",b)},_onWidgetPoolChanged:function(a){a=f.reCreateObject(a);if(1===this.widgetManager.getControllerWidgets().length)this.appConfig.widgetPool.widgets=a.widgets,this.appConfig.widgetPool.groups=a.groups;else{var b=f.getConfigElementById(this.appConfig,a.controllerId);g.forEach(b.controlledWidgets,
function(a){this._removeWidgetOrGroupFromPoolById(this.appConfig,a)},this);g.forEach(b.controlledGroups,function(a){this._removeWidgetOrGroupFromPoolById(this.appConfig,a)},this);this.appConfig.widgetPool.widgets="undefined"===typeof this.appConfig.widgetPool.widgets?a.widgets:this.appConfig.widgetPool.widgets.concat(a.widgets);this.appConfig.widgetPool.groups="undefined"===typeof this.appConfig.widgetPool.groups?a.groups:this.appConfig.widgetPool.groups.concat(a.groups);this.configLoader.addNeedValues(this.appConfig);
b.controlledWidgets=g.map(a.widgets,function(a){return a.id});b.controlledGroups=g.map(a.groups,function(a){return a.id})}this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);d.publish("appConfigChanged",this.getAppConfig(),"widgetPoolChange",a)},_removeWidgetOrGroupFromPoolById:function(a,b){g.some(a.widgetPool.widgets,function(c,h){if(c.id===b)return a.widgetPool.widgets.splice(h,1),!0});g.some(a.widgetPool.groups,function(c,h){if(c.id===b)return a.widgetPool.groups.splice(h,
1),!0})},_onOpenAtStartChanged:function(a){var b=f.reCreateObject(a),c=this.appConfig;a.isOnScreen?(c=c.widgetOnScreen&&c.widgetOnScreen.widgets)&&0<c.length&&g.forEach(c,e.hitch(this,function(b){b.id===a.id?b.openAtStart=!b.openAtStart:delete b.openAtStart})):((c=c.widgetPool)&&c.groups&&0<c.groups.length&&g.forEach(c.groups,e.hitch(this,function(b){b.id===a.id?b.openAtStart=!b.openAtStart:delete b.openAtStart})),c&&c.widgets&&0<c.widgets.length&&g.forEach(c.widgets,e.hitch(this,function(b){b.id===
a.id?b.openAtStart=!b.openAtStart:delete b.openAtStart})));d.publish("appConfigChanged",this.getAppConfig(),"openAtStartChange",b)},_onScreenOrderChanged:function(a){var b=f.reCreateObject(a);g.forEach(this.appConfig.widgetOnScreen.widgets,function(a){a.isController||(!1!==a.inPanel||!0!==a.closeable)&&!0!==a.inPanel&&a.uri||g.some(b,function(b){if(a.id===b.id)return a.position=b.position,!0})},this);d.publish("appConfigChanged",this.getAppConfig(),"onScreenOrderChange",b)},_onAppAttributeChanged:function(a){a=
f.reCreateObject(a);e.mixin(this.appConfig,a);this.configLoader.processProxy(this.appConfig);this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);d.publish("appConfigChanged",this.getAppConfig(),"attributeChange",a)},_onLoadingPageChanged:function(a){a=f.reCreateObject(a);var b;"backgroundColor"in a?this.appConfig.loadingPage.backgroundColor=a.backgroundColor:"backgroundImage"in a?(b=this.appConfig.loadingPage.backgroundImage||{},this.appConfig.loadingPage.backgroundImage=
e.mixin(b,a.backgroundImage)):"loadingGif"in a&&(b=this.appConfig.loadingPage.loadingGif||{},this.appConfig.loadingPage.loadingGif=e.mixin(b,a.loadingGif));this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);d.publish("appConfigChanged",this.getAppConfig(),"loadingPageChange",a)},_onTemplateConfigChanged:function(a){a=f.reCreateObject(a);this.appConfig.templateConfig=a;this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);d.publish("appConfigChanged",
this.getAppConfig(),"templateConfigChange",a)},_onLayoutDefinitionChanged:function(a){a=f.reCreateObject(a);f.isEqual(this.appConfig.layoutDefinition,a.layoutDefinition)||(this.appConfig.layoutDefinition=a.layoutDefinition,this.appConfig.widgetOnScreen.groups=f.handleGridLayoutOnScreenGroupChange(this.appConfig.widgetOnScreen.groups,a.groupIds),this.configLoader.addNeedValues(this.appConfig),this._addDefaultValues(this.appConfig),d.publish("appConfigChanged",this.getAppConfig(),"layoutDefinitionChange",
a.layoutDefinition))},_onSceneViewChanged:function(a){a=f.reCreateObject(a);a.itemId&&a.itemId!==this.appConfig.map.itemId&&this.appConfig.map.mapOptions&&f.deleteMapOptions(this.appConfig.map.mapOptions);e.mixin(this.appConfig.map,a);this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);d.publish("appConfigChanged",this.getAppConfig(),"mapChange",a)},_onMapOptionsChanged:function(a){a=f.reCreateObject(a);this.appConfig.map.mapOptions||(this.appConfig.map.mapOptions=
{});e.mixin(this.appConfig.map.mapOptions,a);d.publish("appConfigChanged",this.getAppConfig(),"mapOptionsChange",a)},_onThemeChanged:function(a){this._getAppConfigFromTheme(a).then(e.hitch(this,function(b){this.appConfig=b;d.publish("appConfigChanged",this.getAppConfig(),"themeChange",a.getName())}))},_onLayoutChanged:function(a){this.appConfig=f.mixinAppConfigPosition(this.appConfig,a.layoutConfig);this.appConfig.layoutDefinition=a.layoutConfig.layoutDefinition;this.configLoader.addNeedValues(this.appConfig);
this._addDefaultValues(this.appConfig);this._addDefaultPanelAndPosition(this.appConfig);d.publish("appConfigChanged",this.getAppConfig(),"layoutChange",a.name)},_onStyleChanged:function(a){this.appConfig.theme.styles=this._genStyles(this.appConfig.theme.styles,a.name);a.isCustom?this.appConfig.theme.customStyles={mainBackgroundColor:a.styleColor}:(delete this.appConfig.theme.customStyles,delete this.appConfig.titleColor,this.appConfig.theme.sharedTheme={isPortalSupport:this.appConfig.theme.sharedTheme.isPortalSupport,
useHeader:!1,useLogo:!1});d.publish("appConfigChanged",this.getAppConfig(),"styleChange",a.name)},_onSharedThemeChanged:function(a){var b=this.appConfig.theme.sharedTheme;a=f.reCreateObject(a);a.useHeader&&!b.useHeader&&(this.portalSelf.portalProperties&&this.portalSelf.portalProperties.sharedTheme?(this.appConfig.theme.customStyles={mainBackgroundColor:this.portalSelf.portalProperties.sharedTheme.header.background},this.appConfig.titleColor=this.portalSelf.portalProperties.sharedTheme.header.text,
this._onAppAttributeChanged({titleColor:this.appConfig.titleColor})):console.error("Portal does not support sharedTheme."));!a.useHeader&&b.useHeader&&(delete this.appConfig.titleColor,this._onAppAttributeChanged({titleColor:this.appConfig.titleColor}));a.useLogo&&!b.useLogo&&(this.portalSelf.portalProperties&&this.portalSelf.portalProperties.sharedTheme?(this.appConfig.logo=this.portalSelf.portalProperties.sharedTheme.logo.small?this.portalSelf.portalProperties.sharedTheme.logo.small:"images/app-logo.png",
this.appConfig.logoLink=this.portalSelf.portalProperties.sharedTheme.logo.link,this._onAppAttributeChanged({logo:this.appConfig.logo,logoLink:this.appConfig.logoLink})):console.error("Portal does not support sharedTheme."));!a.useLogo&&b.useLogo&&this._onAppAttributeChanged({logo:this.appConfig.logo});e.mixin(b,a);d.publish("appConfigChanged",this.getAppConfig(),"sharedThemeChange",a)},_onSyncExtent:function(a){d.publish("syncExtent",a)},_genStyles:function(a,b){var c=[];c.push(b);g.forEach(a,function(a){0>
c.indexOf(a)&&c.push(a)});return c},_getAppConfigFromTheme:function(a){var b=new q,c,h=[],d=this.getAppConfig().getCleanConfig();d.mode=this.urlParams.mode;g.forEach(d.widgetPool.groups,function(a){delete a.panel},this);if(a.appConfig)c=e.clone(a.appConfig),c.map=d.map,c.map.position=a.appConfig.map.position,this._copyPoolToThemePool(d,c),c.links=d.links,c.title=d.title,c.subtitle=d.subtitle,c.logo=d.logo;else{var f=a.getCurrentLayout(),h=a.getCurrentStyle();c=e.clone(d);f=e.clone(f.layoutConfig);
c.widgetOnScreen=f.widgetOnScreen;f.widgetPool&&(g.forEach(f.widgetPool.widgets,function(a){a.isPreconfiguredInTheme=!0}),g.forEach(f.widgetPool.groups,function(a){a.isPreconfiguredInTheme=!0}));this._copyPoolToThemePool(d,f);c.widgetPool=f.widgetPool;f.map&&f.map.position&&(c.map.position=f.map.position);c.mobileLayout=f.mobileLayout;c.layoutDefinition=f.layoutDefinition;h=this._genStyles(g.map(a.getStyles(),function(a){return a.name}),h.name);c.theme={name:a.getName(),styles:h,version:a.getVersion()};
this.portalSelf.portalProperties&&this.portalSelf.portalProperties.sharedTheme?(c.theme.sharedTheme={useHeader:!0,useLogo:!0,isPortalSupport:!0},c.theme.customStyles={mainBackgroundColor:this.portalSelf.portalProperties.sharedTheme.header.background}):(c.theme.sharedTheme={useHeader:!1,useLogo:!1,isPortalSupport:!1},c.theme.customStyles={mainBackgroundColor:""});c.titleColor=d.titleColor;c.logoLink=d.logoLink}this.configLoader.addNeedValues(c);this.configLoader.loadWidgetsManifest(c).then(e.hitch(this,
function(){this._addDefaultValues(c);b.resolve(c)}));return b},_copyPoolToThemePool:function(a,b){var c=a.widgetPool;b.widgetPool||(b.widgetPool={});a=b.widgetPool;var h=g.filter(a.widgets,function(a){if(a.isPreconfiguredInTheme||!g.some(c.widgets,function(b){return b.name===a.name}))return!0}),d=g.filter(a.groups,function(a){return a.isPreconfiguredInTheme}),e=g.filter(c.widgets,function(a){return!a.isPreconfiguredInTheme}),f=g.filter(c.groups,function(a){return!a.isPreconfiguredInTheme}),e=this._getPoolWidgetsWithoutDuplicated(e,
b.widgetOnScreen.widgets||[]);a.widgets=e.concat(h);a.groups=f.concat(d)},_getPoolWidgetsWithoutDuplicated:function(a,b){for(var c=e.clone(a),h=this.getAppConfig(),d=a.length-1;0<=d;d--)for(var g=b.length-1;0<=g;g--)if(b[g].uri){var k=b[g].name;k||(k=f.getWidgetNameFromUri(b[g].uri));var l=h.getConfigElementById(a[d].id);a[d]&&a[d].name===k&&!1===l.supportMultiInstance&&(console.log("Widget",a[d].name,"is not copied to new theme because this widget exists in new theme."),c.splice(d,1))}return c},
_onAppConfigSet:function(a){a=f.reCreateObject(a);window.appInfo.isRunInMobile=this._isRunInMobile();this.configLoader.processProxy(a);this.configLoader.addNeedValues(a);this._addDefaultValues(a);w.setPortalUrl(a.portalUrl);this.appConfig?(a.map.itemId&&a.map.itemId!==this.appConfig.map.itemId&&f.deleteMapOptions(a.map.mapOptions),this.appConfig=a,d.publish("appConfigChanged",this.getAppConfig(),"resetConfig",a)):(this.appConfig=a,x.getPortal(a.portalUrl).loadSelfInfo().then(e.hitch(this,function(a){this.portalSelf=
a;d.publish("appConfigLoaded",this.getAppConfig())})))},_addDefaultValues:function(a){this._addDefaultPortalUrl(a);this._addDefaultGeometryService(a);this._addDefaultStyle(a);this._addDefaultMap(a);this._addDefaultVisible(a);this._addDefaultSharedTheme(a);"undefined"===typeof a.widgetOnScreen&&(a.widgetOnScreen={});"undefined"===typeof a.widgetPool&&(a.widgetPool={});this._addDefaultPanelAndPosition(a);this._addDefaultOfWidgetGroup(a);(a.widgetPool.widgets&&0<a.widgetPool.widgets.length&&void 0===
a.widgetPool.widgets[0].index||a.widgetPool.groups&&0<a.widgetPool.groups.length&&void 0===a.widgetPool.groups[0].index)&&this._addIndexForWidgetPool(a);return a},_addDefaultPortalUrl:function(a){"undefined"===typeof a.portalUrl&&(a.portalUrl="http://www.arcgis.com/");a.portalUrl&&"/"!==a.portalUrl.substr(a.portalUrl.length-1)&&(a.portalUrl+="/")},_addDefaultGeometryService:function(a){var b=a&&a.geometryService,b=b&&"string"===typeof b&&e.trim(b)?e.trim(b):this.portalSelf.helperServices.geometry.url;
a.geometryService=b;y.geometryService=new z(a.geometryService);f.setGlobalGeometryService(a.geometryService)},_addDefaultStyle:function(a){!a.theme||a.theme.styles&&0!==a.theme.styles.length||(a.theme.styles=["default"])},_addDefaultMap:function(a){a.map.id="map";"undefined"===typeof a.map["3D"]&&"undefined"===typeof a.map["2D"]&&(a.map["2D"]=!0);"undefined"===typeof a.map.position&&(a.map.position={left:0,right:0,top:0,bottom:0});"undefined"===typeof a.map.portalUrl&&(a.map.portalUrl=a.portalUrl)},
_addDefaultVisible:function(a){f.visitElement(a,function(a){void 0===a.visible&&(a.visible=!0)})},_addDefaultSharedTheme:function(a){a.theme.sharedTheme?("undefined"===typeof a.theme.sharedTheme.useHeader&&(a.theme.sharedTheme.useHeader=!1),"undefined"===typeof a.theme.sharedTheme.useLogo&&(a.theme.sharedTheme.useLogo=!1)):a.theme.sharedTheme={useHeader:!1,useLogo:!1}},_addDefaultPanelAndPosition:function(a){this._addOnScreenDefaultPanelAndPosition(a);this._addPoolDefaultPanelAndPosition(a)},_addOnScreenDefaultPanelAndPosition:function(a){var b,
c;if(a=a.widgetOnScreen){b=a.panel&&a.panel.positionRelativeTo?a.panel.positionRelativeTo:"map";"undefined"===typeof a.panel||"undefined"===typeof a.panel.uri?a.panel={uri:"jimu/OnScreenWidgetPanel",position:{relativeTo:b}}:"undefined"===typeof a.panel.position?a.panel.position={relativeTo:b}:"undefined"===typeof a.panel.position.relativeTo&&(a.panel.position.relativeTo=b);if(a.widgets)for(b=0;b<a.widgets.length;b++)a.widgets[b].position||(a.widgets[b].position={}),a.widgets[b].position.relativeTo||
(a.widgets[b].position.relativeTo=a.widgets[b]&&a.widgets[b].positionRelativeTo?a.widgets[b].positionRelativeTo:"map"),!0!==a.widgets[b].inPanel||a.widgets[b].panel||(a.widgets[b].panel=e.clone(a.panel),a.widgets[b].panel.position=a.widgets[b].position,a.widgets[b].panel.position.relativeTo=a.widgets[b].position.relativeTo);if(a.groups)for(b=0;b<a.groups.length;b++)for(a.groups[b].panel||(a.groups[b].panel=a.panel),a.groups[b].panel&&!a.groups[b].panel.position&&(a.groups[b].panel.position={}),a.groups[b].panel.position.relativeTo||
(a.groups[b].panel.position.relativeTo=a.groups[b].panel.positionRelativeTo?a.groups[b].panel.positionRelativeTo:"map"),a.groups[b].widgets||(a.groups[b].widgets=[]),c=0;c<a.groups[b].widgets.length;c++)a.groups[b].widgets[c].panel=a.groups[b].panel}},_addPoolDefaultPanelAndPosition:function(a){var b,c,d=a.widgetPool;if(d){b=d.panel&&d.panel.positionRelativeTo?d.panel.positionRelativeTo:"map";"undefined"===typeof d.panel||"undefined"===typeof d.panel.uri?d.panel={uri:"jimu/OnScreenWidgetPanel",position:{relativeTo:b}}:
"undefined"===typeof d.panel.position?d.panel.position={relativeTo:b}:"undefined"===typeof d.panel.position.relativeTo&&(d.panel.position.relativeTo=b);if(d.groups)for(b=0;b<d.groups.length;b++)for(d.groups[b].panel?d.groups[b].panel.position.relativeTo||(d.groups[b].panel.position.relativeTo=d.groups[b].panel.positionRelativeTo?d.groups[b].panel.positionRelativeTo:"map"):d.groups[b].panel=d.panel,d.groups[b].widgets||(d.groups[b].widgets=[]),c=0;c<d.groups[b].widgets.length;c++)d.groups[b].widgets[c].panel=
d.groups[b].panel;if(d.widgets)for(b=0;b<d.widgets.length;b++)!1===d.widgets[b].inPanel?(c=d.widgets[b].positionRelativeTo?d.widgets[b].positionRelativeTo:"map",d.widgets[b].position)?d.widgets[b].position.relativeTo||(d.widgets[b].position.relativeTo=c):d.widgets[b].position={relativeTo:c}:d.widgets[b].panel||(d.widgets[b].panel=a.widgetPool.panel)}},_addDefaultOfWidgetGroup:function(a){f.visitElement(a,e.hitch(this,function(a,c){a.isOnScreen=c.isOnScreen;a.widgets?(a.gid=a.id,1===a.widgets.length?
(a.label||(a.label=a.widgets[0].label?a.widgets[0].label:"Group"),a.icon||(a.icon=a.widgets[0].uri?this._getDefaultIconFromUri(a.widgets[0].uri):"jimu.js/images/group_icon.png")):(a.icon=a.icon?a.icon:"jimu.js/images/group_icon.png",a.label=a.label?a.label:"Group_"+c.index)):(a.gid=c.groupId,a.uri&&f.processWidgetSetting(a))}))},_getDefaultIconFromUri:function(a){a=a.split("/");a.pop();return a.join("/")+"/images/icon.png"},_addIndexForWidgetPool:function(a){var b=0,c,d;if(a.widgetPool.widgets)for(c=
0;c<a.widgetPool.widgets.length;c++)a.widgetPool.widgets[c].index=b,b++;if(a.widgetPool.groups)for(c=0;c<a.widgetPool.groups.length;c++)for(a.widgetPool.groups[c].index=b,b++,d=0;d<a.widgetPool.groups[c].widgets.length;d++)a.widgetPool.groups[c].widgets[d].index=d}});m.getInstance=function(a){null===k?k=new m(a):a&&(k.urlParams=a);window.getAppConfig=e.hitch(k,k.getAppConfig);return k};return m});