// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("exports dojo/_base/lang dojo/_base/array dojo/_base/html dojo/has dojo/Deferred jimu/utils esri/tasks/QueryTask esri/tasks/support/Query".split(" "),function(e,u,m,t,r,q,l,v,w){e.exportCSV=function(c,d,b){return e._createCSVStr(d,b).then(function(a){return e._download(c+".csv",a)})};e.exportCSVFromFeatureLayer=function(c,d,b){b=b||{};return e._getExportData(d,{datas:b.datas,fromClient:b.fromClient,outFields:b.outFields,filterExpression:b.filterExpression}).then(function(a){return e._formattedData(d,
a,{formatNumber:b.formatNumber,formatDate:b.formatDate,formatCodedValue:b.formatCodedValue}).then(function(a){return e.exportCSV(c,a.datas,a.columns)})})};e.exportCSVByAttributes=function(c,d,b,a){a=u.mixin({},a);a.datas=b;return e.exportCSVFromFeatureLayer(c,d,a)};e.exportCSVByGraphics=function(c,d,b,a){b=m.map(b,function(a){return a.attributes});return e.exportCSVByAttributes(c,d,b,a)};e._createCSVStr=function(c,d){var b=new q,a="",e=0,f=0,g="",h="";try{m.forEach(d,function(b){a=a+g+b;g=","});for(var a=
a+"\r\n",e=c.length,f=d.length,p=0;p<e;p++){for(var g="",n=0;n<f;n++)(h=c[p][d[n]])||"number"===typeof h||(h=""),h&&/[",\r\n]/g.test(h)&&(h='"'+h.replace(/(")/g,'""')+'"'),a=a+g+h,g=",";a+="\r\n"}b.resolve(a)}catch(x){console.error(x),b.resolve("")}return b};e._isIE11=function(){return 11===l.has("ie")};e._isEdge=function(){return l.has("edge")};e._getDownloadUrl=function(c){return window.Blob&&window.URL&&window.URL.createObjectURL?(c=new Blob(["\ufeff"+c],{type:"text/csv"}),URL.createObjectURL(c)):
"data:attachment/csv;charset\x3dutf-8,\ufeff"+encodeURIComponent(c)};e._download=function(c,d){var b=new q;try{if(r("ie")&&10>r("ie")){var a=window.top.open("about:blank","_blank");a.document.write("sep\x3d,\r\n"+d);a.document.close();a.document.execCommand("SaveAs",!0,c);a.close()}else if(10===r("ie")||e._isIE11()||e._isEdge()){var k=new Blob(["\ufeff"+d],{type:"text/csv"});navigator.msSaveBlob(k,c)}else{var f=t.create("a",{href:e._getDownloadUrl(d),target:"_blank",download:c},document.body);if(r("safari")){var g=
document.createEvent("MouseEvents");g.initEvent("click",!0,!0);f.dispatchEvent(g)}else f.click();t.destroy(f)}b.resolve()}catch(h){b.reject(h)}return b};e._getExportData=function(c,d){var b=new q,a=null,k=d.datas,a=d.outFields;a&&a.length||(a=c.fields);k&&0<k.length?b.resolve({data:k||[],outFields:a}):d.fromClient?(k=m.map(c.graphics,function(a){return a.attributes}),b.resolve({data:k||[],outFields:a})):e._getExportDataFromServer(c,a,d).then(function(c){b.resolve({data:c||[],outFields:a})});return b};
e._getExportDataFromServer=function(c,d,b){var a=new q;if("esri.layers.FeatureLayer"!==c.declaredClass)return a.resolve([]),a;var e=new v(c.url),f=new w;f.where=b.filterExpression||c.getDefinitionExpression&&c.getDefinitionExpression()||"1\x3d1";0<d.length?(c=m.map(d,function(a){return a.name}),f.outFields=c):f.outFields=["*"];f.returnGeometry=!1;e.execute(f,function(b){b=m.map(b.features,function(a){return a.attributes});a.resolve(b)},function(b){console.error(b);a.resolve([])});return a};e._formattedData=
function(c,d,b){var a=new q,k=[],f=d.data;d=d.outFields;for(var g=0,h=f.length;g<h;g++){for(var p={},n=0;n<d.length;n++){var l=d[n];p[l.alias||l.name]=e._getExportValue(f[g][l.name],l,c.objectIdField,c.typeIdField,f[g][c.typeIdField],c.types,b)}k.push(p)}c=m.map(d,function(a){return a.alias||a.name});a.resolve({datas:k,columns:c});return a};e._getExportValue=function(c,d,b,a,e,f,g){var h=!!d.domain&&g.formatCodedValue;g="esriFieldTypeDate"===d.type&&g.formatDate;var k=b&&d.name===b;a=a&&d.name===
a;return g?l.fieldFormatter.getFormattedDate(c):a?l.fieldFormatter.getTypeName(c,f):h?l.fieldFormatter.getCodedValue(d.domain,c):h||g||k||a?c:(h=null,b&&f&&0<f.length&&(b=(b=m.filter(f,function(a){return a.id===e}))&&b[0])&&b.domains&&b.domains[d.name]&&b.domains[d.name].codedValues&&(h=l.fieldFormatter.getFormattedCodedValue(b.domains[d.name],c)),null!==h?h:c)}});