// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/json dojo/Deferred esri/tasks/support/Query esri/tasks/QueryTask ./jsonConverters".split(" "),function(g,c,k,n,h,p,q,v){function r(a,b){var d="",t=b.length,e=a.length,c="",f="",h;try{k.forEach(a,function(a){d="string"===typeof a?d+c+a:d+c+(a.alias||a.name);c=","});for(var d=d+"\r\n",g=0;g<t;g++){c="";h=b[g];for(var l=0;l<e;l++){var m=a[l];(f=h["string"===typeof m?m:m.name])||"number"===typeof f||(f="");f&&/[",\r\n]/g.test(f)&&(f='"'+
f.replace(/(")/g,'""')+'"');d=d+c+f;c=","}d+="\r\n"}return d}catch(y){return""}}var e={createDataSource:function(a){return a.type===e.TYPE_TABLE?new w(a):a.type===e.TYPE_FEATURESET?new x(a):null},TYPE_TABLE:"table",TYPE_FEATURESET:"FeatureSet",FORMAT_CSV:"CSV",FORMAT_FEATURESET:"FeatureSet",FORMAT_GEOJSON:"GeoJSON"},u=g(null,{filename:void 0,suffix:".txt",format:void 0,nls:void 0,constructor:function(){this.nls=window.jimuNls.exportTo},getExportString:function(){},getSupportExportFormats:function(){},
setFormat:function(a){this.format=a},download:function(){this.getExportString().then(c.hitch(this,function(a){var b=this.filename+this.suffix,d;try{d=!!new Blob}catch(t){d=!1}d?(a=new Blob([a],{type:"text/plain;charset\x3dutf-8"}),saveAs(a,b)):saveTextAs(a,b,"utf-8")}))},exportToPortal:function(a,b){}}),x=g(u,{featureSet:null,constructor:function(a){this.inherited(arguments);this.featureSet=a.data;this.url=a.url;this.filename=a.filename},getExportString:function(){if(this.format===e.FORMAT_CSV)return this.suffix=
".csv",this._getAsCSVString();if(this.format===e.FORMAT_FEATURESET)return this.suffix=".json",this._getAsFeatureSetString();if(this.format===e.FORMAT_GEOJSON)return this.suffix=".geojson",this._getAsGeoJsonString();var a=new h;a.resolve("");return a},getSupportExportFormats:function(){return[{value:e.FORMAT_CSV,label:this.nls.toCSV},{value:e.FORMAT_FEATURESET,label:this.nls.toFeatureCollection},{value:e.FORMAT_GEOJSON,label:this.nls.toGeoJSON}]},_getFeatureSet:function(){var a=new h;if(this.featureSet)a.resolve(this.featureSet);
else if(this.url){var b=new p;b.returnGeometry=!0;b.outFields=["*"];this.queryTask=new q(this.url);this.queryTask.execute(b,c.hitch(this,function(b){a.resolve(b)}),c.hitch(this,function(){a.resolve(null)}))}else a.resolve(null);return a},_getAsFeatureSetString:function(){return this._getFeatureSet().then(c.hitch(this,function(a){var b="";a&&(a=a.toJson())&&(b=n.stringify(a));return b}))},_getAsGeoJsonString:function(){return this._getFeatureSet().then(c.hitch(this,function(a){var b="";a&&(a=(new v.esriConverter).toGeoJson(a))&&
(b=n.stringify(a));return b}))},_getAsCSVString:function(){return this._getFeatureSet().then(c.hitch(this,function(a){var b="";a&&(b=this._createCSVFromFeatureSet(a));return b}))},_createCSVFromFeatureSet:function(a){var b=a.features,d=[],c;if(a.fieldAliases)for(c in a.fieldAliases)a.fieldAliases.hasOwnProperty(c)&&d.push({name:c,alias:a.fieldAliases[c]});else for(c in b=b[0].attributes,b)b.hasOwnProperty(c)&&d.push({name:c});a=k.map(a.features,function(a){return a.attributes});return r(d,a)}}),w=
g(u,{table:null,constructor:function(a){this.inherited(arguments);this.table=a.data;this.url=a.url;this.filename=a.filename},getExportString:function(){if(this.format===e.FORMAT_CSV)return this.suffix=".csv",this._getAsCSVString();var a=new h;a.resolve("");return a},getSupportExportFormats:function(){return[{value:e.FORMAT_CSV,label:this.nls.toCSV}]},_getTableData:function(){var a=new h;if(this.table)a.resolve(this.table);else if(this.url){var b=new p;b.outFields=["*"];this.queryTask=new q(this.url);
this.queryTask.execute(b,c.hitch(this,function(b){var c={};c.fields=b.fields;c.datas=k.map(b.features,function(a){return a.attributes});a.resolve(c)}),c.hitch(this,function(){a.resolve(null)}))}else a.resolve(null);return a},_getAsCSVString:function(){return this._getTableData().then(c.hitch(this,function(a){var b="";a&&(b="\ufeff"+r(a.fields,a.datas));return b}))}});return e});