// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
(function(){function p(h){var k=0,a=0,d=h.length,b=h[a],c;for(a;a<d-1;a++)c=h[a+1],k+=(c[0]-b[0])*(c[1]+b[1]),b=c;return 0<=k}function q(){function h(a){var d,b,c;if(a){if((a.x&&"NaN"!==a.x||0===a.x)&&(a.y&&"NaN"!==a.y||0===a.y))c="Point",b=[a.x,a.y];else if(a.points&&a.points.length)c="MultiPoint",b=a.points;else if(a.paths&&a.paths.length)a=a.paths,1===a.length?(c="LineString",b=a[0]):(c="MultiLineString",b=a);else if(a.rings&&a.rings.length){c=[];a=a.rings;for(d=0;d<a.length;d++)b=a[d],p(b)?c.push([b]):
0<c.length&&c[c.length-1].push(b);1<c.length?(b=c,c="MultiPolygon"):(b=c.pop(),c="Polygon")}d=b&&c?{type:c,coordinates:b}:null}return d}function k(a){var d=null,b,c;if(a&&(d={type:"Feature"},a.geometry&&(d.geometry=h(a.geometry)),a.attributes)){c={};for(b in a.attributes)c[b]=a.attributes[b];d.properties=c}return d}return{toGeoJson:function(a){var d,b,c;if(a)if(a.features)for(d={type:"FeatureCollection",features:[]},b=a.features,a=0;a<b.length;a++)(c=k(b[a]))&&d.features.push(c);else d=a.geometry?
k(a):h(a);return d}}}function r(){function h(b){var c,a;if("Point"===b)c="esriGeometryPoint";else if("MultiPoint"===b)c="esriGeometryMultipoint",a="points";else if("LineString"===b||"MultiLineString"===b)c="esriGeometryPolyline",a="paths";else if("Polygon"===b||"MultiPolygon"===b)c="esriGeometryPolygon",a="rings";return{type:c,geomHolder:a}}function k(b){var c,a,d=[],e;c=0;for(a=b.length;c<a;c++)e=b[c],0===c!==p(e)&&(e=e.reverse()),d.push(e);return d}function a(b){var a,d,f,e,g;if("GeometryCollection"===
b.type)for(d=[b.geometries.shift()],a=h(d[0].type),f=0;f<b.geometries.length;f++){e=a.type;g=b.geometries[f].type;var l=!1;"esriGeometryPoint"!==e&&"esriGeometryMultipoint"!==e||"Point"!==g&&"MultiPoint"!==g?"esriGeometryPolyline"!==e||"LineString"!==g&&"MultiLineString"!==g?"esriGeometryPolygon"!==e||"Polygon"!==g&&"MultiPolygon"!==g||(l=!0):l=!0:l=!0;l&&d.push(b.geometries[f])}else a=h(b.type),d=[b];"esriGeometryPoint"===a.type&&1<d.length&&(a=h("MultiPoint"));b={spatialReference:{wkid:4326}};if("esriGeometryPoint"===
a.type)0===d[0].coordinates.length?(b.x=null,b.y=null):(b.x=d[0].coordinates[0],b.y=d[0].coordinates[1]);else for(b[a.geomHolder]=[],f=0;f<d.length;f++){e=d[f];var m=l=g=void 0;if("MultiPoint"===e.type||"MultiLineString"===e.type)m=e.coordinates;else if("Point"===e.type||"LineString"===e.type)m=[e.coordinates];else if("Polygon"===e.type)m=k(e.coordinates);else if("MultiPolygon"===e.type)for(m=[],g=0,l=e.coordinates.length;g<l;g++)m.push(k(e.coordinates[g])[0]);g=m;for(e=0;e<g.length;e++)b[a.geomHolder].push(g[e])}return b}
function d(b){var c,d,f;if(b&&(c={},b.geometry&&(c.geometry=a(b.geometry)),b.properties)){f={};for(d in b.properties)f[d]=b.properties[d];c.attributes=f}return c}return{toEsri:function(b){var c,h,f;if(b)if("FeatureCollection"===b.type)for(c={features:[]},h=b.features,b=0;b<h.length;b++)(f=d(h[b]))&&c.features.push(f);else c="Feature"===b.type?d(b):a(b);return c}}}var n;n="undefined"!==typeof exports&&null!==exports?exports:this;if("function"===typeof define){var t={esriConverter:q,geoJsonConverter:r};
define([],function(){return t})}else n.esriConverter=q,n.geoJsonConverter=r}).call(this);