// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dijit/_WidgetBase dojo/topic dojo/on dojo/query dojo/Deferred dojo/promise/all dojo/debounce require ./MapManager ./utils".split(" "),function(p,d,c,q,e,r,t,l,m,u,k,v,n){var g=null,h;h=p([q],{constructor:function(a,b){this.own(e.subscribe("appConfigLoaded",d.hitch(this,this._onAppConfigLoaded)));this.own(e.subscribe("appConfigChanged",d.hitch(this,this._onAppConfigChanged)));this.own(e.subscribe("sceneViewLoaded",d.hitch(this,this._onSceneViewLoaded)));
this.own(e.subscribe("sceneViewChanged",d.hitch(this,this._onSceneViewChanged)));this.own(e.subscribe("beforeSceneViewDestory",d.hitch(this,this._onBeforeSceneViewDestroy)));this.own(e.subscribe("builder/actionTriggered",d.hitch(this,this._onActionTriggered)));this.own(e.subscribe("openWidget",d.hitch(this,this._onOpenWidgetRequest)));this.own(r(window,"resize",u(d.hitch(this,this.resize),200)));this.id=b},postCreate:function(){this.containerNode=this.domNode},sceneView:null,mapId:"map",mapDiv:null,
layoutManager:null,animTime:500,resize:function(){this.layoutManager&&this.layoutManager.resize()},_onAppConfigLoaded:function(a){this.appConfig=d.clone(a);this._loadLayoutManager(this.appConfig).then(d.hitch(this,function(a){this.layoutManager=a;this.layoutManager.onEnter(this.appConfig,this.mapId).then(d.hitch(this,function(){this.mapDiv=this.layoutManager.getMapDiv();this._loadMap(this.mapId);this.appConfig.theme&&this._loadTheme(this.appConfig.theme)}))}))},_loadLayoutManager:function(a){a=a.layoutDefinition?
a.layoutDefinition.manager:"jimu/layoutManagers/AbsolutePositionLayoutManager";var b=new l;k([a],d.hitch(this,function(a){a=a.getInstance();this.sceneView&&a.setSceneView(this.sceneView);b.resolve(a)}));return b},_loadMap:function(){this.mapManager=v.getInstance({appConfig:this.appConfig,urlParams:this.urlParams},this.mapId);this.mapManager.showMap()},_onSceneViewLoaded:function(a){this.sceneView=a;this.layoutManager.setSceneView(a);this.layoutManager.loadAndLayout(this.appConfig)},_loadTheme:function(a){var b=
new l;k(["themes/"+a.name+"/main"],d.hitch(this,function(){m([this._loadThemeCommonStyle(a),this._loadThemeCurrentStyle(a)]).then(d.hitch(this,function(){this._addCustomStyle(a);this.layoutManager.onThemeLoad();b.resolve()}))}));return b},_loadThemeCommonStyle:function(a){c.addClass(this.domNode,a.name);return n.loadStyleLink(this._getThemeCommonStyleId(a),"themes/"+a.name+"/common.css")},_loadThemeCurrentStyle:function(a){c.addClass(this.domNode,a.styles[0]);return n.loadStyleLink(this._getThemeCurrentStyleId(a),
"themes/"+a.name+"/styles/"+a.styles[0]+"/style.css")},_addCustomStyle:function(a){var b=d.getObject("customStyles",!1,a);if(b){var f=".jimu-main-background{background-color: ${mainBackgroundColor} !important;}";(a=this._getFixedThemeStyles(a))&&(f+=a);f=d.replace(f,b,/\$\{([^\}]+)\}/g);b=c.create("style",{type:"text/css"});try{b.appendChild(document.createTextNode(f))}catch(w){b.styleSheet.cssText=f}b.setAttribute("source","custom");document.head.appendChild(b)}},_getFixedThemeStyles:function(a){var b=
".esriPopup .titlePane {background-color: ${mainBackgroundColor} !important;}";"PlateauTheme"===a.name?b+=".jimu-widget-header-controller .jimu-title, .jimu-widget-header-controller .jimu-subtitle{color: ${mainBackgroundColor} !important;}.jimu-widget-header-controller .links .jimu-link{color: ${mainBackgroundColor} !important;}.jimu-widget-homebutton .HomeButton .home, .jimu-widget-mylocation, .jimu-widget-mylocation .place-holder, .jimu-widget-zoomslider.vertical .zoom-in, .jimu-widget-zoomslider.vertical .zoom-out, .jimu-widget-extent-navigate.vertical .operation{background-color: ${mainBackgroundColor} !important;}.jimu-preload-widget-icon-panel \x3e .jimu-panel-title, .jimu-foldable-panel \x3e .jimu-panel-title, .jimu-title-panel \x3e .title{color: ${mainBackgroundColor} !important;}.jimu-panel{border-color: ${mainBackgroundColor} !important;}.jimu-widget-header-controller{border-bottom-color: ${mainBackgroundColor} !important;}.jimu-tab\x3e.control\x3e.tab{color: ${mainBackgroundColor} !important; border-color: ${mainBackgroundColor} !important}":
"BillboardTheme"===a.name?b+=".jimu-widget-homebutton .HomeButton .home, .jimu-widget-mylocation, .jimu-widget-mylocation .place-holder, .jimu-widget-zoomslider.vertical .zoom-in, .jimu-widget-zoomslider.vertical .zoom-out, .jimu-widget-extent-navigate .operation, .jimu-widget-navigate, .jimu-widget-home, .jimu-widget-zoom .esri-zoom .esri-widget, .jimu-widget-placeholder{background-color: ${mainBackgroundColor} !important;}.jimu-widget-onscreen-icon{background-color: ${mainBackgroundColor} !important;}":
"BoxTheme"===a.name?b+=".jimu-widget-homebutton .HomeButton .home, .jimu-widget-mylocation, .jimu-widget-mylocation .place-holder, .jimu-widget-zoomslider.vertical .zoom-in, .jimu-widget-zoomslider.vertical .zoom-out, .jimu-widget-extent-navigate, .jimu-widget-navigate, .jimu-widget-home, .jimu-widget-zoom .esri-zoom .esri-widget, .jimu-widget-placeholder{background-color: ${mainBackgroundColor} !important;}":"TabTheme"===a.name?b+=".tab-widget-frame .title-label{color: ${mainBackgroundColor} !important;}":
"DashboardTheme"===a.name?b+=".jimu-widget-dnd-header{background-color: ${mainBackgroundColor} !important;}":"DartTheme"===a.name&&(b+=".jimu-widget-fullScreen .fullScreen{background-color: ${mainBackgroundColor} !important;}");return b},_onAppConfigChanged:function(a,b,c){a=d.clone(a);switch(b){case "themeChange":this._onThemeChange(a);break;case "styleChange":this._onStyleChange(a);break;case "layoutChange":this._onLayoutChange(a);break;case "widgetChange":this._onWidgetChange(a,c);break;case "groupChange":this._onGroupChange(a,
c);break;case "widgetPoolChange":this._onWidgetPoolChange(a,c);break;case "resetConfig":this._onResetConfig(a);break;case "loadingPageChange":this._onLoadingPageChange(a,c);break;case "layoutDefinitionChange":this._onLayoutDefinitionChange(a,c);break;case "onScreenGroupsChange":this._onOnScreenGroupsChange(a,c);break;case "onScreenOrderChange":this._onOnScreenOrderChange(a,c)}this.appConfig=a},_onSceneViewChanged:function(a){this.sceneView=a;this.layoutManager.setSceneView(a);this.layoutManager.loadAndLayout(this.appConfig)},
_onBeforeSceneViewDestroy:function(){this.layoutManager.destroyOnScreenWidgetsAndGroups()},_onActionTriggered:function(a){this.layoutManager.onActionTriggered(a)},_onWidgetChange:function(a,b){this.layoutManager.onWidgetChange(a,b)},_onGroupChange:function(a,b){this.layoutManager.onGroupChange(a,b)},_onWidgetPoolChange:function(a,b){this.layoutManager.onWidgetPoolChange(a,b)},_onLayoutDefinitionChange:function(a,b){this.layoutManager.onLayoutDefinitionChange(a,b)},_onOnScreenGroupsChange:function(a,
b){this.layoutManager.onOnScreenGroupsChange(a,b)},_onOnScreenOrderChange:function(a,b){this.layoutManager.onOnScreenOrderChange(a,b)},_onThemeChange:function(a){this.layoutManager.destroyOnScreenWidgetsAndGroups();this._removeThemeCommonStyle(this.appConfig.theme);this._removeThemeCurrentStyle(this.appConfig.theme);this._removeCustomStyle();m([this._loadLayoutManager(a),this._loadTheme(a.theme)]).then(d.hitch(this,function(b){var c=b[0];this.layoutManager.name!==c.name?(this.layoutManager.onLeave(),
c.onEnter(a,this.mapId).then(d.hitch(this,function(){this.layoutManager=c;this.layoutManager.loadAndLayout(a)}))):this.layoutManager.loadAndLayout(a)}))},_onResetConfig:function(a){var b=this.appConfig;e.publish("appConfigChanged",a,"mapChange",a);this.appConfig=b;this._loadLayoutManager(a).then(d.hitch(this,function(a){this.layoutManager=a;this._removeThemeCommonStyle(this.appConfig.theme);this._removeThemeCurrentStyle(this.appConfig.theme);this._removeCustomStyle();this._loadTheme(this.appConfig.theme)}))},
_onLoadingPageChange:function(a,b){"backgroundColor"in b?c.setStyle(jimuConfig.loadingId,"background-color",a.loadingPage.backgroundColor):"backgroundImage"in b?(a=a.loadingPage.backgroundImage,a.visible&&a.uri?(c.setStyle(jimuConfig.loadingImageId,"background-image","url('"+a.uri+"')"),c.setStyle(jimuConfig.loadingImageId,"width",a.width+"px"),c.setStyle(jimuConfig.loadingImageId,"height",a.height+"px")):(c.setStyle(jimuConfig.loadingImageId,"background-image","url('')"),c.setStyle(jimuConfig.loadingImageId,
"width","0px"),c.setStyle(jimuConfig.loadingImageId,"height","0px"))):"loadingGif"in b&&(a=a.loadingPage.loadingGif,a.visible&&a.uri?(c.setStyle(jimuConfig.loadingGifId,"background-image","url('"+a.uri+"')"),c.setStyle(jimuConfig.loadingGifId,"width",a.width+"px"),c.setStyle(jimuConfig.loadingGifId,"height",a.height+"px")):(c.setStyle(jimuConfig.loadingGifId,"background-image","url('')"),c.setStyle(jimuConfig.loadingGifId,"width","0px"),c.setStyle(jimuConfig.loadingGifId,"height","0px")))},_onStyleChange:function(a){this._removeThemeCurrentStyle(this.appConfig.theme);
this._loadThemeCurrentStyle(a.theme);this._removeCustomStyle();this._addCustomStyle(a.theme)},_onLayoutChange:function(a){this.layoutManager.onLayoutChange(a)},_removeThemeCommonStyle:function(a){c.removeClass(this.domNode,a.name);c.destroy(this._getThemeCommonStyleId(a))},_removeThemeCurrentStyle:function(a){c.removeClass(this.domNode,a.styles[0]);c.destroy(this._getThemeCurrentStyleId(a))},_removeCustomStyle:function(){t('style[source\x3d"custom"]',document.head).forEach(function(a){c.destroy(a)})},
_getThemeCommonStyleId:function(a){return"theme_"+a.name+"_style_common"},_getThemeCurrentStyleId:function(a){return"theme_"+a.name+"_style_"+a.styles[0]},_doPostLoad:function(){k(["dynamic-modules/postload"])},_onOpenWidgetRequest:function(a){this.layoutManager.openWidget(a)}});h.getInstance=function(a,b){null===g&&(g=new h(a,b),window._layoutManager=g);return g};return h});