// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/topic dojo/on dojo/keys esri/geometry/Extent esri/geometry/Point ./utils ./dijit/LoadingShelter ./AppStateManager ./WebSceneLoader esri/Viewpoint".split(" "),function(p,d,f,l,e,m,q,r,t,n,u,v,w,g){var h=null,k=p(null,{appConfig:null,mapDivId:"",map:null,previousInfoWindow:null,mobileInfoWindow:null,isMobileInfoWindow:!1,layerInfosObj:null,constructor:function(a,b){this.appConfig=a.appConfig;this.urlParams=a.urlParams;
this.id=this.mapDivId=b;this.appStateManager=v.getInstance(this.urlParams);e.subscribe("appConfigChanged",d.hitch(this,this.onAppConfigChanged));e.subscribe("changeMapPosition",d.hitch(this,this.onChangeMapPosition));e.subscribe("syncViewpoint",d.hitch(this,this.onSyncViewpoint));m(window,"resize",d.hitch(this,this.onWindowResize));m(window,"beforeunload",d.hitch(this,this.onBeforeUnload))},showMap:function(){this._showMap(this.appConfig)},_showMap:function(a){console.time("Load Map");this.loading=
new u;this.loading.placeAt(this.mapDivId);this.loading.startup();a.map["3D"]?a.map.itemId?this._show3DWebScene(a):console.log("No webscene found. Please set map.itemId in config.json."):a.map.itemId?this._show2DWebMap(a):console.log("No webmap found. Please set map.itemId in config.json.")},onBeforeUnload:function(){this.appStateManager.saveWabAppState(this.map,this.layerInfosObj)},onWindowResize:function(){this.map&&this.map.resize&&(this.map.resize(),this.resetInfoWindow(!1))},getMapInfoWindow:function(){return{mobile:this._mapMobileInfoWindow,
bigScreen:this._mapInfoWindow}},resetInfoWindow:function(a){a&&(this._mapInfoWindow=this.map.infoWindow,this._mapMobileInfoWindow&&this._mapMobileInfoWindow.destroy(),this.isMobileInfoWindow=!1);window.appInfo.isRunInMobile&&!this.isMobileInfoWindow?this.isMobileInfoWindow=!0:!window.appInfo.isRunInMobile&&this.isMobileInfoWindow&&(this.isMobileInfoWindow=!1)},onChangeMapPosition:function(a){var b=d.clone(this.mapPosition);d.mixin(b,a);this.setMapPosition(b)},setMapPosition:function(a){this.mapPosition=
a;a=n.getPositionStyle(a);l.setStyle(this.mapDivId,a);this.map&&this.map.resize&&this.map.resize()},getMapPosition:function(){return this.mapPosition},onSyncViewpoint:function(a){this.sceneView&&(this.sceneView.viewpoint=a.clone())},_visitConfigMapLayers:function(a,b){f.forEach(a.map.basemaps,function(a,c){a.isOperationalLayer=!1;b(a,c)},this);f.forEach(a.map.operationallayers,function(a,c){a.isOperationalLayer=!0;b(a,c)},this)},_destroySceneView:function(){if(this.sceneView)try{this.sceneView.destroy()}catch(a){console.error(a)}this.sceneView=
null;window._sceneView=null},_show3DWebScene:function(a){var b=a.map.portalUrl,x=a.map.itemId;this._destroySceneView();w.createMap(this.mapDivId,b,x).then(d.hitch(this,function(c){this._publishSceneViewEvent(c);if(a.map.mapOptions)if((c=a.map.mapOptions.initialState)&&c.viewpoint)try{var b=g.fromJSON(c.viewpoint);b&&(this.sceneView.map.initialViewProperties.viewpoint=b,this.sceneView.viewpoint=b.clone())}catch(y){console.error(y)}else this.sceneView.map.initialViewProperties.viewpoint=this.sceneView.viewpoint}),
d.hitch(this,function(){this.loading&&this.loading.destroy();e.publish("mapCreatedFailed")}))},_publishSceneViewEvent:function(a){window._sceneView=a;console.timeEnd("Load Map");this.loading&&this.loading.destroy();this.sceneView?(this.sceneView=a,console.log("sceneView changed"),e.publish("sceneViewChanged",this.sceneView)):(this.sceneView=a,console.log("sceneView loaded"),e.publish("sceneViewLoaded",this.sceneView))},_show2DWebMap:function(a){a.map.mapOptions||(a.map.mapOptions={});var b=this._processMapOptions(a.map.mapOptions)||
{};b.isZoomSlider=!1;n.createWebMap(a.map.portalUrl,a.map.itemId,this.mapDivId,{mapOptions:b,bingMapsKey:a.bingMapsKey,usePopupManager:!0}).then(d.hitch(this,function(b){var c=b.map;c.hideZoomSlider();c.infoWindow.resize(270,316);c.itemId=a.map.itemId;c.itemInfo=b.itemInfo;c.webMapResponse=b;c.enableSnapping({snapKey:q.copyKey});l.setStyle(c.root,"zIndex",0);c._initialExtent=c.extent;f.forEach("extent center marker find query scale level".split(" "),function(a){},this);this._publishMapEvent(c)}),
d.hitch(this,function(){this.loading&&this.loading.destroy();e.publish("mapCreatedFailed")}))},_processMapOptions:function(a){if(a)return a.lods||delete a.lods,a.lods&&0===a.lods.length&&delete a.lods,a=d.clone(a),a.extent&&(a.extent=new r(a.extent)),a.center&&!d.isArrayLike(a.center)&&(a.center=new t(a.center)),a},onAppConfigChanged:function(a,b,d){this.appConfig=a;"mapChange"===b?this._recreateMap(a):"mapOptionsChange"===b&&d.initialState&&(a=d.initialState.viewpoint)&&(this.sceneView.map.initialViewProperties.viewpoint=
g.fromJSON(a),this.sceneView.animateTo(g.fromJSON(a)))},_recreateMap:function(a){this.sceneView&&(e.publish("beforeSceneViewDestory",this.sceneView),this._destroySceneView());this._showMap(a)},disableWebMapPopup:function(){},enableWebMapPopup:function(){}});k.getInstance=function(a,b){null===h&&(h=new k(a,b));return h};return k});