// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dijit/_WidgetBase ./utils".split(" "),function(h,b,k,c,e,l,m){return h(l,{"class":"jimu-widget-onscreen-icon",postCreate:function(){this.inherited(arguments);this.iconNode=c.create("img",{src:this.widgetConfig.icon},this.domNode);window.isRTL&&this.widgetConfig.mirrorIconForRTL&&c.addClass(this.iconNode,"jimu-flipx");c.setAttr(this.domNode,"title",this.widgetConfig.label);this.own(e(this.domNode,"click",b.hitch(this,
function(){this.onClick()})));this.position=b.clone(this.widgetConfig.position);"map"===this.widgetConfig.position.relativeTo&&this.own(e(this.sceneView,"resize",b.hitch(this,function(){var a=b.clone(this.position);delete a.width;delete a.height;this.panel&&this.panel.setPosition(a)})));this.state="closed"},startup:function(){this.inherited(arguments)},onClick:function(){"closed"===this.state?this.switchToOpen():this.switchToClose()},moveTo:function(a){var f={left:"auto",right:"auto",bottom:"auto",
top:"auto",width:"auto",height:"auto"},f=b.mixin(f,m.getPositionStyle(a));delete f.width;delete f.height;c.setStyle(this.domNode,f);this.position=b.clone(a);this.widgetConfig&&this.widgetConfig.panel&&(this.widgetConfig.panel.position=b.clone(a),this.widgetConfig.position=b.clone(a));this.panel&&this.panel.setPosition(b.clone(a));this.widget&&this.widget.setPosition(this.getOffPanelWidgetPosition(this.widget))},destroy:function(){this.panel?this.panelManager.destroyPanel(this.panel):this.widget&&
this.widgetManager.destroyWidget(this.widget);this.inherited(arguments)},switchToOpen:function(){this.state="opened";this.panelManager.closeAllPanelsInGroup(this.widgetConfig.gid);k.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(a){a.closeable&&this.widgetManager.closeWidget(a)},this);c.addClass(this.domNode,"jimu-state-selected");this._showLoading();!1===this.widgetConfig.inPanel?this.widgetManager.loadWidget(this.widgetConfig).then(b.hitch(this,function(a){this.widget=a;a.setPosition(this.getOffPanelWidgetPosition(a));
this.widgetManager.openWidget(a);this.own(e(a,"close",b.hitch(this,function(){this.switchToClose()})));this._hideLoading()})):this.panelManager.showPanel(b.clone(this.widgetConfig)).then(b.hitch(this,function(a){this.panel=a;this.own(e(a,"close",b.hitch(this,function(){this.switchToClose()})));this._hideLoading()}))},switchToClose:function(){this.state="closed";c.removeClass(this.domNode,"jimu-state-selected");!1===this.widgetConfig.inPanel?this.widgetManager.closeWidget(this.widget):this.panelManager.closePanel(this.panel)},
getOffPanelWidgetPosition:function(a){var b={relativeTo:a.position.relativeTo},d=c.getMarginBox(this.domNode);a=this.widgetManager.getWidgetMarginBox(a);var e=c.getMarginBox("map"===b.relativeTo?this.sceneView.map.id:jimuConfig.layoutId),g=d.t+d.h+1;g+a.h>e.h?b.bottom=e.h-d.t+1:b.top=g;window.isRTL?b.right=0>d.l+d.w-a.w?0:d.l+d.w-a.w:d.l+a.w>e.w?b.right=0:b.left=d.l;return b},_showLoading:function(){c.setAttr(this.iconNode,"src",require.toUrl("jimu")+"/images/loading_circle.gif")},_hideLoading:function(){c.setAttr(this.iconNode,
"src",this.widgetConfig.icon)}})});