// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/_base/fx dojo/Deferred dojo/promise/all dojo/on dojo/topic dojo/when require ./utils ./WidgetManager".split(" "),function(u,f,m,c,p,e,v,n,q,h,r,w,x){var k,l=null;k=u(null,{constructor:function(){this.panels=[];this.widgetManager=x.getInstance();n(window,"resize",f.hitch(this,this.onWindowResize));this.activePanel=null;q.subscribe("/dnd/move/start",f.hitch(this,this._onMoveStart));q.subscribe("widgetActived",f.hitch(this,
this._onWidgetActived))},showPanel:function(a){var b=new e,d=this.getPanelById(a.id+"_panel");d?("closed"===d.state&&this.openPanel(d),b.resolve(d)):v({Panel:this._loadPanelClass(a.panel.uri),nls:this._loadThemeI18N(a.panel.uri)}).then(f.hitch(this,function(d){var c=a.id+"_panel",g=this.getPanelById(c),e={label:a.label,config:a,uri:a.panel.uri,position:a.panel.position,sceneView:this.sceneView,widgetManager:this.widgetManager,panelManager:this,id:c,gid:a.gid,nls:d.nls};f.mixin(e,a.panel.options);
try{g=new d.Panel(e),console.log("panel ["+c+"] created.")}catch(t){console.log("create panel error: "+t+", panelId: "+c);b.reject(t);return}g.setPosition(a.panel.position);w.setVerticalCenter(g.domNode);this.openPanel(g);this.panels.push(g);n(g.domNode,"click",f.hitch(this,this._onPanelClick,g));b.resolve(g)}));return b},setSceneView:function(a){this.sceneView=a;n(this.sceneView,"resize",f.hitch(this,this.onMapResize))},closeOtherPanelsInTheSameGroup:function(a){if("string"===typeof a&&(a=this.getPanelById(a),
!a))return;for(var b=0;b<this.panels.length;b++)this.panels[b].gid===a.gid&&this.panels[b].id!==a.id&&this.closePanel(this.panels[b])},closeAllPanelsInGroup:function(a){for(var b=0;b<this.panels.length;b++)this.panels[b].gid===a&&this.closePanel(this.panels[b])},openPanel:function(a){var b=new e;if("string"===typeof a&&(a=this.getPanelById(a),!a))return b.reject(),b;if(!a.started)try{a.started=!0,a.startup()}catch(d){console.error("fail to startup panel "+a.id+". "+d.stack)}if("opened"===a.state)return b.resolve(a),
b;a.setState("opened");return this.playOpenPanelAnimation(a).then(f.hitch(this,function(){c.setStyle(a.domNode,"display","");a.onOpen();this._activePanel(a);return a}))},closePanel:function(a){var b=new e;return"string"===typeof a&&(a=this.getPanelById(a),!a)||"closed"===a.state?(b.resolve(),b):this.playClosePanelAnimation(a).then(function(){this.activePanel&&this.activePanel.id===a.id&&(this.activePanel.onDeActive(),this.activePanel=null);a.setState("closed");a.onClose();a.domNode&&c.setStyle(a.domNode,
"display","none")})},minimizePanel:function(a){if("string"===typeof a&&(a=this.getPanelById(a),!a))return;"closed"===a.state&&this.openPanel(a);a.setWindowState("minimized");try{a.onMinimize()}catch(b){console.log(console.error("fail to minimize panel "+a.id+". "+b.stack))}},maximizePanel:function(a){if("string"===typeof a&&(a=this.getPanelById(a),!a))return;"closed"===a.state&&this.openPanel(a);a.setWindowState("maximized");try{a.onMaximize()}catch(b){console.log(console.error("fail to maximize panel "+
a.id+". "+b.stack))}},normalizePanel:function(a){if("string"===typeof a&&(a=this.getPanelById(a),!a))return;"closed"===a.state&&this.openPanel(a);a.setWindowState("normal");try{a.onNormalize()}catch(b){console.log(console.error("fail to noralize panel "+a.id+". "+b.stack))}},changeWindowStateTo:function(a,b){if("string"===typeof a&&(a=this.getPanelById(a),!a))return;"normal"===b?this.normalizePanel(a):"minimized"===b?this.minimizePanel(a):"maximized"===b?this.maximizePanel(a):console.log("error state: "+
b)},getPanelById:function(a){for(var b=0;b<this.panels.length;b++)if(this.panels[b].id===a)return this.panels[b]},onWindowResize:function(){for(var a=0;a<this.panels.length;a++)"closed"!==this.panels[a].state&&"map"!==this.panels[a].position.relativeTo&&this.panels[a].resize()},onMapResize:function(){for(var a=0;a<this.panels.length;a++)"closed"!==this.panels[a].state&&"map"===this.panels[a].position.relativeTo&&this.panels[a].resize()},destroyPanel:function(a){if("string"===typeof a&&(a=this.getPanelById(a),
!a))return;if(a.domNode){"closed"!==a.state&&this.closePanel(a);this._removePanel(a);try{a.destroy()}catch(b){console.log(console.error("fail to destroy panel "+a.id+". "+b.stack))}}},destroyAllPanels:function(){var a=m.map(this.panels,function(a){return a.id});m.forEach(a,function(a){this.destroyPanel(a)},this);this.panels=[]},playOpenPanelAnimation:function(a){if("string"===typeof a&&(a=this.getPanelById(a),!a)||!a.openAnimation||0===a.animationDuration)return h();var b=new e;"string"===typeof a.openAnimation?
"fadeIn"===a.openAnimation?(c.setStyle(a.domNode,{opacity:0,display:""}),p.fadeIn({node:a.domNode,duration:a.animationDuration,onEnd:function(){b.resolve()}}).play()):b.resolve():b.resolve();return b},playClosePanelAnimation:function(a){if("string"===typeof a&&(a=this.getPanelById(a),!a)||!a.closeAnimation||0===a.animationDuration)return h();var b=new e;"string"===typeof a.closeAnimation&&("fadeOut"===a.closeAnimation?p.fadeOut({node:a.domNode,duration:a.animationDuration,onEnd:function(){b.resolve()}}).play():
b.resolve());return b},getPositionOnMobile:function(a){if("string"===typeof a&&(a=this.getPanelById(a),!a))return{};var b=c.getMarginBox(window.jimuConfig.layoutId),d=b.h/2;a.titleHeight||(a.titleHeight=35);return"maximized"===a.windowState?{left:0,right:0,top:0,bottom:0,width:"auto",height:"auto",contentHeight:b.h-a.titleHeight,borderRadiusStyle:{borderTopLeftRadius:0,borderTopRightRadius:0,borderBottomLeftRadius:0,borderBottomRightRadius:0}}:"minimized"===a.windowState?b.h>b.w?{left:0,right:0,top:"auto",
bottom:0,width:"auto",height:a.titleHeight,contentHeight:0,borderRadiusStyle:{borderTopLeftRadius:"4px",borderTopRightRadius:"4px",borderBottomLeftRadius:0,borderBottomRightRadius:0}}:{left:b.w-b.w/2,right:0,top:"auto",bottom:0,width:b.w/2,height:a.titleHeight,contentHeight:b.h,borderRadiusStyle:window.isRTL?{borderTopLeftRadius:0,borderTopRightRadius:"4px",borderBottomLeftRadius:0,borderBottomRightRadius:"4px"}:{borderTopLeftRadius:"4px",borderTopRightRadius:0,borderBottomLeftRadius:"4px",borderBottomRightRadius:0}}:
b.h>b.w?{left:0,right:0,top:d,bottom:0,width:"auto",height:"auto",contentHeight:b.h-d-a.titleHeight,borderRadiusStyle:{borderTopLeftRadius:"4px",borderTopRightRadius:"4px",borderBottomLeftRadius:0,borderBottomRightRadius:0}}:{left:b.w-b.w/2,right:0,top:0,bottom:0,width:b.w/2,height:"auto",contentHeight:b.h-d-a.titleHeight,borderRadiusStyle:window.isRTL?{borderTopLeftRadius:0,borderTopRightRadius:"4px",borderBottomLeftRadius:0,borderBottomRightRadius:"4px"}:{borderTopLeftRadius:"4px",borderTopRightRadius:0,
borderBottomLeftRadius:"4px",borderBottomRightRadius:0}}},_onPanelClick:function(a){this._activePanel(a)},_activePanel:function(a){if(this.activePanel){if(this.activePanel.id===a.id){this.activePanel.moveTopOnActive&&c.setStyle(this.activePanel.domNode,"zIndex",101);return}"active"===this.activePanel.state&&(this.activePanel.setState("opened"),c.setStyle(this.activePanel.domNode,"zIndex","undefined"!==typeof this.activePanel.position.zIndex?this.activePanel.position.zIndex:"auto"),this.activePanel.onDeActive())}var b=
this.widgetManager.activeWidget;b&&"active"===b.state&&b.getPanel()!==a&&(b.setState("opened"),!1===b.inPanel&&c.setStyle(b.domNode,"zIndex","undefined"!==typeof b.position.zIndex?b.position.zIndex:"auto"),b.onDeActive(),this.widgetManager.activeWidget=null);this.activePanel=a;"active"!==this.activePanel.state&&(this.activePanel.setState("active"),this.activePanel.moveTopOnActive&&c.setStyle(this.activePanel.domNode,"zIndex",101),this.activePanel.onActive())},_removePanel:function(a){var b=this.panels.indexOf(a);
-1<b&&this.panels.splice(b,1);this.activePanel&&this.activePanel.id===a.id&&(this.activePanel=null)},_onMoveStart:function(a){m.forEach(this.panels,function(b){b.domNode===a.node&&this._activePanel(b)},this)},_onWidgetActived:function(a){this.activePanel&&"active"===this.activePanel.state&&a.getPanel()!==this.activePanel&&(this.activePanel.setState("opened"),c.setStyle(this.activePanel.domNode,"zIndex","undefined"!==typeof this.activePanel.position.zIndex?this.activePanel.position.zIndex:"auto"),
this.activePanel.onDeActive(),this.activePanel=null)},_loadPanelClass:function(a){var b=new e;r([a],function(a){b.resolve(a)});return b},_loadThemeI18N:function(a){var b=new e;a.startWith("themes")?(a=a.split("/"),r(["dojo/i18n!"+(a[0]+"/"+a[1]+"/nls/strings")],function(a){b.resolve(a)})):b.resolve({});return b}});k.getInstance=function(){null===l&&(l=new k,window._panelManager=l);return l};return k});