// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/config dojo/Deferred dojo/topic dojo/json esri/request ./utils ./portalUrlUtils ./tokenUtils".split(" "),function(n,d,m,p,f,w,x,h,u,g,l){var A=n([],{declaredClass:"jimu.Portal",selfUrl:null,user:null,selfInfo:null,portalUrl:null,credential:null,constructor:function(a){this.portalUrl=g.getStandardPortalUrl(a);this.selfUrl=g.getPortalSelfInfoUrl(a)},loadSelfInfo:function(){var a=new f,b={query:{f:"json"},responseType:"json",callbackParamName:"callback",
cacheBust:!0};this.isValidCredential()&&(b.query.token=this.credential.token);h(this.selfUrl,b).then(d.hitch(this,function(c){c=c.data;var b=c.user;delete c.user;d.mixin(this,c);c.user=b;a.resolve(c)}),d.hitch(this,function(b){console.error(b);a.reject(b)}));return a},_checkCredential:function(){var a=l.isValidCredential(this.credential);a||this.clearCredentialAndUser();return a},isValidCredential:function(){this.updateCredential();return this._checkCredential()},updateCredential:function(){this._checkCredential()||
(this.credential=l.getPortalCredential(this.portalUrl))},signIn:function(){var a=new f;this.updateCredential();this.isValidCredential()?setTimeout(d.hitch(this,function(){a.resolve(this.credential)}),0):a=l.signInPortal(this.portalUrl);return a},haveSignIn:function(){return l.userHaveSignInPortal(this.portalUrl)},clearCredentialAndUser:function(){this.user=this.credential=null},getUser:function(){this.updateCredential();var a=new f;this.user&&"jimu.PortalUser"===this.user.declaredClass?setTimeout(d.hitch(this,
function(){this.user.updateCredential();a.resolve(this.user)}),0):this.isValidCredential()?this.credential.userId?this._getUser(this.credential.userId).then(d.hitch(this,function(b){this.user=b;a.resolve(this.user)}),d.hitch(this,function(b){console.error(b);a.reject(b)})):l.getUserIdByToken(this.credential.token,this.portalUrl).then(d.hitch(this,function(b){this.credential.userId=b;this._getUser(this.credential.userId).then(d.hitch(this,function(b){this.user=b;a.resolve(this.user)}),d.hitch(this,
function(b){console.error(b);a.reject(b)}))}),d.hitch(this,function(b){console.error(b);a.reject(b)})):setTimeout(d.hitch(this,function(){a.reject("credential is null.")}),0);return a},queryItems:function(a){this.updateCredential();var b=new f,c=g.getBaseSearchUrl(this.portalUrl),e={f:"json"};a&&(e=d.mixin(e,a));this.isValidCredential()&&(e.token=this.credential.token);e.sortField||e.sortOrder||(e.sortField="title",e.sortOrder="asc");h(c,{responseType:"json",query:e,callbackParamName:"callback"}).then(d.hitch(this,
function(a){a=a.data;a.results=m.map(a.results,d.hitch(this,function(a){a.portalUrl=this.portalUrl;a.credential=this.credential;a.portal=this;return new q(a)}));b.resolve(a)}),d.hitch(this,function(a){console.error(a);b.reject(a)}));return b},getItemData:function(a){this.updateCredential();a=g.getItemDataUrl(this.portalUrl,a);var b={responseType:"json",query:{f:"json"},callbackParamName:"callback"};this.isValidCredential()&&(b.query.token=this.credential.token);var c=new f;h(a,b).then(d.hitch(this,
function(a){c.resolve(a.data)}),d.hitch(this,function(a){c.reject(a)}));return c},getItemById:function(a){var b=new f;this.updateCredential();a=g.getItemUrl(this.portalUrl,a);var c={responseType:"json",query:{f:"json"},callbackParamName:"callback"};this.isValidCredential()&&(c.query.token=this.credential.token);h(a,c).then(d.hitch(this,function(a){a=a.data;a.portalUrl=this.portalUrl;a.credential=this.credential;a.portal=this;a=new q(a);b.resolve(a)}),d.hitch(this,function(a){console.error(a);b.reject(a)}));
return b},getAppById:function(a){var b=new f;this.updateCredential();this.isValidCredential()?(a=g.getAppIdUrl(this.portalUrl,a),h(a,{responseType:"json",query:{f:"json",token:this.credential.token}}).then(d.hitch(this,function(a){b.resolve(a.data)}),d.hitch(this,function(a){b.reject(a)}))):setTimeout(d.hitch(this,function(){b.reject("token is null.")}),0);return b},queryGroups:function(a){this.updateCredential();var b=new f,c=g.getBaseGroupUrl(this.portalUrl),e={f:"json"};a&&(e=d.mixin(e,a));this.isValidCredential()&&
(e.token=this.credential.token);h(c,{responseType:"json",query:e,callbackParamName:"callback"}).then(d.hitch(this,function(a){a=a.data;a.results=m.map(a.results,d.hitch(this,function(a){a.portalUrl=this.portalUrl;a.credential=this.credential;a.portal=this;return new r(a)}));b.resolve(a)}),d.hitch(this,function(a){console.error(a);b.reject(a)}));return b},registerApp:function(a,b,c){var e=new f;this.updateCredential();if(this.isValidCredential()){var k=this.credential&&this.credential.token,y=g.getOAuth2Url(this.portalUrl);
h(y+"/registerApp",{query:{itemId:a,appType:b,redirect_uris:x.stringify(c),token:k,f:"json"},responseType:"json",method:"post"}).then(d.hitch(this,function(a){e.resolve(a.data)}),d.hitch(this,function(a){e.reject(a)}))}else setTimeout(d.hitch(this,function(){e.reject("token is null.")}),0);return e},createAndRegisterApp:function(a){var b=new f;this.updateCredential();this.isValidCredential()?this.getUser().then(d.hitch(this,function(c){c.addItem({title:"Web AppBuilder for ArcGIS",type:"Web Mapping Application",
text:"",snippet:"",tags:"Registered App for OAuth"},"").then(d.hitch(this,function(c){c.success?this.registerApp(c.id,"browser",a).then(d.hitch(this,function(a){b.resolve(a)}),d.hitch(this,function(a){console.error(a);b.reject(a)})):b.reject("create app failed")}),d.hitch(this,function(a){console.error(a);b.reject(a)}))}),d.hitch(this,function(a){console.error(a);b.reject(a)})):setTimeout(d.hitch(this,function(){b.reject("token is null.")}),0);return b},_getUser:function(a){this.updateCredential();
var b=new f;a=g.getUserUrl(this.portalUrl,a);var c={query:{f:"json"},responseType:"json",callbackParamName:"callback"};this.isValidCredential()&&(c.query.token=this.credential&&this.credential.token);h(a,c).then(d.hitch(this,function(a){a=a.data;a.portalUrl=this.portalUrl;a.credential=this.credential;a.portal=this;this.user=new z(a);b.resolve(this.user)}),d.hitch(this,function(a){console.error(a);b.reject(a)}));return b},getItemResources:function(a,b,c){c||(c=100);a=g.getStandardPortalUrl(a);a=g.getItemResourceUrl(a,
b);return h({url:a,content:{f:"json",num:c}}).then(function(a){if(a&&a.resources)return a.resources})},addResource:function(a,b,c,d,k){a=g.getStandardPortalUrl(a);var e=this.getPortal(a),f=new FormData;f.append("file",c,d);f.append("fileName",d);f.append("f","json");var t="";k?(f.append("resourcesPrefix",k),t=k+"/"+d):t=d;return e.getItemById(b,!0).then(function(c){c=g.getUserContentItemUrl(a,c.owner,b);return h({url:c+"/addResources",form:f}).then(function(b){var c="";b&&b.success&&(c=g.getItemResourceUrl(a,
"${itemId}",t));return c},function(a){console.error(a.message||a);return a})})},removeResources:function(a,b,c,d){var e={resource:d?d+"/"+c:c,f:"json"};a=g.getStandardPortalUrl(a);return this.getPortal(a).getItemById(b,!0).then(function(c){c=g.getUserContentItemUrl(a,c.owner,b);return h({url:c+"/removeResources",content:e},{usePost:!0}).then(function(a){return a},function(a){console.error(a.message||a);return a})})}}),z=n([],{declaredClass:"jimu.PortalUser",portalUrl:null,credential:null,portal:null,
constructor:function(a){a&&d.mixin(this,a)},_checkCredential:function(){var a=l.isValidCredential(this.credential);a||(this.credential=null);return a},isValidCredential:function(){this.updateCredential();return this._checkCredential()},updateCredential:function(){this._checkCredential()||(this.portal.updateCredential(),this.credential=this.portal.credential)},getGroups:function(){var a=[];this.groups&&(a=m.map(this.groups,d.hitch(this,function(a){a.portalUrl=this.portalUrl;a.credential=this.credential;
a.portal=this.portal;return new r(a)})));return a},getItemsByKeywords:function(a,b){return this.portal.queryItems({start:b||1,num:100,q:"owner:"+this.username+' AND typekeywords:"'+a+'"'})},getContent:function(){this.updateCredential();var a=g.getUserContentUrl(this.portalUrl,this.username),b={responseType:"json",query:{f:"json"},callbackParamName:"callback"};this.isValidCredential&&(b.query.token=this.credential.token);var c=new f;h(a,b).then(d.hitch(this,function(a){c.resolve(a.data)}),d.hitch(this,
function(a){c.reject(a)}));return c},getTags:function(){this.updateCredential();var a=g.getUserTagsUrl(this.portalUrl,this.username),b={responseType:"json",query:{f:"json"},callbackParamName:"callback"};this.isValidCredential()&&(b.query.token=this.credential.token);var c=new f;h(a,b).then(d.hitch(this,function(a){c.resolve(a.data)}),d.hitch(this,function(a){c.reject(a)}));return c},addItem:function(a,b){this.updateCredential();var c=new f;if(this.isValidCredential()){var e={f:"json",token:this.credential.token};
a&&(e=d.mixin(e,a));a=g.getAddItemUrl(this.portalUrl,this.username,b);h(a,{responseType:"json",callbackParamName:"callback",query:e,method:"post"}).then(d.hitch(this,function(a){c.resolve(a.data)}),d.hitch(this,function(a){console.error(a);c.reject(a)}))}else setTimeout(d.hitch(this,function(){c.reject("token is null.")}),0);return c},deleteItem:function(a){this.updateCredential();var b=new f;this.isValidCredential()?(a=g.getDeleteItemUrl(this.portalUrl,this.username,a),h(a,{query:{token:this.credential.token,
f:"json"},responseType:"json",method:"post"}).then(d.hitch(this,function(a){b.resolve(a.data)}),d.hitch(this,function(a){b.reject(a)}))):setTimeout(d.hitch(this,function(){b.reject("token is null.")}),0);return b},getItemById:function(a,b){this.updateCredential();var c=new f;b=g.getUserItemsUrl(this.portalUrl,this.username,b);var e={responseType:"json",query:{f:"json"},callbackParamName:"callback"};this.isValidCredential()&&(e.query.token=this.credential.token);h(b+"/"+a,e).then(d.hitch(this,function(a){a=
a.data;a.portalUrl=this.portalUrl;a.credential=this.credential;a.portal=this;a=new q(a);c.resolve(a)}),d.hitch(this,function(a){console.error(a);c.reject(a)}));return c},shareItem:function(a,b,c){this.updateCredential();var e=new f;this.isValidCredential()?(b=g.shareItemUrl(this.portalUrl,this.username,b,c),c={responseType:"json",callbackParamName:"callback",query:{f:"json",token:this.credential.token},method:"post"},a&&(a.content&&!a.query&&(a.query=a.content),c.query=d.mixin(c.query,a)),h(b,c).then(d.hitch(this,
function(a){e.resolve(a.data)}),d.hitch(this,function(a){console.error(a);e.reject(a)}))):setTimeout(d.hitch(this,function(){e.reject("token is null.")}),0);return e},updateItem:function(a,b){this.updateCredential();var c=new f;this.isValidCredential()?this.portal.getItemById(a).then(d.hitch(this,function(e){var k={f:"json",token:this.credential.token};b&&(k=d.mixin(k,b));e=g.getUpdateItemUrl(this.portalUrl,this.username,a,e.ownerFolder);h(e,{responseType:"json",callbackParamName:"callback",timeout:1E5,
query:k,method:"post"}).then(d.hitch(this,function(a){c.resolve(a.data)}),d.hitch(this,function(a){console.error(a);c.reject(a)}))}),d.hitch(this,function(a){console.error(a);c.reject(a)})):setTimeout(d.hitch(this,function(){c.reject("token is null.")}),0);return c},isAdminRole:function(){return"org_admin"===this.role||"account_admin"===this.role},isPublisherRole:function(){return"org_publisher"===this.role||"account_publisher"===this.role},isUserRole:function(){return"org_user"===this.role||"account_user"===
this.role}}),r=n([],{declaredClass:"jimu.PortalGroup",portalUrl:null,credential:null,portal:null,constructor:function(a){a&&d.mixin(this,a)},_checkCredential:function(){var a=l.isValidCredential(this.credential);a||(this.credential=null);return a},isValidCredential:function(){this.updateCredential();return this._checkCredential()},updateCredential:function(){this._checkCredential()||(this.portal.updateCredential(),this.credential=this.portal.credential)},queryItems:function(a){a.q="group:"+this.id+
" AND "+a.q;return this.portal.queryItems(a)}}),q=n([],{declaredClass:"jimu.PortalItem",itemUrl:null,detailsPageUrl:null,ownerPageUrl:null,portalUrl:null,credential:null,portal:null,token:null,constructor:function(a){a&&d.mixin(this,a);this.itemUrl=g.getItemUrl(this.portalUrl,this.id);!this.thumbnailUrl&&this.thumbnail&&this.itemUrl&&(this.thumbnailUrl=this.itemUrl+"/info/"+this.thumbnail);this.token=this.credential&&this.credential.token;this.thumbnailUrl&&this.token&&(this.thumbnailUrl+="?token\x3d"+
this.token);this.portalUrl&&this.id&&(this.detailsPageUrl=g.getItemDetailsPageUrl(this.portalUrl,this.id));this.portalUrl&&this.owner&&(this.ownerPageUrl=g.getUserProfilePageUrl(this.portalUrl,this.owner))},_checkCredential:function(){var a=l.isValidCredential(this.credential);a||(this.credential=null);return a},isValidCredential:function(){this.updateCredential();return this._checkCredential()},updateCredential:function(){this._checkCredential()||(this.portal.updateCredential(),this.credential=this.portal.credential)},
getItemData:function(){return this.portal.getItemData(this.id)}}),v={portals:[],webMapQueryStr:" "+u.getItemQueryStringByTypes(["Web Map"])+" ",webSceneQueryStr:" "+u.getItemQueryStringByTypes(["Web Scene"])+" ",_findPortal:function(a){for(var b=0;b<this.portals.length;b++){var c=this.portals[b];if(g.isSamePortalUrl(a,c.portalUrl))return c.updateCredential(),c}return null},getPortal:function(a){if(!a||"string"!==typeof a||!d.trim(a))return null;a=g.getStandardPortalUrl(a);var b=this._findPortal(a);
b||(b=new A(a),b.credential=l.getPortalCredential(b.portalUrl),b.updateCredential(),this.portals.push(b));return b},getPortalSelfInfo:function(a){return this.getPortal(a).loadSelfInfo()},getBasemapGalleryGroup:function(a){return this._getPortalSelfGroup(a,"basemapGalleryGroupQuery")},getTemplatesGroup:function(a){return this._getPortalSelfGroup(a,"templatesGroupQuery")},getUnits:function(a){var b="english",c="",e=new f;this.getPortal(a).getUser().then(d.hitch(this,function(a){a&&a.units?b=a.units:
(c=p.locale,b=c.startWith("en")?"english":"metric");e.resolve(b)}),d.hitch(this,function(k){console.warn(k);this.getPortalSelfInfo(a).then(d.hitch(this,function(a){var b=null;a&&a.units?b=a.units:(c=a&&a.culture||p.locale,b=c.startWith("en")?"english":"metric");e.resolve(b)}),d.hitch(this,function(a){console.warn(a);c=p.locale;b=c.startWith("en")?"english":"metric";e.resolve(b)}))}));return e.promise},_getPortalSelfGroup:function(a,b){var c=new f,e=this.getPortal(a);e||setTimeout(d.hitch(this,function(){c.reject()}),
0);this.getPortalSelfInfo(a).then(d.hitch(this,function(a){e.queryGroups({f:"json",q:a[b]}).then(d.hitch(this,function(a){0<a.results.length?(a=a.results[0],a.portalUrl=e.portalUrl,a.credential=e.credential,a.portal=e,a=new r(a),c.resolve(a)):c.reject("Can't find portal self group.")}),d.hitch(this,function(a){console.error(a);c.reject(a)}))}),d.hitch(this,function(a){console.error(a);c.reject(a)}));return c},getWebMapsFromBasemapGalleryGroup:function(a){var b=new f;this.getBasemapGalleryGroup(a).then(d.hitch(this,
function(a){a?a.queryItems({start:1,num:100,f:"json",q:this.webMapQueryStr}).then(d.hitch(this,function(a){b.resolve(a)}),d.hitch(this,function(a){console.error(a);b.reject(a)})):b.reject()}),d.hitch(this,function(a){console.error(a);b.reject(a)}));return b},getDefaultWebScene:function(a){var b=new f,c=this.getPortal(a);c.getUser().then(d.hitch(this,function(a){c.queryItems({start:1,num:1,f:"json",q:this.webSceneQueryStr+' AND owner:"'+a.username+'" ',sortField:"numViews",sortOrder:"desc"}).then(d.hitch(this,
function(a){a=a.results;a=m.filter(a,d.hitch(this,function(a){return a.type&&"web scene"===a.type.toLowerCase()}));0<a.length?b.resolve(a[0].id):b.resolve(null)}),d.hitch(this,function(a){b.reject(a)}))}),d.hitch(this,function(){b.reject("not sign in")}));return b},getDefaultWebMap:function(a){var b=new f;this.getPortalSelfInfo(a).then(d.hitch(this,function(c){var e=c.defaultBasemap&&c.defaultBasemap.id;e?b.resolve(e):this._getDefaultWebMapByBasemapGallery(a,c).then(d.hitch(this,function(c){c?b.resolve(c):
this._getMostNumViewsWebMap(a).then(d.hitch(this,function(a){a?b.resolve(a):b.reject()}),d.hitch(this,function(a){console.error(a);b.reject(a)}))}),d.hitch(this,function(a){console.error(a);b.reject(a)}))}),d.hitch(this,function(a){console.error(a);b.reject(a)}));return b},_getDefaultWebMapByBasemapGallery:function(a,b){var c=new f,e=this.getPortal(a),g=b.defaultBasemap&&b.defaultBasemap.title;e.queryGroups({f:"json",q:b.basemapGalleryGroupQuery}).then(d.hitch(this,function(a){a=a.results;0<a.length?
e.queryItems({start:1,num:1,f:"json",q:this.webMapQueryStr+" AND group:"+a[0].id+" AND title:"+g}).then(d.hitch(this,function(a){a=a.results;a=m.filter(a,d.hitch(this,function(a){return a.type&&"web map"===a.type.toLowerCase()}));0<a.length?c.resolve(a[0].id):(console.log("Can't find web map under basemapGalleryGroupQuery."),e.queryItems({start:1,num:1,f:"json",q:this.webMapQueryStr+" AND title:"+g}).then(d.hitch(this,function(a){a=a.results;a=m.filter(a,d.hitch(this,function(a){return a.type&&"web map"===
a.type.toLowerCase()}));if(0<a.length){var b=a[0];e.getItemData(b.id).then(d.hitch(this,function(a){a&&(a.operationalLayers||a.baseMap||a.version)?c.resolve(b.id):c.resolve(null)}),d.hitch(this,function(){c.resolve(null)}))}else console.log("Can't find web map by defaultBasemap.title."),c.resolve(null)}),d.hitch(this,function(a){console.error(a);c.reject(a)})))}),d.hitch(this,function(a){console.error(a);c.reject(a)})):(console.log("Can't find group by basemapGalleryGroupQuery."),c.resolve(null))}),
d.hitch(this,function(a){console.error(a);c.reject(a)}));return c},_getMostNumViewsWebMap:function(a){var b=new f;this.getPortal(a).queryItems({start:1,num:1,f:"json",q:this.webMapQueryStr+" AND access:public AND owner:esri_en",sortField:"numViews",sortOrder:"desc"}).then(d.hitch(this,function(a){a=a.results;a=m.filter(a,d.hitch(this,function(a){return a.type&&"web map"===a.type.toLowerCase()}));0<a.length?b.resolve(a[0].id):b.reject("Can't find most-num-views web map.")}),d.hitch(this,function(a){console.error(a);
b.reject(a)}));return b}};w.subscribe("userSignOut",function(a){(a=v._findPortal(a))&&a.clearCredentialAndUser()});return v});