// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/_base/html dojo/_base/sniff dojo/_base/config dojo/io-query dojo/query dojo/NodeList-traverse dojo/Deferred dojo/promise/all dojo/on dojo/json dojo/cookie dojo/number dojo/date/locale dojo/i18n!dojo/cldr/nls/number dojox/encoding/base64 esri/kernel esri/config esri/geometry/SpatialReference esri/geometry/Extent esri/geometry/Multipoint esri/geometry/Polyline esri/geometry/Polygon esri/geometry/support/webMercatorUtils esri/tasks/GeometryService esri/tasks/support/ProjectParameters esri/core/urlUtils esri/request esri/identity/IdentityManager esri/identity/OAuthInfo jimu/portalUrlUtils ./shared/utils".split(" "),
function(k,g,m,z,A,L,r,la,q,X,B,w,F,M,Y,Z,N,aa,p,ba,ca,da,ea,O,fa,G,ga,t,H,I,ha,P,Q){function ia(a,b){a=a||"";var c=0,d=[{test:window.File&&window.FileReader&&window.FileList&&window.Blob||!e.file.isEnabledFlash(),failure:[a+"libs/polyfills/fileAPI/FileAPI.js"],callback:function(){c++;c===d.length&&b()}}];for(a=0;a<d.length;a++)testLoad(d[a])}function R(a,b){var c=a.match(/url\([^)]+\)/gi),d,f;if(null===c||""===b)return a;for(d=0;d<c.length;d++)if(f=c[d].match(/(url\(["|']?)(.*)((?:['|"]?)\))/i),
4<=f.length){var h=f[2];/^data:image\/.*;/.test(h)||(b.endWith("/")||(b+="/"),a=a.replace(f[1]+h+f[3],f[1]+b+h+f[3]))}return a}function J(a,b){var c=Array.isArray(b),d=c&&[]||{};c?(a=a||[],d=d.concat(a),b.forEach(function(b,c){"undefined"===typeof a[c]?d[c]=b:"object"===typeof b?d[c]=J(a[c],b):-1===a.indexOf(b)&&d.push(b)})):(a&&"object"===typeof a&&Object.keys(a).forEach(function(b){d[b]=a[b]}),Object.keys(b).forEach(function(c){d[c]="object"===typeof b[c]&&b[c]?a[c]?J(a[c],b[c]):b[c]:b[c]}));return d}
function S(a){var b,c={};b=a.indexOf("/");a.substring(0,b);b=a.substring(0,a.lastIndexOf("/")+1);c.folderUrl=require(e.getRequireConfig()).toUrl(b);c.amdFolder=b;c.url=c.folderUrl;if(/^http(s)?:\/\//.test(a)||/^\/\//.test(a))c.isRemote=!0;return c}function ja(a){a.panels.forEach(function(a){a.uri="panels/"+a.name+"/Panel.js"});a.styles.forEach(function(a){a.uri="styles/"+a.name+"/style.css"});a.layouts.forEach(function(a){a.uri="layouts/"+a.name+"/config.json";a.icon="layouts/"+a.name+"/icon.png";
a.RTLIcon="layouts/"+a.name+"/icon_rtl.png"})}function T(a,b){var c=a.map(function(a){return a.id});g.forEach(b,function(b){0>c.indexOf(b)&&a.push({id:b,widgets:[]})},this);var d=[];a=g.filter(a,function(a){return 0>b.indexOf(a.id)?(d.push(a),!1):!0},this);if(0===a.length)return[];var f=a[a.length-1];g.forEach(d,function(a){f.widgets=f.widgets.concat(a.widgets)},this);return a=a.sort(function(a,c){return b.indexOf(a.id)-b.indexOf(c.id)})}function K(a,b,c){function d(a,b){return k.isArray(a[b.key])?
a[b.key][b.index]:a[b.key]}b=function(a){var b=[];a.split("_").forEach(function(a){var c=!1,d;"--"===a.slice(a.length-2)&&(c=!0,a=a.slice(0,a.length-2));d=a.search(/\[[0-9]+\]/);-1===d&&(d=a.length);b.push({key:a.slice(0,d),index:Number(a.slice(d+1,-1)),deleteFlag:c})});return b}(b);for(var f=1;f<b.length-1;f++)if(a=d(a,b[f]),!a)return;if(b[b.length-1].deleteFlag)!0===c&&(k.isArray(a[b[b.length-1].key])?delete a[b[b.length-1].key][b[b.length-1].index]:delete a[b[b.length-1].key]);else if(k.isArray(a[b[b.length-
1].key])){if(void 0===c)return a[b[b.length-1].key][b[b.length-1].index];a[b[b.length-1].key][b[b.length-1].index]=c}else{if(void 0===c)return a[b[b.length-1].key];a[b[b.length-1].key]=c}}function U(a,b,c){function d(c){c=e.template.getSearchRange(b,c,"]");var d=b.slice(c.firstPos,c.lastPos);return-1!==c.firstPos?(d=b.slice(c.firstPos+d.indexOf("[")+1,c.lastPos-1),c=b.slice(c.lastPos+1),(d=e.getConfigElementById(a,d))?{object:d,key:"section_"+c,state:"isSection"}:{state:"deleted"}):{state:"isNotSection"}}
var f=a,h=b=b.replace(/\//g,"_"),l=d("groups\\[.+\\]");if("deleted"!==l.state&&("isSection"===l.state&&(f=l.object,h=l.key),l=d("widgets\\[.+\\]"),"delete"!==l.state))return"isSection"===l.state&&(f=l.object,h=l.key),K(f,h,c)}var e={},V={geometryService:"http://utility.arcgisonline.com/arcgis/rest/services/Geometry/GeometryServer"};k.mixin(e,Q);window.atob||(window.atob=function(a){a=N.decode(a);for(var b="",c=0,d=a.length;c<d;c++)b+=String.fromCharCode(a[c]);return b});window.btob||(window.btob=
function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(String.charCodeAt(a[c]));return N.encode(b)});var y="unload",W=[];require.on("error",function(a){g.forEach(W,function(b){a.info[0]&&-1<a.info[0].indexOf(b.resKey)&&b.def.reject(a);for(var c in a.info)-1<c.indexOf(b.resKey)&&b.def.reject(a)})});e.checkError=function(a,b){W.push({resKey:a,def:b})};e.replacePlaceHolder=function(a,b){var c=w.stringify(a),d=c.match(/\$\{(\w)+\}/g);if(null===d)return a;for(a=0;a<d.length;a++){var f=d[a].match(/(\w)+/g)[0];
b[f]&&(c=c.replace(d[a],b[f]))}return w.parse(c)};e.changeUnit=function(a){var b=Math.abs(a),c;a=Math.floor(b);c=Math.floor(60*(b-a));b=(60*(60*(b-a)-c)).toFixed(2);return a+"\u00b0"+(10>c?"0"+c:c)+"'"+(10>b?"0"+b:b)+'"'};e.formatTime=function(a){var b=a/1E3;a=Math.floor(b/60);b=Number(b-60*a).toFixed(1);return(10>a?"0"+a:a)+":"+(10>b?"0"+b:b)};e.parseTime=function(a){var b=/(\d{2,})\:(\d{2})\.(\d{1})/;if(!b.test(a))return console.log("wrong time format."),-1;a=a.match(b);return 1E3*(60*parseInt(a[1],
10)+parseInt(a[2],10)+parseInt(a[3],10)/10)};e.preloadImg=function(a,b){var c=[],c="string"===typeof a?[a]:a;g.forEach(c,function(a){(new Image).src=b?b+a:a})};e.setWABLogoDefaultAlt=function(a){if(a){a=r("img",a);for(var b=["img_1412759111499","img_1545621838463","img_1560482577021"],c=0,d=a.length;c<d;c++){var f=a[c];-1<b.indexOf(m.getAttr(f,"id"))&&!m.getAttr(f,"alt")&&m.setAttr(f,"alt","Web AppBuilder for ArcGIS.png")}}};var v=null;e.getImagesSize=function(a){var b=new q;if(!a||0!==a.indexOf("http"))return b.reject(),
b;null===v&&(v=m.create("img",{id:"__test-image-size",style:{position:"absolute",left:"-9999px",top:"-9999px"}},document.body));var c=B(v,"load",function(){clearTimeout(d);d=null;c.remove();var a=m.getContentBox(v);1===a.w&&1===a.h||0===a.w||0===a.h?b.reject():b.resolve([a.w,a.h])},{}),d=setTimeout(function(){clearTimeout(d);d=null;b.reject()},5E3);m.setAttr(v,"src",a);return b};e.getPositionStyle=function(a){var b={};if(!a)return b;a=k.clone(a);if(window.isRTL){var c;"undefined"!==typeof a.left&&
"undefined"!==typeof a.right?(c=a.left,a.left=a.right,a.right=c):"undefined"!==typeof a.left?(a.right=a.left,delete a.left):"undefined"!==typeof a.right&&(a.left=a.right,delete a.right);"undefined"!==typeof a.paddingLeft&&"undefined"!==typeof a.paddingRight?(c=a.paddingLeft,a.paddingLeft=a.paddingRight,a.paddingRight=c):"undefined"!==typeof a.paddingLeft?(a.paddingRight=a.paddingLeft,delete a.paddingLeft):"undefined"!==typeof a.paddingRight&&(a.paddingLeft=a.paddingRight,delete a.paddingRight);"undefined"!==
typeof a.marginLeft&&"undefined"!==typeof a.marginRight?(c=a.marginLeft,a.marginLeft=a.marginRight,a.marginRight=c):"undefined"!==typeof a.marginLeft?(a.marginRight=a.marginLeft,delete a.marginLeft):"undefined"!==typeof a.marginRight&&(a.marginLeft=a.marginRight,delete a.marginRight)}c="left top right bottom width height padding paddingLeft paddingRight paddingTop paddingBottom margin marginLeft marginRight marginTop marginBottom".split(" ");for(var d=0;d<c.length;d++){var f=c[d];"number"===typeof a[f]?
b[f]=a[f]+"px":"undefined"!==typeof a[f]?b[f]=a[f]:"padding"===f.substr(0,7)||"margin"===f.substr(0,7)?b[f]=0:b[f]="auto"}b.zIndex="undefined"===typeof a.zIndex?"auto":a.zIndex;return b};e.isEqual=function(a,b){function c(a,b){var e;if(null===a&&null===b||"undefined"===typeof a&&"undefined"===typeof b)return!0;if(null===a&&null!==b||null===b&&null!==a||"undefined"===typeof a&&"undefined"!==typeof b||"undefined"===typeof b&&"undefined"!==typeof a)return!1;if(isNaN(a)&&isNaN(b)&&"number"===typeof a&&
"number"===typeof b||a===b)return!0;if("function"===typeof a&&"function"===typeof b||a instanceof Date&&b instanceof Date||a instanceof RegExp&&b instanceof RegExp||a instanceof String&&b instanceof String||a instanceof Number&&b instanceof Number)return a.toString()===b.toString();if(-1<d.indexOf(a)||-1<f.indexOf(b))return!1;if(null!==b){for(e in b)if(b.hasOwnProperty(e)!==a.hasOwnProperty(e)||typeof b[e]!==typeof a[e])return!1;for(e in a){if(b.hasOwnProperty(e)!==a.hasOwnProperty(e)||typeof b[e]!==
typeof a[e])return!1;switch(typeof a[e]){case "object":case "function":d.push(a);f.push(b);if(!c(a[e],b[e]))return!1;d.pop();f.pop();break;default:if(a[e]!==b[e])return!1}}}return!0}var d,f;d=[];f=[];return c(a,b)?!0:!1};e.getUriInfo=S;e.file={loadFileAPI:function(){var a=new q;if("unload"===y){var b=window.isBuilder?"stemapp/":"";window.FileAPI={debug:!1,flash:!0,staticPath:b+"libs/polyfills/fileAPI/",flashUrl:b+"libs/polyfills/fileAPI/FileAPI.flash.swf",flashImageUrl:b+"libs/polyfills/fileAPI/FileAPI.flash.image.swf"};
ia(b,k.hitch(this,function(){y="loaded";a.resolve()}));y="loading"}else"loaded"===y&&a.resolve();return a},supportHTML5:function(){return window.File&&window.FileReader&&window.FileList&&window.Blob?!0:!1},supportFileAPI:function(){return z("safari")&&6>z("safari")?!1:window.FileAPI&&window.FileAPI.readAsDataURL?!0:!1},isEnabledFlash:function(){var a=null;if(document.all)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(b){a=null}else navigator.plugins&&0<navigator.plugins.length&&(a=
navigator.plugins["Shockwave Flash"]);return!!a},containSeparator:function(a){return 0<=a.indexOf("/")?!0:0<=a.indexOf("\\")?!0:!1},getNameFromPath:function(a){var b="",b=0<=a.indexOf("/")?"/":"\\";a=a.split(b);return 0<a.length?a[a.length-1]:null},getFolderFromPath:function(a){return a.substr(0,a.length-e.file.getNameFromPath(a).length)},readFile:function(a,b,c,d){if(this.supportHTML5()){var f=a.target.files[0];f&&(f.type.match(b)?f.size>=c?d({errCode:"exceed"}):(a=new FileReader,a.onload=function(a){d(null,
f.name,a.target.result)},a.readAsDataURL(f)):d({errCode:"invalidType"}))}else if(this.supportFileAPI()){var e=window.FileAPI.getFiles(a);e[0].type.match(b)?e[0].size>=c?d({errCode:"exceed"}):window.FileAPI.readAsDataURL(e[0],function(a){a&&a.result?d(null,e[0].name,a.result):d({errCode:"readError"})}):d({errCode:"invalidType"})}}};e.processWidgetSetting=function(a){if(!a.uri)return a;k.mixin(a,S(a.uri));a.icon||(a.icon=a.amdFolder+"images/icon.png");a.thumbnail||(a.thumbnail=a.amdFolder+"images/thumbnail.png");
return a};e.getRequireConfig=function(){if(jimuConfig){var a=[];jimuConfig.widgetsPackage&&(a=a.concat(jimuConfig.widgetsPackage));jimuConfig.themesPackage&&(a=a.concat(jimuConfig.themesPackage));jimuConfig.configsPackage&&(a=a.concat(jimuConfig.configsPackage));return{packages:a}}return{}};e.getTypeByGeometryType=function(a){var b="",c="esriGeometryLine esriGeometryCircularArc esriGeometryEllipticArc esriGeometryBezier3Curve esriGeometryPath esriGeometryPolyline".split(" "),d=["esriGeometryRing",
"esriGeometryPolygon","esriGeometryEnvelope"];0<=["esriGeometryPoint","esriGeometryMultipoint"].indexOf(a)?b="point":0<=c.indexOf(a)?b="polyline":0<=d.indexOf(a)&&(b="polygon");return b};e.getSymbolTypeByGeometryType=function(a){var b=null;a=e.getTypeByGeometryType(a);"point"===a?b="marker":"polyline"===a?b="line":"polygon"===a&&(b="fill");return b};e.getServices=function(){return V};e.getArcGISDefaultGeometryService=function(){return new G(V.geometryService)};e.restoreToDefaultWebMapExtent=function(a,
b,c){var d=new q;if(!a||"esri.Map"!==a.declaredClass)return setTimeout(function(){d.reject("Invalid map.")},0),d;b=b&&b.itemInfo;if(!b)return setTimeout(function(){d.reject("Invalid itemInfo")},0),d;b=b.item&&b.item.extent;if(!b)return setTimeout(function(){d.reject("Invalid itemInfo.item.extent")}),d;var f=new ba({wkid:4326}),f=new ca(b[0][0],b[0][1],b[1][0],b[1][1],f);if(4326===parseInt(a.spatialReference.wkid,10))return a.setExtent(f);if(a.spatialReference.isWebMercator)return f=fa.geographicToWebMercator(f),
a.setExtent(f);b=new ga;b.geometries=[f];b.outSR=a.spatialReference;f=p&&p.defaults&&p.defaults.geometryService;f&&"esri.tasks.GeometryService"===f.declaredClass||(c&&"string"===typeof c&&k.trim(c)?(c=k.trim(c),f=new G(c)):f=e.getArcGISDefaultGeometryService());f.project(b).then(function(b){if(b=b&&b[0])return a.setExtent(b);d.reject("Invalid projected geometry.");return d},function(a){console.error(a);d.reject(a);return d});return d};e.getAncestorWindow=function(){for(var a=window;a&&a.parent&&a!==
a.parent;)a=a.parent;return a};e.getAncestorDom=function(a,b,c){if(a&&1===a.nodeType&&b&&"function"===typeof b){var d=100,f=document.body;c&&("number"===typeof c?(c=parseInt(c,10),0<c&&(d=c)):1===c.nodeType&&(f=c));for(c=0;a.parentNode&&c<d&&m.isDescendant(a.parentNode,f);){if(b(a.parentNode))return a.parentNode;a=a.parentNode;c++}}return null};e.bindClickAndDblclickEvents=function(a,b,c,d){var f=null;if(a&&1===a.nodeType&&b&&"function"===typeof b&&c&&"function"===typeof c){var e=200;d&&"number"===
typeof d&&(d=parseInt(d,10),0<d&&(e=d));var l=0,f=B(a,"click",function(a){l++;1===l?setTimeout(function(){1===l&&(l=0,b(a))},e):2===l&&(l=0,c(a))})}return f};e.isScrollToBottom=function(a){var b=m.getContentBox(a);return 1>a.scrollHeight-(a.scrollTop+b.h)};e.getAllItemTypes=function(){var a=[],a=a.concat(["Web Map","Web Scene","CityEngine Web Scene"]).concat("Feature Service;Map Service;Image Service;KML;WMS;Feature Collection;Feature Collection Template;Geodata Service;Globe Service".split(";")).concat(["Geometry Service",
"Geocoding Service","Network Analysis Service","Geoprocessing Service"]).concat(["Web Mapping Application","Mobile Application","Code Attachment","Operations Dashboard Add In","Operation View"]).concat("Symbol Set;Color Set;Shapefile;CSV;Service Definition;Document Link;Microsoft Word;Microsoft PowerPoint;Microsoft Excel;PDF;Image;Visio Document".split(";"));return a=a.concat("Map Document;Map Package;Tile Package;ArcPad Package;Explorer Map;Globe Document;Scene Document;Published Map;Map Template;Windows Mobile Package".split(";")).concat(["Layer",
"Layer Package","Explorer Layer"]).concat(["Geoprocessing Package","Geoprocessing Sample","Locator Package","Rule Package"]).concat("Workflow Manager Package;Desktop Application;Desktop Application Template;Code Sample;Desktop Add In;Explorer Add In".split(";"))};e.getItemQueryStringByTypes=function(a){var b="",c=e.getAllItemTypes();if(a&&0<a.length&&0<a.length){var d="";g.forEach(a,function(b,c){d+=' type:"'+b+'" ';c!==a.length-1&&(d+=" OR ")});b=" ( "+d+" ) ";c=a.concat(c);c=g.filter(c,function(b){return g.every(a,
function(a){return 0>a.toLowerCase().indexOf(b.toLowerCase())})});g.forEach(c,function(a){b+=' -type:"'+a+'" '})}return b};e.getItemQueryStringByTypeKeywords=function(a){var b="";a&&0<a.length&&(b=' typekeywords:"'+a.join(",")+'" ');return b};e.isNotEmptyString=function(a,b){var c=a&&"string"===typeof a;return c?b?c&&k.trim(a):!0:!1};e.isValidNumber=function(a){return"number"===typeof a&&!isNaN(a)};e.isObject=function(a){return a&&"object"===typeof a};e.getRandomString=function(){var a=Math.random().toString();
return a=a.slice(2,a.length)};e._getDomainsByServerName=function(a){var b=a.split("."),c=b.length;return g.map(b,k.hitch(this,function(a,f){a=b.slice(f,c);var d="",e=a.length-1;g.forEach(a,k.hitch(this,function(a,b){d+=a;b!==e&&(d+=".")}));return d}))};e.removeCookie=function(a,b){var c=this._getDomainsByServerName(window.location.hostname);g.forEach(c,k.hitch(this,function(c){F(a,null,{expires:-1,path:b});F(a,null,{expires:-1,path:b,domain:c});F(a,null,{expires:-1,path:b,domain:"."+c})}))};e.isLocaleChanged=
function(a,b){return!a.startWith(b)};e.hashToObject=function(a){a=a.replace("#","");a=L.queryToObject(a);for(var b in a)if(a.hasOwnProperty(b))try{a[b]=w.parse(a[b])}catch(c){}return a};e.reCreateObject=function(a){function b(a){var d=[];a.forEach(function(a){Array.isArray(a)?d.push(b(a)):"object"===typeof a?d.push(c(a)):d.push(a)});return d}function c(a){var d={},e;for(e in a)a.hasOwnProperty(e)&&(null===a[e]?d[e]=null:Array.isArray(a[e])?d[e]=b(a[e]):d[e]="object"===typeof a[e]?c(a[e]):a[e]);return d}
return Array.isArray(a)?b(a):c(a)};e.setVerticalCenter=function(a){setTimeout(function(){var b=r(".jimu-vcenter-text",a),c,d;g.forEach(b,function(a){c=m.getContentBox(a).h;m.setStyle(a,{lineHeight:c+"px"})},this);b=r(".jimu-vcenter",a);g.forEach(b,function(a){c=m.getContentBox(a).h;d=m.getContentBox(r(a).parent()[0]).h;m.setStyle(a,{marginTop:(d-c)/2+"px"})},this)},10)};e.merge=J;e.loadStyleLink=function(a,b,c){var d=new q,f,h=require(e.getRequireConfig()).toUrl(b);if(require.cache["url:"+h]){f=require.cache["url:"+
h];var l=h.split("/").pop(),h=h.substr(0,h.length-l.length);f=R(f,h);a=c?m.create("style",{id:a,type:"text/css"},m.byId(c),"before"):m.create("style",{id:a,type:"text/css"},document.getElementsByTagName("head")[0]);a.styleSheet&&!a.sheet?a.styleSheet.cssText=f:a.appendChild(m.toDom(f));d.resolve("load");return d}f=c?m.create("link",{id:a,rel:"stylesheet",type:"text/css",href:h},m.byId(c),"before"):m.create("link",{id:a,rel:"stylesheet",type:"text/css",href:h},document.getElementsByTagName("head")[0]);
B(f,"load",function(){d.resolve("load")});var u=setInterval(function(){var a;if(g.some(document.styleSheets,function(c){if(c.href&&c.href.substr(c.href.indexOf(b),c.href.length)===b)return a=c,!0}))try{!d.isFulfilled()&&(a.cssRules&&a.cssRules.length||a.rules&&a.rules.length)&&d.resolve("load"),clearInterval(u)}catch(x){}},50);return d};e.changeLocation=function(a){window.history.pushState&&window.history.pushState({path:a},"",a)};e.urlToObject=function(a){var b=null;-1===a.indexOf("#")?(b=t.urlToObject(a),
b.hash=null):(a=a.split("#"),b=t.urlToObject(a[0]),b.hash=a[1]?-1<a[1].indexOf("\x3d")?L.queryToObject(a[1]):a[1]:null);return b};e.addManifestProperies=function(a){a.icon=a.url+"images/icon.png";"theme"===a.category?ja(a):("undefined"!==typeof a["2D"]&&(a.support2D=a["2D"]),"undefined"!==typeof a["3D"]&&(a.support3D=a["3D"]),"undefined"===typeof a["2D"]&&"undefined"===typeof a["3D"]&&(a.support2D=!0),delete a["2D"],delete a["3D"],"undefined"===typeof a.properties&&(a.properties={}),Q.processWidgetProperties(a))};
e.getUniqueValues=function(a,b){var c=new q;a=a.replace(/\/*$/g,"")+"/generateRenderer";b=w.stringify({type:"uniqueValueDef",uniqueValueFields:[b]});H(a,{query:{classificationDef:b,f:"json"},responseType:"json",callbackParamName:"callback"}).then(k.hitch(this,function(a){var b=a.data;a=[];(b=b&&b.uniqueValueInfos)&&0<b.length&&(a=g.map(b,k.hitch(this,function(a){return a.value})));c.resolve(a)}),k.hitch(this,function(a){c.reject(a)}));return c};e.combineRadioCheckBoxWithLabel=function(a,b){var c=
!1;if(a&&1===a.nodeType&&"input"===a.tagName.toLowerCase()){var d=a.getAttribute("type")||"",d=d.toLowerCase();if("radio"===d||"checkbox"===d)c=!0}d=!1;b&&1===b.nodeType&&"label"===b.tagName.toLowerCase()&&(d=!0);c&&d&&(c=a.getAttribute("id"),c||(c="input_"+e.getRandomString(),a.setAttribute("id",c)),b.setAttribute("for",c),m.setStyle(b,"cursor","pointer"))};e.convertExtentToPolygon=function(a){var b=a.xmin,c=a.xmax,d=a.ymin,e=a.ymax;return new O({rings:[[[b,e],[c,e],[c,d],[b,d],[b,e]]],spatialReference:a.toJson()})};
e.combineGeometries=function(a){function b(a){var b={points:[],spatialReference:a[0].spatialReference.toJson()};g.forEach(a,function(a){b.points=b.points.concat(a.points)});return new da(b)}function c(a){var b={paths:[],spatialReference:a[0].spatialReference.toJson()};g.forEach(a,function(a){b.paths=b.paths.concat(a.paths)});return new ea(b)}function d(a){var b={rings:[],spatialReference:a[0].spatialReference.toJson()};g.forEach(a,function(a){"polygon"===a.type?b.rings=b.rings.concat(a.rings):"extent"===
a.type&&(a=e.convertExtentToPolygon(a),b.rings=b.rings.concat(a.rings))});return new O(b)}var f=null;if(a&&0<a.length)if(1===a.length)f=a[0];else{for(var h=null,l=null,u=null,n=null,x=0;x<a.length;x++){h=a[x];switch(h.type){case "point":case "multipoint":n="point";break;case "polyline":n="polyline";break;case "polygon":case "extent":n="polygon";break;default:return null}if(0===x)u=n;else if(u!==n)return null;if(x!==a.length-1&&(l=a[x+1],!h.spatialReference.equals(l.spatialReference)))return null}"point"===
n?f=b(a):"polyline"===n?f=c(a):"polygon"===n&&(f=d(a))}return f};e.isFeaturelayerUrlSupportQuery=function(a,b){var c=!1,d=/\/featureserver\//gi.test(a);a=/\/mapserver\//gi.test(a);b=(b||"").toLowerCase();d?c=0<=b.indexOf("query"):a&&(c=0<=b.indexOf("data"));return c};e.isImageServiceSupportQuery=function(a){return 0<=(a||"").toLowerCase().indexOf("catalog")};e.isStringEndWith=function(a,b){return a.lastIndexOf(b)+b.length===a.length};e.processManifestLabel=function(a,b){a.label=a.i18nLabels&&(a.i18nLabels[b]||
a.i18nLabels.defaultLabel)||a.label||a.name;a.layouts&&g.forEach(a.layouts,function(c){var d="i18nLabels_layout_"+c.name;c.label=a[d]&&(a[d][b]||a[d].defaultLabel)||c.label||c.name});a.styles&&g.forEach(a.styles,function(c){var d="i18nLabels_style_"+c.name;c.label=a[d]&&(a[d][b]||a[d].defaultLabel)||c.label||c.name})};e.addManifest2WidgetJson=function(a,b){k.mixin(a,b.properties);a.name=b.name;a.label||(a.label=b.label);a.manifest=b};e.widgetJson=function(){var a={addManifest2WidgetJson:function(a,
c){k.mixin(a,c.properties);a.name=c.name;a.label||(a.label=c.label);a.manifest=c;a.isRemote=c.isRemote;a.isRemote&&(a.itemId=c.itemId);c.featureActions&&(a.featureActions=c.featureActions);a.icon||(a.icon=c.icon);a.thumbnail||(a.thumbnail=c.thumbnail);a.folderUrl=c.folderUrl;a.amdFolder=c.amdFolder},removeManifestFromWidgetJson:function(a){if(a.manifest){for(var b in a.manifest.properties)a[b]=void 0;a.name=void 0;a.label=void 0;a.featureActions=void 0;a.manifest=void 0}},getUriFromItem:function(b){return b.url?
a.getFolderUrlFromItem(b)+"Widget":null},getFolderUrlFromItem:function(a){if(!a.url)return null;a=/manifest\.json$/.test(a.url)?a.url.substring(0,a.url.length-13):/\/$/.test(a.url)?a.url:a.url+"/";"https:"===window.location.protocol&&(a=a.replace(/^http:\/\//,"https://"));return a}};return a}();e.addI18NLabel=function(a){var b=new q;if(a.i18nLabels)return b.resolve(a),b;a.i18nLabels={};if(a.properties&&!1===a.properties.hasLocale)return b.resolve(a),b;var c="widget"===a.category?"_widgetLabel":"_themeLabel";
require(e.getRequireConfig(),["dojo/i18n!"+a.amdFolder+"nls/strings"],function(d){a.i18nLabels[dojoConfig.locale]=d[c];"theme"===a.category&&(a.layouts&&a.layouts.forEach(function(b){a["i18nLabels_layout_"+b.name]={};a["i18nLabels_layout_"+b.name][dojoConfig.locale]=d["_layout_"+b.name]}),a.styles&&a.styles.forEach(function(b){a["i18nLabels_style_"+b.name]={};a["i18nLabels_style_"+b.name][dojoConfig.locale]=d["_style_"+b.name]}));b.resolve(a)});return b};e.localizeNumber=function(a,b){var c=(a.toString().split(".")[1]||
"").length,d="",d=b&&isFinite(b.places)&&b.places,d=0<d||0<c?"#,###,###,##0.0"+Array.prototype.join.call({length:0<d?d+1:c},"0"):"#,###,###,##0",c={locale:A.locale,pattern:d};k.mixin(c,b||{});try{return M.format(a,c)}catch(f){return console.error(f),a.toLocaleString()}};e.parseNumber=function(a,b){var c={locale:A.locale};k.mixin(c,b||{});try{return M.parse(a,c)}catch(d){return console.error(d),a}};e.localizeDate=function(a,b){var c={locale:A.locale,fullYear:!0};k.mixin(c,b||{});try{return Y.format(a,
c)}catch(d){return console.error(d),"date"===c.selector?a.toLocaleDateString():"time"===c.selector?a.toLocaleTimeString():a.toLocaleString()}};e.localizeNumberByFieldInfo=function(a,b){var c=null,c=k.exists("format.places",b)&&b.format.places,c=e.localizeNumber(a,{places:c});return k.exists("format.digitSeparator",b)&&!b.format.digitSeparator?c.toString().replace(new RegExp("\\"+Z.group,"g"),""):c};e.fieldFormatter={getFormattedUrl:function(a){if(a&&"string"===typeof a){var b=a.indexOf("http:");-1===
b&&(b=a.indexOf("https:"));if(-1<b&&-1===a.indexOf("href\x3d")){var c=a.indexOf(" ",b);-1===c&&(c=a.length);var d=a.substring(b,c);a=a.substring(0,b)+'\x3cA href\x3d"'+d+'" target\x3d"_blank"\x3e'+d+"\x3c/A\x3e"+a.substring(c,a.length)}}return a||""},getFormattedNumber:function(a,b){if("number"===typeof a){var c=(a.toString().split(".")[1]||"").length;a=e.localizeNumberByFieldInfo(a,{format:{places:b&&"number"===typeof b.places?parseInt(b.places,10):c,digitSeparator:b&&b.digitSeparator}});return'\x3cspan class\x3d"jimu-numeric-value"\x3e'+
(a||"")+"\x3c/span\x3e"}return a},getFormattedDate:function(a){a&&(a=e.localizeDate(new Date(a),{fullYear:!0}));return a||""},getCodedValue:function(a,b){if(a&&a.codedValues){for(var c=0,d=a.codedValues.length;c<d;c++){var f=a.codedValues[c];if(e.isDefined(b)&&k.exists("code",f)&&b.toString()===f.code.toString())return f.name}return b}return b||null},getTypeName:function(a,b){for(var c=b.length,d=0;d<c;d++)if(a===b[d].id)return b[d].name;return a}};e.addRelativePathInCss=R;e.url={isAbsolute:function(a){return a?
a.startWith("http")||a.startWith("/"):!1},removeQueryParamFromUrl:function(a,b){a=t.urlToObject(a);a.query&&delete a.query[b];b=a.path;for(var c in a.query)b=b===a.path?b+"?"+c+"\x3d"+a.query[c]:b+"\x26"+c+"\x3d"+a.query[c];return b},addQueryParamToUrl:function(a,b,c){a=t.urlToObject(a);a.query||(a.query={});a.query[b]=c;b=a.path;for(var d in a.query)b=b===a.path?b+"?"+d+"\x3d"+a.query[d]:b+"\x26"+d+"\x3d"+a.query[d];return b}};e.processUrlInWidgetConfig=function(a,b){if(a)return a.startWith("data:")||
a.startWith("http")||a.startWith("/")?a:a.startWith("${appPath}")?a.replace("${appPath}",window.appInfo.appPath):b+a};e.processUrlInAppConfig=function(a){if(a)return a.startWith("data:")||a.startWith("http")||a.startWith("/")?a:window.appInfo.appPath+a};e.getLocationUrlWithoutHashAndQueryParams=function(){var a=window.location,b=a.protocol+"//"+a.host+a.pathname,a=t.urlToObject(a.href);a.query&&a.query.apiurl&&(b=e.url.addQueryParamToUrl(b,"apiurl",a.query.apiurl));return b};e.getDefaultWebMapThumbnail=
function(){return require.toUrl("jimu/images/webmap.png")};e.invertColor=function(a){a=a.substring(1);3===a.length&&(a=a.slice(0,1)+a.slice(0,1)+a.slice(1,1)+a.slice(1,1)+a.slice(2,1)+a.slice(2,1));a=parseInt(a,16);return 7829367<a?"#000000":"#ffffff"};e.mixinAppConfigPosition=function(a,b){var c=k.clone(a);if(!b)return c;b=k.clone(b);var d=c.widgetOnScreen,e=b.widgetOnScreen;e&&e.widgets&&("[object Object]"===Object.prototype.toString.call(e.widgets)?g.forEach(d.widgets,function(a,b){b=a.uri?a.uri:
"ph_"+b;e.widgets[b]&&e.widgets[b].position&&(e.widgets[b].position.relativeTo||(e.widgets[b].position.relativeTo="map"),a.position=e.widgets[b].position)},this):g.forEach(e.widgets,function(a,b){a.position&&!a.position.relativeTo&&(a.position.relativeTo="map");d.widgets[b]&&a.position&&(d.widgets[b].position=a.position)}));e&&e.groups&&("[object Object]"===Object.prototype.toString.call(e.groups)?g.forEach(d.groups,function(a,b){b=a.label?a.label:"g_"+b;e.groups[b]&&e.groups[b].panel&&e.groups[b].panel.position&&
(e.groups[b].panel.position.relativeTo||(e.groups[b].panel.position.relativeTo="map"),a.panel.position=e.groups[b].panel.position)},this):(a=a.layoutDefinition?a.layoutDefinition.manager:"jimu/layoutManagers/AbsolutePositionLayoutManager","jimu/layoutManagers/AbsolutePositionLayoutManager"===a?g.forEach(e.groups,function(a,b){a.panel&&a.panel.position&&!a.panel.position.relativeTo&&(a.panel.position.relativeTo="map");d.groups[b]&&a.panel&&a.panel.position&&(d.groups[b].panel.position=a.panel.position)}):
"jimu/layoutManagers/GridLayoutManager"===a&&(d.groups=T(d.groups,e.groups.map(function(a){return a.id})))));b.map&&b.map.position&&(c.map?c.map.position=b.map.position:c.map={position:b.map.position});b.widgetPool&&b.widgetPool.panel&&(b.widgetPool.panel.position&&!b.widgetPool.panel.position.relativeTo&&(b.widgetPool.panel.position.relativeTo="map"),c.widgetPool.panel.position=b.widgetPool.panel.position);b.mobileLayout&&(c.mobileLayout=b.mobileLayout);return c};e.handleGridLayoutOnScreenGroupChange=
T;e.template={groupIdentification:"groups\\[.+\\]",widgetIdentification:"widgets\\[.+\\]",getSearchRange:function(a,b,c){var d=-1;b=a.search(new RegExp(b));0<=b&&(a=a.slice(b,a.length),a=a.indexOf(c),d=b+a+c.length);return{firstPos:b,lastPos:d}},setConfigValue:function(a,b,c){K(a,b,c)},getConfigValue:function(a,b){return K(a,b)},setConfigValueWithId:function(a,b,c){U(a,b,c)},getConfigValueWithId:function(a,b){return U(a,b)},getKeyInfo:function(a){var b=this.getWidgetIdByKey(a);if(null!==b)return{type:"widget",
id:b};a=this.getGroupIdByKey(a);return null!==a?{type:"group",id:a}:{type:"unknow",id:null}},getWidgetIdByKey:function(a){var b=e.template.getSearchRange(a,e.template.widgetIdentification,"]");if(-1===b.firstPos)a=null;else{var c=a.slice(b.firstPos,b.lastPos);a=a.slice(b.firstPos+c.indexOf("[")+1,b.lastPos-1)}return a},getGroupIdByKey:function(a){var b=e.template.getSearchRange(a,e.template.groupIdentification,"]");if(-1===b.firstPos)a=null;else{var c=a.slice(b.firstPos,b.lastPos);a=a.slice(b.firstPos+
c.indexOf("[")+1,b.lastPos-1)}return a},getConfigedWidgetsByTemplateConfig:function(a){var b=[],c=e.template.widgetIdentification+"_config",d;g.forEach(a.configurationSettings,function(a){g.forEach(a.fields,function(a){a.fieldName&&(d=e.template.getSearchRange(a.fieldName,c,"]"),0<=d.firstPos&&(a=e.template.getWidgetIdByKey(a.fieldName),-1===b.indexOf(a)&&b.push(a)))},this)},this);return b},mergeTemplateAppConfigToAppConfig:function(a,b,c){function d(a){var b=[];g.forEach(a,function(a){a&&b.push(a)},
this);return b}var f=a.widgetOnScreen,h=a.portalUrl;b.values.webmap&&(a.map.itemId=b.values.webmap);c&&(a.map.mapOptions&&e.deleteMapOptions(a.map.mapOptions),a.map.portalUrl=h,b.values.app_title||(b.values.app_title=c.title),b.values.app_subtitle||(b.values.app_subtitle=c.snippet));for(var l in b.values)"webmap"!==l&&e.template.setConfigValueWithId(a,l,b.values[l]);a.widgetPool.widgets=d(a.widgetPool.widgets);f.widgets=d(f.widgets);if(a.widgetPool.groups)for(b=0;b<a.widgetPool.groups.length;b++)a.widgetPool.groups[b].widgets=
d(a.widgetPool.groups[b].widgets);if(f.groups)for(b=0;b<f.groups.length;b++)f.groups[b].widgets=d(f.groups[b].widgets);return a}};e.deleteMapOptions=function(a){a&&(delete a.extent,delete a.lods,delete a.center,delete a.scale,delete a.zoom,delete a.maxScale,delete a.maxZoom,delete a.minScale,delete a.minZoom,delete a.initialState)};e.localeIsSame=function(a,b){return a.split("-")[0]===b.split("-")[0]};e.graphicsExtent=function(){return null};e.sanitizeHTML=function(a){return html_sanitize(a,function(a){return a},
function(a){return a})};e.stripHTML=function(a){return a?-1<a.indexOf("\x3c")&&-1<a.indexOf("\x3e")?a.replace(/<(?:.|\s)*?>/g,""):a:a};e.removeSuffixSlashes=function(a){return a.replace(/\/*$/g,"")};e.getBestDisplayAttributes=function(a,b){var c={},d=null,f;for(f in a)d=e.getBestDisplayValue(f,a,b),c[f]=d;return c};e.getBestDisplayValue=function(a,b,c){var d="",f=null;k.isArrayLike(c)?f=e.getFieldInfoByFieldName(c,a):"object"===typeof c&&c.name===a&&(f=c);f&&(d=b[a],"esriFieldTypeDate"===f.type?d&&
(a=new Date(parseInt(d,10)),d=e._tryLocaleDate(a)):"number"===typeof d&&(f.domain&&"codedValue"===f.domain.type?g.some(f.domain.codedValues,function(a){if(a.code===d)return d=a.name,!0}):d=e._tryLocaleNumber(d)));if(null===d||void 0===d)d="";return d};e._tryLocaleNumber=function(a){var b=e.localizeNumber(a);if(null===b||void 0===b)b=a;return b};e._tryLocaleDate=function(a){var b=e.localizeDate(a);b||(b=a.toLocaleDateString());return b};e.getFieldInfoByFieldName=function(a,b){var c=null;a&&0<a.length&&
g.some(a,k.hitch(this,function(a){return a.name===b?(c=a,!0):!1}));return c};e.containsNonLatinCharacter=function(a){for(var b=0;b<a.length;b++)if(255<a.charCodeAt(b))return!0;return!1};e.isVersion4API=function(){return 0===aa.version.indexOf("4")};e.getEsriConfig=function(){return p};e.getEsriConfigRequestObject=function(){var a=null;return a=e.isVersion4API()?p.request:p.defaults.io};e.setGlobalGeometryService=function(a){a=new G(a);e.isVersion4API()?p.geometryService=a:p.defaults.geometryService=
a;return a};e.getQueryableFeatureLayersFromMap=function(a){var b=[];a.layers&&(b=a.layers.filter(function(a){return"esri.layers.FeatureLayer"===a.declaredClass&&a.url&&a.supportedQueryFormats&&0<=a.supportedQueryFormats.toUpperCase().indexOf("JSON")}));return b};e.has=function(a){var b=z(a);if(b)return b;if("ie"===a.toLowerCase()){a=0;var c=/MSIE (\d+\.\d+);/.test(navigator.userAgent),d=!!navigator.userAgent.match(/Trident\/7.0/),e=navigator.userAgent.indexOf("rv:11.0");c&&(a=Number(RegExp.$1));-1!==
navigator.appVersion.indexOf("MSIE 10")&&(a=10);d&&-1!==e&&(a=11);return 11===a&&11||b}if("edge"===a.toLowerCase())return navigator.userAgent.split("Edge/")[1]||b};e.detectUserAgent=function(){var a={},b={},c=navigator.userAgent,d=navigator.platform,e=c.match(/Web[kK]it[\/]{0,1}([\d.]+)/),h=c.match(/(Android);?[\s\/]+([\d.]+)?/),l=!!c.match(/\(Macintosh\; Intel /),u=c.match(/(iPad).*OS\s([\d_]+)/),n=c.match(/(iPod)(.*OS\s([\d_]+))?/),k=!u&&c.match(/(iPhone\sOS)\s([\d_]+)/),g=c.match(/(webOS|hpwOS)[\s\/]([\d.]+)/),
d=/Win\d{2}|Windows/.test(d),m=c.match(/Windows Phone ([\d.]+)/),q=g&&c.match(/TouchPad/),p=c.match(/Kindle\/([\d.]+)/),r=c.match(/Silk\/([\d._]+)/),t=c.match(/(BlackBerry).*Version\/([\d.]+)/),v=c.match(/(BB10).*Version\/([\d.]+)/),w=c.match(/(RIM\sTablet\sOS)\s([\d.]+)/),y=c.match(/PlayBook/),C=c.match(/Chrome\/([\d.]+)/)||c.match(/CriOS\/([\d.]+)/),D=c.match(/Firefox\/([\d.]+)/),z=c.match(/\((?:Mobile|Tablet); rv:([\d.]+)\).*Firefox\/[\d.]+/),E=c.match(/MSIE\s([\d.]+)/)||c.match(/Trident\/[\d](?=[^\?]+).*rv:([0-9.].)/),
A=!C&&c.match(/(iPhone|iPod|iPad).*AppleWebKit(?!.*Safari)/),B=A||c.match(/Version\/([\d.]+)([^S](Safari)|[^M]*(Mobile)[^S]*(Safari))/);b.webkit=!!e;b.webkit&&(b.version=e[1]);h&&(a.android=!0,a.version=h[2]);k&&!n&&(a.ios=a.iphone=!0,a.version=k[2].replace(/_/g,"."));u&&(a.ios=a.ipad=!0,a.version=u[2].replace(/_/g,"."));n&&(a.ios=a.ipod=!0,a.version=n[3]?n[3].replace(/_/g,"."):null);m&&(a.wp=!0,a.version=m[1]);g&&(a.webos=!0,a.version=g[2]);q&&(a.touchpad=!0);t&&(a.blackberry=!0,a.version=t[2]);
v&&(a.bb10=!0,a.version=v[2]);w&&(a.rimtabletos=!0,a.version=w[2]);y&&(b.playbook=!0);p&&(a.kindle=!0,a.version=p[1]);r&&(b.silk=!0,b.version=r[1]);!r&&a.android&&c.match(/Kindle Fire/)&&(b.silk=!0);C&&(b.chrome=!0,b.version=C[1]);D&&(b.firefox=!0,b.version=D[1]);z&&(a.firefoxos=!0,a.version=z[1]);E&&(b.ie=!0,b.version=E[1]);B&&(l||a.ios||d)&&(b.safari=!0,a.ios||(b.version=B[1]));A&&(b.webview=!0);a.tablet=!!(u||y||h&&!c.match(/Mobile/)||D&&c.match(/Tablet/)||E&&!c.match(/Phone/)&&c.match(/Touch/));
a.phone=!(a.tablet||a.ipod||!(h||k||g||t||v||C&&c.match(/Android/)||C&&c.match(/CriOS\/([\d.]+)/)||D&&c.match(/Mobile/)||E&&c.match(/Touch/)));return{os:a,browser:b}};e.isMobileUa=function(){var a=e.detectUserAgent();return!0===a.os.phone||!0===a.os.tablet?!0:!1};e.isNeedHttpsButNot=function(){var a=navigator.geolocation,b=window.hasOwnProperty("isSecureContext");return(b&&window.isSecureContext||!b&&"https:"===window.location.protocol)&&a?!1:!0};e.isInConfigOrPreviewWindow=function(){var a=!1;try{a=
!window.isBuilder&&window.parent&&window.parent!==window&&window.parent.isBuilder}catch(b){a=!1}return!!a};e.getAppHref=function(){var a="";return a=e.isInConfigOrPreviewWindow()?window.parent.location.href:window.location.href};e.getAppIdFromUrl=function(){var a=!0,b=e.getAppHref();if(-1!==b.indexOf("id\x3d")||-1!==b.indexOf("appid\x3d")||-1!==b.indexOf("apps"))a=!1;if(!0===a)return b;a=this.urlToObject(window.location.href);if(a.query&&(a.query.id||a.query.appid))return a.query.id||a.query.appid;
if(window.appInfo){if(window.appInfo.id)return window.appInfo.id;if(window.appInfo.appPath){if(a=window.appInfo.appPath.split("/"),a.length&&2<a.length)return a[a.length-2]}else console.error("CAN NOT getAppIdFromUrl")}};e.getEditorContentHeight=function(a,b,c){var d=new q;this._content=a;this._dom=b;this._domParam=c;var e=setTimeout(k.hitch(this,function(){clearTimeout(e);e=null;var a=0,b=this._domParam.contentWidth;try{var c=document.createElement("div");c.setAttribute("id","fakeContent");m.setStyle(c,
"background-size","contain");c.innerHTML=this._content;this._dom.appendChild(c);if(c){var f=r("img",c);f&&f.length&&f.style({maxWidth:b-20+"px"});m.setStyle(c,"position","absolute");m.setStyle(c,"width",b+"px");m.setStyle(c,"left","-99999px");m.setStyle(c,"top","-99999px");m.setStyle(c,"visibility","hidden");var g=m.getContentBox(c);g.h&&(a=g.h,a+=this._domParam.contentMarginTop+this._domParam.footerHeight+8)}}catch(ka){console.error("can't getEditorContentHeight"+ka),a=200}d.resolve(a)}),1500);return d};
e.getEditorTextColor=function(a,b){return{name:"dijit.editor.plugins.EditorTextColor",custom:{recordUID:e.getColorRecordName(a),forceAttr:b}}};e.getEditorBackgroundColor=function(a){return{name:"dijit.editor.plugins.EditorBackgroundColor",custom:{recordUID:e.getColorRecordName(a)}}};e.getColorRecordName=function(a){return"wab_cr_"+(a||"")};e.isEsriDomain=function(a){return/^https?:\/\/(?:[\w\-\_]+\.)+(?:esri|arcgis)\.com/.test(a)};e.b64toBlob=function(a,b,c){b=b||"";c=c||512;a=window.atob(a.replace(/^data:image\/(png|jpg|jpeg|gif);base64,/,
""));for(var d=[],e=0;e<a.length;e+=c){for(var h=a.slice(e,e+c),l=Array(h.length),g=0;g<h.length;g++)l[g]=h.charCodeAt(g);h=new Uint8Array(l);d.push(h)}return new Blob(d,{type:b})};e.subtractionArray=function(a,b){for(var c=a.length-1;0<=c;c--)for(var d=a[c],e=b.length-1;0<=e;e--)if(d===b[e]){a.splice(c,1);b.splice(e,1);break}return a};e.resourcesUrlToBlob=function(a){return H({url:a,handleAs:"blob"})};e.processItemResourceOfAppConfig=function(a,b){function c(a){var b=a.obj,c=a.key,d={obj:b,key:c};
"number"===typeof a.i?(d.i=a.i,d.value=b[c][a.i]):d.value=b[c];return d}function d(a){for(var b in a)if("object"===typeof a[b])if(Array.isArray(a[b]))for(var c=a,f=b,g=0;g<c[f].length;g++)"string"===typeof c[f][g]?e(c,f,g):"object"===typeof c[f][g]&&d(c[f][g]);else d(a[b]);else"string"===typeof a[b]&&e(a,b)}function e(a,d,e){"number"===typeof e?b.test(a[d][e])&&(g=b.func(c({obj:a,key:d,i:e})),"function"===typeof g.then?l.push(g):h.push(g)):b.test(a[d])&&(g=b.func(c({obj:a,key:d})),"function"===typeof g.then?
l.push(g):h.push(g))}var h=[],l=[],g;d(a);return 0<l.length?X(l).then(function(b){0<h.length&&(b=b.concat(h));return{appConfig:a,result:b}}):{appConfig:a,result:h}};e.isDefined=function(a){return void 0!==a&&null!==a};e.getDefaultPopupInfo=function(a,b,c){var d=null;a&&a.fields&&(d={title:b,fieldInfos:[],description:null,showAttachments:!0,mediaInfos:[]},g.forEach(a.fields,function(a){var b=!1;c?g.some(c,k.hitch(this,function(b){return b&&a.name.toLowerCase()===b.toLowerCase()}))&&(b=!0):b=!0;b&&
(b=this.getDefaultPortalFieldInfo(a),b.visible=!0,b.isEditable=a.editable,d.fieldInfos.push(b))},this));return d};e.getDefaultPortalFieldInfo=function(a){var b=a.name,b={fieldName:b,label:a.alias||b,tooltip:"",visible:!1,format:null,stringFieldOption:"textbox"};switch(a.type){case "esriFieldTypeSmallInteger":case "esriFieldTypeInteger":b.format={places:0,digitSeparator:!0};break;case "esriFieldTypeSingle":case "esriFieldTypeDouble":b.format={places:2,digitSeparator:!0};break;case "esriFieldTypeDate":b.format=
{dateFormat:"longMonthDayYear"}}return b};e.checkEssentialAppsLicense=function(a,b,c){var d=P.getStandardPortalUrl(b.portalUrl),e=P.getSharingUrl(d),d=new ha({appId:"arcgisWebApps",portalUrl:d});I.registerOAuthInfos([d]);return c?I.checkAppAccess(e,"arcgisWebApps"):b.getItemById(a).then(function(a){if("public"!==a.access)return I.checkAppAccess(e,"arcgisWebApps",{force:!0})})};e.getStyleColorInTheme=function(a){var b=new q,c,d;window&&window.isBuilder?(d="./stemapp3d/themes/",c=window.appConfig):
(d="./themes/",c=window.getAppConfig());if(c&&c.theme.customStyles&&c.theme.customStyles.mainBackgroundColor)return b.resolve(c.theme.customStyles.mainBackgroundColor),b.promise;var e=c.theme.name,g=c.theme.styles[0];a&&(g=a);H(d+e+"/manifest.json",{responseType:"json"}).then(k.hitch(this,function(a){if(a&&a.data){a=a.data.styles;for(var c=0;c<a.length;c++){var d=a[c];d.name===g&&b.resolve(d.styleColor)}}}),k.hitch(this,function(a){console.error(a);b.reject(null)}));return b.promise};return e});