// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/_base/html dojo/_base/sniff dojo/_base/config dojo/io-query dojo/query dojo/NodeList-traverse dojo/Deferred dojo/promise/all dojo/on dojo/json dojo/cookie dojo/number dojo/date/locale dojo/i18n!dojo/cldr/nls/number dojox/encoding/base64 esri/kernel esri/config esri/core/lang esri/geometry/SpatialReference esri/geometry/Extent esri/geometry/Multipoint esri/geometry/Polyline esri/geometry/Polygon esri/geometry/support/webMercatorUtils esri/tasks/GeometryService esri/tasks/support/ProjectParameters esri/core/urlUtils esri/request ./shared/utils".split(" "),
function(g,k,h,y,z,F,u,fa,q,R,A,v,B,G,S,T,H,U,n,V,W,X,Y,Z,I,aa,C,ba,r,J,K){function ca(a,b){a=a||"";var c=0,d=[{test:window.File&&window.FileReader&&window.FileList&&window.Blob||!e.file.isEnabledFlash(),failure:[a+"libs/polyfills/fileAPI/FileAPI.js"],callback:function(){c++;c===d.length&&b()}}];for(a=0;a<d.length;a++)testLoad(d[a])}function L(a,b){var c=a.match(/url\([^)]+\)/gi),d,f;if(null===c||""===b)return a;for(d=0;d<c.length;d++)if(f=c[d].match(/(url\(["|']?)(.*)((?:['|"]?)\))/i),4<=f.length){var l=
f[2];/^data:image\/.*;/.test(l)||(b.endWith("/")||(b+="/"),a=a.replace(f[1]+l+f[3],f[1]+b+l+f[3]))}return a}function D(a,b){var c=Array.isArray(b),d=c&&[]||{};c?(a=a||[],d=d.concat(a),b.forEach(function(b,c){"undefined"===typeof a[c]?d[c]=b:"object"===typeof b?d[c]=D(a[c],b):-1===a.indexOf(b)&&d.push(b)})):(a&&"object"===typeof a&&Object.keys(a).forEach(function(b){d[b]=a[b]}),Object.keys(b).forEach(function(c){d[c]="object"===typeof b[c]&&b[c]?a[c]?D(a[c],b[c]):b[c]:b[c]}));return d}function M(a){var b,
c={};b=a.indexOf("/");a.substring(0,b);b=a.substring(0,a.lastIndexOf("/")+1);c.folderUrl=require(e.getRequireConfig()).toUrl(b);c.amdFolder=b;c.url=c.folderUrl;if(/^http(s)?:\/\//.test(a)||/^\/\//.test(a))c.isRemote=!0;return c}function da(a){a.panels.forEach(function(a){a.uri="panels/"+a.name+"/Panel.js"});a.styles.forEach(function(a){a.uri="styles/"+a.name+"/style.css"});a.layouts.forEach(function(a){a.uri="layouts/"+a.name+"/config.json";a.icon="layouts/"+a.name+"/icon.png";a.RTLIcon="layouts/"+
a.name+"/icon_rtl.png"})}function N(a,b){var c=a.map(function(a){return a.id});k.forEach(b,function(b){0>c.indexOf(b)&&a.push({id:b,widgets:[]})},this);var d=[];a=k.filter(a,function(a){return 0>b.indexOf(a.id)?(d.push(a),!1):!0},this);if(0===a.length)return[];var f=a[a.length-1];k.forEach(d,function(a){f.widgets=f.widgets.concat(a.widgets)},this);return a=a.sort(function(a,c){return b.indexOf(a.id)-b.indexOf(c.id)})}function E(a,b,c){function d(a,b){return g.isArray(a[b.key])?a[b.key][b.index]:a[b.key]}
b=function(a){var b=[];a.split("_").forEach(function(a){var c=!1,d;"--"===a.slice(a.length-2)&&(c=!0,a=a.slice(0,a.length-2));d=a.search(/\[[0-9]+\]/);-1===d&&(d=a.length);b.push({key:a.slice(0,d),index:Number(a.slice(d+1,-1)),deleteFlag:c})});return b}(b);for(var f=1;f<b.length-1;f++)if(a=d(a,b[f]),!a)return;if(b[b.length-1].deleteFlag)!0===c&&(g.isArray(a[b[b.length-1].key])?delete a[b[b.length-1].key][b[b.length-1].index]:delete a[b[b.length-1].key]);else if(g.isArray(a[b[b.length-1].key])){if(void 0===
c)return a[b[b.length-1].key][b[b.length-1].index];a[b[b.length-1].key][b[b.length-1].index]=c}else{if(void 0===c)return a[b[b.length-1].key];a[b[b.length-1].key]=c}}function O(a,b,c){function d(c){c=e.template.getSearchRange(b,c,"]");var d=b.slice(c.firstPos,c.lastPos);return-1!==c.firstPos?(d=b.slice(c.firstPos+d.indexOf("[")+1,c.lastPos-1),c=b.slice(c.lastPos+1),(d=e.getConfigElementById(a,d))?{object:d,key:"section_"+c,state:"isSection"}:{state:"deleted"}):{state:"isNotSection"}}var f=a,l=b=b.replace(/\//g,
"_"),m=d("groups\\[.+\\]");if("deleted"!==m.state&&("isSection"===m.state&&(f=m.object,l=m.key),m=d("widgets\\[.+\\]"),"delete"!==m.state))return"isSection"===m.state&&(f=m.object,l=m.key),E(f,l,c)}var e={},P={geometryService:"http://utility.arcgisonline.com/arcgis/rest/services/Geometry/GeometryServer"};g.mixin(e,K);window.atob||(window.atob=function(a){a=H.decode(a);for(var b="",c=0,d=a.length;c<d;c++)b+=String.fromCharCode(a[c]);return b});window.btob||(window.btob=function(a){for(var b=[],c=0,
d=a.length;c<d;c++)b.push(String.charCodeAt(a[c]));return H.encode(b)});var x="unload",Q=[];require.on("error",function(a){k.forEach(Q,function(b){a.info[0]&&-1<a.info[0].indexOf(b.resKey)&&b.def.reject(a);for(var c in a.info)-1<c.indexOf(b.resKey)&&b.def.reject(a)})});e.checkError=function(a,b){Q.push({resKey:a,def:b})};e.replacePlaceHolder=function(a,b){var c=v.stringify(a),d=c.match(/\$\{(\w)+\}/g);if(null===d)return a;for(a=0;a<d.length;a++){var f=d[a].match(/(\w)+/g)[0];b[f]&&(c=c.replace(d[a],
b[f]))}return v.parse(c)};e.changeUnit=function(a){var b=Math.abs(a),c;a=Math.floor(b);c=Math.floor(60*(b-a));b=(60*(60*(b-a)-c)).toFixed(2);return a+"\u00b0"+(10>c?"0"+c:c)+"'"+(10>b?"0"+b:b)+'"'};e.formatTime=function(a){var b=a/1E3;a=Math.floor(b/60);b=Number(b-60*a).toFixed(1);return(10>a?"0"+a:a)+":"+(10>b?"0"+b:b)};e.parseTime=function(a){var b=/(\d{2,})\:(\d{2})\.(\d{1})/;if(!b.test(a))return console.log("wrong time format."),-1;a=a.match(b);return 1E3*(60*parseInt(a[1],10)+parseInt(a[2],10)+
parseInt(a[3],10)/10)};e.preloadImg=function(a,b){var c=[],c="string"===typeof a?[a]:a;k.forEach(c,function(a){(new Image).src=b?b+a:a})};var t=null;e.getImagesSize=function(a){var b=new q;if(!a||0!==a.indexOf("http"))return b.reject(),b;null===t&&(t=h.create("img",{id:"__test-image-size",style:{position:"absolute",left:"-9999px",top:"-9999px"}},document.body));var c=A(t,"load",function(){clearTimeout(d);d=null;c.remove();var a=h.getContentBox(t);1===a.w&&1===a.h||0===a.w||0===a.h?b.reject():b.resolve([a.w,
a.h])},{}),d=setTimeout(function(){clearTimeout(d);d=null;b.reject()},5E3);h.setAttr(t,"src",a);return b};e.getPositionStyle=function(a){var b={};if(!a)return b;a=g.clone(a);if(window.isRTL){var c;"undefined"!==typeof a.left&&"undefined"!==typeof a.right?(c=a.left,a.left=a.right,a.right=c):"undefined"!==typeof a.left?(a.right=a.left,delete a.left):"undefined"!==typeof a.right&&(a.left=a.right,delete a.right);"undefined"!==typeof a.paddingLeft&&"undefined"!==typeof a.paddingRight?(c=a.paddingLeft,
a.paddingLeft=a.paddingRight,a.paddingRight=c):"undefined"!==typeof a.paddingLeft?(a.paddingRight=a.paddingLeft,delete a.paddingLeft):"undefined"!==typeof a.paddingRight&&(a.paddingLeft=a.paddingRight,delete a.paddingRight);"undefined"!==typeof a.marginLeft&&"undefined"!==typeof a.marginRight?(c=a.marginLeft,a.marginLeft=a.marginRight,a.marginRight=c):"undefined"!==typeof a.marginLeft?(a.marginRight=a.marginLeft,delete a.marginLeft):"undefined"!==typeof a.marginRight&&(a.marginLeft=a.marginRight,
delete a.marginRight)}c="left top right bottom width height padding paddingLeft paddingRight paddingTop paddingBottom margin marginLeft marginRight marginTop marginBottom".split(" ");for(var d=0;d<c.length;d++){var f=c[d];"number"===typeof a[f]?b[f]=a[f]+"px":"undefined"!==typeof a[f]?b[f]=a[f]:"padding"===f.substr(0,7)||"margin"===f.substr(0,7)?b[f]=0:b[f]="auto"}b.zIndex="undefined"===typeof a.zIndex?"auto":a.zIndex;return b};e.isEqual=function(a,b){function c(a,b){var e;if(null===a&&null===b||
"undefined"===typeof a&&"undefined"===typeof b)return!0;if(null===a&&null!==b||null===b&&null!==a||"undefined"===typeof a&&"undefined"!==typeof b||"undefined"===typeof b&&"undefined"!==typeof a)return!1;if(isNaN(a)&&isNaN(b)&&"number"===typeof a&&"number"===typeof b||a===b)return!0;if("function"===typeof a&&"function"===typeof b||a instanceof Date&&b instanceof Date||a instanceof RegExp&&b instanceof RegExp||a instanceof String&&b instanceof String||a instanceof Number&&b instanceof Number)return a.toString()===
b.toString();if(-1<d.indexOf(a)||-1<f.indexOf(b))return!1;if(null!==b){for(e in b)if(b.hasOwnProperty(e)!==a.hasOwnProperty(e)||typeof b[e]!==typeof a[e])return!1;for(e in a){if(b.hasOwnProperty(e)!==a.hasOwnProperty(e)||typeof b[e]!==typeof a[e])return!1;switch(typeof a[e]){case "object":case "function":d.push(a);f.push(b);if(!c(a[e],b[e]))return!1;d.pop();f.pop();break;default:if(a[e]!==b[e])return!1}}}return!0}var d,f;d=[];f=[];return c(a,b)?!0:!1};e.getUriInfo=M;e.file={loadFileAPI:function(){var a=
new q;if("unload"===x){var b=window.isBuilder?"stemapp/":"";window.FileAPI={debug:!1,flash:!0,staticPath:b+"libs/polyfills/fileAPI/",flashUrl:b+"libs/polyfills/fileAPI/FileAPI.flash.swf",flashImageUrl:b+"libs/polyfills/fileAPI/FileAPI.flash.image.swf"};ca(b,g.hitch(this,function(){x="loaded";a.resolve()}));x="loading"}else"loaded"===x&&a.resolve();return a},supportHTML5:function(){return window.File&&window.FileReader&&window.FileList&&window.Blob?!0:!1},supportFileAPI:function(){return y("safari")&&
6>y("safari")?!1:window.FileAPI&&window.FileAPI.readAsDataURL?!0:!1},isEnabledFlash:function(){var a=null;if(document.all)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(b){a=null}else navigator.plugins&&0<navigator.plugins.length&&(a=navigator.plugins["Shockwave Flash"]);return!!a},containSeparator:function(a){return 0<=a.indexOf("/")?!0:0<=a.indexOf("\\")?!0:!1},getNameFromPath:function(a){var b="",b=0<=a.indexOf("/")?"/":"\\";a=a.split(b);return 0<a.length?a[a.length-1]:null},getFolderFromPath:function(a){return a.substr(0,
a.length-e.file.getNameFromPath(a).length)},readFile:function(a,b,c,d){if(this.supportHTML5()){var f=a.target.files[0];f&&(f.type.match(b)?f.size>=c?d({errCode:"exceed"}):(a=new FileReader,a.onload=function(a){d(null,f.name,a.target.result)},a.readAsDataURL(f)):d({errCode:"invalidType"}))}else if(this.supportFileAPI()){var e=window.FileAPI.getFiles(a);e[0].type.match(b)?e[0].size>=c?d({errCode:"exceed"}):window.FileAPI.readAsDataURL(e[0],function(a){a&&a.result?d(null,e[0].name,a.result):d({errCode:"readError"})}):
d({errCode:"invalidType"})}}};e.processWidgetSetting=function(a){if(!a.uri)return a;g.mixin(a,M(a.uri));a.icon||(a.icon=a.amdFolder+"images/icon.png");a.thumbnail||(a.thumbnail=a.amdFolder+"images/thumbnail.png");return a};e.getRequireConfig=function(){if(jimuConfig){var a=[];jimuConfig.widgetsPackage&&(a=a.concat(jimuConfig.widgetsPackage));jimuConfig.themesPackage&&(a=a.concat(jimuConfig.themesPackage));jimuConfig.configsPackage&&(a=a.concat(jimuConfig.configsPackage));return{packages:a}}return{}};
e.getTypeByGeometryType=function(a){var b="",c="esriGeometryLine esriGeometryCircularArc esriGeometryEllipticArc esriGeometryBezier3Curve esriGeometryPath esriGeometryPolyline".split(" "),d=["esriGeometryRing","esriGeometryPolygon","esriGeometryEnvelope"];0<=["esriGeometryPoint","esriGeometryMultipoint"].indexOf(a)?b="point":0<=c.indexOf(a)?b="polyline":0<=d.indexOf(a)&&(b="polygon");return b};e.getSymbolTypeByGeometryType=function(a){var b=null;a=e.getTypeByGeometryType(a);"point"===a?b="marker":
"polyline"===a?b="line":"polygon"===a&&(b="fill");return b};e.getServices=function(){return P};e.getArcGISDefaultGeometryService=function(){return new C(P.geometryService)};e.restoreToDefaultWebMapExtent=function(a,b,c){var d=new q;if(!a||"esri.Map"!==a.declaredClass)return setTimeout(function(){d.reject("Invalid map.")},0),d;b=b&&b.itemInfo;if(!b)return setTimeout(function(){d.reject("Invalid itemInfo")},0),d;b=b.item&&b.item.extent;if(!b)return setTimeout(function(){d.reject("Invalid itemInfo.item.extent")}),
d;var f=new W({wkid:4326}),f=new X(b[0][0],b[0][1],b[1][0],b[1][1],f);if(4326===parseInt(a.spatialReference.wkid,10))return a.setExtent(f);if(a.spatialReference.isWebMercator)return f=aa.geographicToWebMercator(f),a.setExtent(f);b=new ba;b.geometries=[f];b.outSR=a.spatialReference;f=n&&n.defaults&&n.defaults.geometryService;f&&"esri.tasks.GeometryService"===f.declaredClass||(c&&"string"===typeof c&&g.trim(c)?(c=g.trim(c),f=new C(c)):f=e.getArcGISDefaultGeometryService());f.project(b).then(function(b){if(b=
b&&b[0])return a.setExtent(b);d.reject("Invalid projected geometry.");return d},function(a){console.error(a);d.reject(a);return d});return d};e.getAncestorWindow=function(){for(var a=window;a&&a.parent&&a!==a.parent;)a=a.parent;return a};e.getAncestorDom=function(a,b,c){if(a&&1===a.nodeType&&b&&"function"===typeof b){var d=100,f=document.body;c&&("number"===typeof c?(c=parseInt(c,10),0<c&&(d=c)):1===c.nodeType&&(f=c));for(c=0;a.parentNode&&c<d&&h.isDescendant(a.parentNode,f);){if(b(a.parentNode))return a.parentNode;
a=a.parentNode;c++}}return null};e.bindClickAndDblclickEvents=function(a,b,c,d){var f=null;if(a&&1===a.nodeType&&b&&"function"===typeof b&&c&&"function"===typeof c){var e=200;d&&"number"===typeof d&&(d=parseInt(d,10),0<d&&(e=d));var m=0,f=A(a,"click",function(a){m++;1===m?setTimeout(function(){1===m&&(m=0,b(a))},e):2===m&&(m=0,c(a))})}return f};e.isScrollToBottom=function(a){var b=h.getContentBox(a);return 1>a.scrollHeight-(a.scrollTop+b.h)};e.getAllItemTypes=function(){var a=[],a=a.concat(["Web Map",
"Web Scene","CityEngine Web Scene"]).concat("Feature Service;Map Service;Image Service;KML;WMS;Feature Collection;Feature Collection Template;Geodata Service;Globe Service".split(";")).concat(["Geometry Service","Geocoding Service","Network Analysis Service","Geoprocessing Service"]).concat(["Web Mapping Application","Mobile Application","Code Attachment","Operations Dashboard Add In","Operation View"]).concat("Symbol Set;Color Set;Shapefile;CSV;Service Definition;Document Link;Microsoft Word;Microsoft PowerPoint;Microsoft Excel;PDF;Image;Visio Document".split(";"));
return a=a.concat("Map Document;Map Package;Tile Package;ArcPad Package;Explorer Map;Globe Document;Scene Document;Published Map;Map Template;Windows Mobile Package".split(";")).concat(["Layer","Layer Package","Explorer Layer"]).concat(["Geoprocessing Package","Geoprocessing Sample","Locator Package","Rule Package"]).concat("Workflow Manager Package;Desktop Application;Desktop Application Template;Code Sample;Desktop Add In;Explorer Add In".split(";"))};e.getItemQueryStringByTypes=function(a){var b=
"",c=e.getAllItemTypes();if(a&&0<a.length&&0<a.length){var d="";k.forEach(a,function(b,c){d+=' type:"'+b+'" ';c!==a.length-1&&(d+=" OR ")});b=" ( "+d+" ) ";c=a.concat(c);c=k.filter(c,function(b){return k.every(a,function(a){return 0>a.toLowerCase().indexOf(b.toLowerCase())})});k.forEach(c,function(a){b+=' -type:"'+a+'" '})}return b};e.getItemQueryStringByTypeKeywords=function(a){var b="";a&&0<a.length&&(b=' typekeywords:"'+a.join(",")+'" ');return b};e.isNotEmptyString=function(a,b){var c=a&&"string"===
typeof a;return c?b?c&&g.trim(a):!0:!1};e.isValidNumber=function(a){return"number"===typeof a&&!isNaN(a)};e.isObject=function(a){return a&&"object"===typeof a};e.getRandomString=function(){var a=Math.random().toString();return a=a.slice(2,a.length)};e._getDomainsByServerName=function(a){var b=a.split("."),c=b.length;return k.map(b,g.hitch(this,function(a,f){a=b.slice(f,c);var d="",e=a.length-1;k.forEach(a,g.hitch(this,function(a,b){d+=a;b!==e&&(d+=".")}));return d}))};e.removeCookie=function(a,b){var c=
this._getDomainsByServerName(window.location.hostname);k.forEach(c,g.hitch(this,function(c){B(a,null,{expires:-1,path:b});B(a,null,{expires:-1,path:b,domain:c});B(a,null,{expires:-1,path:b,domain:"."+c})}))};e.isLocaleChanged=function(a,b){return!a.startWith(b)};e.hashToObject=function(a){a=a.replace("#","");a=F.queryToObject(a);for(var b in a)if(a.hasOwnProperty(b))try{a[b]=v.parse(a[b])}catch(c){}return a};e.reCreateObject=function(a){function b(a){var d=[];a.forEach(function(a){Array.isArray(a)?
d.push(b(a)):"object"===typeof a?d.push(c(a)):d.push(a)});return d}function c(a){var d={},e;for(e in a)a.hasOwnProperty(e)&&(null===a[e]?d[e]=null:Array.isArray(a[e])?d[e]=b(a[e]):d[e]="object"===typeof a[e]?c(a[e]):a[e]);return d}return Array.isArray(a)?b(a):c(a)};e.setVerticalCenter=function(a){setTimeout(function(){var b=u(".jimu-vcenter-text",a),c,d;k.forEach(b,function(a){c=h.getContentBox(a).h;h.setStyle(a,{lineHeight:c+"px"})},this);b=u(".jimu-vcenter",a);k.forEach(b,function(a){c=h.getContentBox(a).h;
d=h.getContentBox(u(a).parent()[0]).h;h.setStyle(a,{marginTop:(d-c)/2+"px"})},this)},10)};e.merge=D;e.loadStyleLink=function(a,b,c){var d=new q,f,l=require(e.getRequireConfig()).toUrl(b);if(require.cache["url:"+l]){f=require.cache["url:"+l];var m=l.split("/").pop(),l=l.substr(0,l.length-m.length);f=L(f,l);a=c?h.create("style",{id:a,type:"text/css"},h.byId(c),"before"):h.create("style",{id:a,type:"text/css"},document.getElementsByTagName("head")[0]);a.styleSheet&&!a.sheet?a.styleSheet.cssText=f:a.appendChild(h.toDom(f));
d.resolve("load");return d}f=c?h.create("link",{id:a,rel:"stylesheet",type:"text/css",href:l},h.byId(c),"before"):h.create("link",{id:a,rel:"stylesheet",type:"text/css",href:l},document.getElementsByTagName("head")[0]);A(f,"load",function(){d.resolve("load")});var w=setInterval(function(){var a;if(k.some(document.styleSheets,function(c){if(c.href&&c.href.substr(c.href.indexOf(b),c.href.length)===b)return a=c,!0}))try{!d.isFulfilled()&&(a.cssRules&&a.cssRules.length||a.rules&&a.rules.length)&&d.resolve("load"),
clearInterval(w)}catch(ga){}},50);return d};e.changeLocation=function(a){window.history.pushState&&window.history.pushState({path:a},"",a)};e.urlToObject=function(a){var b=null;-1===a.indexOf("#")?(b=r.urlToObject(a),b.hash=null):(a=a.split("#"),b=r.urlToObject(a[0]),b.hash=a[1]?-1<a[1].indexOf("\x3d")?F.queryToObject(a[1]):a[1]:null);return b};e.addManifestProperies=function(a){a.icon=a.url+"images/icon.png";"theme"===a.category?da(a):("undefined"!==typeof a["2D"]&&(a.support2D=a["2D"]),"undefined"!==
typeof a["3D"]&&(a.support3D=a["3D"]),"undefined"===typeof a["2D"]&&"undefined"===typeof a["3D"]&&(a.support2D=!0),delete a["2D"],delete a["3D"],"undefined"===typeof a.properties&&(a.properties={}),K.processWidgetProperties(a))};e.getUniqueValues=function(a,b){var c=new q;a=a.replace(/\/*$/g,"")+"/generateRenderer";b=v.stringify({type:"uniqueValueDef",uniqueValueFields:[b]});J(a,{query:{classificationDef:b,f:"json"},responseType:"json",callbackParamName:"callback"}).then(g.hitch(this,function(a){var b=
a.data;a=[];(b=b&&b.uniqueValueInfos)&&0<b.length&&(a=k.map(b,g.hitch(this,function(a){return a.value})));c.resolve(a)}),g.hitch(this,function(a){c.reject(a)}));return c};e.combineRadioCheckBoxWithLabel=function(a,b){var c=!1;if(a&&1===a.nodeType&&"input"===a.tagName.toLowerCase()){var d=a.getAttribute("type")||"",d=d.toLowerCase();if("radio"===d||"checkbox"===d)c=!0}d=!1;b&&1===b.nodeType&&"label"===b.tagName.toLowerCase()&&(d=!0);c&&d&&(c=a.getAttribute("id"),c||(c="input_"+e.getRandomString(),
a.setAttribute("id",c)),b.setAttribute("for",c),h.setStyle(b,"cursor","pointer"))};e.convertExtentToPolygon=function(a){var b=a.xmin,c=a.xmax,d=a.ymin,e=a.ymax;return new I({rings:[[[b,e],[c,e],[c,d],[b,d],[b,e]]],spatialReference:a.toJson()})};e.combineGeometries=function(a){function b(a){var b={points:[],spatialReference:a[0].spatialReference.toJson()};k.forEach(a,function(a){b.points=b.points.concat(a.points)});return new Y(b)}function c(a){var b={paths:[],spatialReference:a[0].spatialReference.toJson()};
k.forEach(a,function(a){b.paths=b.paths.concat(a.paths)});return new Z(b)}function d(a){var b={rings:[],spatialReference:a[0].spatialReference.toJson()};k.forEach(a,function(a){"polygon"===a.type?b.rings=b.rings.concat(a.rings):"extent"===a.type&&(a=e.convertExtentToPolygon(a),b.rings=b.rings.concat(a.rings))});return new I(b)}var f=null;if(a&&0<a.length)if(1===a.length)f=a[0];else{for(var l=null,m=null,w=null,p=null,g=0;g<a.length;g++){l=a[g];switch(l.type){case "point":case "multipoint":p="point";
break;case "polyline":p="polyline";break;case "polygon":case "extent":p="polygon";break;default:return null}if(0===g)w=p;else if(w!==p)return null;if(g!==a.length-1&&(m=a[g+1],!l.spatialReference.equals(m.spatialReference)))return null}"point"===p?f=b(a):"polyline"===p?f=c(a):"polygon"===p&&(f=d(a))}return f};e.isFeaturelayerUrlSupportQuery=function(a,b){var c=!1,d=/\/featureserver\//gi.test(a);a=/\/mapserver\//gi.test(a);b=(b||"").toLowerCase();d?c=0<=b.indexOf("query"):a&&(c=0<=b.indexOf("data"));
return c};e.isImageServiceSupportQuery=function(a){return 0<=(a||"").toLowerCase().indexOf("catalog")};e.isStringEndWith=function(a,b){return a.lastIndexOf(b)+b.length===a.length};e.processManifestLabel=function(a,b){a.label=a.i18nLabels&&(a.i18nLabels[b]||a.i18nLabels.defaultLabel)||a.label||a.name;a.layouts&&k.forEach(a.layouts,function(c){var d="i18nLabels_layout_"+c.name;c.label=a[d]&&(a[d][b]||a[d].defaultLabel)||c.label||c.name});a.styles&&k.forEach(a.styles,function(c){var d="i18nLabels_style_"+
c.name;c.label=a[d]&&(a[d][b]||a[d].defaultLabel)||c.label||c.name})};e.addManifest2WidgetJson=function(a,b){g.mixin(a,b.properties);a.name=b.name;a.label||(a.label=b.label);a.manifest=b};e.widgetJson=function(){var a={addManifest2WidgetJson:function(a,c){g.mixin(a,c.properties);a.name=c.name;a.label||(a.label=c.label);a.manifest=c;a.isRemote=c.isRemote;a.isRemote&&(a.itemId=c.itemId);c.featureActions&&(a.featureActions=c.featureActions);a.icon||(a.icon=c.icon);a.thumbnail||(a.thumbnail=c.thumbnail);
a.folderUrl=c.folderUrl;a.amdFolder=c.amdFolder},removeManifestFromWidgetJson:function(a){if(a.manifest){for(var b in a.manifest.properties)a[b]=void 0;a.name=void 0;a.label=void 0;a.featureActions=void 0;a.manifest=void 0}},getUriFromItem:function(b){return b.url?a.getFolderUrlFromItem(b)+"Widget":null},getFolderUrlFromItem:function(a){if(!a.url)return null;a=/manifest\.json$/.test(a.url)?a.url.substring(0,a.url.length-13):/\/$/.test(a.url)?a.url:a.url+"/";"https:"===window.location.protocol&&(a=
a.replace(/^http:\/\//,"https://"));return a}};return a}();e.addI18NLabel=function(a){var b=new q;if(a.i18nLabels)return b.resolve(a),b;a.i18nLabels={};if(a.properties&&!1===a.properties.hasLocale)return b.resolve(a),b;var c="widget"===a.category?"_widgetLabel":"_themeLabel";require(e.getRequireConfig(),["dojo/i18n!"+a.amdFolder+"nls/strings"],function(d){a.i18nLabels[dojoConfig.locale]=d[c];"theme"===a.category&&(a.layouts&&a.layouts.forEach(function(b){a["i18nLabels_layout_"+b.name]={};a["i18nLabels_layout_"+
b.name][dojoConfig.locale]=d["_layout_"+b.name]}),a.styles&&a.styles.forEach(function(b){a["i18nLabels_style_"+b.name]={};a["i18nLabels_style_"+b.name][dojoConfig.locale]=d["_style_"+b.name]}));b.resolve(a)});return b};e.localizeNumber=function(a,b){var c=(a.toString().split(".")[1]||"").length,d="",d=b&&isFinite(b.places)&&b.places,d=0<d||0<c?"#,###,###,##0.0"+Array.prototype.join.call({length:0<d?d+1:c},"0"):"#,###,###,##0",c={locale:z.locale,pattern:d};g.mixin(c,b||{});try{return G.format(a,c)}catch(f){return console.error(f),
a.toLocaleString()}};e.parseNumber=function(a,b){var c={locale:z.locale};g.mixin(c,b||{});try{return G.parse(a,c)}catch(d){return console.error(d),a}};e.localizeDate=function(a,b){var c={locale:z.locale,fullYear:!0};g.mixin(c,b||{});try{return S.format(a,c)}catch(d){return console.error(d),"date"===c.selector?a.toLocaleDateString():"time"===c.selector?a.toLocaleTimeString():a.toLocaleString()}};e.localizeNumberByFieldInfo=function(a,b){var c=null,c=g.exists("format.places",b)&&b.format.places,c=e.localizeNumber(a,
{places:c});return g.exists("format.digitSeparator",b)&&!b.format.digitSeparator?c.toString().replace(new RegExp("\\"+T.group,"g"),""):c};e.fieldFormatter={getFormattedUrl:function(a){if(a&&"string"===typeof a){var b=a.indexOf("http:");-1===b&&(b=a.indexOf("https:"));if(-1<b&&-1===a.indexOf("href\x3d")){var c=a.indexOf(" ",b);-1===c&&(c=a.length);var d=a.substring(b,c);a=a.substring(0,b)+'\x3cA href\x3d"'+d+'" target\x3d"_blank"\x3e'+d+"\x3c/A\x3e"+a.substring(c,a.length)}}return a||""},getFormattedNumber:function(a,
b){if("number"===typeof a){var c=(a.toString().split(".")[1]||"").length;a=e.localizeNumberByFieldInfo(a,{format:{places:b&&"number"===typeof b.places?parseInt(b.places,10):c,digitSeparator:b&&b.digitSeparator}});return'\x3cspan class\x3d"jimu-numeric-value"\x3e'+(a||"")+"\x3c/span\x3e"}return a},getFormattedDate:function(a){a&&(a=e.localizeDate(new Date(a),{fullYear:!0}));return a||""},getCodedValue:function(a,b){if(a&&a.codedValues){for(var c=0,d=a.codedValues.length;c<d;c++){var e=a.codedValues[c];
if(V.isDefined(b)&&g.exists("code",e)&&b.toString()===e.code.toString())return e.name}return b}return b||null},getTypeName:function(a,b){for(var c=b.length,d=0;d<c;d++)if(a===b[d].id)return b[d].name;return a}};e.addRelativePathInCss=L;e.url={isAbsolute:function(a){return a?a.startWith("http")||a.startWith("/"):!1},removeQueryParamFromUrl:function(a,b){a=r.urlToObject(a);a.query&&delete a.query[b];b=a.path;for(var c in a.query)b=b===a.path?b+"?"+c+"\x3d"+a.query[c]:b+"\x26"+c+"\x3d"+a.query[c];return b},
addQueryParamToUrl:function(a,b,c){a=r.urlToObject(a);a.query||(a.query={});a.query[b]=c;b=a.path;for(var d in a.query)b=b===a.path?b+"?"+d+"\x3d"+a.query[d]:b+"\x26"+d+"\x3d"+a.query[d];return b}};e.processUrlInWidgetConfig=function(a,b){if(a)return a.startWith("data:")||a.startWith("http")||a.startWith("/")?a:a.startWith("${appPath}")?a.replace("${appPath}",window.appInfo.appPath):b+a};e.processUrlInAppConfig=function(a){if(a)return a.startWith("data:")||a.startWith("http")||a.startWith("/")?a:
window.appInfo.appPath+a};e.getLocationUrlWithoutHashAndQueryParams=function(){var a=window.location,b=a.protocol+"//"+a.host+a.pathname,a=r.urlToObject(a.href);a.query&&a.query.apiurl&&(b=e.url.addQueryParamToUrl(b,"apiurl",a.query.apiurl));return b};e.getDefaultWebMapThumbnail=function(){return require.toUrl("jimu/images/webmap.png")};e.invertColor=function(a){a=a.substring(1);3===a.length&&(a=a.slice(0,1)+a.slice(0,1)+a.slice(1,1)+a.slice(1,1)+a.slice(2,1)+a.slice(2,1));a=parseInt(a,16);return 7829367<
a?"#000000":"#ffffff"};e.mixinAppConfigPosition=function(a,b){var c=g.clone(a);if(!b)return c;b=g.clone(b);var d=c.widgetOnScreen,e=b.widgetOnScreen;e&&e.widgets&&("[object Object]"===Object.prototype.toString.call(e.widgets)?k.forEach(d.widgets,function(a,b){b=a.uri?a.uri:"ph_"+b;e.widgets[b]&&e.widgets[b].position&&(e.widgets[b].position.relativeTo||(e.widgets[b].position.relativeTo="map"),a.position=e.widgets[b].position)},this):k.forEach(e.widgets,function(a,b){a.position&&!a.position.relativeTo&&
(a.position.relativeTo="map");d.widgets[b]&&a.position&&(d.widgets[b].position=a.position)}));e&&e.groups&&("[object Object]"===Object.prototype.toString.call(e.groups)?k.forEach(d.groups,function(a,b){b=a.label?a.label:"g_"+b;e.groups[b]&&e.groups[b].panel&&e.groups[b].panel.position&&(e.groups[b].panel.position.relativeTo||(e.groups[b].panel.position.relativeTo="map"),a.panel.position=e.groups[b].panel.position)},this):(a=a.layoutDefinition?a.layoutDefinition.manager:"jimu/layoutManagers/AbsolutePositionLayoutManager",
"jimu/layoutManagers/AbsolutePositionLayoutManager"===a?k.forEach(e.groups,function(a,b){a.panel&&a.panel.position&&!a.panel.position.relativeTo&&(a.panel.position.relativeTo="map");d.groups[b]&&a.panel&&a.panel.position&&(d.groups[b].panel.position=a.panel.position)}):"jimu/layoutManagers/GridLayoutManager"===a&&(d.groups=N(d.groups,e.groups.map(function(a){return a.id})))));b.map&&b.map.position&&(c.map?c.map.position=b.map.position:c.map={position:b.map.position});b.widgetPool&&b.widgetPool.panel&&
(b.widgetPool.panel.position&&!b.widgetPool.panel.position.relativeTo&&(b.widgetPool.panel.position.relativeTo="map"),c.widgetPool.panel.position=b.widgetPool.panel.position);b.mobileLayout&&(c.mobileLayout=b.mobileLayout);return c};e.handleGridLayoutOnScreenGroupChange=N;e.template={groupIdentification:"groups\\[.+\\]",widgetIdentification:"widgets\\[.+\\]",getSearchRange:function(a,b,c){var d=-1;b=a.search(new RegExp(b));0<=b&&(a=a.slice(b,a.length),a=a.indexOf(c),d=b+a+c.length);return{firstPos:b,
lastPos:d}},setConfigValue:function(a,b,c){E(a,b,c)},getConfigValue:function(a,b){return E(a,b)},setConfigValueWithId:function(a,b,c){O(a,b,c)},getConfigValueWithId:function(a,b){return O(a,b)},getKeyInfo:function(a){var b=this.getWidgetIdByKey(a);if(null!==b)return{type:"widget",id:b};a=this.getGroupIdByKey(a);return null!==a?{type:"group",id:a}:{type:"unknow",id:null}},getWidgetIdByKey:function(a){var b=e.template.getSearchRange(a,e.template.widgetIdentification,"]");if(-1===b.firstPos)a=null;else{var c=
a.slice(b.firstPos,b.lastPos);a=a.slice(b.firstPos+c.indexOf("[")+1,b.lastPos-1)}return a},getGroupIdByKey:function(a){var b=e.template.getSearchRange(a,e.template.groupIdentification,"]");if(-1===b.firstPos)a=null;else{var c=a.slice(b.firstPos,b.lastPos);a=a.slice(b.firstPos+c.indexOf("[")+1,b.lastPos-1)}return a},getConfigedWidgetsByTemplateConfig:function(a){var b=[],c=e.template.widgetIdentification+"_config",d;k.forEach(a.configurationSettings,function(a){k.forEach(a.fields,function(a){a.fieldName&&
(d=e.template.getSearchRange(a.fieldName,c,"]"),0<=d.firstPos&&(a=e.template.getWidgetIdByKey(a.fieldName),-1===b.indexOf(a)&&b.push(a)))},this)},this);return b},mergeTemplateAppConfigToAppConfig:function(a,b,c){function d(a){var b=[];k.forEach(a,function(a){a&&b.push(a)},this);return b}var f=a.widgetOnScreen,l=a.portalUrl;b.values.webmap&&(a.map.itemId=b.values.webmap);c&&(a.map.mapOptions&&e.deleteMapOptions(a.map.mapOptions),a.map.portalUrl=l,b.values.app_title||(b.values.app_title=c.title),b.values.app_subtitle||
(b.values.app_subtitle=c.snippet));for(var g in b.values)"webmap"!==g&&e.template.setConfigValueWithId(a,g,b.values[g]);a.widgetPool.widgets=d(a.widgetPool.widgets);f.widgets=d(f.widgets);if(a.widgetPool.groups)for(b=0;b<a.widgetPool.groups.length;b++)a.widgetPool.groups[b].widgets=d(a.widgetPool.groups[b].widgets);if(f.groups)for(b=0;b<f.groups.length;b++)f.groups[b].widgets=d(f.groups[b].widgets);return a}};e.deleteMapOptions=function(a){a&&(delete a.extent,delete a.lods,delete a.center,delete a.scale,
delete a.zoom,delete a.maxScale,delete a.maxZoom,delete a.minScale,delete a.minZoom,delete a.initialState)};e.localeIsSame=function(a,b){return a.split("-")[0]===b.split("-")[0]};e.graphicsExtent=function(){return null};e.sanitizeHTML=function(a){return html_sanitize(a,function(a){return a},function(a){return a})};e.stripHTML=function(a){return a?-1<a.indexOf("\x3c")&&-1<a.indexOf("\x3e")?a.replace(/<(?:.|\s)*?>/g,""):a:a};e.removeSuffixSlashes=function(a){return a.replace(/\/*$/g,"")};e.getBestDisplayAttributes=
function(a,b){var c={},d=null,f;for(f in a)d=e.getBestDisplayValue(f,a,b),c[f]=d;return c};e.getBestDisplayValue=function(a,b,c){var d="",f=null;g.isArrayLike(c)?f=e.getFieldInfoByFieldName(c,a):"object"===typeof c&&c.name===a&&(f=c);f&&(d=b[a],"esriFieldTypeDate"===f.type?d&&(a=new Date(parseInt(d,10)),d=e._tryLocaleDate(a)):"number"===typeof d&&(f.domain&&"codedValue"===f.domain.type?k.some(f.domain.codedValues,function(a){if(a.code===d)return d=a.name,!0}):d=e._tryLocaleNumber(d)));if(null===d||
void 0===d)d="";return d};e._tryLocaleNumber=function(a){var b=e.localizeNumber(a);if(null===b||void 0===b)b=a;return b};e._tryLocaleDate=function(a){var b=e.localizeDate(a);b||(b=a.toLocaleDateString());return b};e.getFieldInfoByFieldName=function(a,b){var c=null;a&&0<a.length&&k.some(a,g.hitch(this,function(a){return a.name===b?(c=a,!0):!1}));return c};e.containsNonLatinCharacter=function(a){for(var b=0;b<a.length;b++)if(255<a.charCodeAt(b))return!0;return!1};e.isVersion4API=function(){return 0===
U.version.indexOf("4")};e.getEsriConfig=function(){return n};e.getEsriConfigRequestObject=function(){var a=null;return a=e.isVersion4API()?n.request:n.defaults.io};e.setGlobalGeometryService=function(a){a=new C(a);e.isVersion4API()?n.geometryService=a:n.defaults.geometryService=a;return a};e.getQueryableFeatureLayersFromMap=function(a){var b=[];a.layers&&(b=a.layers.filter(function(a){return"esri.layers.FeatureLayer"===a.declaredClass&&a.url&&a.supportedQueryFormats&&0<=a.supportedQueryFormats.toUpperCase().indexOf("JSON")}));
return b};e.has=function(a){var b=y(a);if(b)return b;if("ie"===a.toLowerCase()){a=0;var c=/MSIE (\d+\.\d+);/.test(navigator.userAgent),d=!!navigator.userAgent.match(/Trident\/7.0/),e=navigator.userAgent.indexOf("rv:11.0");c&&(a=Number(RegExp.$1));-1!==navigator.appVersion.indexOf("MSIE 10")&&(a=10);d&&-1!==e&&(a=11);return 11===a&&11||b}if("edge"===a.toLowerCase())return navigator.userAgent.split("Edge/")[1]||b};e.isNeedHttpsButNot=function(){var a=navigator.geolocation,b=window.hasOwnProperty("isSecureContext");
return(b&&window.isSecureContext||!b&&"https:"===window.location.protocol)&&a?!1:!0};e.isInConfigOrPreviewWindow=function(){var a=!1;try{a=!window.isBuilder&&window.parent&&window.parent!==window&&window.parent.isBuilder}catch(b){a=!1}return!!a};e.getAppHref=function(){var a="";return a=e.isInConfigOrPreviewWindow()?window.parent.location.href:window.location.href};e.getAppIdFromUrl=function(){var a=!0,b=e.getAppHref();if(-1!==b.indexOf("id\x3d")||-1!==b.indexOf("appid\x3d")||-1!==b.indexOf("apps"))a=
!1;if(!0===a)return b;a=this.urlToObject(window.location.href);if(a.query&&(a.query.id||a.query.appid))return a.query.id||a.query.appid;if(window.appInfo){if(window.appInfo.id)return window.appInfo.id;if(window.appInfo.appPath){if(a=window.appInfo.appPath.split("/"),a.length&&2<a.length)return a[a.length-2]}else console.error("CAN NOT getAppIdFromUrl")}};e.getEditorContentHeight=function(a,b,c){var d=new q;this._content=a;this._dom=b;this._domParam=c;var e=setTimeout(g.hitch(this,function(){clearTimeout(e);
e=null;var a=0,b=this._domParam.contentWidth;try{var c=document.createElement("div");c.setAttribute("id","fakeContent");h.setStyle(c,"background-size","contain");c.innerHTML=this._content;this._dom.appendChild(c);if(c){var f=u("img",c);f&&f.length&&f.style({maxWidth:b-20+"px"});h.setStyle(c,"position","absolute");h.setStyle(c,"width",b+"px");h.setStyle(c,"left","-99999px");h.setStyle(c,"top","-99999px");h.setStyle(c,"visibility","hidden");var g=h.getContentBox(c);g.h&&(a=g.h,a+=this._domParam.contentMarginTop+
this._domParam.footerHeight+8)}}catch(ea){console.error("can't getEditorContentHeight"+ea),a=200}d.resolve(a)}),1500);return d};e.getEditorTextColor=function(a,b){return{name:"dijit.editor.plugins.EditorTextColor",custom:{recordUID:e.getColorRecordName(a),forceAttr:b}}};e.getEditorBackgroundColor=function(a){return{name:"dijit.editor.plugins.EditorBackgroundColor",custom:{recordUID:e.getColorRecordName(a)}}};e.getColorRecordName=function(a){return"wab_cr_"+(a||"")};e.isEsriDomain=function(a){return/^https?:\/\/(?:[\w\-\_]+\.)+(?:esri|arcgis)\.com/.test(a)};
e.b64toBlob=function(a,b,c){b=b||"";c=c||512;a=window.atob(a.replace(/^data:image\/(png|jpg|jpeg|gif);base64,/,""));for(var d=[],e=0;e<a.length;e+=c){for(var g=a.slice(e,e+c),k=Array(g.length),h=0;h<g.length;h++)k[h]=g.charCodeAt(h);g=new Uint8Array(k);d.push(g)}return new Blob(d,{type:b})};e.subtractionArray=function(a,b){for(var c=a.length-1;0<=c;c--)for(var d=a[c],e=b.length-1;0<=e;e--)if(d===b[e]){a.splice(c,1);b.splice(e,1);break}return a};e.resourcesUrlToBlob=function(a){return J({url:a,handleAs:"blob"})};
e.processItemResourceOfAppConfig=function(a,b){function c(a){var b=a.obj,c=a.key,d={obj:b,key:c};"number"===typeof a.i?(d.i=a.i,d.value=b[c][a.i]):d.value=b[c];return d}function d(a){for(var b in a)if("object"===typeof a[b])if(Array.isArray(a[b]))for(var c=a,f=b,g=0;g<c[f].length;g++)"string"===typeof c[f][g]?e(c,f,g):"object"===typeof c[f][g]&&d(c[f][g]);else d(a[b]);else"string"===typeof a[b]&&e(a,b)}function e(a,d,e){"number"===typeof e?b.test(a[d][e])&&(h=b.func(c({obj:a,key:d,i:e})),"function"===
typeof h.then?k.push(h):g.push(h)):b.test(a[d])&&(h=b.func(c({obj:a,key:d})),"function"===typeof h.then?k.push(h):g.push(h))}var g=[],k=[],h;d(a);return 0<k.length?R(k).then(function(b){0<g.length&&(b=b.concat(g));return{appConfig:a,result:b}}):{appConfig:a,result:g}};return e});