// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/Deferred dojo/topic dojo/Evented dojo/on dojo/aspect dojo/json dojo/query dojo/request/xhr dojo/promise/all ./utils jimu/tokenUtils ./dijit/Message".split(" "),function(z,e,l,m,h,k,A,B,n,x,C,u,q,f,y,v){var r=null,w=z(A,{constructor:function(){this.loaded=[];this.missedActions=[];this.activeWidget=null;window.isBuilder?(k.subscribe("app/sceneViewLoaded",e.hitch(this,this._onSceneViewLoaded)),k.subscribe("app/sceneViewChanged",
e.hitch(this,this._onSceneViewChanged))):(k.subscribe("sceneViewLoaded",e.hitch(this,this._onSceneViewLoaded)),k.subscribe("sceneViewChanged",e.hitch(this,this._onSceneViewChanged)));window.isBuilder?(k.subscribe("app/appConfigLoaded",e.hitch(this,this._onAppConfigLoaded)),k.subscribe("app/appConfigChanged",e.hitch(this,this._onAppConfigChanged))):(k.subscribe("appConfigLoaded",e.hitch(this,this._onAppConfigLoaded)),k.subscribe("appConfigChanged",e.hitch(this,this._onAppConfigChanged)));k.subscribe("userSignIn",
e.hitch(this,this._onUserSignIn));k.subscribe("userSignOut",e.hitch(this,this._onUserSignOut));k.subscribe("builder/actionTriggered",e.hitch(this,this._onActionTriggered));k.subscribe("/dnd/move/start",e.hitch(this,this._onMoveStart))},loadWidget:function(a){var b=new h,c;a=e.clone(a);a.folderUrl||f.processWidgetSetting(a);(c=this.getWidgetById(a.id))?b.resolve(c):q([this.loadWidgetClass(a),this.loadWidgetManifest(a)]).then(e.hitch(this,function(a){var c=a[0],d=a[1];this.loadWidgetResources(d).then(e.hitch(this,
function(a){try{var g=this.createWidget(d,c,a);console.log("widget ["+d.uri+"] created.")}catch(t){console.log("create ["+d.uri+"] error:"+t.stack),new v({message:window.jimuNls.createWidgetError+": "+d.uri}),b.reject(t)}setTimeout(e.hitch(this,function(){b.resolve(g);this.emit("widget-created",g);k.publish("widgetCreated",g)}),50)}),function(a){b.reject(a)})}),function(a){b.reject(a)});return b},loadWidgetClass:function(a){var b=new h,c;c=a.isRemote?a.uri+".js":a.uri;require(f.getRequireConfig(),
[c],e.hitch(this,function(a){b.resolve(a)}));f.checkError(a.uri,b);return b},loadWidgetResources:function(a){var b=new h,c,d,g,p=[];g=e.clone(a);a=this.tryLoadWidgetConfig(g);c=this._tryLoadResource(g,"i18n");d=this._tryLoadResource(g,"style");g=this._tryLoadResource(g,"template");p.push(a);p.push(c);p.push(g);p.push(d);q(p).then(e.hitch(this,function(a){var c={};c.config=a[0];c.i18n=a[1];c.template=a[2];c.style=a[3];b.resolve(c)}),function(a){b.reject(a)});return b},loadWidgetManifest:function(a){var b=
new h,c=f.getUriInfo(a.uri),c=c.isRemote?c.folderUrl+"manifest.json?f\x3djson":c.folderUrl+"manifest.json";if(a.manifest)return b.resolve(a),b;u(c,{handleAs:"json",headers:{"X-Requested-With":null}}).then(e.hitch(this,function(c){if(c.error&&c.error.code)return b.reject(c.error);c.amdFolder=a.amdFolder;c.category="widget";a.label?(this._processManifest(c),f.addManifest2WidgetJson(a,c),b.resolve(a)):f.addI18NLabel(c).then(e.hitch(this,function(){this._processManifest(c);f.addManifest2WidgetJson(a,
c);b.resolve(a)}))}),function(a){b.reject(a)});return b},getWidgetMarginBox:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return{};if(a._marginBox)return a._marginBox;a.setPosition({left:-9999,top:-9999,relativeTo:a.position.relativeTo});this.openWidget(a);a._marginBox=a.getMarginBox();this.closeWidget(a);return a._marginBox},_processManifest:function(a){f.addManifestProperies(a);f.processManifestLabel(a,window.dojoConfig.locale)},createWidget:function(a,b,c){if(this.getWidgetById(a.id))return this.getWidgetById(a.id);
c.config&&c.i18n&&(c.config=f.replacePlaceHolder(c.config,c.i18n));a.rawConfig=a.config;a.config=c.config||{};this.appConfig._appData&&this._mergeAgolConfig(a);a.nls=c.i18n||{};c.template&&(a.templateString=c.template);a["class"]="jimu-widget";a.label||(a.label=a.name);a.sceneView=this.sceneView;a.appConfig=this.appConfig;c={};for(var d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);c.widgetManager=this;a=new b(c);a.clazz=b;n.after(a,"startup",e.hitch(this,this._postWidgetStartup,a));n.before(a,"destroy",
e.hitch(this,this._onDestroyWidget,a));B(a.domNode,"click",e.hitch(this,this._onClickWidget,a));this.loaded.push(a);return a},getAllWidgets:function(){return this.loaded},destroyAllWidgets:function(){var a=l.map(this.loaded,function(a){return a.id});l.forEach(a,function(a){this.destroyWidget(a)},this);this.loaded=[]},loadWidgetSettingPage:function(a){var b=new h;a=e.clone(a);a.id+="_setting";q([this.loadWidgetSettingClass(a)]).then(e.hitch(this,function(c){var d=c[0];this.loadWidgetSettingPageResources(a).then(e.hitch(this,
function(c){var g,f={nls:c.i18n,appConfig:this.appConfig,sceneView:this.sceneView,"class":"jimu-widget-setting"};null!==c.template&&(f.templateString=c.template);for(var h in a)a.hasOwnProperty(h)&&(f[h]=a[h]);try{g=new d(f),n.before(g,"destroy",e.hitch(this,this._onDestroyWidgetSetting,g)),b.resolve(g)}catch(t){new v({message:window.jimuNls.createWidgetSettingError+":"+a.uri}),b.reject(t)}}),function(a){console.log(a)})}),function(a){b.reject(a)});return b},loadWidgetSettingClass:function(a){var b=
new h,c;c=a.isRemote?a.folderUrl+"setting/Setting.js":a.amdFolder+"setting/Setting";require(f.getRequireConfig(),[c],e.hitch(this,function(a){b.resolve(a)}));f.checkError(a.folderUrl+"setting/Setting.js",b);return b},loadWidgetSettingPageResources:function(a){var b=new h,c,d,g=[];a=e.clone(a);c=this._tryLoadResource(a,"settingI18n");d=this._tryLoadResource(a,"settingTemplate");a=this._tryLoadResource(a,"settingStyle");g.push(c);g.push(d);g.push(a);q(g).then(e.hitch(this,function(a){var c={};c.i18n=
a[0]||{};c.template=a[1];c.style=a[2];b.resolve(c)}),function(a){console.log(a)});return b},getWidgetById:function(a){var b;l.some(this.loaded,function(c){if(c.id===a)return b=c,!0},this);return b},getWidgetByLabel:function(a){var b;l.some(this.loaded,function(c){if(c.label===a)return b=c,!0},this);return b},getWidgetsByName:function(a){var b=[];l.some(this.loaded,function(c){c.name===a&&b.push(c)},this);return b},changeWindowStateTo:function(a,b){"normal"===b?this.normalizeWidget(a):"minimized"===
b?this.minimizeWidget(a):"maximized"===b?this.maximizeWidget(a):console.log("error state: "+b)},closeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;if("closed"!==a.state){this.activeWidget&&this.activeWidget.id===a.id&&(this.activeWidget.onDeActive(),this.activeWidget=null);m.setStyle(a.domNode,"display","none");a.setState("closed");try{a.onClose()}catch(b){console.log(console.error("fail to close widget "+a.name+". "+b.stack))}}},openWidget:function(a){if("string"===
typeof a&&(a=this.getWidgetById(a),!a))return;if(!a.started)try{a.started=!0,a.startup()}catch(b){console.error("fail to startup widget "+a.name+". "+b.stack)}if("closed"===a.state){m.setStyle(a.domNode,"display","");a.setState("opened");try{a.onOpen()}catch(b){console.error("fail to open widget "+a.name+". "+b.stack)}}},activateWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;"opened"===a.state&&this._activeWidget(a)},maximizeWidget:function(a){if("string"===typeof a&&
(a=this.getWidgetById(a),!a))return;"closed"===a.state&&this.openWidget(a);a.setWindowState("maximized");try{a.onMaximize()}catch(b){console.log(console.error("fail to maximize widget "+a.name+". "+b.stack))}},minimizeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;"closed"===a.state&&this.openWidget(a);a.setWindowState("minimized");try{a.onMinimize()}catch(b){console.log(console.error("fail to minimize widget "+a.name+". "+b.stack))}},normalizeWidget:function(a){if("string"===
typeof a&&(a=this.getWidgetById(a),!a))return;"closed"===a.state&&this.openWidget(a);a.setWindowState("normal");try{a.onNormalize()}catch(b){console.log(console.error("fail to normalize widget "+a.name+". "+b.stack))}},destroyWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;this._removeWidget(a);try{a.destroy()}catch(b){console.log(console.error("fail to destroy widget "+a.name+". "+b.stack))}},tryLoadWidgetConfig:function(a){return this._tryLoadWidgetConfig(a).then(e.hitch(this,
function(b){return this._upgradeWidgetConfig(a,b).then(function(b){return a.config=b})}))},triggerWidgetOpen:function(a){function b(a){var b=n.after(a,"onOpen",function(){b.remove();c.resolve(a)})}var c=new h,d=this.getWidgetById(a);if(d){if("closed"!==d.state)return c.resolve(d),c;b(d)}else var g=k.subscribe("widgetCreated",e.hitch(this,function(b){b.id===a&&(g.remove(),c.resolve(b))}));k.publish("openWidget",a);return c},_tryLoadWidgetConfig:function(a){var b=new h;if(a.config&&e.isObject(a.config))return b.resolve(a.config),
b;if(a.config){if(require.cache["url:"+a.config])return b.resolve(x.parse(require.cache["url:"+a.config])),b;b=f.processUrlInAppConfig(a.config);b=b.split("/");b[b.length-1]=encodeURIComponent(b[b.length-1]);b=b.join("/");return u(b,{handleAs:"json"})}return this._tryLoadResource(a,"config").then(function(b){a.isDefaultConfig=!0;return b})},_upgradeWidgetConfig:function(a,b){var c=new h,d=a.manifest.version,g=a.version,k;if(d===g)return c.resolve(b),c;if(!1===a.hasVersionManager)return a.version=
d,c.resolve(b),c;require(f.getRequireConfig(),[a.amdFolder+"VersionManager"],e.hitch(this,function(e){e=new e;var f=e.getVersionIndex(g),h=e.getVersionIndex(d);if(f>h)c.reject("Bad widget version number, "+a.name+","+g);else try{k=e.upgrade(b,g,d),a.version=d,c.resolve(k)}catch(D){console.log("Read widget ["+a.name+"] old config error,"+D.stack),c.resolve(b)}}));return c},loadWidgetStyle:function(a){var b="widget/style/"+a.uri,c=new h,b=this._replaceId(b);return m.byId(b)?(c.resolve("load"),c):f.loadStyleLink(b,
a.styleFile,"theme_"+this.appConfig.theme.name+"_style_common")},loadWidgetSettingStyle:function(a){var b="widget/style/"+a.uri+"/setting",c=new h,b=this._replaceId(b);return m.byId(b)?(c.resolve("load"),c):f.loadStyleLink(b,a.settingStyleFile)},loadWidgetConfig:function(a){a=require(f.getRequireConfig()).toUrl(a.configFile);if(require.cache["url:"+a]){var b=new h;b.resolve(x.parse(require.cache["url:"+a]));return b}return u(a,{handleAs:"json"})},loadWidgetI18n:function(a){var b=new h;require(f.getRequireConfig(),
["dojo/i18n!"+a.i18nFile],function(a){b.resolve(a)});return b},loadWidgetSettingI18n:function(a){var b=new h;require(f.getRequireConfig(),["dojo/i18n!"+a.settingI18nFile],function(a){b.resolve(a)});return b},loadWidgetTemplate:function(a){var b=new h;require(f.getRequireConfig(),["dojo/text!"+a.templateFile],function(a){b.resolve(a)});f.checkError(a.templateFile,b);return b},loadWidgetSettingTemplate:function(a){var b=new h;require(f.getRequireConfig(),["dojo/text!"+a.settingTemplateFile],function(a){b.resolve(a)});
f.checkError(a.settingTemplateFile,b);return b},removeWidgetStyle:function(a){m.destroy(this._replaceId("widget/style/"+a.uri))},removeWidgetSettingStyle:function(a){m.destroy(this._replaceId("widget/style/"+a.uri+"/setting"))},getControllerWidgets:function(){return l.filter(this.loaded,function(a){return a.isController})},getOffPanelWidgets:function(){return l.filter(this.loaded,function(a){return!a.inPanel})},getOnScreenOffPanelWidgets:function(){return l.filter(this.loaded,function(a){return a.isOnScreen&&
!a.inPanel})},closeOtherWidgetsInTheSameGroup:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;for(var b=0;b<this.loaded.length;b++)this.loaded[b].gid===a.gid&&this.loaded[b].id!==a.id&&this.closeWidget(this.loaded[b])},closeAllWidgetsInGroup:function(a){for(var b=0;b<this.loaded.length;b++)this.loaded[b].gid===a&&this.closeWidget(this.loaded[b])},_mergeAgolConfig:function(a){var b=this.appConfig._appData.values,c="widgets["+a.id+"]",d;for(d in b){var e=d.replace(/\//g,"_").indexOf(c+
"_config");0<=e&&f.template.setConfigValue(a,d.replace(/\//g,"_").substr(e,d.length).replace(c,"widget"),b[d])}},_onUserSignIn:function(a){l.forEach(this.loaded,function(b){b.onSignIn(a)},this)},_onUserSignOut:function(){l.forEach(this.loaded,function(a){a.onSignOut()},this)},_activeWidget:function(a){if(this.activeWidget){if(this.activeWidget.id===a.id){!1===this.activeWidget.inPanel&&this.activeWidget.moveTopOnActive&&m.setStyle(this.activeWidget.domNode,"zIndex",101);return}"active"===this.activeWidget.state&&
(this.activeWidget.setState("opened"),!1===this.activeWidget.inPanel&&m.setStyle(a.domNode,"zIndex","zIndex"in a.position?a.position.zIndex:"auto"),this.activeWidget.onDeActive())}this.activeWidget=a;"opened"===this.activeWidget.state&&(this.activeWidget.setState("active"),!1===this.activeWidget.inPanel&&this.activeWidget.moveTopOnActive&&m.setStyle(this.activeWidget.domNode,"zIndex",101),this.activeWidget.onActive(),k.publish("widgetActived",a))},_onClickWidget:function(a,b){var c=C(".jimu-widget",
a.domNode);if(0<c.length)for(var d=0;d<c.length;d++)if(b.target===c[d]||m.isDescendant(b.target,c[d]))return;this._activeWidget(a)},_onMoveStart:function(a){l.forEach(this.loaded,function(b){b.domNode===a.node&&this._activeWidget(b)},this)},_onAppConfigLoaded:function(a){this.appConfig=a=e.clone(a);y.setPortalUrl(a.portalUrl)},_onSceneViewLoaded:function(a){this.sceneView=a},_onSceneViewChanged:function(a){this.sceneView=a},_onAppConfigChanged:function(a,b,c,d){var g=e.clone(a);this.appConfig=g;l.forEach(this.loaded,
function(a){a&&(a.onAppConfigChanged(g,b,c,d),"widgetChange"===b&&this._onConfigChanged(c.id,c.config,d))},this)},_onConfigChanged:function(a,b){if(a=this.getWidgetById(a))a.onConfigChanged(b),e.mixin(a.config,b)},_onActionTriggered:function(a){if("map"!==a.elementId&&"app"!==a.elementId){var b=this.getWidgetById(a.elementId);if(b)b.onAction(a.action,a.data);else this.missedActions.push({id:a.elementId,action:{name:a.action,data:a.data}});l.forEach(this.getControllerWidgets(),function(b){if(b.widgetIsControlled(a.elementId))b.onAction(a.action,
{widgetId:a.elementId,data:a.data})},this)}},_postWidgetStartup:function(a){a.started=!0;f.setVerticalCenter(a.domNode);n.after(a,"resize",e.hitch(this,f.setVerticalCenter,a.domNode));this.openWidget(a);var b=y.getPortalCredential(this.appConfig.portalUrl);if(b)a.onSignIn(b);else a.onSignOut();this._triggerMissedAction(a)},_triggerMissedAction:function(a){this.missedActions.forEach(function(b){if(b.id===a.id)a.onAction(b.action.name,b.action.data)})},_remove:function(a){return l.some(this.loaded,
function(b,c){if(b.id===a)return this.loaded.splice(c,1),!0},this)},_tryLoadResource:function(a,b){var c,d=new h;if("config"===b)c=a.amdFolder+"config.json",a.configFile=c,c="hasConfig";else if("style"===b)c=a.amdFolder+"css/style.css",a.styleFile=c,c="hasStyle";else if("i18n"===b)c=a.amdFolder+"nls/strings.js",a.i18nFile=a.isRemote?c:a.amdFolder+"nls/strings",c="hasLocale";else if("template"===b)c=a.amdFolder+"Widget.html",a.templateFile=c,c="hasUIFile";else if("settingTemplate"===b)c=a.amdFolder+
"setting/Setting.html",a.settingTemplateFile=c,c="hasSettingUIFile";else if("settingI18n"===b)c=a.amdFolder+"setting/nls/strings.js",a.settingI18nFile=a.isRemote?c:a.amdFolder+"setting/nls/strings",c="hasSettingLocale";else if("settingStyle"===b)c=a.amdFolder+"setting/css/style.css",a.settingStyleFile=c,c="hasSettingStyle";else return d;a[c]?function(){var c;if("config"===b)c=this.loadWidgetConfig(a);else if("style"===b)c=this.loadWidgetStyle(a);else if("i18n"===b)c=this.loadWidgetI18n(a);else if("template"===
b)c=this.loadWidgetTemplate(a);else if("settingTemplate"===b)c=this.loadWidgetSettingTemplate(a);else if("settingStyle"===b)c=this.loadWidgetSettingStyle(a);else if("settingI18n"===b)c=this.loadWidgetSettingI18n(a);else return d;c.then(function(a){d.resolve(a)},function(c){console.error("Load widget resource error. resource:",b);console.error(c);new v({message:window.jimuNls.loadWidgetResourceError+": "+a.uri});d.reject(c)})}.apply(this):d.resolve(null);return d},_replaceId:function(a){return a.replace(/\//g,
"_").replace(/\./g,"_")},_onDestroyWidget:function(a){"closed"!==a.state&&this.closeWidget(a);this._removeWidget(a);console.log("destroy widget ["+a.uri+"].")},_onDestroyWidgetSetting:function(a){this.removeWidgetSettingStyle(a)},_removeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;this.activeWidget&&this.activeWidget.id===a.id&&(this.activeWidget=null);this._remove(a.id);0===this.getWidgetsByName(a.name).length&&this.removeWidgetStyle(a)}});w.getInstance=function(a){null===
r&&(r=new w(a),window._widgetManager=r);return r};return w});