//>>built
define("dojo/_base/lang dojo/_base/array esri/core/declare esri/core/Accessor esri/core/Evented esri/core/now esri/geometry/support/webMercatorUtils esri/geometry/Extent esri/views/3d/webgl-engine/lib/Util esri/views/3d/webgl-engine/lib/gl-matrix esri/views/3d/webgl-engine/lib/FloatingBoxLocalOriginFactory esri/views/3d/support/projectionUtils ../webgl-engine-extensions/GLVerTexture ../support/fx3dUtils".split(" "),function(k,l,q,E,F,r,G,H,v,A,I,B,w,x){var y,C,t,u,z,D=A.vec2d;v=A.vec3d;var p=(v.create(),
v.create()),h={};q=q([E,F],{declaredClass:"esri.views.3d.effects.Effect",effectName:"Effect",constructor:function(a){this._view=a.view;this._layerView=a.layerView;this._renderCoordsHelper=a.view.renderCoordsHelper;this._renderSpatialReference=a.view.renderSpatialReference;this._layer=a.layer;this._wgs84SpatialReference=this._layerView._fx3dSpatialReference;this._stateStack=[];this._currentVizPage=0;this._preVizId=-1;this._repeatCount=0;this._hasSentReady=this._isReachedRepeatLimit=!1;this._vizFieldDefault=
"default";this._vizFields=a.layer.vizFields;this._vizFieldMinMaxs={};this._vizFieldMinMaxs[this._vizFieldDefault]={min:0,max:0,maxFeature:null};l.forEach(this._vizFields,function(a){this._vizFieldMinMaxs[a]={min:null,max:null,maxFeature:null}}.bind(this));this._eventHandlers=[];this._vizFieldVerTextureSize=D.create();this._vizFieldVerTextures={};this._allLoaded=this._needsAllLoaded=!1;this._material=this._shaderSnippets=this._gl=null;this._addedGraphicsCount=this._toAddGraphicsIndex=0;this._addedGraphics=
[];this._resetState();this._resetTime();this._pause=!1;this._eventHandlers.push(this._layer.watch("pauseTag",function(a,c,e){this.ready&&(this._pause=a,a?a&&(this._pausedTime=this.time):this._lastTime=r())}.bind(this)));this._spin=!1;this._eventHandlers.push(this._layer.watch("spinTag",function(a,c,e){return a&&"local"==this._view.viewingMode?(console.warn("Spinning operation is not supported in local scene."),void(this._layer.spinTag=!1)):void(this._spin=a)}.bind(this)));this._addLayerWatchHandler("visible");
this.renderingInfo={visible:!0,repeat:5,transparency:100,animationInterval:5};this.orderId=0},_addLayerWatchHandler:function(a){k.isString(a)&&this._eventHandlers.push(this._layer.watch(a,function(b,c,e){this.renderingInfo[e]=b;"visible"===a.toLowerCase()&&this.ready&&(b?this._lastTime=r():b||(this._pausedTime=this.time))}.bind(this)))},_resetState:function(){this._pause=this.ready=!1;this._shapeDirty=this._vacDirty=!0;this._isAddingGeometry=!1;this._colorBarDirty=this._colourMapDirty=this._renderingInfoDirty=
!0;this._hasSentReady=this._firstAnimatedTo=this._isReachedRepeatLimit=this._shadersReady=!1},_resetTime:function(){this._pausedTime=this.time=this._lastTime=0},_pushState:function(a){for(var b=0;b<this._stateStack.length;b++)if(this._stateStack[b][0]==a[0])return;this._stateStack.push(a)},_restoreState:function(a){for(var b=0;b<this._stateStack.length;b++)"function"==typeof a[this._stateStack[b][0]]&&a[this._stateStack[b][0]].apply(a,this._stateStack[b][1]instanceof Array?this._stateStack[b][1]:
[this._stateStack[b][1]]);this._stateStack=[]},destroy:function(){l.forEach(this._eventHandlers,function(a){"function"==typeof a.remove&&a.remove()||"function"==typeof a.destroy&&a.destroy()});this._resetState();this._destroy("_material");var a=Object.getOwnPropertyNames(this._vizFieldVerTextures);l.forEach(a,function(a){this._vizFieldVerTextures[a]instanceof w&&this._vizFieldVerTextures[a].dispose()}.bind(this))},_dispose:function(a){this[a]&&(this[a].dispose(),delete this[a]);this[a]=null},_destroy:function(a){this[a]&&
(this[a].destroy(),delete this[a]);this[a]=null},setContext:function(a){this._gl=a.gl;this._shaderSnippets=a.shaderSnippets;this._vaoExt=a.vaoExt;this._effectConfig=x.effectConfig(this.effectName);this._initRenderingInfo(this._effectConfig);var b=this._layer._get("renderingInfo");if(this._layer&&b){a=Object.getOwnPropertyNames(b);var c=Object.getOwnPropertyNames(this.renderingInfo),e=this;l.forEach(a,function(a){c?l.some(c,function(f){if(a.toLowerCase()===f.toLowerCase())return"shapetype"===a.toLowerCase()?
e.renderingInfo[f]=b[a].toLowerCase():e.renderingInfo[f]=b[a],!0}):e.renderingInfo[a]=b[a]})}this._renderingInfoChange(this.renderingInfo);this._updateDefaultLabelHeight();this._vizFieldVerTextures[this._vizFieldDefault]=new w(this._gl);l.forEach(this._vizFields,function(a){this._vizFieldVerTextures[a]=new w(this._gl)}.bind(this));this._eventHandlers.push(this._layer.on("fx3d-add-graphics",function(a){this._needsAllLoaded||this._addGraphicsHandler(a)}.bind(this)));this._eventHandlers.push(this._layer.on("all-features-loaded",
function(a){this._needsAllLoaded&&(this._addGraphicsHandler(a),this._allLoaded=!0);this._initVizFieldVertextures();this._layer.emit("can-locating-now")}.bind(this)));this._eventHandlers.push(this._layer.on("fx3d-active-viz-field",k.hitch(this,this._activeVizFieldHandler)));this._eventHandlers.push(this._layer.watch("renderingInfo",this._renderingInfoChange.bind(this)))},_toWGS84Extent:function(a){var b={xmin:a.xmin,ymin:a.ymin,xmax:a.xmax,ymax:a.ymax};return a.spatialReference&&(h.x=a.xmin,h.y=a.ymin,
h.z=0,h.spatialReference=a.spatialReference,B.pointToVector(h,p,this._wgs84SpatialReference),b.xmin=p[0],b.ymin=p[1],h.x=a.xmax,h.y=a.ymax,B.pointToVector(h,p,this._wgs84SpatialReference),b.xmax=p[0],b.ymax=p[1]),b},_calculateExtentCenter:function(a){var b=a.length;if(b){var c,e,f,n,d,m,g;if("point"==this._layer.geometryType)for(c=e=a[0].geometry.longitude,f=n=a[0].geometry.latitude,m=1;m<b;m++)d=a[m],null!=d.geometry&&(d.geometry.longitude<c&&(c=d.geometry.longitude),d.geometry.longitude>e&&(e=d.geometry.longitude),
d.geometry.latitude<f&&(f=d.geometry.latitude),d.geometry.latitude>n&&(n=d.geometry.latitude));else if("polyline"==this._layer.geometryType||"polygon"==this._layer.geometryType)for(g=a[0].geometry.extent,c=g.xmin,e=g.xmax,f=g.ymin,n=g.ymax,m=1;m<b;m++)d=a[m],null!=d.geometry&&null!=d.geometry.extent&&(g=d.geometry.extent,g.xmin<c&&(c=g.xmin),g.xmax>e&&(e=g.xmax),g.ymin<f&&(f=g.ymin),g.ymax>n&&(n=g.ymax));return new H(c,f,e,n,this._wgs84SpatialReference)}return null},_addGraphicsHandler:function(a){k.isArray(a.graphics)&&
0<a.graphics.length&&(this._toAddGraphicsIndex=this._addedGraphicsCount,this._addedGraphicsCount+=a.graphics.length,this._needsAllLoaded?this._addedGraphics=a.graphics:this._addedGraphics=this._addedGraphics.concat(a.graphics),this._isAddingGeometry=!0,this._shapeDirty=!0)},_activeVizFieldHandler:function(a){"number"==typeof a.currentVizPage&&((0>this._currentVizPage||this._currentVizPage>=this._vizFields.length)&&(this._currentVizPage=0),this.ready=!1,this._hasSentReady=!1,this._restoreRenderingInfo(),
k.isObject(a.newRenderingInfo)&&k.mixin(this.renderingInfo,a.newRenderingInfo),this._shapeDirty=!1,this._colorBarDirty=!1,this._colourMapDirty=!1,this._renderingInfoChange(this.renderingInfo),this._updateDefaultLabelHeight(),this.update(),this._resetAnimation(),this._currentVizPage=a.currentVizPage,this._updateVizFieldMinMaxToLayer(),this._layerView._updateSelectedFeatureLabel(),this._emitSyncEvent())},_resetAnimation:function(){this._repeatCount=0;this._preVizId=-1;this._isReachedRepeatLimit=!1;
this._resetTime();this._layer.startAnimation()},_resetAddGeometries:function(){this._addedGraphics=[]},_allGraphics:function(){return this._layerView.getLoadedGraphics()},_renderingInfoChange:function(a,b,c){a!==b&&a&&k.isObject(a)&&this._doRenderingInfoChange(a)},_doRenderingInfoChange:function(a){this._renderingInfoDirty=!0;for(var b in a)a.hasOwnProperty(b)&&this.renderingInfo.hasOwnProperty(b)&&("visible"===b.toLowerCase()?(this._layer&&(this._layer[b]=a[b]),this.renderingInfo[b]=a[b]):"repeat"!==
b.toLowerCase()&&"animationinterval"!==b.toLowerCase()||(this._resetAnimation(),this._clampScope(a,b),this.renderingInfo[b]=a[b]))},_initRenderingInfo:function(a){this._scopes={};a&&k.isObject(a)&&k.isArray(a.renderingInfo)&&l.forEach(a.renderingInfo,function(a){"shapetype"===a.name.toLowerCase()?this.renderingInfo[a.name]=a.defaultValue.toLowerCase():this.renderingInfo[a.name]=a.defaultValue;k.isArray(a.scope)&&(this._scopes[a.name]=a.scope)}.bind(this))},_restoreRenderingInfo:function(){this.renderingInfo=
{visible:!0,repeat:5,transparency:100,animationInterval:5};this._initRenderingInfo(this._effectConfig);var a=this._layer._get("renderingInfo");if(this._layer&&a){var b=Object.getOwnPropertyNames(a),c=Object.getOwnPropertyNames(this.renderingInfo),e=this;l.forEach(b,function(b){c?l.some(c,function(c){if(b.toLowerCase()===c.toLowerCase())return"shapetype"===b.toLowerCase()?e.renderingInfo[c]=a[b].toLowerCase():e.renderingInfo[c]=a[b],!0}):e.renderingInfo[b]=a[b]})}this._updateDefaultLabelHeight()},
_clampScope:function(a,b){var c=this._scopes[b];k.isArray(c)&&"number"==typeof a[b]&&"number"==typeof c[0]&&"number"==typeof c[1]&&(a[b]<c[0]?a[b]=c[0]:a[b]>c[1]&&(a[b]=c[1]),0>a[b]&&(a[b]=0))},_updateRenderingInfo:function(){var a=!0;(!this._needsAllLoaded||this._needsAllLoaded&&this._allLoaded)&&0<this._allGraphics().length&&(this._colorBarDirty?(a=this._initColorBar(),a&&(this._colorBarDirty=!1)):a=!0,this._colourMapDirty&&a?(a=this._initColourMap(),a&&(this._colourMapDirty=!1)):a=!0,a=!(!this._renderingInfoDirty||
!a),this._renderingInfoDirty=!a)},_updateRenderingGeometry:function(){var a=!0;(!this._needsAllLoaded||this._needsAllLoaded&&this._allLoaded)&&0<this._allGraphics().length&&(a=this._initRenderContext(),a?(a=this._initVizFieldVertextures(),this._shapeDirty=!a):this._shapeDirty=!0,!0===this._shapeDirty&&(this._isAddingGeometry=!1))},preRender:function(){this.renderingInfo.visible&&(this._shadersReady||(this._shadersReady=this._loadShaders()))},_emitSyncEvent:function(){this._layer&&0<this._repeatCount&&
(0>=this.renderingInfo.repeat||0<this.renderingInfo.repeat&&this._repeatCount<=this.renderingInfo.repeat)&&this._layer.emit("sync-viz-timer",{vizPage:this._currentVizPage,repeat:this._repeatCount})},_calculateRepeatCount:function(){z=Math.floor(this.time/this.renderingInfo.animationInterval);this._preVizId!==z&&(this._repeatCount++,this._preVizId=z,this._emitSyncEvent())},_updateVizPage:function(){0<this.renderingInfo.repeat?this._repeatCount<=this.renderingInfo.repeat?this._calculateRepeatCount():
this._isReachedRepeatLimit||(this._isReachedRepeatLimit=!0,this._layer.pauseAnimation(),this._layer.emit("reached-repeat-limit")):0>this.renderingInfo.repeat?(this._calculateRepeatCount(),this._isReachedRepeatLimit&&(this._isReachedRepeatLimit=!1)):this._isReachedRepeatLimit||(this._isReachedRepeatLimit=!0)},render:function(a,b){this.renderingInfo.visible&&(a.time=this.time,a.reachedRepeatLimit=this._isReachedRepeatLimit)},update:function(){this.renderingInfo.visible&&(this._renderingInfoDirty&&this._updateRenderingInfo(),
this._shapeDirty&&this._updateRenderingGeometry(),this._renderingInfoDirty||this._shapeDirty||!this._shadersReady?this.ready=!1:this.ready=!0,this._updateSelfTime(),this._updateVizPage(),this._spin&&this._doSpin())},_doSpin:function(){y=this._view.camera.position;C=G.webMercatorToGeographic(y);t=C.x-1;-180>=t&&(t=179);u=y.z;8E6>u&&(u=8E6);this._view.goTo({position:[t,0,u],tilt:0,heading:0})},_bindPramsReady:function(){return 0<=this._currentVizPage&&this._currentVizPage<Object.getOwnPropertyNames(this._vizFieldMinMaxs).length&&
this._currentVizPage<Object.getOwnPropertyNames(this._vizFieldVerTextures).length},_updateSelfTime:function(){this.ready&&!this._pause&&(0!==this._lastTime?this.time=this._pausedTime+.001*(r()-this._lastTime):(this._lastTime=r(),this.time=0))},_loadShaders:function(){return!0},_initVertexLayout:function(){return!0},_initRenderContext:function(){return!0},_initVizFieldVertextures:function(){var a=this._allGraphics();if(0<a.length){var b=this._gl.getParameter(3379),c=a.length,e=x.nextHighestPowerOfTwo(c);
e>b&&(e=b,console.warn("Too many graphics, and extra features will be discarded."));var f=Math.ceil(c/e),f=x.nextHighestPowerOfTwo(f);f>b&&(f=b,console.warn("Too many graphics, and extra features will be discarded."));this._vizFieldVerTextures[this._vizFieldDefault].setData(e,f,new Float32Array(e*f*4));var k,d,m,g;return l.forEach(this._vizFields,function(b){var c=new Float32Array(e*f*4);(d=a[0].attributes[b])||(d=0);(!d||"number"!=typeof d||0>d)&&(d=0);m=g=d;for(var l=a[0],h=0;h<a.length;h++)k=a[h].attributes,
d=k[b],(!d||"number"!=typeof d||0>d)&&(d=0),c[4*h]=d,g<d&&(g=d,l=a[h]),m>d&&(m=d);this._vizFieldVerTextures[b].setData(e,f,c);this._vizFieldMinMaxs[b].min=m;this._vizFieldMinMaxs[b].max=g;this._vizFieldMinMaxs[b].maxFeature=l;this._updateVizFieldMinMaxToLayer()}.bind(this)),D.set2(e,f,this._vizFieldVerTextureSize),!0}return!1},_updateVizFieldMinMaxToLayer:function(){this._layer._currentVizPage=this._currentVizPage;this._layer._currentVizFieldMinMax=this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]]},
_initColourMap:function(){return!0},_initColorBar:function(){return!0},_updateDefaultLabelHeight:function(){}});return q.createLocalOriginFactory=function(){return new I(5E6,16)},q});