//>>built
define("dojo/_base/lang dojo/_base/array esri/core/declare esri/core/lang esri/views/3d/webgl-engine/lib/Util ../../webgl-engine-extensions/VertexBufferLayout ../../webgl-engine-extensions/GLVertexArrayObject ../../webgl-engine-extensions/GLXBO ../../support/fx3dUtils ../../support/fx3dUnits ../Effect ./PulseMaterial".split(" "),function(p,v,w,D,q,x,y,r,l,t,z,A){var B=q.assert,u=q.VertexAttrConstants,C={circle:48,square:4,triangle:3,hexagon:6};return w([z],{declaredClass:"esri.views.3d.effects.Pulse.PulseEffect",
effectName:"Pulse",constructor:function(b){p.hitch(this,b);this.orderId=2;this._sizeInMeters=[]},_initRenderingInfo:function(){this.renderingInfo.radius=1E4;this.renderingInfo.solidColor=[255,255,20];this.renderingInfo.haloColors=[l.rgbNames.cadetblue,l.rgbNames.yellowgreen,l.rgbNames.lightpink,l.rgbNames.orangered,l.rgbNames.green,l.rgbNames.indianred];this._colorBarDirty=!0;this.renderingInfo.shapeType="circle";this._shapeDirty=this._vacDirty=this._renderingInfoDirty=this._drawRing=!0;this.inherited(arguments)},
_doRenderingInfoChange:function(b){this.inherited(arguments);for(var a in b)b.hasOwnProperty(a)&&this.renderingInfo.hasOwnProperty(a)&&(l.endsWith(a.toLowerCase(),"info")?l.isInforAttrChanged(this.renderingInfo[a],b[a])&&(this._renderingInfoDirty=!0):l.endsWith(a.toLowerCase(),"color")?b[a]instanceof Array&&3==b[a].length&&(this.renderingInfo[a]=[b[a][0]/255,b[a][1]/255,b[a][2]/255]):l.endsWith(a.toLowerCase(),"colors")?b[a]instanceof Array&&(this.renderingInfo[a]=b[a],this._colorBarDirty=!0,this._renderingInfoDirty=
!0):"shapetype"===a.toLowerCase()?this.renderingInfo[a]!=b[a].toLowerCase()&&(this._vacDirty=!0,this._shapeDirty=!0,this._isAddingGeometry=!1,this._renderingInfoDirty=!0,this.renderingInfo[a]=b[a].toLowerCase(),this._colourMapDirty=!0):"radius"===a.toLowerCase()||"transparency"===a.toLowerCase()?(this._clampScope(b,a),"radius"==a&&this._radiusUnit?this.renderingInfo[a]=t.toMeters(this._radiusUnit,b[a],this._view.viewingMode):this.renderingInfo[a]=b[a]):typeof b[a]==typeof this.renderingInfo[a]&&(this.renderingInfo[a]=
b[a]))},_updateDefaultLabelHeight:function(){this._layer._labelDefaultHeight=null},setContext:function(b){this.inherited(arguments);this._effectConfig&&p.isArray(this._effectConfig.renderingInfo)&&(this._radiusUnit=null,v.forEach(this._effectConfig.renderingInfo,function(a){"radius"===a.name.toLowerCase()&&(this._radiusUnit=a.unit,this.renderingInfo.radius=t.toMeters(this._radiusUnit,this.renderingInfo.radius,this._view.viewingMode))}.bind(this)))},destroy:function(){this._resetXBOs();this._dispose("_vao")},
_resetXBOs:function(){this._dispose("_vbo");this._dispose("_ibo")},_initVertexLayout:function(){this._vertexAttrConstants=[u.POSITION,u.AUXPOS1];this._vertexBufferLayout=new x(this._vertexAttrConstants,[3,3],[5126,5126])},_initRenderContext:function(){this.inherited(arguments);this._vacDirty&&(this._initVertexLayout(),this._resetXBOs(),this._vacDirty=!1,this._vao&&(this._vao.unbind(),this._vao._initialized=!1));this._vbo||(this._vbo=new r(this._gl,!0,this._vertexBufferLayout));this._ibo||(this._ibo=
new r(this._gl,!1));this._vaoExt&&(this._vao=new y(this._gl,this._vaoExt));var b=!1;switch(this.renderingInfo.shapeType){case "circle":case "triangle":case "square":case "hexagon":this._geometryVertexNum=4;this._geometryIndexNum=6;this._drawRing=!0;b=this._buildRingGeometries();break;case "wave":this._geometryVertexNum=3;this._geometryIndexNum=6;this._drawRing=!1;b=this._buildWaveGeometries();break;default:this._drawRing=!1}return b},_getAltitude:function(b){return"number"==typeof b?40.11>b&&(b=40.11):
b=40.11,b},_buildRingGeometries:function(){var b=this._isAddingGeometry?this._addedGraphics:this._allGraphics(),a=this._isAddingGeometry?this._toAddGraphicsIndex:0;if(0<b.length){var h,c,d,e,n=Math.max(3,C[this.renderingInfo.shapeType]),f=e=0,k=n*this._geometryVertexNum,l=this._vertexBufferLayout.getStride(),m=new Float32Array(b.length*l*k),g=new Uint32Array(b.length*n*this._geometryIndexNum),p=f=0;for(c=0;c<b.length;c++)if(h=b[c],null!=h.geometry){for(d=0;d<k;d++)e=(c*k+d)*l,f=d%this._geometryVertexNum,
m[0+e]=h.geometry.longitude,m[1+e]=h.geometry.latitude,m[2+e]=this._getAltitude(h.geometry.altitude),m[3+e]=c+a,m[4+e]=f,p=Math.floor(d/4),2!==f&&3!==f||(p+=1),m[5+e]=p/n;e=(c+a)*k;for(d=0;d<n;d++)f=(c*n+d)*this._geometryIndexNum,g[0+f]=0+e+d*this._geometryVertexNum,g[1+f]=2+e+d*this._geometryVertexNum,g[2+f]=1+e+d*this._geometryVertexNum,g[3+f]=0+e+d*this._geometryVertexNum,g[4+f]=3+e+d*this._geometryVertexNum,g[5+f]=2+e+d*this._geometryVertexNum}return this._vbo.addData(this._isAddingGeometry,m),
this._ibo.addData(this._isAddingGeometry,g),this._vao&&(this._vao._initialized=!1),this._resetAddGeometries(),!0}return!1},_buildWaveGeometries:function(){var b=this._isAddingGeometry?this._addedGraphics:this._allGraphics(),a=this._isAddingGeometry?this._toAddGraphicsIndex:0;if(0<b.length){this._waveSegments=32;var h,c,d,e,n,f,k=this._waveSegments;h=k-1;var l=[],m=[];for(n=0;n<k;n++)for(e=0;e<k;e++)l.push([e,n]),n<k-1&&e<k-1&&(f=n*k+e,c=(n+1)*k+e,m.push([f,c,f+1,f+1,c,c+1]));e=l.length;n=this._vertexBufferLayout.getStride();
f=new Float32Array(b.length*n*e);h=h*h*this._geometryIndexNum;B(m.length*m[0].length===h);var k=new Uint32Array(b.length*h),g=0;for(h=g=0;h<b.length;h++){d=b[h];for(c=0;c<e;c++)g=(h*e+c)*n,f[0+g]=d.geometry.longitude,f[1+g]=d.geometry.latitude,f[2+g]=this._getAltitude(d.geometry.altitude),f[3+g]=h+a,f[4+g]=l[c][0],f[5+g]=l[c][1];d=h*e+a;for(c=0;c<m.length;c++)g=(h*m.length+c)*this._geometryIndexNum,k[0+g]=m[c][0]+d,k[1+g]=m[c][1]+d,k[2+g]=m[c][2]+d,k[3+g]=m[c][3]+d,k[4+g]=m[c][4]+d,k[5+g]=m[c][5]+
d}return this._vbo.addData(this._isAddingGeometry,f),this._ibo.addData(this._isAddingGeometry,k),this._resetAddGeometries(),!0}return!1},_initColorBar:function(){if(!this._colorBarDirty)return!0;this._colorBarTexture||(this._colorBarTexture=this._gl.createTexture());var b=this._gl.getParameter(32873);this._gl.bindTexture(3553,this._colorBarTexture);this._gl.pixelStorei(37440,!0);this._gl.texParameteri(3553,10240,9728);this._gl.texParameteri(3553,10241,9728);this._gl.texParameteri(3553,10242,33071);
this._gl.texParameteri(3553,10243,33071);var a=l.createColorBarTexture(32,1,this.renderingInfo.haloColors);return this._gl.texImage2D(3553,0,6408,6408,5121,a),this._gl.generateMipmap(3553),this._gl.bindTexture(3553,b),0===this._gl.getError()},_loadShaders:function(){return this.inherited(arguments),this._material||(this._material=new A({pushState:this._pushState.bind(this),restoreState:this._restoreState.bind(this),gl:this._gl,viewingMode:this._view.viewingMode,shaderSnippets:this._shaderSnippets})),
this._material.loadShaders()},_localBinds:function(){this._vbo.bind(this._material._program);this._vertexBufferLayout.enableVertexAttribArrays(this._gl,this._material._program);this._ibo.bind()},_bindBuffer:function(){this._vao?(this._vao._initialized||this._vao.initialize(this._localBinds.bind(this)),this._vao.bind()):this._localBinds()},_unBindBuffer:function(){this._vao?this._vao.unbind():(this._vbo.unbind(),this._vertexBufferLayout.disableVertexAttribArrays(this._gl,this._material._program),this._ibo.unbind())},
render:function(b,a){this.inherited(arguments);this._layer.visible&&this.ready&&this._bindPramsReady()&&(this._hasSentReady||(this._layer.emit("fx3d-ready"),this._hasSentReady=!0),this._material.bind(p.mixin({},{lo:this._drawRing,os:this._waveSegments,so:this._vizFieldVerTextures[this._vizFieldDefault],oi:this._vizFieldVerTextures[this._vizFields[this._currentVizPage]],oo:this._vizFieldVerTextureSize,ii:this.renderingInfo.animationInterval,pi:[this._scopes.radius[0],this.renderingInfo.radius],ei:this.renderingInfo.transparency,
ie:this._colorBarTexture,op:this._vizFieldMinMaxs[this._vizFieldDefault].min>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min?this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min:this._vizFieldMinMaxs[this._vizFieldDefault].min,po:this._vizFieldMinMaxs[this._vizFieldDefault].max>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max?this._vizFieldMinMaxs[this._vizFieldDefault].max:this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max,ss:this.renderingInfo.solidColor},
b),a),this._bindBuffer(),this._gl.drawElements(4,this._ibo.getNum(),5125,0),this._material.release(a),this._unBindBuffer())}})});