// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"dojo/throttle":function(){define([],function(){return function(f,e){var d=!0;return function(){d&&(d=!1,f.apply(this,arguments),setTimeout(function(){d=!0},e))}}})},"widgets/FullScreen/_build-generate_module":function(){define(["dojo/text!./Widget.html","dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/FullScreen/Widget.html":'\x3cdiv\x3e\r\n\t\x3cdiv class\x3d"operate-item fullScreen" data-dojo-attach-event\x3d"onclick:_onFullScreenClick" data-dojo-attach-point\x3d"fullScreenBtn" title\x3d"${label}"\x3e\x3c/div\x3e\r\n\x3c/div\x3e',
"url:widgets/FullScreen/css/style.css":'.jimu-widget-fullScreen {opacity: 0.8; color: rgba(0, 0, 0, 0.8);}.jimu-widget-fullScreen:hover{opacity: 1;}.jimu-widget-fullScreen .fullScreen {width: 32px; height: 32px; border: 1px solid rgba(0, 0, 0, 0.3); text-align: center; line-height: 32px; font-size: 14px; background-color: #fff; margin-left: auto; margin-right: auto; border-radius: 50%; cursor: pointer;}.jimu-widget-fullScreen .fullScreen:before{font-family: \'Themefont\';}.jimu-widget-fullScreen .fullScreen.restore:before {content: "\\a906";}.jimu-widget-fullScreen .fullScreen.maximize:before {content: "\\a905";}:-webkit-full-screen {width: 100%; height: 100%; background: #11ee11;}:-moz-full-screen {width: 100%; height: 100%; background: #11ee11;}:-ms-fullscreen {width: 100%; height: 100%; background: #11ee11;}:fullscreen {width: 100%; height: 100%; background: #11ee11;}:full-screen {width: 100%; height: 100%; background: #11ee11;}:fullscreen-ancestor {z-index: -1;}.body-fullscreened \x3e .dijitPopup {z-index: 2147483647 !important;}',
"*now":function(f){f(['dojo/i18n!*preload*widgets/FullScreen/nls/Widget*["ar","bs","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sl","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])}}});
define("dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/on dojo/query dojo/dom-style jimu/BaseWidget dojo/throttle dojo/_base/fx dijit/focus dojo/topic dojo/_base/window jimu/PanelManager jimu/utils".split(" "),function(f,e,d,g,h,c,l,m,k,n,p,q,r,t){return f([l],{name:"FullScreen",baseClass:"jimu-widget-fullScreen",domsCache:{map:null,doc:null},ACTION:{HIDE:"hide",SHOW:"show"},MODE:{RESTORE:"restore",MAXIMIZE:"maximize"},status:{lastState:{top:0,right:0,bottom:0,left:0},_mouseX:-1,_mouseY:-1},
_timer:null,_waitMouseStopTime:2E3,_animationList:[],_animFadeTime:500,startup:function(){this.domsCache={doc:this._getDocument(),body:q.body(),map:this.sceneView.container};this.status.state=this.MODE.RESTORE;d.add(this.fullScreenBtn,this.status.state);this.own(g(this.domsCache.doc,"webkitfullscreenchange,mozfullscreenchange,MSFullscreenChange,fullscreenchange",e.hitch(this,"_onFullScreenChangeEvent")));this.own(g(this.domsCache.map,"mousemove",m(e.hitch(this,this._setTimerByMouseMove),100)));this.own(p.subscribe("changeMapPosition",
e.hitch(this,this._changeMapPositionHandler)))},_onFullScreenClick:function(){this._toggleFullScreen()},_onFullScreenChangeEvent:function(){!1===this._isFullScreen(this.domsCache.doc)?(this.status.state=this.MODE.RESTORE,this._toggleFullScreen(this.status.state),this._restoreDisplayAllItems()):this.status.state=this.MODE.MAXIMIZE;this._toggleBtnIcon()},_setTimerByMouseMove:function(a){if(this._isMouseMoved(a)&&(this._timer&&(this._toggleItems(this.ACTION.SHOW),window.clearTimeout(this._timer),this._timer=
null),this.status.state===this.MODE.MAXIMIZE)){this._restoreDisplayAllItems();var b=this;this._timer=window.setTimeout(function(){b._toggleItems(b.ACTION.HIDE,null)},this._waitMouseStopTime)}},_getDocument:function(){return t.isInConfigOrPreviewWindow()?window.top.document:window.document},_isMouseMoved:function(a){if(a&&a.pageX&&a.pageY){if(this.status._mouseX===a.pageX&&this.status._mouseY===a.pageY)return!1;this.status._mouseX=a.pageX;this.status._mouseY=a.pageY;return!0}},_isAnyInputOnFocus:function(a){if(a===
this.ACTION.HIDE){a=h("input");for(var b=0,c=a.length;b<c;b++)if(n.curNode===a[b])return!0}return!1},_changeMapPositionHandler:function(a){!a||0===a.left&&0===a.top||this.status.state!==this.MODE.MAXIMIZE||(c.set(this.domsCache.map,"top","0px"),c.set(this.domsCache.map,"right","0px"),c.set(this.domsCache.map,"bottom","0px"),c.set(this.domsCache.map,"left","0px"))},_toggleMapPosition:function(a){this._isFullScreen(this.domsCache.doc)||a===this.MODE.RESTORE?(c.set(this.domsCache.map,"top",this.status.lastState.top),
c.set(this.domsCache.map,"right",this.status.lastState.right),c.set(this.domsCache.map,"bottom",this.status.lastState.bottom),c.set(this.domsCache.map,"left",this.status.lastState.left)):(this._getPositionEndWithPx("top"),this._getPositionEndWithPx("right"),this._getPositionEndWithPx("bottom"),this._getPositionEndWithPx("left"),c.set(this.domsCache.map,"top","0px"),c.set(this.domsCache.map,"right","0px"),c.set(this.domsCache.map,"bottom","0px"),c.set(this.domsCache.map,"left","0px"))},_getPositionEndWithPx:function(a){if(a){var b=
c.get(this.domsCache.map,a);if("number"===typeof b||"string"===typeof b&&!b.endWith("px"))b+="px";this.status.lastState[a]=b}},_toggleBtnIcon:function(){d.toggle(this.fullScreenBtn,"restore");d.toggle(this.fullScreenBtn,"maximize");d.toggle(this.domsCache.body,"body-fullscreened")},_toggleFullScreen:function(a){this._toggleMapPosition(a);this._isFullScreen(this.domsCache.doc)||a===this.MODE.RESTORE?(this._timer&&(window.clearTimeout(this._timer),this._timer=null),this._toggleItems(this.ACTION.SHOW,
null),this._cancelFullScreen(this.domsCache.doc)):this._launchFullScreen(this.domsCache.map)},_toggleItems:function(a,b,c){if(!0!==this._isAnyInputOnFocus(a)||b)this._interruptAndCleanAnimationList(),this._toggleWidgetsAndPanels(a,c),this._toggleItemsByMode(h(".jimu-widget-placeholder"),a,c),this._toggleItemsByMode(h(".jimu-widget-onscreen-icon"),a,c)},_toggleItemsByMode:function(a,b,c){for(var d=0,u=a.length;d<u;d++){var e=a[d];b===this.ACTION.SHOW?this._fadeInItem(e,c):this._fadeOutItem(e,c)}},
_toggleWidgetsAndPanels:function(a,b){var c=this.widgetManager.getOffPanelWidgets().filter(function(a){return"closed"!==a.state}),d=r.getInstance().panels.filter(function(a){return"closed"!==a.state}),c=[].concat(c,d);a===this.ACTION.SHOW?c.forEach(function(a){this._fadeInItem(a.domNode,b)}.bind(this)):c.forEach(function(a){this._fadeOutItem(a.domNode,b)}.bind(this))},_fadeOutItem:function(a,b){b=k.fadeOut({node:a,duration:b?1:this._animFadeTime,end:0}).play(0,!0);this.own(g(b,"End",e.hitch(this,
function(){c.set(a,"display","none");c.set(a,"opacity","")}),!0));this._addToAnimationList(b)},_fadeInItem:function(a,b){b=b?1:this._animFadeTime;c.set(a,"display","block");b=k.fadeIn({node:a,duration:b,end:.8}).play(0,!0);this.own(g(b,"End",e.hitch(this,function(){c.set(a,"opacity","")}),!0));this._addToAnimationList(b)},_addToAnimationList:function(a){this._animationList.push(a)},_interruptAndCleanAnimationList:function(){for(var a=0,b=this._animationList.length;a<b;a++)this._animationList[a].stop(!0);
this._animationList.length=0;this._animationList=[]},_restoreDisplayAllItems:function(){this._interruptAndCleanAnimationList();this._toggleItems(this.ACTION.SHOW,!0,!0)},_isFullScreen:function(a){return!!(a.fullscreenElement||a.mozFullScreenElement||a.webkitFullscreenElement||a.msFullscreenElement)},_launchFullScreen:function(a){if(a.requestFullScreen)a.requestFullScreen();else if(a.mozRequestFullScreen)a.mozRequestFullScreen();else if(a.webkitRequestFullScreen)a.webkitRequestFullScreen();else if(a.msRequestFullscreen)a.msRequestFullscreen();
else return!1},_cancelFullScreen:function(a){if(a.exitFullscreen)a.exitFullscreen();else if(a.mozCancelFullScreen)a.mozCancelFullScreen();else if(a.webkitCancelFullScreen)a.webkitCancelFullScreen();else if(a.msExitFullscreen)a.msExitFullscreen();else return!1}})});